### ISSUE TITLE
Configure Polkadot <> Kusama Bridge to Use Asset Conversion to Buy Execution

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#104]
At least initially, we expect the Polkadot<>Kusama bridge to maintain some assets on each side with which to buy execution. For example, we'd expect the Kusama Asset Hub (AH) to have some DOT in its sovereign account on Polkadot's AH, and then charge users extra KSM for transacting on Kusama's AH over the bridge to Polkadot's AH, where the XCM program would withdraw some DOT from its sovereign account to pay for execution locally.

This has some flaws, like ensuring that the correct additional amount is withdrawn on the Kusama side, and that it will be sufficient given the current weight-to-fee rate on Polkadot's AH, and the fact that this account would need to be occasionally topped up via governance.

By using asset conversion, the bridge could buy execution (accurately) in any asset it sends over, provided there is a pool for it (e.g. a pKSM <> DOT pair).

**Comment by acatangiu** [comment]
With https://kusama.subsquare.io/referenda/258 and https://polkadot.subsquare.io/referenda/122 we now have `(k)DOT` on Kusama AssetHub and `(p)KSM` on Polkadot AssetHub, both of which are marked as `sufficient` on their respective side. Meaning that fees and execution can be bought on either side with both `DOT` and `KSM`.

So we no longer need to manage (and periodically balance) these sovereign accounts of AHs on each respective side.

**But**, I believe we still need to use asset conversion (i.e. `pKSM <> DOT` and `kDOT <> KSM` pools) to figure out "the exchange rate" at which to spend non-native asset for buying execution on remote chain.

E.g.: Alice transfers 10 DOT from `PAH` (Polkadot AssetHub) to `KAH` (Kusama AssetHub) - and specifies that she wants to pay fees from transferred DOT - so Alice pays:
1. 0.1 DOT for `tx_fee` on `PAH`
2. buys `X weight` for execution of `ExportMessage` on `PBH` (Polkadot BridgeHub) - `X weight` on Polkadot -> `1 DOT` (we have hardcoded exchange rate between weight and DOT on Polkadot)
3. buys `Y weight` for XCM execution on target `KAH` - `Y weight` on Kusama -> `??? DOT` (we know `kusama_weight` -> `KSM` conversion, but we don't know how much DOT to charge)

So, my guess is we'd use `AssetConversion` for `#3`, but don't know how/if we can hook that up to weight->asset calculator to make it "just work" for everyone.

**Comment by joepetrowski** [comment]
I think ultimately we will need https://github.com/paritytech/polkadot-sdk/issues/606 to make that work. Asset Conversion can publish recent rates of selected assets (e.g. KSM, USDT, ETH, etc.) and the Bridge Hub could subscribe to those.

**Comment by acatangiu** [comment]
This is all concerning target AssetHub, not BridgeHub.

I spoke to @bkontur and have more detail/context on what happens at target AH:

On `AssetHub`s we configure [new XCM Trader](https://github.com/paritytech/polkadot-sdk/pull/1352/files#diff-ea9251f22dd8abd9e29a6ecae8a27eba7f1548996c3413596af33b099efeb81eR461-R473) which uses [this multiplier](https://github.com/paritytech/polkadot-sdk/pull/1352/files#diff-ea9251f22dd8abd9e29a6ecae8a27eba7f1548996c3413596af33b099efeb81eR413-R421) to convert `weight`->`asset_amount` based on the asset's Existential Deposit.

I guess this is ok(ish), but it'd be better if we could use `AssetConversion` here to go from `weight` --static-ED-based-ration--> `native-asset` --dynamic-pool-ratio--> `foreign-asset`.

> I think ultimately we will need https://github.com/paritytech/polkadot-sdk/issues/606 to make that work. Asset Conversion can publish recent rates of selected assets (e.g. KSM, USDT, ETH, etc.) and the Bridge Hub could subscribe to those.

Right now, we don't charge anything on target BH so we don't need this, but yes, we would use it if we start charging (possibly XCM HRMP delivery fee to target AH).

**Comment by acatangiu** [comment]
Ok, so we have https://github.com/paritytech/polkadot-sdk/issues/105 exactly for what I described above.

I guess we can close this issue then. 👍

**Comment by acatangiu** [comment]
close on behalf of https://github.com/paritytech/polkadot-sdk/issues/105
