### ISSUE TITLE
[asset-conversion] Add runtime api to polkadot-js/api

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#108]
E.g.: FungiblesApi: https://github.com/polkadot-js/api/blob/3f90f72bd69c49a7ef6902366572c90c1efcdb52/packages/types/src/interfaces/fungibles/runtime.ts

**Comment by NachoPal** [comment]
Can it be closed? both PRs are already merged, not sure if there is still something missing or not.

**Comment by jsidorenko** [comment]
As I see, this issue is still open: https://github.com/paritytech/polkadot-sdk/issues/1129 ,@bkontur, could you comment on this pls?

**Comment by bkontur** [comment]
iirc, initially, we've added some stuff to the polkadot.js, but I am not sure if it is still compatible, because there were several refactors in asset-conversion pallet, so we should check this.

@franciscoaguirre Cisco has already fixed some stuff within XCMv4, I would say we need to revisit that #1129 again, what would be the best option

**Comment by franciscoaguirre** [comment]
I pinned version 3 so we can do a storage migration whenever

**Comment by bkontur** [comment]
yes, one thing is storage and another thing is public APIs for indexers/wallets and so on, maybe for them it would be better to use `Versioned*` stuff, not to break when we change XCM version for storage items, if `Location` is not compatible.

Another thing, I think we should maybe add some `try-runtime` / `try-state` stuff, which would check actual data if they are compatible with actual XCM version used for storage items - but this would be a separate issue. At least, we will see if we can do runtime upgrade or not.

**Comment by kianenigma** [comment]
Shouldn't this issue be in PJS apps?

**Comment by bkchr** [comment]
Yeah, it should be.

**Comment by bkchr** [comment]
https://github.com/polkadot-js/api/pull/5694 but also looks like it was already done.
