### ISSUE TITLE
Contract: Native function to retrieve entire call input bytes array

### ISSUE THREAD

**Issue by shunsukew** [paritytech/polkadot-sdk#112]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

In certain scenarios involving Wasm contracts, there is a desire to transmit data as extra bytes within the ExecutionInput of cross-contract calls and subsequently access this data within the callee contracts. Unfortunately, as long as I know, there is presently no capability to read the complete array of call input bytes within contracts, making it impractical to accomplish this objective without changing the signature of the functions within the callee contracts.

For example,
[ERC2771](https://eips.ethereum.org/EIPS/eip-2771)-like meta transaction use case, Forwarder contract append extra 32bytes array representing AccountId of Transaction Signer to the ExecutionInput of cross-contract call.
```
build_call::<<Self as ::ink::env::ContractEnv>::Env>()
                .call(req.callee)
                .gas_limit(req.gas_limit)
                .transferred_value(req.transferred_value)
                .call_flags(CallFlags::default().set_allow_reentry(req.allow_reentry))
                .exec_input(
                    // Add signer's account_id as extra input bytes
                    // SCALE encoded
                    ExecutionInput::new(req.selector.into())
                        .push_arg(CallInput(&req.input))
                        .push_arg(req.from.encode()), // <- **HERE**
                )
                .returns::<()>()
                .try_invoke();
```
Since there are currently no built-in mechanisms to read the complete array of ExecutionInput bytes, it is necessary to modify the function signatures of the callee contracts in order to read extra bytes. Specifically, the function signatures of these contracts will need to be adjusted to include a parameter of type Vec<u8>, which will be used to decode any additional bytes appended by the calling contracts.
```
#[ink(message)]
pub fn some_message(&mut self, input: String, _data: Vec<u8>) {}
```
If pallet-contracts had this feature, modifying the function signatures of the callee contracts to transmit additional data wouldn't be required.

### Request

The same feature as Solidity's `calldataload`, `calldatasize` (Doc: https://docs.soliditylang.org/en/v0.8.16/yul.html#evm-dialect, Example usage: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7e7060e00e107460fc57c178859d3cf0c6ac64ef/contracts/metatx/ERC2771Context.sol#LL29C35-L29C47) in pallet-contracts and available in contracts language such as ink!.

### Are you willing to help with this request?

Yes!

**Comment by athei** [comment]
[It is possible](https://docs.rs/pallet-revive/latest/pallet_revive/trait.SyscallDoc.html#tymethod.input) to read the whole input data. It seems to just not be exposed by ink. Closing as this is an ink! issue.
