### ISSUE TITLE
[rococo/wococo] create new testing runtime AssetHubRococo full-featured

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#1128]
Right now we have two "asset hub" parachains on Rococo:

- [Rococo Asset Hub (formerly Rockmine)](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/explorer)
- [Rockmine2](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws-rococo-rockmine2-collator-node-0.parity-testnet.parity.io#/explorer)

Both of them are deploying runtimes built from [asset-hub-kusama](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/parachains/runtimes/assets/asset-hub-kusama) runtime code.

Let's create full-featured (asset-conversion, bridging, nfts, ...) runtime version for AH Rococo/Wococo for testing new features before merging them in AssetHubKusama.

TODOs:
- [ ] create new runtime AssetHubRococo
- [ ] add all features
- [ ] reonboard Rockmine
- [ ] unboard Rockmine2

**Comment by gitkit13** [comment]
#10397
