### ISSUE TITLE
CI to check each individual pallet compiles with supported feature configurations.

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1136]
There are many pallets (in Substrate & Polkadot) that doesn't compile by itself due to mis configured features.
The runtime compiles fine thanks for feature pollution, but it can cause trouble when working with those pallet directly.

Some related fixes that can be detected by CI:
https://github.com/paritytech/substrate/pull/6995
https://github.com/paritytech/substrate/pull/5833
https://github.com/paritytech/substrate/pull/10324
https://github.com/paritytech/polkadot/pull/4355

**Comment by xlc** [comment]
I am going to leave a message here overtime I encountered a bad feature flag config.

```
error[E0046]: not all trait items implemented, missing: `ensure_successful`
   --> /Users/xiliangchen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pallet-asset-rate-4.0.0/src/lib.rs:229:1
    |
229 | impl<T> ConversionFromAssetBalance<BalanceOf<T>, AssetKindOf<T>, BalanceOf<T>> for Pallet<T>
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `ensure_successful` in implementation
    |
    = help: implement the missing item: `fn ensure_successful(_: <T as pallet::Config>::AssetKind) { todo!() }`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `pallet-asset-rate` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by ggwpez** [comment]
Where did you compile that? As part of another repo?  
Master should have proper feature configs now.

**Comment by xlc** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/actions/runs/6777961997/job/18422558667
