### ISSUE TITLE
Avoid `()` error return type for scheduler

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1142]
https://github.com/paritytech/substrate/blob/05cac0ddb96e1ca03775e491540e450537548844/frame/support/src/traits/schedule.rs#L77

https://github.com/paritytech/substrate/blob/05cac0ddb96e1ca03775e491540e450537548844/frame/support/src/traits/schedule.rs#L111

https://github.com/paritytech/substrate/blob/05cac0ddb96e1ca03775e491540e450537548844/frame/support/src/traits/schedule.rs#L120

This discard the DisaptchError returned by pallet-scheduler

**Comment by ggwpez** [comment]
Fixed in V3 scheduler: https://github.com/paritytech/polkadot-sdk/blob/8b061a5c5d29a4ef8efa0f2919fdc5c3cfc36361/substrate/frame/support/src/traits/schedule.rs#L414
