### ISSUE TITLE
pallet-membership should implement ContainsLengthBound

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1143]
otherwise we can't use it with pallet-tips without wrapper

**Comment by xlc** [comment]
I guess not

**Comment by Aideepakchaudhary** [comment]
Can you please elaborate this issue statement?

**Comment by xlc** [comment]
implement `trait ContainsLengthBound` for pallet membership

https://github.com/paritytech/polkadot-sdk/blob/6daa939bc7c3f26c693a876d5a4b7ea00c6b2d7f/substrate/frame/support/src/traits/members.rs#L280

example

https://github.com/paritytech/polkadot-sdk/blob/6daa939bc7c3f26c693a876d5a4b7ea00c6b2d7f/substrate/frame/elections-phragmen/src/lib.rs#L1194-L1203

**Comment by Aideepakchaudhary** [comment]
@xlc I have raised a PR for this issue. Please let me know if something need to be update further.

**Comment by Aideepakchaudhary** [comment]
I think we close this issue
