### ISSUE TITLE
Investigate errors from BEEFY `SessionKeys` migration

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#1149]
[CI output](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/3435640) of Kusama try-runtime indicates that `UpgradeSessionKeys` has issues decoding entries at storage item `Session::NextKeys`.  
I assume the `Session::upgrade_keys::<OldSessionKeys, _>(transform_session_keys);` is unable to decode all of the old values. On Westend it seems to work though. cc @acatangiu 

```pre
Corrupted state at `[206, 197, 7, 13, 96, 157, 211, 73, 127, 114, 189, 224, 127, 201, 107, 160, 76, 1, 78, 107, 248, 184, 194, 192, 17, 231, 41, 11, 133, 105, 107, 179, 255, 220, 13, 65, 27, 98, 174, 212, 215, 196, 191, 188, 184, 223, 114, 71, 17, 222, 101, 73, 164, 181, 250, 22, 103, 106, 183, 255, 4, 239, 141, 208]: Error`
... many more lines like this
```

I will try to do a metadata comparison to see the exact change.

**Comment by acatangiu** [comment]
hmm, the migration worked for me on `kusama-local` when doing a runtime upgrade on local chain test.

how does one test this with `try-runtime`? 😄

**Comment by ggwpez** [comment]
Not sure if we have a tutorial yet, but the docs are linked in the repo https://github.com/paritytech/try-runtime-cli.  
Otherwise @liamaharon can help you :smile:

**Comment by liamaharon** [comment]
Hey @acatangiu, see installation instructions here: https://paritytech.github.io/try-runtime-cli/try_runtime/#installation

and instructions to dry-run Migrations using real data here: https://paritytech.github.io/try-runtime-cli/try_runtime/#examples-1

Let me know if you have any questions

**Comment by bkchr** [comment]
@acatangiu any update on this? Do we maybe have some old session keys in the state that break some assumptions?

**Comment by acatangiu** [comment]
I’m sorry, I haven’t looked at this.. I mistakenly lumped it in together with https://github.com/paritytech/polkadot-sdk/issues/1305, but it looks like something else.

I can look into it tomorrow.

**Comment by ggwpez** [comment]
I compared the metadata between master and on-chain but it does not report anything for `UpgradeSessionKeys`. I hoped it would give some quick insights, but apparently not.

**Comment by acatangiu** [comment]
Seems like state is already broken on kusama, this just surfaces it:

![Screenshot 2023-09-12 at 15 54 07](https://github.com/paritytech/polkadot-sdk/assets/31917973/1846f96d-1aef-475b-884f-8e66bbde5248)

**Comment by acatangiu** [comment]
Also note `nextKeys` != `queuedKeys`, `queuedKeys` is the list of next keys to be used by the _active set_, whereas `nextKeys` contains every validator's next keys if they were ever to reach _active set_.

So I guess we need to find the broken keys are remove them?

**Comment by ggwpez** [comment]
> So I guess we need to find the broken keys are remove them?

Yea just also realised this and wrote a script to check `Found 381 broken entries, 3958 good`.  
So actually we dont have to do anything, since the `translate` ignores undecodable entries. Maybe still worth to actually remove them though.

**Comment by liamaharon** [comment]
What's the best way we can cleanup the undecodable entries @ggwpez ? I'm happy to jump on that.

**Comment by alindima** [comment]
Slightly related: `UpgradeSessionKeys` performs no check on the pallet version so it breaks when doing a runtime upgrade on a westend-based runtime (like Versi, or in zombienet) whose chainspec includes a runtime built from recent master code.
I am now manually commenting it out when building a westend runtime, as a workaround.

**Comment by bkchr** [comment]
@alindima there is no pallet version to check for this, as this is a pure runtime configuration change. However, we could change the migration to check if it can decode with the new format and if so, skip the migration. Maybe you @alindima could do this and create a pr.

**Comment by alindima** [comment]
I'll take a stab at it, sure

**Comment by andresilva** [comment]
> Slightly related: `UpgradeSessionKeys` performs no check on the pallet version so it breaks when doing a runtime upgrade on a westend-based runtime (like Versi, or in zombienet) whose chainspec includes a runtime built from recent master code. I am now manually commenting it out when building a westend runtime, as a workaround.

Just for historical purposes, we just got bitten by this on Westend. The migration ran twice and borked session keys.

**Comment by bkchr** [comment]
I think we can close this.

**Comment by ggwpez** [comment]
>The migration ran twice and borked session keys.

Can this also happen to other chains? Did we fix it yet? Dont know if this is related: https://substrate.stackexchange.com/questions/10500

**Comment by andresilva** [comment]
The migration code was kept as-is and nothing was changed, so yes this can happen to anyone that runs the migration twice. Not sure it's the same problem happening on that stackexchange question though.
