### ISSUE TITLE
Allow justifications on non-finalized blocks

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#1159]
Currently Substrate enforces that blocks must not have justifications unless they are finalized: https://github.com/paritytech/polkadot-sdk/blob/1a38d6d6be42b30e8be3ffccec75a4ec995fef9d/substrate/client/service/src/client/client.rs#L606

It is useful, however, for other purposes as well, for instance I would like to use justifications to make nodes send extra data alongside blocks that are not strictly required, but do help with block verification.

Grandpa already has a check that finalized blocks must have justifications (with redundant assertion afterwards) if I understand it correctly, so should not be an issue to remove this requirement (I think): https://github.com/paritytech/polkadot-sdk/blob/1a38d6d6be42b30e8be3ffccec75a4ec995fef9d/substrate/client/consensus/grandpa/src/import.rs#L548-L555

Any concerns if I send a PR removing this restriction?

**Comment by bkchr** [comment]
Okay perfect :) @andresilva is on holidays. @nazar-pc let's create a pr :)
