### ISSUE TITLE
Contracts: change `ensure_no_start` to `start`

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/polkadot-sdk#116]
Blocked by https://github.com/paritytech/substrate/issues/13639

### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Some languages must init basic env(GC) for later call.
It's very hard to remove `start` function.

BTW, It's a break change since `sp-sandbox` support to call `start` before other call. Now not support `start` anymore.

> Reject contracts with start functions
Having a start function in contracts give us all kinds of headaches. They were allowed but neither Rust nor solang make use of them. Strictly speaking this is a change that breaks existing contracts with start functions but that would be some very exotic contracts written in assembly and we prefer to get rid of that before a substantial amount of contracts start depending on it. We might need to roll it back when too many people start complaining.

### Request

Support to call `start` before `deploy`/`call`

### Solution

Also compute gas cost for `start` function.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by yjhmelody** [comment]
@athei Hi it's time to fix this. Hope to hear some good news.

**Comment by athei** [comment]
Yes. I am on it.
