### ISSUE TITLE
contracts: XCM support

### ISSUE THREAD

**Issue by HCastano** [paritytech/polkadot-sdk#121]
# The Vision
Contracts should be able to execute and send arbitrary XCM messages. This will allow contracts to participate in the wider ecosystem. A common use case would be to make use of assets on statemint.

# The Plan

A while ago I created a chain extension to support executing, sending and receiving XCM messages from a contract: https://github.com/paritytech/pallet-contracts-xcm

This is a prototype but already outlines all the features we need:
- Sending XCM programs
- Executing XCM programs locally
- Receiving replies
    - We opted for polling here instead of callbacks. So **no** `ink_xcm_receive`. This solves the weight problems around  receiving replies.

It doesn't do this in a secure way, though. It is a prototype. For example, it doesn't charge storage deposits for the reply id and reply buffer.

It is a chain extension rather than a core API solely because of technical reasons: It depends on the XCM crates which are part of the `polkadot` repo. However, pallet-contracts is in the `substrate` repository on which `polkadot` depends. Therefore `pallet-contracts` can't depend on XCM as this would be a circle. As a workaround we placed the code into another repository. The only way to do that is a chain extension. The real implementation should be bundled with `pallet-contracts` once we have the monorepo. It still needs to be optional as some chains might decide not to implement it. Hence it might make sense to keep it a chain extension rather than a core API.

- [ ] Port existing chain extensions to XCMv3
- [ ] Move extension into the soon to be existent monorepo
- [ ] Make it production ready (make it sound with regard to resource usage, add docs,  add tests)
- [ ] Update ink! support (ink! needs support for multiple chain extensions first)

# Open Questions
_If you want to help us out and contribute to this issue, in this section you can find open questions and tasks where we would appreciate any input._

<Leave open questions or tasks where the community could help>

---
Here you can find the board with specific sub-tasks to this milestone:
[<Link to your project's view>](https://github.com/orgs/paritytech/projects/29/views/2)

**Comment by athei** [comment]
XCM host functions are implemented in pallet-revive. We will enable them at a later time, though.
