### ISSUE TITLE
DecodeLen impl for BTreeSet is inconsisent with StorageAppend

### ISSUE THREAD

**Issue by dandanlen** [paritytech/polkadot-sdk#126]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

`StorageAppend` treats BTreeSets as a Vecs in storage: `append()` simply writes the value to the end of the buffer. This is fine when decoding back to a BTreeSet: any duplicate values are dropped and we get the expected set.

However, `StorageDecodeLength` for BTreeSet returns the length of the underlying stored Vec, and any duplicate value are included.

Presumably some variation of the same is true for BTreeMap and the bounded equivalents of both.

### Steps to reproduce

Minimal failing test:

```rust
	#[frame_support::storage_alias]
	type Store = StorageValue<Prefix, BTreeSet<()>>;

	#[test]
	fn test() {
		TestExternalities::default().execute_with(|| {
			Store::put(Default::default());
			Store::append(());
			Store::append(());

			assert_eq!(Store::decode_len().unwrap(), Store::get().unwrap().len());
		});
	}
```

Gives: 

```
thread 'storage::test::test' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', frame/support/src/storage/mod.rs:2007:13
```

**Comment by 0xmovses** [comment]
@dandanlen I can't reproduce the bug. The minimal test passes. You can checkout to `0xmovses-storage-length` and run the my tests there.

**Comment by ggwpez** [comment]
> @dandanlen I can't reproduce the bug. The minimal test passes. You can checkout to `0xmovses-storage-length` and run the my test there.

I see that you added two test, but non of them insert identical elements. Try this one:  
```rust
#[test]
fn btree_set_decode_len_works() {
	#[crate::storage_alias]
	type Store = StorageValue<Prefix, BTreeSet<u32>>;

	TestExternalities::default().execute_with(|| {
		Store::append(4);
		Store::append(4);
		Store::append(5);

		assert_eq!(Store::get().unwrap().len(), 2);
		assert_eq!(Store::decode_len().unwrap(), Store::get().unwrap().len());
	});
}

**Comment by 0xmovses** [comment]
Thanks @ggwpez, yes with dup items I can reproduce. Working on the fix!

**Comment by kianenigma** [comment]
Having seen #1932, I would actually prevent `::apend` on a btree_set and call it a day. Are we even using it anywhere?

**Comment by dandanlen** [comment]
> Having seen #1932, I would actually prevent `::apend` on a btree_set and call it a day. Are we even using it anywhere?

We use it at Chainflip. We don't use decode_len but i was curious how/if it worked, which is how I came across this bug. 

My view: It's not essential (easy to work around by storing a Vec explicitly instead) but nice to have, and it works as advertised. `append` is also much more useful than `decode_len`, so if either of the two have to go, I would vote to keep `append`, and remove `decode_len`.
