### ISSUE TITLE
GHW - srtool

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-sdk#1271]
Cumulus had a [srtool](https://github.com/paritytech/cumulus/blob/master/.github/workflows/srtool.yml) workflow mainly used as CI check (the release builds are done in another GHW).

If some runtimes remain in this repo, we need to bring this CI check back in here.

**Comment by ggwpez** [comment]
> If some runtimes remain in this repo, we need to bring this CI check back in here.

Remaining here will be Rococo/Westend+parachains.

**Comment by EgorPopelyaev** [comment]
@chevdor @ggwpez The part for the `polkadot-sdk` is done, do we need the same thing in the fellows repo?
