### ISSUE TITLE
Default is called on storage item when generating metadata

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#1282]
I have following storage item that is always populated in genesis config, hence I made `Default` implementation panic because it will essentially never be called:
```rust
    pub(super) struct DefaultPotSlotIterations {}

    impl Get<NonZeroU32> for DefaultPotSlotIterations {
        fn get() -> NonZeroU32 {
            unreachable!("Always instantiated during genesis; qed");
        }
    }

    /// Number of iterations for proof of time per slot
    #[pallet::storage]
    pub(super) type PotSlotIterations<T> =
        StorageValue<_, NonZeroU32, ValueQuery, DefaultPotSlotIterations>;
```

I was wrong, when opening Polkadot.js apps I've got this in UI:
> FATAL: Unable to initialize the API: -32000: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed WASM backtrace: error while executing at wasm backtrace: 0: 0x4f86c - <unknown>!rust_begin_unwind 1: 0x11ce1 - <unknown>!core::panicking::panic_fmt::h021607b2ba950e84 2: 0x3439d - <unknown>!<pallet_subspace::pallet::DefaultPotSlotIterations as bounded_collections::Get<core::num::nonzero::NonZeroU32>>::get::hd57d4b875ac72697 3: 0xf922c - <unknown>!pallet_subspace::pallet::Pallet<T>::storage_metadata::h2c69a538692fcda2 4: 0x1101e5 - <unknown>!subspace_runtime::Runtime::metadata_ir::hc52c359c5026bd57 5: 0xbb5b8 - <unknown>!Metadata_metadata

And on the runtime side was this:
```
panicked at 'internal error: entered unreachable code: Always instantiated during genesis; qed', ...    
```

Now I'm confused and I think something is off, it shouldn't be necessary to create default values for storage items if they are already populated.

While this looks like a question, I believe this is an unexpected behavior and should ideally be fixed.

**Comment by bkchr** [comment]
I mean we require that the type implements `Default` and then you are surprised that `default` is called? This sounds like your assumptions are incorrect :P 

You can use `OptionQuery` or `ResultQuery`. Both should not require that `Default` implemented.

**Comment by nazar-pc** [comment]
:joy:
I guess I was trying to avoid `.expect()` every time I use it that way. You're right that it is strange to do it like that indeed.

**Comment by bkchr** [comment]
So, I think we can close this issue?
