### ISSUE TITLE
Allow generic XCM execution

### ISSUE THREAD

**Issue by Szegoo** [paritytech/polkadot-sdk#1283]
Following this post on the Polkadot forum: [link](https://forum.polkadot.network/t/why-is-xcm-program-execution-filtered-out-on-most-chains/3765)

I would like to suggest allowing generic XCM execution on the Kusama system parachains. Kusama already supports this so I don't think it would be a crazy idea to allow it.

Some clear benefits of this would be:
- Possibility of transferring reserve assets on AssetHub into an account from a remote chain.
- Possibility to do two-hop reserve transfers.
- Doing native token transfers with XCM. This could make it easier for wallets and other UIs to do non-cross-chain transfers since they can rely on using the XCM standard for doing this.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/why-is-xcm-program-execution-filtered-out-on-most-chains/3765/5

**Comment by ggwpez** [comment]
There are still some things that need to be fixed. We cannot do this yet - same why it is also not advised to do so for any other production parachain.

**Comment by ggwpez** [comment]
But we can do something in the relays https://github.com/paritytech/polkadot-sdk/pull/1303

**Comment by acatangiu** [comment]
This is now allowed on all test chains (all chains in this repo), as well as on all Kusama chains: https://github.com/polkadot-fellows/runtimes/pull/261. Polkadot chains will come a bit after Kusama as usual.

**Comment by acatangiu** [comment]
Polkadot system chains: https://github.com/polkadot-fellows/runtimes/pull/345
