### ISSUE TITLE
Failed to convert BEEFY PublicKey to ETH address (westend & kusama)

### ISSUE THREAD

**Issue by alindima** [paritytech/polkadot-sdk#1305]
Trying to upgrade the westend runtime in Versi, we start seeing a lot of errors like this one:
`Failed to convert BEEFY PublicKey to ETH address`.

As it scales with the number of validators and session frequency, this can pollute the logs of testnets.

CC: @acatangiu

**Comment by acatangiu** [comment]
Thanks for the report @alindima !

Initial BEEFY keys (ecdsa keys) [are some dummy keys](https://github.com/paritytech/polkadot-sdk/blob/7768b77d53eb9a6585faace16fac27091895bc56/polkadot/runtime/kusama/src/lib.rs#L459C2-L472C2) that need to be replaced by validators with their actual real keys by using [rotate_keys()](https://github.com/paritytech/polkadot-sdk/blob/5eb816d7a685826282632842dbaec7c89d284333/substrate/client/rpc/src/author/mod.rs#L121).

So, on testnets, each validator's initial dummy BEEFY key will throw an error that it can't be converted to ETH address.

We might be able to "fix" this by modifying initial dummy BEEFY keys to be some custom sequences of bytes that can be successfully converted to ETH addresses.

But there's a question on whether we should or not.. now this error logs are arguably useful to motivate validators to rotate keys and actually register valid/unique BEEFY key. It indirectly reports that validators are using invalid BEEFY keys.
At the same time, they are annoying in tests..

@andresilva wdyt? should we "fix" it or not?

**Comment by bkchr** [comment]
> to be some custom sequences of bytes that can be successfully converted to ETH addresses

How hard is this? If it is fairly trivial by setting some bits or something, we should do it.

**Comment by andresilva** [comment]
We are already doing `.unwrap_or_default()` when attempting the conversion, so I don't really see the need to generate "valid" dummy keys. Maybe just downgrade the logging to `debug`? We can instead do an `error` [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/beefy-mmr/src/lib.rs#L192-L209) if we see any of those keys, as this will only issue one log statement per block.
