### ISSUE TITLE
Non-Parity authors in `Cargo.toml`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#1319]
There are two crates with non-Parity authors:
- `substrate-frame-rpc-support`: `Parity Technologies, Andrew Dirksen`
- `pallet-asset-rate`: `William Freudenberger`

And some of the `parachain-template-node` template things have `Anonymous`, but i guess that is fine.

I assume the CLA document that was signed by every contributor should allow us to replace it with parity, or?

**Comment by bkchr** [comment]
> I assume the CLA document that was signed by every contributor should allow us to replace it with parity, or?

Yeah probably.



> And some of the `parachain-template-node` template things have `Anonymous`, but i guess that is fine.

Yeah that is correct.
