### ISSUE TITLE
Update `translate` to use `defensive!`

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1323]
so we should update `translate` to use `defensive!`

_Originally posted by @xlc in https://github.com/paritytech/polkadot-sdk/pull/1290#discussion_r1310133898_
            

So that it will be a hard fail in test

**Comment by liamaharon** [comment]
@xlc do you mean use `debug_assert!`? I understand `defensive!` will log an error, not hard fail
