### ISSUE TITLE
Update VersionedMigration to ensure it is not possible to use the unchecked migration

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1324]
We should have a new `UncheckedOnRuntimeUpgrade` trait, and have the unchecked migration implements it instead of `OnRuntimeUpgrade`. In this way, it will not be possible to accidental use the unchecked migration in the actual migration.

**Comment by dastansam** [comment]
hey @ggwpez 

can I start working on this?

**Comment by ggwpez** [comment]
Need to check with @liamaharon first. The idea is to rename+deprecate the current `OnRuntimeUpgrade` trait and then only advertise the checked version?

**Comment by liamaharon** [comment]
@xlc do you mind elaborating here, to make sure we're on the same page?

**Comment by xlc** [comment]
https://github.com/xlc/polkadot-sdk/blob/b1c51310d7682bf62ceb9823ec7108382cb71252/cumulus/pallets/xcmp-queue/src/migration.rs#L95-L138 
this is an example migration using `VersionedMigration`

It implements a `UncheckedMigrationToV2`, which is unsafe. We have to wrap it with `VersionedMigration` and use it.

However, we can't prevent people from using the `UncheckedMigrationToV2`.

This is because `VersionedMigration` takes a type implements `OnRuntimeUpgrade`, and offers an implementation of `OnRuntimeUpgrade`.

The solution is add a new trait `UncheckedOnRuntimeUpgrade`, and make `VersionedMigration` take it. In that way, the `UncheckedMigration` does not implement `OnRuntimeUpgrade` and therefore cannot be accidentally used.

**Comment by liamaharon** [comment]
Cool thanks @xlc I think this makes sense. So we should leave `OnRuntimeUpgrade` as-is, but make a breaking change to `VersionedMigration` so that it takes a struct implementing an identical trait with a different name `UncheckedOnRuntimeUpgrade`.

**Comment by liamaharon** [comment]
@dastansam I've assigned you, don't hesitate to drop questions here if you have any.
