### ISSUE TITLE
Polkadot install instructions do not work

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#1372]
Install instructions in the Polkadot README should be fixed.

**Comment by kianenigma** [comment]
What doesn't work about it, precisely? I haven't read or validate the whole thing, but it does cover various installation options.

**Comment by ggwpez** [comment]
I have not tried it, but from a glance eg the binary path looks wrong `./target/release/polkadot`.  
Does report came in the over chat from someone internally, I did not verified past that.

**Comment by rajdeep7Singh** [comment]
Hi @kianenigma @ggwpez I am facing a similar issue while running development node. I have asked on stackexcahnge as well. https://substrate.stackexchange.com/questions/9959/unable-to-run-development-node-after-repo-migration?noredirect=1#comment9955_9959

Can you guys help please?

**Comment by skunert** [comment]
@rajdeep7Singh The current problem is that `--dev` used to use the `polkadot-dev` runtime which will not be available anymore (and `polkadot-native` is already disabled by default). The command currently does not work as described in the install instructions. 
A workaround for you in the meantime is to run `cargo run -- --chain rococo-dev` instead. 

The situation will be improved by https://github.com/paritytech/polkadot-sdk/pull/1304, after it lands the `dev` chainspec will mean `rococo-dev`.

**Comment by rajdeep7Singh** [comment]
Got it! I thought it only used the polkadot runtime and specs with different specifications. Thanks i ll run a rococo-dev and import required pallets if it works. Thanks for the information
