### ISSUE TITLE
Lookahead Collator should build only on scheduled relay-parents

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot-sdk#1400]
Currently, the lookahead collator assumes that the chain is scheduled at every block. However, if the lookahead collator builds on a relay parent where the parachain is not scheduled, this candidate can never be included.

The lookahead collator should only build on chains where all in-scope and off-chain blocks are built on allowed relay-parents.

**Comment by bkchr** [comment]
DQ: I thought with async backing we will be able to build on a range of blocks that will then be accepted as parent when the block is allowed to be included on the relay chain? So what does "allowed relay chain parent" means here? Allowed in what sense?

**Comment by rphmeier** [comment]
Yes, this is true.

We chose to implement asynchronous backing so the validator group assigned to back the parachain at the relay parent is responsible for backing candidates with that relay parent. This avoids the need for candidates to be revalidated when groups rotate, but also means that a candidate with a relay parent where there is no backing group for the parachain can never get backed.

**Comment by bkchr** [comment]
Ahh, so I can only include my block retroactively? I always assumed that when you know that your parachain is scheduled at slot X, you can build the block already at X - N. So, you would have the block ready when the slot is goes "live".

**Comment by rphmeier** [comment]
It depends how you define retroactive - the situation you described goes away if we give the parachain a backing group proactively.

**Comment by bkchr** [comment]
Yeah for sure, but you can not give it proactively a backing group for a relay parent that doesn't exist yet?

**Comment by rphmeier** [comment]
Sure, but you can allow the candidate to be built on relay parent X even if it can't be posted on-chain until X+2 or something like that.
