### ISSUE TITLE
Grandpa rpc `proveFinality` could not work 

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/polkadot-sdk#1401]
The bin is `substrate-node` in `./bin/node`.
Now it always return `GRANDPA prove finality rpc failed: Block not covered by authority set changes`.

It seems that it not work for rpc if authority not change at least once.

**Comment by yjhmelody** [comment]
I found this RPC even could not return a same value for same block number.

**Comment by yjhmelody** [comment]
The db seems store justifactiion every grandpa period. But this rpc use a `set_id` to lookup block which is rarely updated compared to period length.

**Comment by yjhmelody** [comment]
It seems that `grandpa_justification` is different with `prove_finality`

**Comment by bkchr** [comment]
Could you please be more specific on what is the problem?

**Comment by yjhmelody** [comment]
Sorry, I just misunderstood this rpc semantics. 
But there is still two questions: 
1. What's the meaning for return `justification` data of block older than rpc param's ? 
2. When start a genesis network, we could not query it normally until we do once authority change.

**Comment by bkchr** [comment]
> 1. What's the meaning for return `justification` data of block older than rpc param's ?

Because you also get the header since this `justification`. The `justification` is the thing you need to check that the `header` is approved.

> * When start a genesis network, we could not query it normally until we do once authority change.

We could probably store a justification at genesis. CC @andresilva
