### ISSUE TITLE
wasmi is not supported anymore

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot-sdk#1414]
Since v0.9.43 it seems `--wasm-execution interpreted-i-know-what-i-do` is not working anymore.
This is problematic as otherwise starting the dev node enforce the compilation of the wasm (even with `--execution native`) which is very very slow.

In comparison:
CPU boot time with wasmi: `user    0m0.597s`
CPU boot time without wasmi: `user    0m24.355s`

**Comment by bkchr** [comment]
`wasmi` removal is done on purpose, the same is true for the native runtime. We should try to find out why it takes 24 seconds to build the wasm? Is this node running in release mode?

**Comment by bkchr** [comment]
There is not really anything actionable here. I tried disabling the optimization of `wasmtime`, but this didn't changed that much (around 1 second less).

**Comment by crystalin** [comment]
So we are left compiling the wasm runtime at every execution, even with native execution? :( :( 
The time difference is big even with just polkadot:
<img width="944" alt="image" src="https://github.com/paritytech/polkadot-sdk/assets/329248/7639c55d-a22f-455d-b615-e0a03a2f0865">

**Comment by burdges** [comment]
We do have PVF artifacts cached across executions in polkadot, no?

**Comment by bkchr** [comment]
> So we are left compiling the wasm runtime at every execution, even with native execution? :( :(

Native execution doesn't exist anymore, but even with native execution the wasm was the canonical source that was required for getting the version etc.



> We do have PVF artifacts cached across executions in polkadot, no?

We have them cached, but this is not related.
