### ISSUE TITLE
async backing: potential memory leak

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#1425]
This has been observed during a load test on Versi @ 300 validators and 60 parachains with async backing enabled.

Configuration:
```
asyncBackingParams: {
    maxCandidateDepth: 3
    allowedAncestryLen: 2
  }
```

I suspect `statement-distribution` or `prospective-parachains`  to be the culprit.

At the same time some nodes seem to stop running with last message: `2023-09-06 12:13:34.377 ERROR tokio-runtime-worker polkadot_overseer: subsystem exited with error subsystem="statement-distribution-subsystem" err=FromOrigin { origin: "statement-distribution", source: SubsystemReceive(Generated(Context("Signal channel is terminated and empty."))) }`

Possibly killed due to OOM, but still investigating.

<img width="1682" alt="Screenshot 2023-09-06 at 16 13 14" src="https://github.com/paritytech/polkadot-sdk/assets/54316454/0e9cce48-4771-4df0-be4e-bf7340ad9815">

**Comment by sandreim** [comment]
![image](https://github.com/paritytech/polkadot-sdk/assets/54316454/a7d32a9f-d0c7-46a7-9168-a95ce91423a0)

Nodes are indeed being evicted due to excessive mem usage, so the `subsystem exited with error` is explained.

**Comment by sandreim** [comment]
<img width="861" alt="Screenshot 2023-09-06 at 17 00 04" src="https://github.com/paritytech/polkadot-sdk/assets/54316454/e10b4492-468a-425d-97e1-7375c708e4c1">

`statement-distribution` as a CPU usage champion.

**Comment by sandreim** [comment]
@rphmeier the new logs you pushed to https://github.com/paritytech/polkadot-sdk/pull/1410 show that we are tracking an ever increasing number of leaves.

https://grafana.teleport.parity.io/goto/Et7Z5lzIR?orgId=1

**Comment by alexggh** [comment]
> [67d1bc0](https://github.com/paritytech/polkadot-sdk/commit/67d1bc0e2467f81c708e9739942b7f2602581e3c)

@rphmeier This fix doesn't seem to have made it into `master`, I can still see high cpu when testing on versi and it seems that the same thing started happening on rococo once we updated to a runtime supporting async-backing. 

Any idea if it wasn't included intentionally or by accident ?

 <img width="2530" alt="Screenshot 2023-10-20 at 13 44 42" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/5e9708c4-b698-4942-88cb-777d9e07567c">

**Comment by sandreim** [comment]
stale fixed issue
