### ISSUE TITLE
Allow TreasuryOrigins to do XCM transfers

### ISSUE THREAD

**Issue by samelamin** [paritytech/polkadot-sdk#1428]
I raised this in the fellows channel but raising this as a separate issue to hopefully keep track of discussions

We want to build out a way for treasury and spender tracks to support reserve asset transfers

Currently, the only way to do this is through the utility pallet dispatchAs. It is very little work to enable the treasury tracks to use XCM

**Comment by bkchr** [comment]
Should also be part of the fellowship runtimes repo.

**Comment by samelamin** [comment]
Closing ticket and reverting to fellowship repo. Apologies for the confusion
