### ISSUE TITLE
Conviction Voting Pallet emits event on vote and remove_vote

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#143]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

On the successful `vote`, `remove_vote` and `remove_other_vote` actions there are no events emitted, which make it hard to subscribe for such an event.

### Request

Emit an event on the successful `vote`, `remove_vote` and `remove_other_vote`.

### Are you willing to help with this request?

Yes!

mentor: @muharem

**Comment by PieWol** [comment]
Hey @muharem, would this just be creating a new event and emitting it whenever `try_vote` is successful? Looks pretty easy to do. If you would agree and this is still relevant I can see myself putting up a PR for it.

**Comment by muharem** [comment]
> Hey @muharem, would this just be creating a new event and emitting it whenever `try_vote` is successful? Looks pretty easy to do. If you would agree and this is still relevant I can see myself putting up a PR for it.

yes, right, go ahead
