### ISSUE TITLE
Test: new statement distribution functions when max_validators is set

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot-sdk#1437]
https://github.com/paritytech/polkadot-sdk/pull/1436/commits/35be89f22da224f925d23757f372e07e2122fa64 in #1436 fixed this bug, where the grid topology would be incomplete if and only if `max_validators` was set (and the `validators` in the session-info had a smaller size than the `discovery_keys`).

This should be tested in the subsystem-wide tests, ensuring that the grid functions correctly even when both of the following are true:
  1. the local node has no key present in `validators` in the session info
  2. the `NewGossipTopology` message specifies an index of `validators.len() + 1`

**Comment by slumber** [comment]
1\) implies that local node is not in active validators set, meaning `local_validator` will be `None` in https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/node/network/statement-distribution/src/vstaging/mod.rs
This code either aborts or sends a report for sender (regardless whether it's statement or manifest) without checking the grid. 

It's clear how to check this in a unit test for grid, but the issue says

> This should be tested in the subsystem-wide tests

Could you provide a scenario for one? In particular, why do we care about inactive validators in topology if they don't participate in statement distribution?

**Comment by rphmeier** [comment]
I meant to update this issue, sorry for not getting around to it yet. The bug is actually worse than I initially thought, because we need to support having a `local_validator` with an empty cluster but a grid tracker as long as the local node is part of the topology.

So let's reframe this issue as fixing that bug. We should instantiate the `LocalValidator` in the `PerRelayParent` state as long as the local node is either an active or inactive validator (as they all participate in the topology).

An `enum LocalIndex { Active(ValidatorIndex), Inactive }` would be helpful for that.
