### ISSUE TITLE
Statement distribution: Add test that cluster members successfully request and respond with each other

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot-sdk#1478]
3 tests, 3 properties:

1. A cluster member seeing a `Seconded` message should request the candidate from the sender
2. A cluster member receiving a request should respond _if_ the requester has not sent them any statements about the candidate
3. A cluster member should reject requests if the requester appears to know the candidate (has sent them a `Seconded` statement)

**Comment by rphmeier** [comment]
This is a test which would have prevented https://github.com/paritytech/polkadot-sdk/pull/1436/commits/c63cb2146a2a366dcb3f0650ab19a3ffd1fb363f - property (2)

**Comment by BradleyOlson64** [comment]
Closed by #1528
