### ISSUE TITLE
Mocked `fungibles::*` traits

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#156]
Instead of always using `pallet-balances` in mock runtimes we should rather write a mock for the `fungibles::*` traits.

Partially addressed by https://github.com/paritytech/substrate/pull/14568

**Comment by kianenigma** [comment]
We technically have consideration for this, and in the meantime more pallets can use `pallet_balances::default_configs::TestDefaultConfig`, i'd say we close?
