### ISSUE TITLE
nomination-pools try-state hook fails on Kusama

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#158]
## Description of bug

A try-state check is failing on Kusama
 
<img width="1502" alt="Screenshot 2023-07-02 at 12 31 26" src="https://github.com/paritytech/substrate/assets/16665596/2b6872ea-a70a-4856-8dcc-1af4721b3e19">

Failing invariant: 

https://github.com/paritytech/substrate/blob/9e8b2f63fb57c5d0fd45da1478508a4509d530e6/frame/nomination-pools/src/lib.rs#L3135-L3139

### Polkadot also has a failing invariant:

https://github.com/paritytech/substrate/blob/9e8b2f63fb57c5d0fd45da1478508a4509d530e6/frame/collective/src/lib.rs#L1038-L1041

## Reproduce

1. Clone `polkadot` and `substrate` into the same dir

2. Sync Kusama (or use a remote node on the next step)

3. Execute
```
cd ../polkadot && cargo build -r -p kusama-runtime --features try-runtime && cd ../substrate && cargo run -r --features=try-runtime try-runtime --runtime ../polkadot/target/release/wbuild/kusama-runtime/kusama_runtime.wasm execute-block live --uri ws://localhost:9944
```

## TODO
- [ ] also check polkadot/westend/rococo

**Comment by kianenigma** [comment]
> This could be a dispatchable function doing what try state is doing, calculate reward of each pool member and hence the deficit in the reward account and allow a permissionless topup. Does that make sense?

We certainly cannot iterate over all pool members of a pool in a dispatchable.

**Comment by kianenigma** [comment]
> Also note that there is another way to fix the issue for future (which I personally like) but it won't fix the deficits of the existing pools. If we never allow last_recorded_total_payouts to decrease (which makes sense, we can never take back what's already paid out), then the current reward counter would not jump abruptly, and any future staking rewards would go on towards first fixing the deficit. I tried this solution [here](https://github.com/paritytech/substrate/blob/ankan/np-bug-reward-deficit/frame/nomination-pools/src/lib.rs#L1312) (its commented out but if we put it in code, the deficit gets fixed automatically).

This is an interesting fix and one that we can explore. If this is the long term approach, I agree that a one-off migration might be better and then we won't deal with this ever again. If not, I am still of the opinion that a one-off migration is too short sighted.

**Comment by Ank4n** [comment]
[ #1236 ](https://github.com/paritytech/polkadot-sdk/pull/1236) helps avoid try-state erroring because of the deficit in reward. But the actual fix for topping up the reward deficit as well as having a way in future to manage changes in ED will be taken care in [this PR](https://github.com/paritytech/polkadot-sdk/pull/1255).
