### ISSUE TITLE
pallet-xcm: enhance `reserve_transfer_assets` to support all types of reserves

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot-sdk#1584]
## Context

When reserve transferring asset `A` from chain `X` to chain `Y`, the reserve location for `A` can fall in one of three scenarios:
1. `LocalReserve`: reserve is on source chain `X` (`Here`),
2. `DestinationReserve`: reserve is on target/destination chain `Y`,
3. `ThirdPartyReserve`: reserve is on third-party chain `Z`.

## Problem

Currently, `pallet-xcm::reserve_transfer_assets()` extrinsic only covers scenario `1` above - even worse, it automatically assumes it is being called under scenario 1, without doing all the proper checks.

This is very limiting in terms of reserve-based transfers supported by `pallet-xcm`.

## Solution proposal

Enhance `pallet-xcm::reserve_transfer_assets()` with support for all scenarios above - it should figure out by itself which scenario it is operating under based on input parameters (ideally without changing function/call API).

Once it figures out which scenario it is operating under, implement the following:

### LocalReserve

Reserve is local chain `reserve_chain == source_chain`.

Same as current implementation:
```rust
let context = T::UniversalLocation::get();
let fees = assets.get(fee_asset_item).reanchored(&dest, context);
Xcm(vec![TransferReserveAsset {
	assets,
	dest,
	xcm: Xcm(vec![
		BuyExecution { fees, weight_limit },
		DepositAsset { assets: Wild(AllCounted(max_assets)), beneficiary }
	]),
}])
```

### DestinationReserve

Implementation when `reserve_chain == destination_chain`:
```rust
let context = T::UniversalLocation::get();
let fees = assets.get(fee_asset_item).reanchored(&dest, context);
Xcm(vec![
	WithdrawAsset(assets),
	InitiateReserveWithdraw {
		assets: Wild(AllCounted(max_assets)),
		reserve: dest,
		xcm: Xcm(vec![
			BuyExecution { fees, weight_limit },
			DepositAsset { assets: Wild(AllCounted(max_assets)), beneficiary }
		]),
	},
])
```

### ThirdPartyReserve

Implementation when `reserve_chain != source_chain && reserve_chain != destination_chain`:
```rust
let context = T::UniversalLocation::get();
let reserve_fees = assets.get(fee_asset_item).reanchored(&reserve, context);
let dest_fees = assets.get(fee_asset_item).reanchored(&dest, context);
let dest = dest.reanchored(&reserve, context);
Xcm(vec![
	WithdrawAsset(assets),
	InitiateReserveWithdraw {
		assets: Wild(AllCounted(max_assets)),
		reserve,
		xcm: Xcm(vec![
			BuyExecution { fees: reserve_fees, weight_limit },
			DepositReserveAsset {
				assets: Wild(AllCounted(max_assets)),
				dest,
				xcm: Xcm(vec![
					BuyExecution { fees: dest_fees, weight_limit },
					DepositAsset { assets: Wild(AllCounted(max_assets)), beneficiary }
				]),
			},
		]),
	},
])
```

**Comment by acatangiu** [comment]
Looking at the [xtokens implementation](https://github.com/open-web3-stack/open-runtime-module-library/blob/2b41f29e749fda52522cb4c7ea0e47f517f6a59d/xtokens/src/lib.rs#L583-L608), I realize for `ThirdPartyReserve` scenario we need to send XCM programs described above **twice** if transferred asset(s) reserve is different than _fee-asset_ reserve, once to the reserve1 then dest, second to fee-reserve then dest.

**Comment by acatangiu** [comment]
Will actually try to make it more general-purpose and send as many XCM programs as required to as many reserves as are required to transfer all assets.

**Comment by acatangiu** [comment]
Transfers will check [IsReserve/IsTeleport](https://github.com/paritytech/polkadot-sdk/blob/a33d7922f8f0f6a4887b5638f2bc09f578b6e2e8/cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs#L482-L489) to reason whether to teleport or reserve-transfer the asset to the destination.

**Comment by acatangiu** [comment]
> Transfers will check [IsReserve/IsTeleport](https://github.com/paritytech/polkadot-sdk/blob/a33d7922f8f0f6a4887b5638f2bc09f578b6e2e8/cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs#L482-L489) to reason whether to teleport or reserve-transfer the asset to the destination.

Proposed logic:
```rust
if IsTeleporter::contains(asset, dest) {
	// we trust destination for teleporting asset
	return TransferType::Teleport
} else if IsReserve::contains(asset, dest) {
	// we trust destination as asset reserve location
	return TransferType::DestinationReserve
}

// try to determine reserve location based on asset id/location
let asset_location = match asset.id {
	Concrete(location) => location.chain_location(),
	_ => fail!(),
};
if asset_location == MultiLocation::here() || IsTeleporter::contains(asset, &asset_location) {
	// local asset, or remote location that allows local teleports => local reserve
	TransferType::LocalReserve
} else if IsReserve::contains(asset, &asset_location) {
	// remote location that is recognized as reserve location for asset
	TransferType::RemoteReserve(asset_location)
} else {
	// remote location that is not configured either as teleporter or reserve => cannot
	// determine asset reserve
	Error::<T>::UnknownReserve
}
```

**Comment by bkontur** [comment]
> We need a filter to say for `asset` and `target` combo, do we teleport or do we reserve-transfer?

In the very first version of asset transfer with custom extrinsic, exactly for this I had [trait ResolveAssetTransferKind](https://github.com/paritytech/cumulus/pull/2013/files#diff-194004fb95867d9a69623d4667f63e71602df1f7cdd93815536b855a965f815bR29-R38):
```
pub trait ResolveAssetTransferKind {
	fn resolve(asset: &MultiAsset, target_location: &MultiLocation) -> AssetTransferKind;
}
```
which was part of [pallet's Config](https://github.com/paritytech/cumulus/pull/2013/files#diff-e33e5afc30ebd89df96d4630222efd1c686a38185d23c958d94d5f6fbebdf6feR119-R120):
```
/// Transfer kind resolver for `asset` to `target_location`.
type AssetTransferKindResolver: ResolveAssetTransferKind;
```

My basic idea was to move _IFs_ like `IsReserve::contains` or `IsTeleporter::contains` out of extrinsic implementation to be more generic and also to give possibility to create runtime dependent logic for resolving supported transfer kinds or maybe disable all like `type AssetTransferKindResolver = ()` or `type AssetTransferKindResolver = Nothing`. And here was some [basic implementation of ResolveAssetTransferKind](https://github.com/paritytech/cumulus/pull/2013/files#diff-b5da0a36061b7247bbf988a1a2e09c03501011ae9ef51dc7ae16e04e2e3d85f4R127-R185).

**Comment by bkontur** [comment]
> The existing [IsTeleporter](https://github.com/paritytech/polkadot-sdk/blob/a33d7922f8f0f6a4887b5638f2bc09f578b6e2e8/cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs#L486-L489) is configured in xcm_executor::Config but not available to pallet-xcm.

>  type XcmExecutor: ExecuteXcm<<Self as SysConfig>::RuntimeCall> + AssetFilters;


So this `trait ResolveAssetTransferKind` is just an idea how to separate [_Proposed logic_ above](https://github.com/paritytech/polkadot-sdk/issues/1584#issuecomment-1734102496) out of `pallet_xcm` and do not make it `ExecuteXcm`-dependent. Also with this solution, we dont need `IsTeleporter` / `IsReserve` in `pallet_xcm`. And probably generic `pallet_xcm` should not do unnecessary assumptions about `type XcmExecutor: ExecuteXcm`.

For example, lets say that any other team is working on their own implementation of `ExecuteXcm` and they dont need reserve-transfer but they need pallet_xcm, so with `+ AssetFilters` we will enforce them to implement dummy `AssetFilters`. So maybe something like `type AssetTransferKindResolver = ()` is better for them.

**Comment by acatangiu** [comment]
> > The existing [IsTeleporter](https://github.com/paritytech/polkadot-sdk/blob/a33d7922f8f0f6a4887b5638f2bc09f578b6e2e8/cumulus/parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs#L486-L489) is configured in xcm_executor::Config but not available to pallet-xcm.
> 
> > type XcmExecutor: ExecuteXcm<::RuntimeCall> + AssetFilters;
> 
> So this `trait ResolveAssetTransferKind` is just an idea how to separate [_Proposed logic_ above](https://github.com/paritytech/polkadot-sdk/issues/1584#issuecomment-1734102496) out of `pallet_xcm` and do not make it `ExecuteXcm`-dependent. Also with this solution, we dont need `IsTeleporter` / `IsReserve` in `pallet_xcm`. And probably generic `pallet_xcm` should not do unnecessary assumptions about `type XcmExecutor: ExecuteXcm`.
> 
> For example, lets say that any other team is working on their own implementation of `ExecuteXcm` and they dont need reserve-transfer but they need pallet_xcm, so with `+ AssetFilters` we will enforce them to implement dummy `AssetFilters`. So maybe something like `type AssetTransferKindResolver = ()` is better for them.

I thought about this, but ultimately decided against it because moving it to runtime configuration means basically duplicating `IsTeleporter` and `IsTrusted` at the runtime xcm_config level -> duplicated code + chances for the two (xcm-executor::config & pallet-xcm::config) to become out of sync.

The  used `trait AssetTransferFilter` is implemented on [XcmExecutor](https://github.com/paritytech/polkadot-sdk/tree/master/polkadot/xcm/xcm-executor). Using any custom executor allows you to also implement custom `AssetTransferFilter` so if your executor doesn't care about transfers, then `AssetTransferFilter = ()`.

But this way, all runtimes that are using [XcmExecutor](https://github.com/paritytech/polkadot-sdk/tree/master/polkadot/xcm/xcm-executor), automatically get `AssetTransferFilter` which is already configured to match the executor's capabilities (config/knowledge of teleporters and reserves).

**Comment by acatangiu** [comment]
We could move [this transfer type resolver](https://github.com/paritytech/polkadot-sdk/issues/1584#issuecomment-1734102496) from `pallet-xcm` into `xcm-executor` and expose just `resolve_transfer_type(asset, dest)` through executor `trait AssetTransferFilter` impl.

Either way, I still believe this should be tied to the executor - it ultimately holds the logic for handling all transfer-related XCM instructions and already uses `IsTeleport` and `IsReserve` to reason about what works how. So it makes sense to expose this stuff, make it clear what the executor's requirements and capabilities are instead of leaving it to runtime developers to manually try to match them when configuring XCM transfers pallets (like pallet-xcm).
