### ISSUE TITLE
Validator disabling in `statement-distribution` subsystem

### ISSUE THREAD

**Issue by tdimitrov** [paritytech/polkadot-sdk#1591]
Followup from https://github.com/paritytech/polkadot-sdk/pull/1259#issuecomment-1714293443

`statement-distribution` should be the main point where validator disabling is enforced. The subsystem should not accept, request, or distribute statements from disabled validators.

A modification to the statement-dist StatementStore would do most of the heavy-lifting here - three parts:

1. StatementStore: generate request bitmasks which exclude disabled validators
2. StatementStore reject statements related to disabled validators
3. Manifest handling: do not count disabled validators towards the seconded & backing thresholds in the advertised bitmask. Likewise in request handling: skip disabled validators' statements in the response.

Part of https://github.com/paritytech/polkadot-sdk/issues/784

**Comment by Overkillus** [comment]
Partially superseded by the new logic in preparation for re-enabling (we now use relay parent state instead of union of leaves). See: https://github.com/paritytech/polkadot-sdk/issues/4744
