### ISSUE TITLE
Runtime error when upgrade kusama to v1.1.0

### ISSUE THREAD

**Issue by nuaays** [paritytech/polkadot-sdk#1608]
we encoutered the transfer erro when upgraded to kusama v1.1.0
![图片](https://github.com/paritytech/polkadot-sdk/assets/1469585/07b628d2-563a-4045-b973-2978ed1d0adb)

 the corresponding error of kusama node was as follows
`ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to validate_transaction: ', /Users/gav/Core/polkadot/runtime/src/lib.rs:635:1`

**Comment by ggwpez** [comment]
Duplicate of https://github.com/paritytech/polkadot/issues/7555.
