### ISSUE TITLE
restore disable-runtime-api

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1621]
Removed at https://github.com/paritytech/polkadot-sdk/pull/1328 but we still need it

              A proper solution will be changes `disable-runtime-api` to `enable-runtime-api` and make it enabled by default so that new feature means add functionality, not the other way around.

_Originally posted by @xlc in https://github.com/paritytech/polkadot-sdk/issues/1328#issuecomment-1724808904_

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/wasm-view-functions/1045/7

**Comment by Ank4n** [comment]
cc: @NachoPal @bkchr

**Comment by bolajahmad** [comment]
There's a [commit here](https://github.com/paritytech/polkadot-sdk/commit/730f955b2c443d331065f88d67e8963efc9af9b4#diff-e31fc2788dafe7c3c260538ddc29864bdeb56f8b8955ee67fb4b21ce1f83f1df) that removes the `disable-runtime-api`. 
The solution should involve sort of a reversal of the changes here, am I right @xlc ?

**Comment by xlc** [comment]
yes

**Comment by xlc** [comment]
not needed anymore
