### ISSUE TITLE
Import runtime Call / Storage metadata without import the whole runtime

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#1624]
Previous issue: https://github.com/paritytech/substrate/issues/8158

In order to use XCM::Transact, we need to know how to encode the call on destination chain. The best way should be just import the Call enum from runtime. But we cannot do it because last time we tried, it tries to import the whole Rococo runtime into our parachain runtime, which obviously wouldn't work.

We should have some way to allow others to import some generated types from runtime, without import the whole thing.

Not exactly sure how it can be implemented though, all the generic makes thing harder. One potential solution is reconstruct the enum from metadata and expose them.

**Comment by bkontur** [comment]
For something very similar, we used [subxt-codegen library](https://github.com/paritytech/subxt/tree/master/codegen) which has ability to generate runtime Call metadata at least (I am not sure about Storage), generated file looks like [this](https://github.com/paritytech/parity-bridges-common/blob/master/relays/client-bridge-hub-rococo/src/codegen_runtime.rs).
E.g. you can generate metadata from live running node or from downloaded wasm file (maybe there are also other options), we integrated just these two options [here](https://github.com/paritytech/parity-bridges-common/tree/master/tools/runtime-codegen).

**Comment by bkchr** [comment]
Actually a very good point @bkontur.

This means the issue can be closed @xlc?
