### ISSUE TITLE
`AllowTopLevelPaidExecutionFrom` barrier prevents multi currency transfers which also effects `assethub`.

### ISSUE THREAD

**Issue by rimbi** [paritytech/polkadot-sdk#1638]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After [this change](https://github.com/paritytech/polkadot-sdk/commit/26be0727e5aaa5ed569b29bd9a6b043899a5617b), `AllowTopLevelPaidExecutionFrom` prevents multi currency transfers which also effects `assethub`; multi currency transfers are not possible anymore.

Here, also, is [a test case in the orml repo](https://github.com/moonbeam-foundation/open-runtime-module-library/blob/6819d3f28f9005c0a375e359c942490e04e20000/xtokens/src/tests.rs#L393) which failed after upgrading dependencies to `polkadot-v1.1.0` (which includes this change) and  [this is the solution](https://github.com/moonbeam-foundation/open-runtime-module-library/blob/9998244c0f6595c442084de553b9a6a45e18ec1d/xtokens/src/mock/mod.rs#L351) for the problem, which is the exact copy of the old version of the barrier.

**Comment by librelois** [comment]
What was the motivation for limiting the `AllowTopLevelPaidExecutionFrom` barrier, is there a security risk in having multiple assets in the holding register at the BuyExecution step?

**Comment by xlc** [comment]
To my understanding, it is indeed a security risk to allow unbounded asset withdrawal. But limit it to 1 is just too much, especially when the number is non configurable.

**Comment by bkchr** [comment]
@franciscoaguirre @KiChjang please look into this ASAP.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-3-0/4614/1

**Comment by acatangiu** [comment]
This was fixed
