### ISSUE TITLE
[Rococo AssetHub] ReserveTransfer got `Error: Unroutable` from AssetHub to Parachain(2105), channel is opened

### ISSUE THREAD

**Issue by jiguantong** [paritytech/polkadot-sdk#1640]
### Is there an existing issue?

- [X] I have searched the existing issues. But there's no answer. https://substrate.stackexchange.com/questions/9935/xcm-reserve-transfer-between-assethub-rococo-is-unroutable

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### There is an opend channel from AssetHub(1000) to Pangolin(2105).
![image](https://github.com/paritytech/polkadot-sdk/assets/27564714/4517d447-8c2b-4cfe-8995-e918e8b0472f)
### But when transfering token from AssetHub to Pangolin, I got this [error: Unroutable](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/explorer/query/0x946afcd3fcf62f3f82d0c1a8d8c22419432b554ebf18a6c2174c12b40596e486).
![image](https://github.com/paritytech/polkadot-sdk/assets/27564714/11e58e22-9de1-4e7c-b4ca-3a4b95baf1d5)

### Steps to reproduce

1. Open Rococo AssetHub apps: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics
2. Decode this call: `0x1f0801010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000`
3. Submit.

**Comment by bkontur** [comment]
I would set dest with V3 like this: `0x1f0803010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000`

and probably because of missing xcm version here:
![image](https://github.com/paritytech/polkadot-sdk/assets/8159517/abbd415f-b153-4b2b-9857-0bc7f9ea7fe2)

let me try and check

**Comment by bkontur** [comment]
@jiguantong ok, xcm version is fixed and [this call](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f0803010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000) passes, encoded call data:
```
0x1f0803010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000
```
also I just change `dest` to V3,

please, let me now if it works for you.

**Comment by jiguantong** [comment]
> @jiguantong ok, xcm version is fixed and [this call](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f0803010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000) passes, encoded call data:
> 
> ```
> 0x1f0803010100e520030001030105f24ff3a9cf04c71dbc94d0b566f7a27b94566cac03040001000002c2eb0b0000000000
> ```
> 
> also I just change `dest` to V3,
> 
> please, let me now if it works for you.

Great! Thanks!
