### ISSUE TITLE
Cumulus `pov_recovery` zombienet test is not failing when doing recovery with `IfDisconnected::ImmediateError`

### ISSUE THREAD

**Issue by alindima** [paritytech/polkadot-sdk#1647]
This is a regression test for attempting availability recovery if the subsystem is creating chunk requests with `IfDisconnected::ImmediateError` instead of `TryConnect`, but it doesn't fail on regression.

See: https://github.com/paritytech/polkadot-sdk/pull/1457#discussion_r1328443779

The root cause is probably: https://github.com/paritytech/zombienet/issues/1360

**Comment by pepoviola** [comment]
Yes, that issue is root cause. I will create a new release of zombienet today with the fix (https://github.com/paritytech/zombienet/pull/1361).
Thx!!

**Comment by bkchr** [comment]
@pepoviola was this fixed? If yes, please close the issue.

**Comment by pepoviola** [comment]
Yes, closing now. Thx!
