### ISSUE TITLE
Parameters pallet

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#169]
This probably should be alterable via governance. Maybe it's time we introduced a generic Parameters pallet to give a place for all these parameters to sit?

_Originally posted by @gavofyork in https://github.com/paritytech/cumulus/pull/2607#discussion_r1203905861_

A pallet that can implement dynamic `Get<…>` and have configurable origins for modifying those would be nice.  
Otherwise we are restricted to either use `pub storage` which can only be modified by root, or doing in the pallet itself.  
For naming: the word `Parameter` is currently used as trait for function params, so maybe not best.

**Comment by xlc** [comment]
orml-parameters is ready https://github.com/open-web3-stack/open-runtime-module-library/pull/927
Example usage at Acala https://github.com/AcalaNetwork/Acala/pull/2605

**Comment by kianenigma** [comment]
Here's how I would think about this, in terms of the final API: 

```rust
// in some ./runtime/lib.rs
pub struct Parameter1; 
impl FRAMEParameter<u32> for Parameter1 {
    // Something that has to implement `EnsureOrigin`
    type AdminOrigin = ...
    /// Something that is Get<u32> the default value for this parameter if not present in storage. 
    /// (if you update this after the parameter has already been set in storage, it would probably have no effect, but that's an implementation detail)
    type Default = ...
} 

```

**Comment by muharem** [comment]
@xlc nice
I will try it in Collectives and share here with you

**Comment by ggwpez** [comment]
> orml-parameters is ready [open-web3-stack/open-runtime-module-library#927](https://github.com/open-web3-stack/open-runtime-module-library/pull/927) Example usage at Acala [AcalaNetwork/Acala#2605](https://github.com/AcalaNetwork/Acala/pull/2605)

I think we can start using this in Rococ/Westend to try it out (eg. pallet NIS). With Kusama/Polkadot it needs audit first.  
I will prepare something.
