### ISSUE TITLE
fungible/s decrease balance should respect `preservation` argument

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#1698]
At present default implementations of `fungible/s` and `fungible` impl by `balances` pallet do not respect `preservation` argument, and might reap the account even if `preservation` set to `Preserve`.

As result methods like `transfer_and_hold`, `withdraw`, `settle` also might reap the account regardless the argument.

All listed methods above should respect the `preservation` argument.

**Comment by muharem** [comment]
might be addressed here https://github.com/paritytech/polkadot-sdk/pull/1683 or here https://github.com/paritytech/polkadot-sdk/pull/1296

need this issue to reference in TODO

cc: @liamaharon

**Comment by liamaharon** [comment]
@muharem happy to get it merged in your PR since mine is taking a long time to get a review

**Comment by muharem** [comment]
solved here - https://github.com/paritytech/polkadot-sdk/pull/1296
