### ISSUE TITLE
Hardcoded `type Hash = H256` in Preimages traits 

### ISSUE THREAD

**Issue by muraca** [paritytech/polkadot-sdk#1701]
QueryPreimage and StorePreimage traits use a hardcoded Hash type set to H256 https://github.com/paritytech/polkadot-sdk/blob/b18fb35e0dada9a23761f511d502b9a73fac9593/substrate/frame/support/src/traits/preimages.rs#L27 

Pallet Preimage itself is bounding to this trait I think the opposite way as it should be https://github.com/paritytech/polkadot-sdk/blob/b18fb35e0dada9a23761f511d502b9a73fac9593/substrate/frame/preimage/src/lib.rs#L534

As I was working on #1445 I incurred in this issue, and I was forced to do some weird things that include
```rust
let proposal_hash: PreimageHash = 
    Decode::decode(&mut &T::Hashing::hash_of(&proposal).encode()[..])
        .expect("Hash length is always 32; qed");
```
and opposite
```rust
if new_hash != PreimageHash::from_slice(hash.as_ref()) {
    // ...	
}
```

or having to use `BlakeTwo256` explicitly instead of `T::Hashing` in tests/benchmarks.

I think it can be fixed by removing the hardcoded type, and putting a `type Hash` in the traits, to be used like
```rust
impl<T: Config> QueryPreimage for Pallet<T> {
    type Hash = T::Hash;
    // ...
}
``` 
Should I proceed? If so, should I handle it in #1445 or is it better to open a new PR on which it will depend?

@kianenigma

**Comment by bkchr** [comment]
Yeah sounds like something that could be made generic. Please create a separate pr for it.

**Comment by kianenigma** [comment]
> Should I proceed? If so, should I handle it in https://github.com/paritytech/polkadot-sdk/pull/1445 or is it better to open a new PR on which it will depend?

Yes looks reasonable to me. I suggest proceeding as a small separate PR 👍

**Comment by ggwpez** [comment]
Just FYI this was done somewhat intentional though:  
<img width="527" alt="Screenshot 2023-09-27 at 15 07 33" src="https://github.com/paritytech/polkadot-sdk/assets/10380170/9c8edba2-5c5c-4553-9af2-54bf4787c944">

https://github.com/paritytech/substrate/pull/11649/files#r905676844
