### ISSUE TITLE
async backing: collator memory leak

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#1702]
During a load test of PR https://github.com/paritytech/polkadot-sdk/pull/1635 this happened: https://grafana.teleport.parity.io/goto/AQpVJvWIR?orgId=1

**Comment by bkchr** [comment]
Maybe not related to async backing: https://github.com/paritytech/polkadot-sdk/issues/1662

**Comment by eskimor** [comment]
This one is fixed - right?

**Comment by Sophia-Gold** [comment]
Fixed according to @sandreim
