### ISSUE TITLE
FRAME: Syntax for marking calls "feeless"

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#1725]
Moving an internal FRAME team discussion to a Github issue.

## Motivation

@gavofyork suggested a new syntax which can be used before a call and have it mean that it can skip all normal transaction fee and account existence requirements.

```rust
#[pallet::feeless_if(|origin: &OriginFor<T>, ticket: &Ticket| -> bool {
	let account = ensure_signed(origin.clone())?;
	some_conditions_here(&account, &ticket)
})]
```

@gupnik volunteered to work on it.

## Solution

@gupnik suggested a solution and requested feedback:

1. Pallet Call enum can optionally have a feeless conditional.
2. Construct Runtime creates a `RuntimeSignedExtension` that takes `OnChargeTransaction`.
3. In `post_dispatch`, we check if the current call has a feeless conditional. If so, the fee is never charged (bypassing the requirement the caller has any balance).

A couple of questions

1. How can `RuntimeSignedExtension` know the amount that was charged originally?
2. Is there a way to test the entire flow using a unit test? Any references that I could use?

## Other questions

- @KiChjang suggested rather than an attribute macro this could be implemented in a way more 'rustic'.
- @liamaharon considered rather than the method returning a `bool`, it returning a `Balance` which could be used to modify the fee in more than a single way way.

**Comment by bkchr** [comment]
> * Pallet Call enum can optionally have a feeless conditional.
> 
> * Construct Runtime creates a `RuntimeSignedExtension` that takes `OnChargeTransaction`.
> 
> * In `post_dispatch`, we check if the current call has a feeless conditional. If so and the condition returns true, the fee is refunded.

All this is already supported by returning [`Pays::No`](https://github.com/paritytech/polkadot-sdk/blob/da937d9f6353e36fdc493a63a319c7d6d259483c/substrate/frame/beefy/src/lib.rs#L234).

**Comment by liamaharon** [comment]
> > * Pallet Call enum can optionally have a feeless conditional.
> > * Construct Runtime creates a `RuntimeSignedExtension` that takes `OnChargeTransaction`.
> > * In `post_dispatch`, we check if the current call has a feeless conditional. If so and the condition returns true, the fee is refunded.
> 
> All this is already supported by returning [`Pays::No`](https://github.com/paritytech/polkadot-sdk/blob/da937d9f6353e36fdc493a63a319c7d6d259483c/substrate/frame/beefy/src/lib.rs#L234).

Oh cool, thanks for pointing that out. I like this solution better than the one proposed because it doesn't require duplicating params.. 

Do you know if it also waives ED requirements?

**Comment by liamaharon** [comment]
This implementation first takes the fee from the user then refunds it at the end, requiring the account exists. 

I wonder if it can be amended so this is not the case?

**Comment by kianenigma** [comment]
I would take this as an opportunity and rethink how much we leak the concept of transaction payment into pallets. 

At the moment, we seem to have one foot in, by allowing pallets to return `Pays::No`, while we have one foot outside by not enforcing any `pallet-transaction-payment` to exist in the runtime. If I am not mistaken, if no `pallet-transaction-payment` (or similar) exists, then `Pays::_` is a noop and is totally ignored. I think this is not a great design and is somewhat difficult to explain to others. 

I am not sure if something cleaner can be conceptualized, but my gut feeling is that we can do better.

**Comment by liamaharon** [comment]
Moreover, @Ank4n correctly pointed out that `Pays::No` requires the caller has funds to make the call, and it is refunded at the end so it does not fit the requirements.

Given how the existing syntax is also potentially treacherous based on your comment @kianenigma, perhaps the `Pays` syntax can be deprecated in favour of this new API. I feel it could be confusing to have both APIs given they both do very similar things.

**Comment by bkchr** [comment]
> Moreover, @Ank4n correctly pointed out that `Pays::No` requires the caller has funds to make the call, and it is refunded at the end so it does not fit the requirements.

> 3\. In `post_dispatch`, we check if the current call has a feeless conditional. If so and the condition returns true, the fee is refunded.

You described exactly the same in the OP. If you return it in `post_dispatch`, it requires that users pay the fees first.

If you want to make a transaction completely fee-less, you can also pass `Pays::No` to the pre-dispatch weight. However, this is a huge footgun and you will need some custom `SignedExtension`. I know that you probably want to replace this custom `SignedExtension` with `feeless_if`. However, we will then need to document this really good as otherwise you have a nice DOS.



> At the moment, we seem to have one foot in, by allowing pallets to return `Pays::No`, while we have one foot outside by not enforcing any `pallet-transaction-payment` to exist in the runtime. If I am not mistaken, if no `pallet-transaction-payment` (or similar) exists, then `Pays::_` is a noop and is totally ignored. I think this is not a great design and is somewhat difficult to explain to others.

I mean giving the programmer the possibility to make the transaction pay back the fees, sounds not that unreasonable. I mean we could probably support this from the runtime level. Shouldn't be that hard. But in general the concept of paying fees isn't such a weird concept in blockchains, that we could not have this included "deep in the system". That the logic higher in the stack then decides on the actual payment also sounds reasonable to me.

**Comment by xlc** [comment]
Can we have some use cases? 
I really don't like this syntax. It is not IDE friendly.
We can already achieve this with existing constructs, so this is just a syntax sugar. Again, what are the expected usages to justify the work and the new syntax overhead?

**Comment by gupnik** [comment]
> If you want to make a transaction completely fee-less, you can also pass Pays::No to the pre-dispatch weight. However, this is a huge footgun and you will need some custom SignedExtension. I know that you probably want to replace this custom SignedExtension with feeless_if. However, we will then need to document this really good as otherwise you have a nice DOS.

Thanks, this provides a bit more clarity, but I am still trying to understand how this will play with the existing signed extensions like `ChargeTransactionPayment` or `ChargeAssetTxPayment`.  

One way could be to actually start using Pays::No in pre-dispatch weight (as you suggested) so that these extensions do not try to deduct any fees. In that case, the new signed extension would entirely be responsible for deducting the fees if the conditions are not met. IIUC, this is why you mentioned that this can be a huge footgun.

The second would be to modify these extensions themselves or make the new one as a wrapper that first validates the conditions and chooses to delegate to these extensions if needed. This seems to add more coupling though, which might not be desirable.

> @gupnik do you have a clearer idea of how this is going to work?

I am still trying out a few approaches, but unable to nail it down yet. Please let me know if you have some thoughts on the two mentioned above.

> We can already achieve this with existing constructs, so this is just a syntax sugar. 

If my understanding as stated above is correct, the current constructs would need to be modified and duplicated heavily if someone wants to achieve this. Is there an easier way that I am missing out?

**Comment by kianenigma** [comment]
> I mean giving the programmer the possibility to make the transaction pay back the fees, sounds not that unreasonable. I mean we could probably support this from the runtime level. Shouldn't be that hard. But in general the concept of paying fees isn't such a weird concept in blockchains, that we could not have this included "deep in the system". That the logic higher in the stack then decides on the actual payment also sounds reasonable to me.

The direction that I am thinking is that things like `Pays` and `PostDispatchInfo` should not be random types that you use and hope someone higher in the stack uses them, but instead should be done through, for example, `type TransactionPayment: TransactionPayment` that is coming from system. `trait TransactionPayment` would standardize what operations you can do with respect to payment, such as `Pays` etc. If `type TransactionPayment = ()` all of this is set to noop. 

This is functionally the same as what we have now, but I find a better grounding to then build more things on top of.

**Comment by xlc** [comment]
I would just use unsigned transactions, which doesn’t pay fees. But I need more context to known if this is the right solution. Otherwise we could modify transaction payment pallet to skip deduct fees for some calls as well.

**Comment by bkchr** [comment]
> The direction that I am thinking is that things like `Pays` and `PostDispatchInfo` should not be random types that you use and hope someone higher in the stack uses them, but instead should be done through, for example, `type TransactionPayment: TransactionPayment` that is coming from system. ``

I don't really get what you want to achieve here. As @xlc said, could you please provide a proper example on what you want to have this look like.

**Comment by gavofyork** [comment]
For what it's worth, this is my request.

This specific functionality is all perfectly possible to do within a `SignedExtension`/`ValidateUnsigned` and this "only" allows for a more elegant means of expressing that pattern (or, to put it more dismissively, it is merely syntactic sugar).

The reason we want this abstraction and API is the same reason we build high-level APIs: **to make common and conceptually simple things easy**. Saying "it's already possible to do this using X, Y or Z" is irrelevant. The point is that it's difficult, tedious and error-prone, leading to reduced maintainability and functionality.

Specifically, if you have many calls over many pallets each with its own specific logic for determining when a transaction can be made totally free, then it ends up being a huge amount of logic and duplication which is very difficult to modularize. You end up with logic very specific to the dispatchable appearing elsewhere in the module in a `SignedExtrinsic` implementation; unless you pull them apart into multiple `SignedExtension` impls (which causes a greater chance of errors in the runtime amalgam in case you miss one), then the logic of each free-dispachable will end up clumped together. You end up having to manually do destructuring of a two-tier `Call` enum to decode and inspect params and you have to do all this for every pallet, not to mention include each new pallet's `SignedExtension` in every runtime config which uses them. All of this is error prone and cumbersome.

An improper parameter to `feeless_if` will indeed have the potential to cause a DoS. However, it's really no worst than returning `Pays::No` in a problematic place, which it would in some cases replace. Many other parts of Frame dispatch and weights (such as benchmarking) are trickier to get right, so this wouldn't be worst offender by some distance. And the alternative, attempting to achieve this pattern using `SignedExtension`, is so cumbersome that introducing this as a well-supported and documented piece of functionality would likely reduce the overall chance of DoS.

**Comment by gavofyork** [comment]
For what it's worth, the issue descri[ption is not what I asked for:

> In `post_dispatch`, we check if the current call has a feeless conditional. If so and the condition returns true, the fee is refunded.

The whole point of this is that the sender account need not exist. Thus they must not be required to pay fees. Thus a fee cannot be "refunded" if it was never paid.

We probably want to implement it as a wrapper around the regular fee-payment `SignedExtension`s (there's at least three now for single currency payment and a couple of multi-currency payments). It should be generic over what it's wrapping and basically be a `struct SkipCheckIfFeeless<MaybeSkipCheck: SignedExtension>`.

**Comment by xlc** [comment]
@gavofyork could you explain a bit more why we want this approach instead of unsigned tx, which is also feeless? If it is only too complicated to implement unsigned tx, then we should just improve it instead.

One use case I can think of is to allow members of a collective to dispatch some tx without paying fees. But it is easier to just fund ED + tx fee to those accounts?

**Comment by gavofyork** [comment]
@xlc I already pointed out why this approach is superior in a pretty comprehensive fashion. If you have specific retorts to make or specific points you're unclear about, please do ask.

I've no idea what "improvement" you could possibly mean with "just improve it instead" which both addresses all the points I made above and also keep backwards compatibility.

`ValidateUnsigned` is not designed to enable specifically this pattern very succinctly. It's an extremely general and low-level API. That makes it possible but not easy. _A good API should make common and conceptually things easy_.

Furthermore this is not about allowing specifically *unsigned* transactions. It's about removing the need for an signing account to already be in existence at the time of fee-payment. The fact it is signed (and thus that we have a caller account) is still quite useful.

**Comment by liamaharon** [comment]
> For what it's worth, the issue description is not what I asked for:

My mistake, I've updated the description.

**Comment by gupnik** [comment]
In @ggwpez's discussion with @gavofyork, it was suggested to keep the first argument as origin for idiomatic purposes. I have modified the PR accordingly.
