### ISSUE TITLE
[Deprecation] `GenesisConfig` -> `RuntimeGenesisConfig`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#175]
We renamed many of the composite enums such that the outer one is called `RuntimeXXX` eg https://github.com/paritytech/substrate/pull/11981, but we seem to have missed this one. 

Like other deprecations, we should keep the old name, but mark its usage is deprecated eg https://github.com/paritytech/polkadot-sdk/issues/182

```[tasklist]
### Deprecation steps
- [x] Soft deprecation and removal from the codebase https://github.com/paritytech/substrate/pull/14210
- [x] Update examples and tutorials https://github.com/substrate-developer-hub/substrate-docs/issues/1996
- [x] Hard deprecation by adding a deprecate compiler warning https://github.com/paritytech/substrate/pull/14224
- [x] Deprecation is noted in the release log
- [x] Removal version is planned -> after 16 Dec
- [ ] Deprecated feature is removed from the code base
- [ ] Removal of the feature is noted in the release log
```

**Comment by kianenigma** [comment]
Yes, you should fully remove https://github.com/paritytech/polkadot-sdk/blob/878c562cd48dd30f412dc493e250ccf46d9773cf/substrate/frame/support/procedural/src/construct_runtime/expand/config.rs#L81 and fix any issues, which I don't think will be that many.

**Comment by RomarQ** [comment]
@kianenigma I created https://github.com/paritytech/polkadot-sdk/pull/3378 for removing the `GenesisConfig` deprecated type, the changes were minimal. 

If I missed something, please let me know.

**Comment by philoniare** [comment]
@RomarQ I believe you should be updating `GenesisConfig` to `RuntimeGenesisConfig` in pallets as well. There's quite a few pallets that still use `GenesisConfig`, so you'll need to update those. I've taken a quick look and identified the below:
```
system
aura
assets
babe
beefy
broker
glutton
grandpa
indices
lottery
mixnet
nfts
nis
salary
benchmarking
society
staking
sudo
treasury
```

**Comment by RomarQ** [comment]
> @RomarQ I believe you should be updating `GenesisConfig` to `RuntimeGenesisConfig` in pallets as well. There's quite a few pallets that still use `GenesisConfig`, so you'll need to update those. I've taken a quick look and identified the below:
> 
> ```
> system
> aura
> assets
> babe
> beefy
> broker
> glutton
> grandpa
> indices
> lottery
> mixnet
> nfts
> nis
> salary
> benchmarking
> society
> staking
> sudo
> treasury
> ```

No, there is no point in renaming the struct in these pallets to `RuntimeGenesisConfig`. The change was specific to the deprecated type, which was removed in the PR mentioned above.
