### ISSUE TITLE
SubscribeVersion from the Relay will be blocked by new parachains

### ISSUE THREAD

**Issue by mrshiposha** [paritytech/polkadot-sdk#1756]
The Relay chain [uses the `WithUniqueTopic` router](https://github.com/paritytech/polkadot-sdk/blob/f60318f68687e601c47de5ad5ca88e2c3f8139a7/polkadot/runtime/polkadot/src/xcm_config.rs#L123C22-L123C37), which [adds a `SetTopic` instruction](https://github.com/paritytech/polkadot-sdk/blob/bf90cb0b73a2d2e0b3e79b2956256831ae79c9f7/polkadot/xcm/xcm-builder/src/routing.rs#L44-L51) to every XCM message the Relay sends if the message doesn't end with such an instruction already.

This could break the XCM version subscriptions for new parachains that didn't receive the `SubscribeVersion` in the past.

The `SubscribeVersion` message will also be augmented with the `SetTopic` instruction. Currently, the `AllowSubscriptionsFrom` barrier used by the parachains [forbids any message that contains anything but the `SubscribeVersion`/`UnsubscribeVersion` instruction](https://github.com/paritytech/polkadot-sdk/blob/f60318f68687e601c47de5ad5ca88e2c3f8139a7/polkadot/xcm/xcm-builder/src/barriers.rs#L367-L371). So, any `SubscribeVersion` or `UnsubscribeVersion` from the Relay chain will be blocked.

**Comment by bkchr** [comment]
CC @franciscoaguirre

**Comment by franciscoaguirre** [comment]
That sounds bad, I'll look into it

**Comment by bkontur** [comment]
@mrshiposha Yes, you're right. `AllowSubscriptionsFrom` accepts just `SubscribeVersion` / `UnsubscribeVersion`, but there is a [`TrailingSetTopicAsId` barrier](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/xcm-builder/src/barriers.rs#L213-L240), which is exactly designed to handle this `SetTopic` added by `WithUniqueTopic` router. Therefore, the parachain should wrap its barrier with `TrailingSetTopicAsId`, for example: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs#L485-L506. Anyway, the parachain still has the possibility to write custom barriers according to its needs.

And it is not a specific problem of the RelayChain, this can happen between any chains when using the `WithUniqueTopic` wrapper for `SendXcm` between them.

I've just added more tests for these barriers here: https://github.com/paritytech/polkadot-sdk/pull/3955.

**Comment by mrshiposha** [comment]
Oh, I forgot I filed this issue :)
Thanks for the response, @bkontur! I used the `TrailingSetTopicAsId` barrier in the Unique Network chain as a fix but forgot to comment here.

It's great to have tests to check that version subscriptions work. IIRC, I filed this issue because the subscription mechanism was unexpectedly broken in our chain when Relay suddenly changed its behavior.

**Comment by bkontur** [comment]
> I filed this issue because the subscription mechanism was unexpectedly broken in our chain when Relay suddenly changed its behavior.

@mrshiposha Thank you for reporting! Yeah, got it. I hope that similar issues will be avoided with our improved release notes, including this kind of breaking change.
