### ISSUE TITLE
Parachains zombienet fails on local machines

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#1765]
The error I'm getting when running zombienet locally is:
```
WARN tokio-runtime-worker parachain::pvf: cannot bind unix socket: Custom { kind: InvalidInput, 
error: "path must be shorter than libc::sockaddr_un.sun_path" } 
debug_id=prepare program_path="/home/alexggh/repos/polkadot-sdk/target/testnet/polkadot-prepare-worker" 
extra_args=["prepare-worker", "--node-impl-version", "1.1.0"] 
worker_dir=WorkerDir { path: "/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO/alice/data/chains/rococo_local_testnet/db/full/pvf-artifacts/worker-dir-prepare-2Q4B1v7qio" } 
socket_path="/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO/alice/data/chains/rococo_local_testnet/db/full/pvf-artifacts/worker-dir-prepare-2Q4B1v7qio/socket"
```

This is because by default zombienet decides to prefix things with `/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO` and that gets us past the socket limitation size.

## Workaround

This can be easily worked around by just specifying explicitly a shorter prefix on zombienet with:
```
zombienet -d /tmp/x/ <your_zombienet_params>
```

This was introduced with https://github.com/paritytech/polkadot-sdk/pull/1373 fyi @mrcnski and it wasn't caught by the CI because it has a shorter prefix. 

Given that we can't really control what prefix paths our users decide to use or already have configured on their validators I think we should try to either prevent this limitation or expose(if it doesn't exist already) some cli parameter or environment variable  for users to be able to manually decide this path.

**Comment by mrcnski** [comment]
Ooh, looks like [the limit is 108 bytes](https://man7.org/linux/man-pages/man7/unix.7.html). This should definitely be fixed, because like you say, users are allowed to use an arbitrary cache path. There may be no need for the socket to be under the cache path though, I think we can revert to using a tmp location like we were before.
