### ISSUE TITLE
PR#13769 ProofRecorder: Implement transactional support

### ISSUE THREAD

**Issue by 0xJayPi** [paritytech/polkadot-sdk#1776]
This issue was created to track fixes from [substrate/pull/13769](https://github.com/paritytech/substrate/pull/13769), which was merged before fixing them and is now archived.

[substrate/pull/13769](https://github.com/paritytech/substrate/pull/13769) fixes findings from [srlabs_findings/issues/148](https://github.com/paritytech-secops/srlabs_findings/issues/148)

**Comment by bkchr** [comment]
Please stop opening issues for things that aren't an issue anymore.
