### ISSUE TITLE
where is the latest release of polkadot-js corresponding to polkadot-sdk

### ISSUE THREAD

**Issue by nuaays** [paritytech/polkadot-sdk#1808]
Hi, 
Just a question about [polkadot-js](https://github.com/polkadot-js/api), where is the latest release corresponding to polkadot-sdk?
Is it still this repo https://github.com/polkadot-js/api? 
The latest release of https://github.com/polkadot-js/api is several months ago.

**Comment by bkchr** [comment]
There is no connection between the node and polkadot js. Please ask questions in the polkadot js issue tracker.
