### ISSUE TITLE
[Meta/PM] Create a deprecation process

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk#182]
There is a need to define a feature deprecation process.
We can use this issue for a discussion to define the process.

Deprecation process
---
Create a 'deprecation' labeled issue with the following steps:

1. Hard deprecation by adding a warning message *
2. Remove usage of the deprecated feature in the code base
3. Update examples and tutorials
4. Deprecation is noted in the release log
5. Removal version is planned
6. Deprecated feature is removed
7. Removal of the feature is noted in the release log
---

_* The warning message should include a removal month and year which is suggested to be 6 months from the deprecation notice is released. This means that the feature will be removed in a release within that month (or shortly after, but never before)._
E.g.
```rust
#[deprecated(note = "GenesisConfig is planned to be removed in December 2023. Use `RuntimeGenesisConfig` instead.")]
```

**Comment by juangirini** [comment]
> As I could understand from all related threads, there is no decision on whether we should include the deprecation note into the metadata or not. 

A simple approach for now could be to just add the `_deprecated` suffix to the dispatchable.

> One simpler decision that we could do, it is a pattern/suffux for PR titles or/and a label (we could include this info into the issue template with the checklists). This will help with release notes and search.

I like this idea, what would you suggest?

**Comment by kianenigma** [comment]
In general I am not against this and find it useful. 

> if a `#[deprecated]` attribute is there, a deprecated text also exists in the docs (or automatically append it).

My only comment is that I think this should not be a random text string in the doc and therefore metadata, but instead it should be a filed in the metadata for calls, events, errors and storage items. 

There will indeed be a cost to this, as a lot of `deprecated?: false` needs to be appended everywhere, but I suppose we can make it worthwhile with a convention where the lack of this field means it is not deprecated. 

Please make a new issue for this, add the FRAME label, and optionally add it to the [developer wishlist project column](https://github.com/orgs/paritytech/projects/27/views/14) as well, where I am trying to track similar issues. 

@jsdw wdyt?

**Comment by rzadp** [comment]
> Please make a new issue for this, add the FRAME label, and optionally add it to the [developer wishlist project column](https://github.com/orgs/paritytech/projects/27/views/14) as well, where I am trying to track similar issues.

@kianenigma Done, created [this issue](https://github.com/paritytech/polkadot-sdk/issues/4098) and added to the wishlist.
