### ISSUE TITLE
Minimal Parachain Upgrade PVFCheckRejected on Rococo Local Relaychain with Alice and Bob. Why?

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/polkadot-sdk#1824]
@bkchr recommended we open this as an issue to discuss and to document in case other teams come across the same problem.

We have posted the same details [in our repo](https://github.com/totem-tech/totem-parachains/issues/33).

# Description

We are having an issue upgrading our parachain on the `rococo-local` which is causing our parachain upgrade to be rejected on the relaychain side. 

We do not necessarily think this is a relaychain bug, because when we restart our `rococo-local` with `alice` and `bob`, and our restart our parachain, we are able to perform all upgrades up to and including the current live parachain version `1.4.3` with no rejections. 

We have been attempting to update our test parachain with work from other branches but these are getting `paras.PVFCheckRejected`, on `rococo-local`. 

<img width="1493" alt="Pasted Graphic 1" src="https://github.com/totem-tech/totem-parachains/assets/1393274/451630e0-be81-4a3f-ab7e-e942b751e654">

The upgrade is 660kb so should pass.

Also the message in the screenshot is somewhat strange because it shows and extrinsic success _and_ an extrinsic failure. 

---

We created a very minimal upgrade on a new [branch](https://github.com/totem-tech/totem-parachains/tree/minimal-upgrade-1.4.4), bumped to the implementation version `1.4.4` and made a small change in order to test - but this gets rejected on the `rococo-local` relaychain. 

We also tried bumping the implementation version `1.5.0` with this same change but this also gets rejected. We did not push this change to the branch.

Each time we test, we restart networks from scratch to be clean about testing.

We need to understanding why this is failing in our test relaychain and what possible reasons there could be for parachain runtime upgrades to get rejected. It isn't clear from the documentation, but moreso, [a cause is available](https://github.com/paritytech/polkadot-sdk/blob/cb944dc54882222453071fc99f2e5014c51823ef/polkadot/runtime/parachains/src/paras/mod.rs#L1622), unfortunately [it is not used in the event](https://github.com/paritytech/polkadot-sdk/blob/cb944dc54882222453071fc99f2e5014c51823ef/polkadot/runtime/parachains/src/paras/mod.rs#L1620).

This appears therefore that the PVF is not receiving sufficient votes from `alice` and `bob` validators on the relaychain hence it is rejected. 

Other reasons that we can think of (but may not be the case) are that:

* the basic rococo-local does not have enough validators assigned to the parachain (2 maximum?) and therefore cannot acheive enough votes or,

* at least one of the validators is voting against this upgrade for reasons unknown.

Block production is not affected by a PVF rejection, but the parachain is in a state whereby it has overlapping upgrades 

* i.e. an upgrade that has been authorized but not enacted, the PVF code remains in the `parachainSystem.PendingValidationCode`.

# Setup

## Our Rococo Local Relaychain 

When extracting the `rococo-local` in raw format on the current 
`polkadot 1.2 version` using this:

    ./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode --raw > rococo-pdk-local-raw.json

we see this message on extraction just for information:

```
2023-10-09 10:22:35 Building chain spec    
2023-10-09 10:22:35 Took active validators from set with wrong size    
2023-10-09 10:22:35 Took active validators from set with wrong size    
2023-10-09 10:22:35 Took active validators from set with wrong size.    
2023-10-09 10:22:35 Took active validators from set with wrong size 
```

* Notice the third message contains a `.` at the end so actually there are at least two reasons why this message is produced.

Our `rococo-local` relaychain is running [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frelaychain.totem.live#/explorer
)

## Our Lego Parachain

Our `totem-lego` parachain is running [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Flego.totem.live#/explorer)

The main [branch](https://github.com/totem-tech/totem-parachains/tree/main) is the current kapex network on polkadot.

It contains all the wasm upgrades [here](https://github.com/totem-tech/totem-parachains/tree/main/upgrades)

The minimal upgrade branch is [here](https://github.com/totem-tech/totem-parachains/tree/minimal-upgrade-1.4.4), version 1.4.4

We can share the keys privately if anyone wants to access lego as sudo.

# What actions should be taken when this happens?

1) What are the cleanup steps on the parachain side?

2) Are there steps to be taken on the relaychain side?

3) Can the authorized PVF be removed from `parachainSystem.PendingValidationCode` on the parachain? If so, how?

4) Our process is that we bump the versions in the node manifest, runtime manifest and runtime `lib.rs` file. This should be sufficient, and hasn't caused problems in the past. 

5) Is there a way to figure out what might cause a validator to vote against an upgrade and what can be done to ensure that it does get accepted?

**Comment by chrisdcosta** [comment]
The issue related to a number of earlier issues on Substrate / Polkadot which required an update to the WASM build code. Our code was out of date. However there are some current issues that appear to be somewhat on going.

The [fix to our issue](https://github.com/totem-tech/totem-parachains/pull/34/commits/eefbf897af0810a388cfa28d50a2f395280faa83) was discovered by finding these related issues:

[https://github.com/paritytech/polkadot-sdk/issues/1755](https://github.com/paritytech/polkadot-sdk/issues/1755)

[https://github.com/paritytech/frontier/issues/1038](https://github.com/paritytech/frontier/issues/1038)

[https://github.com/chevdor/subwasm/issues/79](https://github.com/chevdor/subwasm/issues/79)

[https://github.com/paritytech/substrate/pull/13804/commits/d601709d4ce21ede2398901901e3dd1427af3b1e](https://github.com/paritytech/substrate/pull/13804/commits/d601709d4ce21ede2398901901e3dd1427af3b1e)

**Comment by bkchr** [comment]
@chrisdcosta ty for the update!
