### ISSUE TITLE
Multisig wallet staking via Polkadot-JS UI failed

### ISSUE THREAD

**Issue by dbarobin** [paritytech/polkadot-sdk#1879]
I created a 2/3 multisig wallet and staked 500 DOT with it, but I received this error message.

> This could mean your nomination has not been applied to any validator in the active set by the election algorithm or it has been applied against a validator who is either oversubscribed or chilled.

<img width="750" alt="Screenshot 2023-10-16 at 09 33 10" src="https://github.com/paritytech/polkadot-sdk/assets/3949252/2192a3bf-04fe-4496-941f-e17d9d4a7972">

I checked [Nominate](https://staking.polkadot.network/#/nominate) page and found that the minimum to earn rewards is 450.17 DOT, but I staked 500 DOT. I tried to stake twice, the first time I chose 10 nominators, and the second time I chose 2 nominators, but both attempts failed. I confirmed these nominators were available and healthy.

How can I solve this issue? Doesn’t the multisig wallet support staking?

Thanks for your help.

**Comment by liamaharon** [comment]
Check again next era. 

From https://wiki.polkadot.network/docs/learn-nominator#active-vs-inactive-nomination :

> Your nominations will be effective in the next era; eras are roughly 24 hours on Polkadot.

These types of questions are better suited to [Stack Exchange](https://substrate.stackexchange.com/), so I'm going to close the issue. If you have more questions about this feel free to create a question there.
