### ISSUE TITLE
High network usage when using --relay-chain-rpc-url

### ISSUE THREAD

**Issue by purestakeoskar** [paritytech/polkadot-sdk#1896]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After upgrading to moonbeam 0.33 (based on v0.9.43), we started to see a massive increase of network usage.
When using the `--relay-chain-rpc-url` flag, the node is consuming a massive amount of network traffic, not related to p2p nor rpc traffic. We also started to see a much higher CPU usage.

On the left side of the graph we are using the embedded relay, and on the right side we are attached to en external relay.
The traffic does not show up on the opposing relay rpc side.

![image](https://github.com/paritytech/polkadot-sdk/assets/45081138/3b87e679-b2d2-4add-8333-0aa70b6f2ea5)

Config with `relay-cahin-rpc-url`
```
      --base-path=/data/moonbeam
      --rpc-port=9944
      --prometheus-port=9615
      --prometheus-external
      --name=node_name
      --listen-addr=/ip4/0.0.0.0/tcp/30333
      --chain=moonbeam
      --database=rocksdb
      --relay-chain-rpc-url=ws://nlg3-polkadot-rpc-int:9945
      --execution=wasm
      --wasm-runtime-overrides=/chain-network/tracing-substitutes
      --pruning=archive
      --db-cache=1024
      --trie-cache-size=1073741824
      --rpc-cors=all
      --unsafe-rpc-external
      --rpc-methods=safe
      --ethapi=debug,txpool,trace
      --runtime-cache-size=32
      --eth-log-block-cache=2000000000
      --eth-statuses-cache=2000000000
      --ethapi-max-permits=7
      --detailed-log-output
      --no-hardware-benchmarks
      --rpc-max-connections=1000
      --max-runtime-instances=32
      --
      --chain=polkadot
```

Config without `relay-cahin-rpc-url`
```
      --base-path=/data/moonbeam
      --rpc-port=9944
      --prometheus-port=9615
      --prometheus-external
      --name=node_name
      --listen-addr=/ip4/0.0.0.0/tcp/30333
      --chain=moonbeam
      --database=rocksdb
      --execution=wasm
      --wasm-runtime-overrides=/chain-network/tracing-substitutes
      --pruning=archive
      --db-cache=1024
      --trie-cache-size=1073741824
      --rpc-cors=all
      --unsafe-rpc-external
      --rpc-methods=safe
      --ethapi=debug,txpool,trace
      --runtime-cache-size=32
      --eth-log-block-cache=2000000000
      --eth-statuses-cache=2000000000
      --ethapi-max-permits=7
      --detailed-log-output
      --no-hardware-benchmarks
      --rpc-max-connections=1000
      --max-runtime-instances=32
      --
      --chain=polkadot
      --base-path=/data/polkadot
      --rpc-port=9945
      --prometheus-port=9616
      --prometheus-external
      --name=node_name-relay
      --listen-addr=/ip4/0.0.0.0/tcp/30334
      --database=rocksdb
      --pool-limit=0
      --db-cache=1024
      --execution=wasm
      --state-pruning=2000
      --blocks-pruning=2000
      --rpc-cors=all
      --rpc-methods=safe
      --unsafe-rpc-external
      --in-peers-light=0
      --in-peers=5
      --out-peers=25
```

**Comment by skunert** [comment]
Thanks for reporting this, I will investigate.

Nothing changed in regarding to the RPC-client code in the collator itself. My initial hunch is that maybe something changed in the subsystems. Will take a look at the corresponding commits.

**Comment by skunert** [comment]
While looking into this receiver `_rx` here raised suspicion: https://github.com/paritytech/polkadot-sdk/blob/099ef8fe11fc5fa1a864ec61c412a400a6160156/cumulus/client/relay-chain-minimal-node/src/network.rs#L68

I remember when initially reviewing the PR that introduced this I checked that this receiver is indeed empty. However, by starting a fresh node this receiver is slowly filling up, which means we have a memory leak there as it is never emptied. 
Upon further inspection I found that it consists of alternating `NotificationStreamOpened` and `NotificationStreamClosed` events. The minimal node should not participate in syncing so this is surprising to me. What do you think @altonen?

As for the time line, release v0.9.43 was release on 19th of june 2023.
Networking related PRs in the timeframe:
https://github.com/paritytech/cumulus/pull/2526
https://github.com/paritytech/cumulus/pull/2526

**Comment by altonen** [comment]
There is no way to start networking without starting the block announcement protocol so this is a bit of a problem and also relates to https://github.com/paritytech/substrate/issues/14683. One thing that could work is to set all fields of `default_peers_set` of [`NetworkConfiguration`](https://github.com/paritytech/polkadot-sdk/blob/099ef8fe11fc5fa1a864ec61c412a400a6160156/substrate/client/network/src/config.rs#L544) in [`build_collator_network`](https://github.com/paritytech/polkadot-sdk/blob/099ef8fe11fc5fa1a864ec61c412a400a6160156/cumulus/client/relay-chain-minimal-node/src/network.rs#L38) to zero. That should disable to block announcement protocol.

**Comment by skunert** [comment]
Okay, so you are saying it was always like this and does not raise suspicion w.r.t. the increased bandwidth?

I mean as a bandaid we should empty that receiver and discard the events that are coming to not pile them up.

**Comment by altonen** [comment]
I think it has been like that for a while now and we can't disable the protocol all together, at least not yet. I'll prepare a PR that drains the receiver and disconnects the peers that had connected.

Hard to say whether this is the root cause for the increase in bandwidth but your metrics PR should hopefully shed light on things. If it turns out to be syncing, then we probably have to introduce some hack to get around the problem.

Were you able to reproduce the issue?

**Comment by skunert** [comment]
Sadly not yet, I have two nodes running, but they are not yet synced, so I can not yet compare the traffic.

**Comment by altonen** [comment]
@purestakeoskar 

Are you able to upgrade to a newer version of Polkadot and see if it's still happening? It's possible that this issue is fixed because we've received two similar reports and at least for one of the reporters the issue is no longer happening.

**Comment by purestakeoskar** [comment]
@altonen
We have been testing our client with a polkadot 1.1.0 as a base, but with the same results.
An inconvenience is that when the client is using the light relay client there are no Prometheus metrics generated, so its hard to show the proof of client version.

**Comment by crystalin** [comment]
@altonen I'll try to provide a custom 1.2.0 to @purestakeoskar to test it

**Comment by purestakeoskar** [comment]
Thank you @skunert, we have added the metrics to the new 0.34.0 client (also having this issue). I also "borrowed" the graphs you mentioned. The libp2p node had almost all the CPU time on the relay side.

I have played around alot with this, and i have found that when adding the `--in-peers-light=0` flag on the relays side almost all the traffic is going away.
![image](https://github.com/paritytech/polkadot-sdk/assets/45081138/f78233b3-a651-4b2d-83f3-0b0ce6e4a671)

The graph on the left is the total traffic for the pod, and on the right is the libp2p traffic for the relay part of the node.
After i set the in light peers to 0 on the relay side, the traffic is significantly decreasing. But there are still some traffic.

Also why is there at all libp2p traffic on the relay chain side when using the `--relay-chain-rpc-url` flag?

**Comment by crystalin** [comment]
Probably unrelated, but also why when we specify --reserved-only and --in-peers 0 --out-peers 0 and --in-light-peers 0 does the node try to connect to nodes?
```
~/moonbeam-v0.34.0-alpha --chain moonbeam --base-path ~/moonbeam-rocksdb-pruning-data --no-private-ipv4 --no-mdns --reserved-only --relay-chain-rpc-urls wss://polkadot.kaki.dev --in-peers-light 0  --in-peers 0 --out-peers 0 -llibp2p_dns=debug  -- --in-peers-light 0 --reserved-only --in-peers 0 --out-peers 0
```

```
...
2023-11-03 09:15:25.121 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/18.182.94.14/tcp/30334/p2p/12D3KooWPBze5TnQWAtXccuxjDGU1hfbPqEvJfVs7SK2y1CwqGdd
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/35.78.61.71/tcp/30333/p2p/12D3KooWLDT9rbsqiphyggUcDE2rgF9yaedX75XvRiaaFFZ9B9z9
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/80.190.132.234/tcp/30334/p2p/12D3KooWSPMGqBP9nFMXb4tBk3UkUmH5zqbLMcoNwNVWkoTAfExG
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/51.159.27.242/tcp/30334/p2p/12D3KooWSPMGqBP9nFMXb4tBk3UkUmH5zqbLMcoNwNVWkoTAfExG
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/47.75.104.62/tcp/30334/p2p/12D3KooWLUufsNfFd1Eair6S1UN1wgiQ8wScxuwPAtgkMkbpvd2o
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/88.151.101.156/tcp/36033/p2p/12D3KooWDmmeFgAX6TQozXEKzJwHRvLJu6iN5BsQc7ypn3TePxXz
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/138.59.133.242/tcp/30334/p2p/12D3KooWLUufsNfFd1Eair6S1UN1wgiQ8wScxuwPAtgkMkbpvd2o
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/34.32.190.48/tcp/30334/p2p/12D3KooWHMGobwjvafi4byBdtphouxs8dgHF6j24ouLBKiFAmWJg
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/212.227.224.154/tcp/30334/p2p/12D3KooWG2chR7sZ2TsJj2fUzC9nHqDAjXp4ej26msFRqyGJ3qWK
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip6/2a02:247a:20d:a600:1::1/tcp/30334/p2p/12D3KooWG2chR7sZ2TsJj2fUzC9nHqDAjXp4ej26msFRqyGJ3qWK
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dial error: Transport(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }).
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/51.159.27.242/tcp/30334/p2p/12D3KooWG2chR7sZ2TsJj2fUzC9nHqDAjXp4ej26msFRqyGJ3qWK
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/65.108.97.174/tcp/30334/p2p/12D3KooWKCpTHfTf6Jr5sUEYnn7YZkWxeJiaBLFykHFVDcFissXy
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/216.66.9.75/tcp/30332/p2p/12D3KooWCQEa7HdZmqn2NpuWs3n7ZExSVubn7mEpffYK3W4k24FP
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip6/2a01:4f9:6b:290b::2/tcp/30334/p2p/12D3KooWKCpTHfTf6Jr5sUEYnn7YZkWxeJiaBLFykHFVDcFissXy
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/197.13.204.2/tcp/30334/p2p/12D3KooWQ5hxFkENj7gYccoHD1WTrX2sScy8c591HfXsXUBmkm6n
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dial error: Transport(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }).
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/51.159.27.242/tcp/30334/p2p/12D3KooWQ5hxFkENj7gYccoHD1WTrX2sScy8c591HfXsXUBmkm6n
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/45.76.99.35/tcp/30335/p2p/12D3KooWQwHo63oHmgaq36Gxmtt3dY87q69227W3bzbsiyfpnmKH
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip6/2001:19f0:7001:4fff:3eec:efff:fe30:5014/tcp/30335/p2p/12D3KooWQwHo63oHmgaq36Gxmtt3dY87q69227W3bzbsiyfpnmKH
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dial error: Transport(Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" }).
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/8.210.212.255/tcp/30333/p2p/12D3KooW9uzwiqVa3Su9xZzzhEBFpfxWex9GeMo7P51Adwo1W8Jj
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/51.159.27.242/tcp/30333/p2p/12D3KooW9uzwiqVa3Su9xZzzhEBFpfxWex9GeMo7P51Adwo1W8Jj
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/54.151.138.189/tcp/30334/p2p/12D3KooWBaJ5ja8ksn2cbvjXYfTTmMM2Hostp9ugvVD9yn7fr9N5
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/74.118.140.206/tcp/30334/p2p/12D3KooWCk9J65yAiTADnb5C8PqeEm3WropfSDNynFd6dmDCxiDz
2023-11-03 09:15:25.133 DEBUG tokio-runtime-worker libp2p_dns: [Relaychain] Dialing /ip4/51.159.27.242/tcp/30334/p2p/12D3KooWBaJ5ja8ksn2cbvjXYfTTmMM2Hostp9ugvVD9yn7fr9N5
```

**Comment by altonen** [comment]
@crystalin 

Polkadot enables Kademlia that runs in the background and it establishes connections to peers independently of any `--in-peers/--out-peers` configurations and this is behavior cannot be disabled (unless bootstrapping is completely disabled).

@purestakeoskar 

If light clients are using a lot of traffic, then there is very little we can do on the Polkadot side about it, other than disabling light client connections all together (which obviously as a network-wide fix is a no-go). If you can give `-lsub-libp2p=trace` logs for the relay chain, that would give us a hint as to what is using the network.

**Comment by crystalin** [comment]
@altonen we should provide a way to disable it, specially with `--relay-chain-rpc-url` as the data is not stored on the node itself.
It generates a huge amount of traffic.

**Comment by altonen** [comment]
I doubt Kademlia is the cause for the bandwidth in your latest screenshot, 4 - 8 MiB/s sounds ridiculously high for it. Especially considering that AFAIK we don't store any large objects in the DHT.

Are you able to confirm that the bandwidth shown in your last screenshot is P2P traffic and not something else? This traffic could also be from the validation protocol.

**Comment by crystalin** [comment]
@altonen I can't confirm which part of the bandwidth it is precisely, but the drop is just by doing the workaround I described (it is not just a single node but the total bandwidth of ~4 nodes on which I applied the workaround on each)
1. It comes from the relayside of the parachain (even with `--relay-chain-rpc-url`)
2. The `libp2p_dns [relaychain]` disappears

**Comment by altonen** [comment]
@crystalin 

Are you able to plot `rate(substrate_sub_libp2p_notifications_sizes_count{node}[$__rate_interval])` for the node which still consumes a lot of bandwidth despite setting inbound/outbound peers to zero?

**Comment by skunert** [comment]
> Also why is there at all libp2p traffic on the relay chain side when using the --relay-chain-rpc-url flag?

This mode still spawns a small relay chain node inside of the parachain node. The main point is that we get rid of the runtime, the syncing and other kinds of overhead. But we still need to be connected to the relay chain network for some protocols:
- Parachain collators that produced a block need to send it to the relay chains backing group. 
  - For this, we still need to maintain a libp2p stack that is connected to the relay chain.
- It can happen that we see a parachain candidate that has been submitted to the relay chain and we need to fetch it via PoV-recovery. For this we need to the `availability-recovery` subsystem that also uses the relay network.
There is no way to completely remove the relay networking from the collator currently, so it is expected that there is still some traffic.

> If light clients are using a lot of traffic, then there is very little we can do on the Polkadot side about it, other than disabling light client connections all together (which obviously as a network-wide fix is a no-go). If you can give -lsub-libp2p=trace logs for the relay chain, that would give us a hint as to what is using the network.

@altonen Actually we do not register the `LightClientRequestHandler` in the minimal-node network. This might be the missing piece. We should probably set `--in-peers-light 0` by default when users run with `--relay-chain-rpc-url`.

**Comment by crystalin** [comment]
@skunert I see. 

It doesn't make too much sense to me that we still maintain those protocol on the parachain (but I'm no expert :p). Collators can't have `relay-chain-rpc-url` so why would they send the candidate to a parachain node, and why in that case the parachain node needs to have a relay p2p network and not simply send it to the remote relay node ?

At the end, even maintaining them, there shouldn't be a reason for the network usage to be 10x higher when using a remote relay (and I specify that the 10x bandwidth is not between the parachain and the remote relay node) as opposed to when not using this option.

**Comment by skunert** [comment]
> At the end, even maintaining them, there shouldn't be a reason for the network usage to be 10x higher when using a remote relay (and I specify that the 10x bandwidth is not between the parachain and the remote relay node) as opposed to when not using this option.

100%, the bandwidth should be low and the high usage is a bug that needs to be fixed. At some point we will find it and hopefully kill it :sweat_smile:. The problem is that I can not easily manage to reproduce this, as it apparently connected to not only the CLI flags, but needs some specific networking conditions to be triggered.

> It doesn't make too much sense to me that we still maintain those protocol on the parachain (but I'm no expert :p). Collators can't have relay-chain-rpc-url so why would they send the candidate to a parachain node, and why in that case the parachain node needs to have a relay p2p network and not simply send it to the remote relay node ?

Collators can absolutely use that mode, we even have a test that ensures this functionality: https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/zombienet/tests/0006-rpc_collator_builds_blocks.toml
This is part of the reason why we have these protocols enabled. The other half is as I mentioned the pov-recovery. To know who the current validators are, we use `authority-discovery` which relies on the relay chain DHT.

> Why in that case the parachain node needs to have a relay p2p network and not simply send it to the remote relay node ?

The external relay chain node project mostly had the goal to get rid of the relay chain runtime, the large db and the syncing. The new internal node is much more light-weight than a real full-node. However, the external rpc only serves as a datasource about the relay chain. It is informing us about new blocks, giving us insight into relay state, performing runtime calls against the state etc.

However, it should and can not replace the parts that are part of the collation protocol. Some of the subsystems that are running in the collator-side are not running on a normal full node. In addition to that, the external rpc nodes can be shared by multiple collators. That would mean this full node would need to submit collations for multiple paras, breaking a lot of current assumptions. And this list is not exhaustive, I think there are more problems with this :grimacing:

**Comment by crystalin** [comment]
@skunert thank you, I think the support for collator is new as it wasn't supported in our binary (cc @purestakeoskar). However I feel this should not be used for collators as it would introduce the risk to slow down the block production (as IIRC the collator needs to retrieve some data from the relaychain, but maybe that comes with the notification of the new block from the relay).

Can you confirm if using it with collator should be without risks ?

**Comment by skunert** [comment]
Yeah I think initially we did not support that, but support has been there for a year now or so.

We have some collators deployed for our internal testnets and that goes nicely afaik. Assuming you have your own RPC node and good network conditions it should be safe. But of course you are right and I also expect some additional delays due to the RPC. One the external full node learns about new blocks the extra step via RPC is for sure going to introduce some extra milliseconds delay before the notification arrives in the collator. There are some runtime calls during block production too.

With async backing the time window should be more generous soon, so maybe its fast enough. But I encourage you to test and experiment with this. If you want maximum performance I would also still go for the traditional embedded node.

**Comment by purestakeoskar** [comment]
> @crystalin
> 
> Are you able to plot `rate(substrate_sub_libp2p_notifications_sizes_count{node}[$__rate_interval])` for the node which still consumes a lot of bandwidth despite setting inbound/outbound peers to zero?

This shows the total pod network usage, the libp2p reported network usage, and the libp2p notification sizes for the pod in question.
![image](https://github.com/paritytech/polkadot-sdk/assets/45081138/6105ec52-e172-452c-b3ac-98ff7604baf1)
At the left of the graph we were running with basic relay config:
```
--
--chain=polkadot
```
In the middle of the graph we were running with 0 light peers in:
```
--
--chain=polkadot
--in-peers-light=0
```
And at the right of the graph we are running with the following:
```
--
--in-peers-light=0
--in-peers=0
--out-peers=0
--reserved-only
--chain=/chain-network/relay-raw-no-bootnodes-specs.json
```
This spec `relay-raw-no-bootnodes-specs.json` is a polkadot spec without bootnodes.
So when running without bootnodes and peers we can actually get the relay traffic to 0.

**Comment by skunert** [comment]
`--in-peers-light=0` is now the default when `--relay-chain-rpc-urls` is provided. Thanks a lot for the help in debugging and locating the source!

@purestakeoskar I can not recommend this setup here from your last post. It will get the traffic even further down but could impact the pov-recovery mechanism. Maybe we can disable more networking functionality, but it needs some proper investigation.
```
--
--in-peers-light=0
--in-peers=0
--out-peers=0
--reserved-only
--chain=/chain-network/relay-raw-no-bootnodes-specs.json
```
