### ISSUE TITLE
Some Rococo Parachains Stuck

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/polkadot-sdk#1923]
Most of the parachains(except the BridgeHub and AssetHub) under the Rococo are stuck as shown in the pictures below. Any ideas?

![image](https://github.com/paritytech/polkadot-sdk/assets/11801722/f4d13e32-de08-42e9-a3a6-8fe48f71bcdd)

![image](https://github.com/paritytech/polkadot-sdk/assets/11801722/ba73da30-984b-4e8a-bc18-d16b6fdaa1fc)

![image](https://github.com/paritytech/polkadot-sdk/assets/11801722/28283f36-d814-44ee-89d3-d64975aaf216)

**Comment by eskimor** [comment]
Asynchronous Backing was enabled on Rococo. Old collators will still speak the old protocol, which gets rejected by validators after async backing was enabled. We can and want to be actually [more lenient](https://github.com/paritytech/polkadot-sdk/pull/1920). Expect this to be fixed today.

**Comment by eskimor** [comment]
Fixed by: https://github.com/paritytech/polkadot-sdk/pull/1920

**Comment by acatangiu** [comment]
> Fixed by: #1920

In the meantime (before ^ is merged + released), parachains can be unblocked by upgrading collators to https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.2.0
