### ISSUE TITLE
Include extrinsics len in PoV size

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#193]
With WeightsV2 and storage proof tracking we will also need to take the encoded extrinsics length into account. The point being that the actual PoV size is the size of the block header, the extrinsics and the storage proof. 
As we also should include the header, we could use the length of an empty encoded header plus the the size of the digests.

CC @ggwpez

**Comment by librelois** [comment]
Seem's to be fixed by https://github.com/paritytech/polkadot-sdk/pull/4326

**Comment by bkchr** [comment]
Yes! :D Ty @librelois for reminding me.
