### ISSUE TITLE
[Request] Move `substrate-bip39` into `polkadot-sdk` monorepo

### ISSUE THREAD

**Issue by kayabaNerve** [paritytech/polkadot-sdk#1934]
https://github.com/paritytech/substrate-bip39/issues/17, yet placed here. I'd note the lack of eyes on the prior issue demonstrates the reasoning for why.

**Comment by kayabaNerve** [comment]
substrate-bip39 does not implement BIP-39 (it runs pbkdf2 on the entropy, not the mnemonic). If one is willing to make that breaking change, the one function `polkadot-sdk/substrate/` uses from it has an equivalent in tiny-bip39, enabling removing the substrate-bip dependency.

**Comment by ggwpez** [comment]
I a valid reason to move it to the SDK is that it is a substrate-specific (the opposite of generally applicable) crate?  
Looks like the crate just contains two functions, seems inded a bit overkill for its own repo.

**Comment by kayabaNerve** [comment]
Considering that leads it to be ignored, despite being a dependency for effectively the entire Substrate ecosystem, I'd say so. There's no argument I can think of for why it should have an isolated issue board.

Though if the breaking change isn't unacceptable, I'd call for it to be dropped.

**Comment by ggwpez** [comment]
It makes sense to me, but this is normally not decided by a single person. Maybe you can open a merge request for it? Should be pretty small.

**Comment by bkchr** [comment]
We also don't have SCALE in the repo... frame metadata is also living in its own repo. There is no real need to have everything "substrate" in this one repo.

**Comment by bkchr** [comment]
And just because it moves here doesn't mean that it gets more attention..

**Comment by kayabaNerve** [comment]
SCALE has been widely adopted outside of Substrate and has a general purpose use case. I'd rather see it argued SCALE should drop from its README its used in Substrate and insert it's an efficient codec notably used in Substrate than argue for its inclusion in this repo.

As for increased attention, it'll become subject to automated tooling present here, any dependency CTRL+Fs, and since it'd be in workspace can take advantage of `workspace = true` if/when adopted.

@ggwpez I would've made the PR instead of an issue to prompt the PR except I'm reasonably unable to sign the CLA, sorry :/ I'm unsure if that'd be an issue raised if I had make the PR, as while the automated system would require it, it's clear to any human no actual independent contribution was made.
