### ISSUE TITLE
Benchmarks can no longer be executed in native and thus can no longer be debugged

### ISSUE THREAD

**Issue by gilescope** [paritytech/polkadot-sdk#1943]
### Description of bug

Before you could execute a benchmark in a debugger and step through the execution:

`cargo run --features runtime-benchmarks -p polkadot-parachain-bin -- benchmark pallet --chain asset-hub-kusama-dev --pallet "pallet_assets" --extrinsic "transfer_ownership" --steps 2 --repeat 1 --execution native`

Alas the `--execution native` now does nothing. While for production running of benchmarks this is desirable, there's now no way to debug benchmarks of a particular runtime.

(The `cargo test --features runtime-benchmark` allows you to debug natively benchmarks when run against a mock runtime by debugging the generated tests, but that's sometimes is not enough and you need to debug against specific runtimes).

Could we please un-deprecate the `--execution` flag in this instance? (polkavm might have a better debug experience but that is a way off and not anything that can currently be used.)

For categorisation this issue should go in the DexEx category.

**Comment by xlc** [comment]
Is it possible to just have a unit test to run the tests without the executor?

**Comment by bkchr** [comment]
> Is it possible to just have a unit test to run the tests without the executor?

This is the way to go. We want to get rid off the native runtime and will not bring it back.

Wasmtime also supports debugging: https://docs.wasmtime.dev/examples-debugging-native-debugger.html 

If there are things missing to make the wasm debugging experience better, please open an issue with concrete things you have seen.
