### ISSUE TITLE
`defensive!` testing extrinsic

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#1953]
I think we should extend the `RootTesting` pallet with a `trigger_defensive` call that can be used to check that the runtime monitoring for our networks works end-to-end.  
This could then be deployed to Rococo/Westend and called by devops to test it.

**Comment by adelarja** [comment]
@ggwpez, I can take it if no problem.

Just to clarify, is the only idea behind the `trigger_defensive` call for use by the devops team for testing purposes? Would it be a good idea for us to dispatch an event for this?

**Comment by ggwpez** [comment]
> Just to clarify, is the only idea behind the `trigger_defensive` call for use by the devops team for testing purposes? Would it be a good idea for us to dispatch an event for this?

Yea, event sounds good as well.

**Comment by adelarja** [comment]
@ggwpez I've opened a [WIP PR](https://github.com/paritytech/polkadot-sdk/pull/1998/files). I've tested it locally, and I only need to improve the code quality a little bit. Please let me know if you have any comments.
