### ISSUE TITLE
No chilling of validators

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#1962]
Validators should always be up for re-election even if they were slashed. This is necessary so any consensus issues will never lead to malicious actors increasing their share on active validators.

**Comment by eskimor** [comment]
@paritytech/staking-core @kianenigma @gpestana any concerns?

**Comment by eskimor** [comment]
Alternatively: Disabling without slashing (not even 0%)? @ordian

**Comment by eskimor** [comment]
@tdimitrov can we disable without slashing?

**Comment by tdimitrov** [comment]
> @tdimitrov can we disable without slashing? Or please ping @gpestana on this one, thanks!

Yes. With the new disabling strategy we disable each offender no matter if it was slashed or not.

**Comment by gpestana** [comment]
In the current logic, slashed validators are "chilled" and their intention for validating is dropped. However, the validator can still re-validate its intention to become a validator right away. Is this the expected behaviour?

Recently we even changed the logic so that the nominations of slashed/chilled validators are not dropped. This means that once the chilled validator re-validates its intention to become a validator, its nominations remain the same as pre-slash.

Is this the intended behaviour described by this issue?

**Comment by eskimor** [comment]
> Yes. With the new disabling strategy we disable each offender no matter if it was slashed or not.

And do we also do that? So for voting invalid on valid - we disable but don't slash (not even 0%) and thus we get no chilling?

> Is this the intended behavior described by this issue?

Not quite. It is fine if we can disable, without slashing (and thus no chilling). We are worried about the particular case that a determinism issue is abused to get honest validators disabled. We fixed all the concerns we had with disabling, but if those validators would not get re-elected we would still have the original problem just delayed: An attacker can increase its share of validators, by kicking out honest validators from the set (abusing some nondeterminism) and then run an attack.

**Comment by gpestana** [comment]
> This is necessary so any consensus issues will never lead to malicious actors increasing their share on active validators.

Could you elaborate? Are you mentioning the case where offence have been reported on non-faulty validators for some reason?

**Comment by ordian** [comment]
> So for voting invalid on valid - we disable but don't slash (not even 0%) and thus we get no chilling?

currently we don't disable (no offence is submitted)

**Comment by eskimor** [comment]
@ordian just mentioned that he is 80% sure that there is no chilling on 0% slashes. If that is true, then this is good enough and we can close this ticket. Consequences of doing non 0% slashes should be documented in the guide though.

**Comment by ordian** [comment]
https://github.com/paritytech/polkadot-sdk/blob/21f1811c6600d8a7fe043592ff34dcb79284d583/substrate/frame/staking/src/slashing.rs#L236-L239

This doesn't seem to indicate that I was correct. Especially given that the https://github.com/paritytech/polkadot-sdk/blob/21f1811c6600d8a7fe043592ff34dcb79284d583/substrate/frame/staking/src/slashing.rs#L309 seems to be inserting the span
https://github.com/paritytech/polkadot-sdk/blob/21f1811c6600d8a7fe043592ff34dcb79284d583/substrate/frame/staking/src/slashing.rs#L449

**Comment by tdimitrov** [comment]
And also here:
https://github.com/paritytech/polkadot-sdk/blob/9f8c5986cc80ce4d11cb4a42b285a7b209481e82/substrate/frame/staking/src/slashing.rs#L286

I don't know how chilling is related to slashing, but in the current implementation we disable based on `enum DisableStrategy` (attached to the offence). In the new one - we disable unconditionally.

**Comment by tdimitrov** [comment]
Me and @gpestana decided not to touch slashing spans with this issue and only remove validator chilling on offence.

Removing slashing spans is tracked in https://github.com/paritytech/polkadot-sdk/issues/2650
