### ISSUE TITLE
Test backing group sizes of 3 on Kusama

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#1965]
Less backers, means more resources for approval checking. 3 should be enough in general, especially once we have asynchronous backing. Without it could have negative impacts on parachain liveness, but let's test on Kusama.

- [x] Propose backing group size 3 on Kusama
- [x] Once enacted, monitor parachain block times and in general network performance. 
- [ ] Things became better/stayed the same -> Go for Polkadot
- [ ] Things got worse -> role back -> Create follow up ticket to re-evaluate with async backing.

**Comment by eskimor** [comment]
If the outcome is negative we should retry once async backing is fully launched (including most parachains taking advantage of it).

**Comment by ordian** [comment]
* public referenda: https://kusama.polkassembly.io/referenda/294
* fellowship whitelist: https://kusama.polkassembly.io/member-referenda/50

**Comment by eskimor** [comment]
Thanks @ordian ! Great work! Ok, I would say definitely not go for Polkadot. Roll back might not be necessary, given that async backing will be launching soon anyway. Have there been any complaints yet?

**Comment by mrcnski** [comment]
> * public referendum: [kusama.polkassembly.io/referenda/294](https://kusama.polkassembly.io/referenda/294)

> Members spoke highly of their experiences with the proposer

Nice!
