### ISSUE TITLE
Fix consumer handling in pallet balances `update_locks`

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#1970]
When removing all locks of an account there is a bug that leads to reducing the consumer count twice.

First it happens here: https://github.com/paritytech/polkadot-sdk/blob/f0ab54e3e560b661d052ea362a995f3e68acda61/substrate/frame/balances/src/lib.rs#L969

And then the second time here: https://github.com/paritytech/polkadot-sdk/blob/f0ab54e3e560b661d052ea362a995f3e68acda61/substrate/frame/balances/src/lib.rs#L1072

**Comment by liamaharon** [comment]
Self-assigned, I need to spend some time understanding this for writing docs anyway.

**Comment by xlc** [comment]
we need a script to check if this bug have happened on any parachain and generate a list of accounts that needs fix up

**Comment by xlc** [comment]
and this is something should be identified by a fuzzer so I guess we don’t have enough of them

**Comment by xlc** [comment]
I can image it could be hard to write such script that works on all the parachains. That should spark another question: What can we improve to make such task easier in future? e.g. better event system or better indexer or better invariant checker

**Comment by bkchr** [comment]
Writing a script for every chain should be possible. You just need to monitor `pallet_balances::Lock` and the changes to consumers. We would probably only require teams to set the starting block for when the runtime was activated that contained the broken logic.

**Comment by michalisFr** [comment]
@bkchr Does this relate to this issue? https://github.com/paritytech/polkadot-sdk/issues/1404#issuecomment-1767580584

**Comment by bkchr** [comment]
> @bkchr Does this relate to this issue? [#1404 (comment)](https://github.com/paritytech/polkadot-sdk/issues/1404#issuecomment-1767580584)

Could probably be related.
