### ISSUE TITLE
Unable to launch ./substrate/bin/node-template after compilation

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#1977]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When I use cargo build --release in node-template folder code compiles fine, but when I go ahead to launch it with ./target... it says no such file in the repository. I have tried this in every folder until I got to root with cd .. No luck on launching node template unfortunately

### Steps to reproduce

Compile node template and launch with ./target...

**Comment by ggwpez** [comment]
Please write the exact lines that you were using, but this works in the root folder:

```sh
cargo b -r -p node-template
./target/release/node-template --dev
```

**Comment by dudo50** [comment]
Will try today and let you know. Thank you.

**Comment by dudo50** [comment]
Worked! Thank you! Closing the issue.
