### ISSUE TITLE
`parachain-system` undecodable state

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#1978]
[`HostConfiguration`](https://github.com/paritytech/polkadot-sdk/blob/e2b21d00c7856961ab3b692b2e2798747af1e819/cumulus/pallets/parachain-system/src/lib.rs#L837-L845) is undecodable on Polkadot and Kusama Asset Hubs, leading to error logs in `on_initialize`:

```
[2023-10-23T00:43:49Z ERROR runtime::storage] Corrupted state at `[69, 50, 61, 247, 204, 71, 21, 11, 57, 48, 226, 102, 107, 10, 163, 19, 197, 34, 35, 24, 128, 35, 138, 12, 86, 2, 27, 135, 68, 160, 7, 67]: Error`
``` 

Basti noted the reasoning for the breakage [here](https://github.com/paritytech/polkadot-sdk/issues/1952#issuecomment-1773475795):

> The `AbridgedHostConfiguration` structure changed (the async backing stuff was added), but there is not migration for this type in the parachain state. The correct host configuration with the correct data is only set in the `set_validation_data` inherent. Thus, it tries to decode the new struct in `on_initialize` and prints this error as it fails, but then the correct data is set. As this is only used to calculate the weight of `on_finalize` of parachain system for this one block, it is fine to "ignore".

Need to write a migration to correct this on-chain state.

**Comment by liamaharon** [comment]
Just learned very low priority, upgrading to the latest polkadot sdk should fix this. Will close once fix is confirmed.

**Comment by kianenigma** [comment]
should close?
