### ISSUE TITLE
In-tree libraries vulnerable to RUSTSEC-2023-0052 due to jsonrpsee

### ISSUE THREAD

**Issue by kayabaNerve** [paritytech/polkadot-sdk#2]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

jsonrpsee (currently 0.16) pulls in a variety of legacy networking crates, including ones vulnerable to RUSTSEC-2023-0052. AFAICT, updating to 0.20 updates everything (or almost everything) in the dependency tree from webpki to rustls-webpki, resolving the RUSTSEC (and also modernizing the tree in generally).

I did try to perform the work locally, yet the amount of changes to the subscription API made me realize I could not do a proper job within a reasonable amount of time due to my unfamiliarity with the codebase in question.

Apologies if this isn't optimally filed.

**Comment by niklasad1** [comment]
Closed by the jsonrpsee patch release v0.16.3
