### ISSUE TITLE
[Multi-Asset Treasury] Exchange Oracle Pallet

### ISSUE THREAD

**Issue by tonyalaribe** [paritytech/polkadot-sdk#202]
### Motivation

To support a Multi-Asset treasury where the treasury-pallet needs to spend transactions in assets other than the native asset, there needs to be a way to know how much of the native asset that asset id is worth. 

This is useful for book keeping in the treasury, eg to ensure that the total amount of spends irrespective of asset type, is below a particular budget amount which can be configured in a particular asset class (eg the native asset).

### Request

Create an Exchange Oracle pallet and a trait that can be used to get the exchange rate for a particular asset pair. 
This pallet could rely on configuration or an extrinsic to set the asset pairs. 

This is a step towards https://github.com/paritytech/polkadot-sdk/issues/98
More info about the larger plan is on this post: https://github.com/paritytech/polkadot-sdk/issues/98

**Comment by joepetrowski** [comment]
Closed by https://github.com/paritytech/substrate/pull/13608
