### ISSUE TITLE
License information missing from many package `Cargo.toml` files

### ISSUE THREAD

**Issue by seadanda** [paritytech/polkadot-sdk#2043]
The following packages have no license information in their corresponding `Cargo.toml` files.

I believe the parachain runtimes should be licensed under Apache-2.0, but the others would need a wider discussion (than just me) to decide between Apache or GPL-3 (or both?).

Pasting the list here to start discussion. Happy to add them all after some sort of direction.

- [ ] `cumulus/client/cli/Cargo.toml`
- [ ] `cumulus/client/collator/Cargo.toml`
- [ ] `cumulus/client/consensus/aura/Cargo.toml`
- [ ] `cumulus/client/consensus/common/Cargo.toml`
- [ ] `cumulus/client/consensus/proposer/Cargo.toml`
- [ ] `cumulus/client/consensus/relay-chain/Cargo.toml`
- [ ] `cumulus/client/network/Cargo.toml`
- [ ] `cumulus/client/pov-recovery/Cargo.toml`
- [ ] `cumulus/client/relay-chain-inprocess-interface/Cargo.toml`
- [ ] `cumulus/client/relay-chain-interface/Cargo.toml`
- [ ] `cumulus/client/relay-chain-minimal-node/Cargo.toml`
- [ ] `cumulus/client/relay-chain-rpc-interface/Cargo.toml`
- [ ] `cumulus/client/service/Cargo.toml`
- [ ] `cumulus/pallets/aura-ext/Cargo.toml`
- [ ] `cumulus/pallets/dmp-queue/Cargo.toml`
- [ ] `cumulus/pallets/parachain-system/Cargo.toml`
- [ ] `cumulus/pallets/parachain-system/proc-macro/Cargo.toml`
- [ ] `cumulus/pallets/solo-to-para/Cargo.toml`
- [ ] `cumulus/pallets/xcm/Cargo.toml`
- [ ] `cumulus/pallets/xcmp-queue/Cargo.toml`
- [ ] `cumulus/parachains/common/Cargo.toml`
- [ ] `cumulus/parachains/pallets/collective-content/Cargo.toml`
- [ ] `cumulus/parachains/pallets/parachain-info/Cargo.toml`
- [ ] `cumulus/parachains/pallets/ping/Cargo.toml`
- [ ] `cumulus/parachains/runtimes/assets/asset-hub-kusama/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/assets/asset-hub-rococo/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/assets/asset-hub-westend/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/assets/common/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/assets/test-utils/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/bridge-hubs/test-utils/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/collectives/collectives-polkadot/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/contracts/contracts-rococo/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/glutton/glutton-kusama/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/starters/seedling/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/starters/shell/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/test-utils/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/parachains/runtimes/testing/rococo-parachain/Cargo.toml` `Apache-2.0`
- [ ] `cumulus/polkadot-parachain/Cargo.toml`
- [ ] `cumulus/primitives/aura/Cargo.toml`
- [ ] `cumulus/primitives/core/Cargo.toml`
- [ ] `cumulus/primitives/parachain-inherent/Cargo.toml`
- [ ] `cumulus/primitives/timestamp/Cargo.toml`
- [ ] `cumulus/primitives/utility/Cargo.toml`
- [ ] `cumulus/test/client/Cargo.toml`
- [ ] `cumulus/test/relay-sproof-builder/Cargo.toml`
- [ ] `cumulus/test/runtime/Cargo.toml`
- [ ] `cumulus/test/service/Cargo.toml`
- [ ] `cumulus/xcm/xcm-emulator/Cargo.toml`

**Comment by ggwpez** [comment]
Should be done by https://github.com/paritytech/polkadot-sdk/pull/1887 i think.

**Comment by seadanda** [comment]
mostly covered by the list in #1491. Closing, sorry for the noise.
