### ISSUE TITLE
FRAME: Avoid boilerplate weight macros

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot-sdk#205]
Currently we specify weights individually for each call. In cases of complex weights, this is fine. But often times pallets have very simple `O(1)` weights. An example is the new core-fellowship pallet, whose [call block](https://github.com/paritytech/substrate/pull/13503/files#diff-5010523d1a0d024a52a00e67c730c447b4096e3a684596835331ea514bc94829R258-R287) looks like this:

```
#[pallet::call]
impl<T: Config<I>, I: 'static> Pallet<T, I> {
	/// Snip
	#[pallet::weight(T::WeightInfo::set_params())]
	#[pallet::call_index(1)]
	pub fn set_params(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::weight(T::WeightInfo::set_active())]
	#[pallet::call_index(2)]
	pub fn set_active(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::weight(T::WeightInfo::approve())]
	#[pallet::call_index(3)]
	pub fn approve(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::weight(T::WeightInfo::induct())]
	#[pallet::call_index(4)]
	pub fn induct(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}
	
	// etc.
}
```

This is a bit tedious, but more importantly it's very error-prone. If the line reading:

```
	#[pallet::weight(T::WeightInfo::set_active())]
```

were accidentally written:

```
	#[pallet::weight(T::WeightInfo::set_params())]
```

Then there would be no build error or warning and everything would appear to proceed well but the chain would be at risk of a potentially devastating DoS attack.

Instead, we should dispense with per-function weights in the general case and instead have a directive at the level of the call-block instructing the default weight to be determined as the function call in the `WeightInfo` of the same name as the call function. Thus the previous code becomes:

```
#[pallet::call]
#[pallet::weight_info(T::WeightInfo)]
impl<T: Config<I>, I: 'static> Pallet<T, I> {
	/// Snip
	#[pallet::call_index(1)]
	pub fn set_params(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::call_index(2)]
	pub fn set_active(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::call_index(3)]
	pub fn approve(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}

	/// Snip
	#[pallet::call_index(4)]
	pub fn induct(/* snip */) -> DispatchResultWithPostInfo {
		/* snip */
	}
	
	// etc.
}
```

Ideally, we could come up with a combination of pallet macros, `WeightInfo` API/convention and benchmarking macros to allow the complete avoidance of manual weight specification logic in the call block.

For a start, one other pattern which is quite common to see is multi-modal-maximum, whereby a call has two or more  benchmarks, each forcing a different control-flow, and the call's weight is the per-component `max`. See the `bump` call in the core-fellowship pallet:

```
/// Snip
#[pallet::weight(
	T::WeightInfo::bump_offboard().max(T::WeightInfo::bump_demote())
)]
#[pallet::call_index(0)]
pub fn bump(/* snip */) -> DispatchResultWithPostInfo {
	/* snip */
}
```

We might have some better (more declarative, less procedural) means of expressing this:

```
/// Snip
#[pallet::weight_max_over_prefix]
#[pallet::call_index(0)]
pub fn bump(/* snip */) -> DispatchResultWithPostInfo {
	/* snip */
}
```

A better way would be to avoid relying on purely string prefixes, and actually have tagged groupings in the benchmarking/WeightInfo APIs but this would be a bigger job.

**Comment by kianenigma** [comment]
This is already done.
