### ISSUE TITLE
Update Substrate docs to cover latest changes.

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#2076]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Request

https://docs.substrate.io/tutorials/collectibles-workshop/01-prepare/

I am unable to go through following tutorial as new changes to SDK were applied. Please update this tutorial. Thanks

### Are you willing to help with this request?

Yes!

**Comment by liamaharon** [comment]
I would consider marking these entire docs as deprecated. Current pages are few and far between.

**Comment by dudo50** [comment]
@liamaharon Is there any substitute to them? Or is there plan for tutorial of that sort? I would consider that to be very valuable, not only for me but for others as well.

Thanks for the info.

**Comment by liamaharon** [comment]
@kianenigma is working on a new FRAME tutorial, I'm not sure about the rest.

**Comment by kianenigma** [comment]
Yes, these pages should be deprecated, and if desired, a new version of them should be created in the new portal. https://github.com/paritytech/polkadot-sdk-docs/issues/26 is the high level plan around these.

**Comment by dudo50** [comment]
Closing this now, as new docs contain most of the stuff old docs contained and, in some cases, much more.
