### ISSUE TITLE
PVF: consider fetching audit logs with netlink

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2080]
Instead of parsing audit logs, we might be able to connect to audit via netlink and observe audit events directly. see [man 3 audit_open](https://man7.org/linux/man-pages/man3/audit_open.3.html) and further links.

See https://github.com/paritytech/polkadot-sdk/pull/2009#issuecomment-1784964616 by @s0me0ne-unkn0wn.

**Comment by mrcnski** [comment]
@s0me0ne-unkn0wn Does this work even if audit logging is disabled? That might be an advantage, along with not having to locate the audit file location (it is different on some systems) etc.

**Comment by s0me0ne-unkn0wn** [comment]
Well, if audit logging is disabled in the sense that `systemd` does not write the log to disk, the audit events should still be available. But the audit may be disabled altogether on the kernel level, in that case, no audit events are available, it can be checked with [audit_is_enabled](https://man7.org/linux/man-pages/man3/audit_is_enabled.3.html)

**Comment by s0me0ne-unkn0wn** [comment]
I'll take this one for myself, as I'm more or less familiar with netlink and kernel audit. However, I've never tried using it as non-root. The first thing that should be checked is whether it's worth implementing at all. If it requires root privilege, it doesn't make sense. The current implementation (the log parsing) fails on every host I tried, as the audit logs are not usually exposed to normal users.

**Comment by mrcnski** [comment]
Awesome, thank you! Let me know what you find out.

> The current implementation (the log parsing) fails on every host I tried, as the audit logs are not usually exposed to normal users.

Yeah, so we only use them for informative purposes right now. Hopefully, there is at least one validator who is ignoring our recommendation not to run as root, who would notice any warnings that we log and inform us. 🙃

**Comment by mrcnski** [comment]
Related: https://github.com/paritytech/polkadot-sdk/issues/2324

**Comment by bkchr** [comment]
In the light of https://github.com/paritytech/polkadot-sdk/pull/2461, do we still need this?

**Comment by s0me0ne-unkn0wn** [comment]
> In the light of #2461, do we still need this?

If we're not going to ever enforce running node as root, I'd say no.
If we're switching to PolkaVM, I'd say no.
Otherwise, that may be somewhat useful :)

**Comment by bkchr** [comment]
So that sounds to me like a "no" and we can close this issue.

**Comment by mrcnski** [comment]
Can reopen if we need this in the future.
