### ISSUE TITLE
Log xcm `process_message` errors and inputs

### ISSUE THREAD

**Issue by Chralt98** [paritytech/polkadot-sdk#2100]
I am currenly in a debugging session and the error `Unsupported` is emitted from here:

https://github.com/paritytech/polkadot-sdk/blob/18ad449015e243d148d48688f2492d435fc75522/polkadot/xcm/xcm-builder/src/process_xcm_message.rs#L41-L66

Can you add xcm logging here?

**Comment by bkchr** [comment]
@Chralt98 Feel free to open a pr!

**Comment by ggwpez** [comment]
Sure we can add a log there. As hot-fix on your side you could copy&paste the processor and add logging to ease debugging before we adapt here.

**Comment by bkontur** [comment]
@Chralt98 Meanwhile, this was fixed by: https://github.com/paritytech/polkadot-sdk/pull/2799/files#diff-150e895a5f31d5e26c9cab0254f00b9443dc54c7bdb872808feb4a21a69f2430
