### ISSUE TITLE
Make node syncing messages configurable.

### ISSUE THREAD

**Issue by shamil-gadelshin** [paritytech/polkadot-sdk#2110]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Currently, we have node syncing messages produced by the `InformantDisplay` from `sc-informant` crate within `sc-service`. There is no way to alter the messages or change their periodicity which could be suboptimal for some parachains.

### Request

I suggest making `InformantDisplay` configurable in the `sc_service` crate.

### Solution

Make `SpawnTasksParams` from `sc_service`  accept an optional additional parameter.

There are several variants for this parameter:
1. Opaque future similar to the current output of `sc_informant::build()`.
2. Stream of messages.
3. Introduce a dedicated trait with the methods providing 1. or 2. but extendable in the future.

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
This entire `spawn_tasks` function is something I don't like. It doesn't bring any real value and we should remove it at some point.

**Comment by shamil-gadelshin** [comment]
Are you suggesting just not to use this function at all and spawn the necessary tasks separately? Or you have something else in mind?

**Comment by nazar-pc** [comment]
I hit another annoyance with `spawn_tasks`, it requires `sp_session::SessionKeys` runtime API, even though it makes no sense for our chain.

The difficulty with `spawn_tasks` is that while it is fairly small, it relies on a bunch of private functions that anyone reimplementing `spawn_tasks` would have to replicate too.

What do you think about exposing those functions publicly? I can send a PR.

**Comment by bkchr** [comment]
> What do you think about exposing those functions publicly? I can send a PR.

Sounds fine to me.
