### ISSUE TITLE
[CI] Update Rust nightly version for CI

### ISSUE THREAD

**Issue by davxy** [paritytech/polkadot-sdk#2113]
CI pipeline [job](https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4160212) is failing because cargo nightly is not up to date.

```
$ cargo --version
cargo 1.73.0 (9c4383fb5 2023-08-26)
...
$ cargo +nightly --version
cargo 1.71.0-nightly (09276c703 2023-05-16)
```

**Comment by ggwpez** [comment]
Are you trying to use nightly features in Rust code? We do not use nightly for building, only formatting.

**Comment by davxy** [comment]
No. Is the CI that is trying to use nightly. See the job log

**Comment by davxy** [comment]
> Are you trying to use nightly features in Rust code? We do not use nightly for building, only formatting.

Or maybe your question was if my code is using any thing that is available only on nightly :-)
Sorry if I misunderstood...

No my code is using a feature `<integer>::div_ceil` which has been stabilized by 1.73

**Comment by davxy** [comment]
Closed by https://github.com/paritytech/polkadot-sdk/pull/2115
