### ISSUE TITLE
XCM: Could not decode `Instruction::ReserveAssetDeposited.0` when containing multiple assets

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot-sdk#2123]
# Description

Sending XCM message between parachains (through XCMP queue) containing `ReserveAssetDeposited(assets)` with `assets.len() > 1`, fails to decode and thus deliver.

# Steps to reproduce

Use branch https://github.com/acatangiu/polkadot-sdk/tree/debug-xcmp-crash-on-decoding-incoming-multiassets (or cherry-pick commit https://github.com/acatangiu/polkadot-sdk/commit/a290fd9774676d2b2afde659e4b089d901f52dcd) and run:
```
RUST_LOG=error cargo test -p asset-hub-rococo-integration-tests debug_limited_reserve_transfer -- --nocapture
```

with result

```
test tests::reserve_transfer::debug_limited_reserve_transfer_asset_from_system_para_to_para_crashes ... FAILED
test tests::reserve_transfer::debug_limited_reserve_transfer_asset_from_system_para_to_para_works ... ok
```

where the only difference is that crashing version is sending **two** valid assets instead of a single one.

## More debug output coming from same command

```
On executing xcm::process_instruction TransferReserveAsset: ===> send xcm to destination:
	[
		ReserveAssetDeposited(MultiAssets([
			MultiAsset {
				id: Concrete(MultiLocation {
					parents: 1,
					interior: X3(Parachain(1000), PalletInstance(50), GeneralIndex(1)),
				}),
				fun: Fungible(1000000),
			},
			MultiAsset {
				id: Concrete(MultiLocation { parents: 1, interior: Here }),
				fun: Fungible(3333333000),
			},
		])),
		ClearOrigin,
		BuyExecution {
			fees: MultiAsset {
				id: Concrete(MultiLocation { parents: 1, interior: Here }),
				fun: Fungible(3333333000),
			},
			weight_limit: Unlimited,
		},
		DepositAsset {
			assets: Wild(AllCounted(2)),
			beneficiary: MultiLocation {
				parents: 0,
				interior: X1(AccountId32 {
					network: None,
					id: [
						142, 175, 4, 21, 22, 135, 115, 99, 38, 201, 254, 161, 126, 37, 252, 82,
						135, 97, 54, 147, 201, 18, 144, 156, 178, 38, 170, 71, 148, 242, 106, 72,
					],
				}),
			},
		},
	]
```

On receiving sent XCM, `cumulus_pallet_xcmp_queue` throws following error:
```
ERROR cumulus_pallet_xcmp_queue: XCMP failed to decode message, error Error {
		cause: Some(Error {
			cause: Some(Error {
				cause: None, desc: "Out of order"
			}), desc: "Could not decode `Instruction::ReserveAssetDeposited.0`"
		}), desc: "Could not decode `VersionedXcm::V3.0`"
	}
```

**Comment by KiChjang** [comment]
Quick check: are the asssets in the vector sorted? If not, it should be, otherwise the receiver will have problems decoding it.

**Comment by acatangiu** [comment]
> Quick check: are the assets in the vector sorted? If not, it should be, otherwise the receiver will have problems decoding it.

Yes, you cannot really have it any other way since all builder options do sort on inner vec before returning a new `MultiAssets` object. Alas, that is not the issue here :(

**Comment by serban300** [comment]
Thanks @KiChjang for the hint. The problem is indeed the sorting in the following sense:

We have 2 assets. At the beginning they are:
```
a: (Concrete(MultiLocation { parents: 0, interior: X2(PalletInstance(50), GeneralIndex(1)) }), Fungible(1000000))
b: (Concrete(MultiLocation { parents: 1, interior: Here }), Fungible(3333333000))
```

And the result of  `a.cmp(&b)` is `cmp: Less`

Then, after doing [`assets.reanchor()`](https://github.com/acatangiu/polkadot-sdk/blob/a290fd9774676d2b2afde659e4b089d901f52dcd/polkadot/xcm/xcm-executor/src/lib.rs#L518) they become:
```
a: (Concrete(MultiLocation { parents: 1, interior: X3(Parachain(1000), PalletInstance(50), GeneralIndex(1)) }), Fungible(1000000))
b: (Concrete(MultiLocation { parents: 1, interior: Here }), Fungible(3333333000))
```

And the result of  `a.cmp(&b)` is `cmp: Greater` because the `MultiAsset::id` values change.

This form is encoded, but with the old sorting order and then, when decoding, [this error](https://github.com/acatangiu/polkadot-sdk/blob/a290fd9774676d2b2afde659e4b089d901f52dcd/polkadot/xcm/src/v3/multiasset.rs#L606) is triggered, because it's expecting them to be ordered according to the new values.

So I think that inside `MultiAssets::reanchor()` we should sort once again ?
