### ISSUE TITLE
[XCM] Why `AccountId32Aliases` or `AccountKey20Aliases` doesn't support parents:1?

### ISSUE THREAD

**Issue by jiguantong** [paritytech/polkadot-sdk#2130]
Related question: https://substrate.stackexchange.com/questions/10377/how-to-fix-the-failedtotransactassetinsufficientbalance-error/10379?noredirect=1#comment10277_10379

Steps:
1. paraA send this XCM to paraB with a general account like Alice.
```
WithdrawAsset,
BuyExecution
```
2. `pallet-xcm.send_xcm` [insert an instruction](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/pallet-xcm/src/lib.rs#L1523): `DescendOrigin(X1(AccountId32(Alice))`
3. paraB [WithComputedOrigin](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/xcm-builder/src/barriers.rs#L202) change the origin with `{parents: 1, ...}`
4. Then [CurrencyAdapter](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/xcm-builder/src/currency_adapter.rs#L212) convert the location `(parents:1, ...)` with `AcountId32Aliases` or `AccountKey20Aliases` before withdraw.
5. [Convertion result](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/xcm-builder/src/location_conversion.rs#L314) is None due to the parents is 1, and then `FailedToTransactAsset`

Question: 
1. Why [here](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/xcm-builder/src/location_conversion.rs#L310) check parents is 0? Maybe I missed something
2. How to deal with the problem if location_conversion need to check parents is 0?

**Comment by Chralt98** [comment]
The xcm message uses the origin `origin: Some(MultiLocation { parents: 1, interior: X1(Parachain(2000)) })`, but when executing from parachain A with account Alice, I would have expected the following origin on the receiver parachain for the xcm execution: `origin: Some(MultiLocation { parents: 0, interior: X1(AccountId32 { id: [0,212,53,147,199,21,253,211,28,97,20,26,189,4,169,159,214,130,44,133,88,133,76,205,227,154,86,132,231,165,109,162,125], network: None })})`.

From this log:

`2023-11-02 11:21:12.233 TRACE tokio-runtime-worker xcm::execute_xcm_in_credit: [Parachain] origin: MultiLocation { parents: 1, interior: X1(Parachain(2000)) }, message: Xcm([DescendOrigin(X1(AccountId32 { network: None, id: [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] })), WithdrawAsset(MultiAssets([MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000000) }])), BuyExecution { fees: MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000000) }, weight_limit: Limited(<wasm:stripped>) }, LockAsset { asset: MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000) }, unlocker: MultiLocation { parents: 1, interior: X2(Parachain(2000), AccountId32 { network: None, id: [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] }) } }]), weight_credit: <wasm:stripped>`

**Comment by jiguantong** [comment]
> The xcm message uses the origin `origin: Some(MultiLocation { parents: 1, interior: X1(Parachain(2000)) })`, but when executing from parachain A with account Alice, I would have expected the following origin on the receiver parachain for the xcm execution: `origin: Some(MultiLocation { parents: 0, interior: X1(AccountId32 { id: [212,53,147,199,21,253,211,28,97,20,26,189,4,169,159,214,130,44,133,88,133,76,205,227,154,86,132,231,165,109,162,125], network: None })})`.
> 
> From this log:
> 
> `2023-11-02 11:21:12.233 TRACE tokio-runtime-worker xcm::execute_xcm_in_credit: [Parachain] origin: MultiLocation { parents: 1, interior: X1(Parachain(2000)) }, message: Xcm([DescendOrigin(X1(AccountId32 { network: None, id: [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] })), WithdrawAsset(MultiAssets([MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000000) }])), BuyExecution { fees: MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000000) }, weight_limit: Limited(<wasm:stripped>) }, LockAsset { asset: MultiAsset { id: Concrete(MultiLocation { parents: 0, interior: Here }), fun: Fungible(10000000000) }, unlocker: MultiLocation { parents: 1, interior: X2(Parachain(2000), AccountId32 { network: None, id: [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] }) } }]), weight_credit: <wasm:stripped>`

Maybe off topic. If you want use `origin: Some(MultiLocation { parents: 1, interior: X1(Parachain(2000)) })` you should send this XCM through Sudo or Governance. Because this origin represents the sender parachain authority, rather than a general user. If you send an XCM use a general user, pallet-xcm will insert `DescendOrigin()` to change the origin.

**Comment by Chralt98** [comment]
I think the question here is why do we need to have parents changed from 0 to 1? Because if I send an xcm message from Alice (parachain A) to parachain B executing on the Alice account again, I am in the consensus system of parachain B and should be able to reference the account of Alice with `parents: 0` instead of `parents: 1`.

**Comment by jiguantong** [comment]
> I think the question here is why do we need to have parents changed from 0 to 1? Because if I send a xcm message from Alice (parachain A) to parachain B executing on the Alice account again, I am in the consensus system of parachain B and should be able to reference the account of Alice with `parents: 0` instead of `parents: 1`.

I think parents:1 is right, because the origin is coming from another parachain, {parents:1, parachain(XXX)}. And the location convertion [here](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.1.0/polkadot/xcm/xcm-builder/src/location_conversion.rs#L310) should match parents:1 and return id. If so, I think it would work, and it will withdraw from the Alice account on paraB. But I don't know why here doesn't support parents:1, maybe I missed something. Waiting for developer's reply

**Comment by girazoki** [comment]
You cannot let someone claiming to be Alice from parachain X use the Alice account in parachain Y. That would put pretty much any chain at risk, as parachain X can claim to be a descended origin of any account. And that is what `Account32Aliases` prevents by checking that parents is 0 (i.e., in order to use Alice account in parachain Y the message should have been originated in parachain Y).

You can use the convertor `HashedDescription`, which will hash the descended multilocation and give you a fresh new account that Alice from parachain X will be able to control in parachain Y

**Comment by Chralt98** [comment]
Even when using the modified `AccountId32Aliases`, I get the same `InsufficientBalance` error:

```rust
/// Extracts the `AccountId32` from the passed `location` if the network matches.
pub struct AccountId32Aliases<Network, AccountId>(PhantomData<(Network, AccountId)>);
impl<Network: Get<Option<NetworkId>>, AccountId: From<[u8; 32]> + Into<[u8; 32]> + Clone>
    ConvertLocation<AccountId> for AccountId32Aliases<Network, AccountId>
{
    fn convert_location(location: &MultiLocation) -> Option<AccountId> {
        log::info!("AccountId32Aliases::convert_location({:?})", location);
        let id = match *location {
            MultiLocation {
                parents: 1,
                interior: X1(AccountId32 { id, network: None }),
            } => id,
            MultiLocation {
                parents: 0,
                interior: X1(AccountId32 { id, network: None }),
            } => id,
            MultiLocation {
                parents: 1,
                interior: X1(AccountId32 { id, network }),
            } if network == Network::get() => id,
            MultiLocation {
                parents: 0,
                interior: X1(AccountId32 { id, network }),
            } if network == Network::get() => id,
            _ => return None,
        };
        Some(id.into())
    }
}
```

**Comment by Chralt98** [comment]
Okay makes sense @girazoki, but can you briefly explain why [this](https://github.com/paritytech/xcm-docs/blob/0e4a5fb58b9421288f4fc5e6def9c5d8b6b3f065/examples/src/10_locks/mod.rs#L19-L59) works then?

**Comment by Chralt98** [comment]
Ah, I see, from [here](https://github.com/paritytech/xcm-docs/blob/0e4a5fb58b9421288f4fc5e6def9c5d8b6b3f065/examples/src/simple_test_net/mod.rs#L154).
