### ISSUE TITLE
runtime call SessionKeys_generate_session_keys is not working

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/polkadot-sdk#2133]
### Description of bug
RPC runtime call `SessionKeys.generateSessionKeys(seed)` is not working

Node error: 
```
Version: 1.1.0-f60318f6868

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   4: rust_begin_unwind
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   5: core::panicking::panic_fmt
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   6: core::panicking::panic_display
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:150:5
      core::panicking::panic_str
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:134:5
      core::option::expect_failed
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:2025:5
   7: sp_io::crypto::ExtCryptoEd25519GenerateVersion1::call
   8: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2),R>>::into_func::wasm_to_host_shim
   9: <unknown>
  10: <unknown>
  11: wasmtime_runtime::traphandlers::catch_traps::call_closure
  12: wasmtime_setjmp
  13: sc_executor_wasmtime::runtime::perform_call
  14: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  15: sc_executor_common::wasm_runtime::WasmInstance::call_export
  16: sc_executor::executor::WasmExecutor<H>::with_instance::{{closure}}
  17: <sc_executor::executor::WasmExecutor<H> as sp_core::traits::CodeExecutor>::call
  18: sp_state_machine::execution::StateMachine<B,H,Exec>::execute
  19: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  20: <sc_rpc::state::state_full::FullState<BE,Block,Client> as sc_rpc::state::StateBackend<Block,Client>>::call
  21: tokio::runtime::task::raw::poll
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
  24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  25: <unknown>
  26: __clone


Thread 'tokio-runtime-worker' panicked at 'No `keystore` associated for the current context!', substrate/primitives/io/src/lib.rs:794

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

```

### Steps to reproduce

Affected versions:
- master
- v1.2.0
- v1.1.0

Working version:
- v1.0.0 

Steps to reproduce:
![image](https://github.com/paritytech/polkadot-sdk/assets/24387396/4b8c2d69-560c-4855-a481-546fe4b96939)

**Comment by bkchr** [comment]
That is was working before, was not correct.

You need to use the RPC `rotate_keys`. This calls the same runtime api, but setups the correct extensions.

**Comment by BulatSaif** [comment]
This call is not used to `rotate_keys`. 

## Current use case:
It is used in [testnet-manager](https://github.com/paritytech/testnet-manager/blob/ab570e372ae37df27002dcb2d7f04e9a8d878fcb/app/lib/collator_account.py#L29) to verify the session key setup for collators.  


![image](https://github.com/paritytech/polkadot-sdk/assets/24387396/84f4bab1-05e0-4bb4-8ff9-4bceb819ba94)


We need this call to debug a key-related issue, that is important for node operation.

**Comment by bkchr** [comment]
Reopening will not bring it back. As I told you, I was working before by accident.

If you want to control the `seed`, you need to use `author_insertKey`.

**Comment by BulatSaif** [comment]
> If you want to control the seed, you need to use `author_insertKey`. 

We are already using `author_insertKey` to control the seed, but when dealing with multiple parachains, it can be challenging to keep track of the key types or schemas for each parachain. We also aim for the `testnet-manager` to be universal and capable of working with any parachain.

## Current Issue
`author_insertKey` accepts three parameters (keyType, suri, publicKey), and there is no verification; you can set any value, and it will be accepted.
![image](https://github.com/paritytech/polkadot-sdk/assets/24387396/2ef1e806-a596-4862-b87c-b70e6bc63fe7)
For example, `asset-hub-polkadot` and `asset-hub-kusama` have different publicKey schemas:
- asset-hub-polkadot - schema: `Ed25519`
- asset-hub-kusama - schema: `Sr25519`

1. You might insert a key and a publicKey with the wrong schema.
2. You set the wrong session key in chainspec.
3. You face the issue that your new parachain is not creating a block.
4. This issue is hard to debug as all keys appear "correct." `author_hasKey` also does not check whether the key is correct.
![image](https://github.com/paritytech/polkadot-sdk/assets/24387396/96890ca0-587f-4701-b3ca-92b0d1d025fd)

The only way to verify that a node can produce a block is to run `author_hasSessionKeys`. However, how can you generate session keys from a seed if you don't know which schema to use, especially for the relay chain where you have multiple keys?

## Proposal
I fully agree that `SessionKeys_generate_session_keys` should not exist, as it is insecure to send your seed over HTTPS, and it may appear in Nginx logs. It should be considered an "unsafe RPC call" (`--rpc-methods unsafe`) similar to `author_insertKey`.

My proposals:
1. Fix the rpc call and hide it behind `--rpc-methods unsafe`, the RPC call should not deal with keystore, just generate a session key and return it.
or 
1. Develop a system or author RPC call that returns information about session keys, including types, schemas, and order. With this information, we will be able to construct session keys ourselves.

**Comment by bkchr** [comment]
> 2\. Develop a system or author RPC call that returns information about session keys, including types, schemas, and order. With this information, we will be able to construct session keys ourselves.

The info can be found in the metadata. So, you can fetch it from there.
