### ISSUE TITLE
Gossip topology does not properly work if peer_id is not cached at the beginning of the  session

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#2138]
While debugging some  flaky tests on zombienet I observed that gossip topology might not work properly if peer id is not available in `AuthorityDiscovery` at the moment we build the topology.

The issue reproduces occasionally on my machine when running zombienets with more than 10 nodes. 

The problem is:
1. We build the topology here: https://github.com/paritytech/polkadot-sdk/blob/e1c033ebe15e6de5ee6a5a81eab2dd213f09d574/polkadot/node/network/bridge/src/rx/mod.rs#L603
2. And fetch the list of peers ID's here: https://github.com/paritytech/polkadot-sdk/blob/e1c033ebe15e6de5ee6a5a81eab2dd213f09d574/polkadot/node/network/bridge/src/rx/mod.rs#L553C1-L554C1, which does not seem to care that the returned PeerId might be none, which might if the PeerId is not in the AddressCache for various reasons.
3. Then we broadcast the incomplete topology to peers, and they won't be aware that peer_ids are missing for some validators so when they call functions that rely on the peer_id that won't work as expected.
https://github.com/paritytech/polkadot-sdk/blob/e1c033ebe15e6de5ee6a5a81eab2dd213f09d574/polkadot/node/network/protocol/src/grid_topology.rs#L228
4. So, those peers won't received any message that they should have received for the full duration of a session.

I think the system would be more robust if we implement a way to update the topology with the peers_ids if they arrive in the AddressCache after the topology has been broadcasted to the rest of the subsystems.

**Comment by sandreim** [comment]
This happens quite often here: https://grafana.teleport.parity.io/goto/Db_mp7aHR?orgId=1

**Comment by validorange** [comment]
I am seeing this on my Polkadot validator (with --log parachain=debug):

Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-net: Discovering authority failed
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-rx: Could not determine peer_id for validator, let the team know in
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: #011#011#011#011https://github.com/paritytech/polkadot-sdk/issues/2138 validator_index=ValidatorIndex(78)
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-net: Discovering authority failed
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-rx: Could not determine peer_id for validator, let the team know in
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: #011#011#011#011https://github.com/paritytech/polkadot-sdk/issues/2138 validator_index=ValidatorIndex(461)
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-net: Discovering authority failed
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-rx: Could not determine peer_id for validator, let the team know in
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: #011#011#011#011https://github.com/paritytech/polkadot-sdk/issues/2138 validator_index=ValidatorIndex(337)
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-rx: Could not determine peer_id for validator, let the team know in
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: #011#011#011#011https://github.com/paritytech/polkadot-sdk/issues/2138 validator_index=ValidatorIndex(304)
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-net: Discovering authority failed
Jun 14 17:06:40 vo-sgp2 polkadot[1237011]: 2025-06-14 17:06:40.196 DEBUG tokio-runtime-worker parachain::network-bridge-net: Discovering authority failed
