### ISSUE TITLE
Create script to refactor benchmarks v1 to v2

### ISSUE THREAD

**Issue by 0xmovses** [paritytech/polkadot-sdk#2141]
This came up in the FRAME weekly call today. We should create a script that will update all the benchmark v1 syntax and structure to benchmark v2. This would alleviate manual work and help the wider community. 

the script would most likely use the [syn](https://crates.io/crates/syn) crate and the `quote!` macro to parse tokens. 

Some further inspiration (not for logic or functionality, but its use of syn) : https://github.com/sam0x17/macro_magic/blob/main/core_macros/src/lib.rs.

The finished script should be pushed to its own repo so that the wider network can make use of it. Creating this issue to track the progress of it as we can use it to refactor the benchmarks. 

Example refactor https://github.com/paritytech/polkadot-sdk/pull/1868

**Comment by kianenigma** [comment]
cool idea, but I must admit I think this is not anywhere near the front of what is bothering developers. I think the existence of weights itself, lack of education and automation around it is the main challenge. I hardly think creating a script for this niche use case would be a big unblocker for anyone or anything. Happy to be challenged about it though :)

**Comment by 0xmovses** [comment]
So in the call I brought up a minor issue I ran into when working on [this PR] (https://github.com/paritytech/polkadot-sdk/pull/1982). Without going into too much detail, the issue was that I was slowed down in several instances when working on the tests which uses the old benchmark v1 syntax. I was slowed down as we don't get help from the compiler when writing test code inside the macro. We have to run the build and run the code first to see simple bugs (slow). 

It happened enough times to make me see the big dev-ex benefit of the v2 syntax for developers working with substrate. Initially I suggested just rewriting these pallet benchmarks to v2 (quite easy), @ggwpez however mentioned that he had written a script (now lost). So I thought writing that would be more useful. 

As a side note, documentation still primarily uses the v1 syntax (scroll down a bit) https://docs.substrate.io/reference/how-to-guides/weights/add-benchmarks/ . I strongly prefer v2 and feel we should only write documentation examples using v2. 

If I was a new developer considering substrate, the v1 benchmark macro would put me off a little. The v2 however, great 👍 And I would know that I'd be spending a lot of my time writing and working within these tests. 

There may be more higher priority issues I'm happy to switch on to, but I feel that anything relating to testing pallet code is important for dev-ex onboarding new devs etc.

**Comment by 0xmovses** [comment]
So I worked on this tool last week, it works with single benchmark tests, but when working with many tests the tests fail, I would need to spend more time debugging and adding some new logic. For now moving onto other things, anyone is free to PR to it in the meantime. 

https://github.com/0xmovses/substrate-benchmark-upgrader

**Comment by ggwpez** [comment]
We doing it manually now, good onboarding task for new devs.
