### ISSUE TITLE
PVF: refactor errors to use `thiserror`

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2157]
We're already using [`thiserror`](https://github.com/dtolnay/thiserror) in some places, so we should consider expanding its usage to reduce boilerplate. For example, we could add `#[from]` attributes for the variants of [`ValidationError`](https://github.com/paritytech/polkadot-sdk/blob/f84b89710b/polkadot/node/core/pvf/src/error.rs#L21), making it easier to construct. For sure another candidate is [`PrepareError`](https://github.com/paritytech/polkadot-sdk/blob/f84b89710b/polkadot/node/core/pvf/common/src/error.rs#L27), we could provide an auto conversion for e.g. `IoErr`, reducing the boilerplate whenever it's constructed. Then instead of a bunch of `map_err`s on `std::io::Error`, we can just use `?`.

See [here](https://github.com/paritytech/polkadot-sdk/blob/f84b89710b/polkadot/node/core/pvf/common/src/worker/security/seccomp.rs#L90-L98) for an example thiserror usage. cc @eagr since you were interested in some refactorings. :)

**Comment by mrcnski** [comment]
@maksimryndin Hey 👋🏻 That would be great! Please let me know if you have any questions. 

If it helps, we have a README in the `pvf/` crate, some module docs (run `cargo doc --open --document-private-items` to make sure you see them all), and some docs in https://github.com/paritytech/polkadot-sdk/tree/master/docs/contributor as well.

**Comment by maksimryndin** [comment]
Thank you @mrcnski  So a roadmap for now
- [ ] check https://github.com/paritytech/polkadot-sdk/tree/master/docs/contributor
- [ ] read `pvf/` README and some pages of the book
- [ ] refactor `ValidationError` and `PrepareError` to use `thiserror`
- [ ] run tests
- [ ] run zombienet tests

**Comment by maksimryndin** [comment]
@mrcnski `codec` macro was mistakenly applied two times to `Kernel` error (so it was encoded with 10 instead of 11 and the same as `JobDied`). I changed it to 11 because
1) it was an initial goal of the code author
2) `Kernel` is less frequent than `JobDied` so in case of existing error encoding it is more probable to have 10 as `JobDied` than `Kernel`

Output of `cargo expand`

```rust
// before

PrepareError::JobDied { ref err, ref job_pid } => {
    __codec_dest_edqy.push_byte(10usize as ::core::primitive::u8);
    ::parity_scale_codec::Encode::encode_to(err, __codec_dest_edqy);
    ::parity_scale_codec::Encode::encode_to(
        job_pid,
        __codec_dest_edqy,
    );
}
PrepareError::Kernel(ref aa) => {
    __codec_dest_edqy.push_byte(10u8 as ::core::primitive::u8);
    ::parity_scale_codec::Encode::encode_to(aa, __codec_dest_edqy);
}

// after

PrepareError::JobDied { ref err, ref job_pid } => {
    __codec_dest_edqy.push_byte(10u8 as ::core::primitive::u8);
    ::parity_scale_codec::Encode::encode_to(err, __codec_dest_edqy);
    ::parity_scale_codec::Encode::encode_to(
        job_pid,
        __codec_dest_edqy,
    );
}
PrepareError::Kernel(ref aa) => {
    __codec_dest_edqy.push_byte(11u8 as ::core::primitive::u8);
    ::parity_scale_codec::Encode::encode_to(aa, __codec_dest_edqy);
}
```

**Comment by maksimryndin** [comment]
@mrcnski I am not sure on labels as I think it is also worth to add `R0-silent` and `T11-documentation` (although I've checked myself the fixed links)

https://github.com/paritytech/polkadot-sdk/pull/2958

I need some time to prepare a proper working environment as it requires Linux amd64 and more free disk space in order to run integration tests

**Comment by mrcnski** [comment]
> I need some time to prepare a proper working environment as it requires Linux amd64 and more free disk space in order to run integration tests

Yes, unfortunately getting this environment set up and testing on it can be a pain. I rented a VPS, but it is really slow to compile.

I think you don't need it for this particular PR though. Most of the Linux-amd64-only tests are testing things like spawning processes, security features, etc. And if there is a failing test, CI will catch it for you.

**Comment by maksimryndin** [comment]
Thank you for a warm welcome @mrcnski :)

**Comment by mrcnski** [comment]
No problem @maksimryndin, let me know if you have any questions. And I appreciate the thoroughness!
