### ISSUE TITLE
[FRAME] Demote `!signed` check before calling `is_inherent`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#2158]
In the runtime expansion code we have the (correct) assumption that signed transactions can never be inherents [here](https://github.com/paritytech/polkadot-sdk/blob/f84b89710b0e6da655a1b40a491a8184780489e7/substrate/frame/support/procedural/src/construct_runtime/expand/inherent.rs#L177) and in one or two other spots.  
I think we can demote this additional check to a `debug_assert`, since `is_inherent` should never return true for a signed call anyway. Sadly it is not possible to do a compile-time check of this AFAIK, since `is_inherent` takes a call instance.

**Comment by bkchr** [comment]
Nothing prevents you from sending a signed inherent. We should clearly not remove this check or make it a `debug_assert`.
