### ISSUE TITLE
Add OutOfStorage support

### ISSUE THREAD

**Issue by rahulksnv** [paritytech/polkadot-sdk#2166]
The original issue: https://github.com/paritytech/substrate/discussions/14350

Summary of the the code path: `apply_extrinsic()` eventually ends up calling the external crate  `wasmtime::TypedFunc::call()` for execution. Which in turn calls into the externalities (via host function) to access the storage.

There is nothing special in wasm spec spec for storage access. Storage access is like any other memory access in the flat memory space. So introducing a new `OutOfStorage` failure or making the externalities fallible does not look feasible.

One proposal:  around [with_storage_layer()](https://paritytech.github.io/polkadot-sdk/master/frame_support/storage/transactional/fn.with_storage_layer.html), after executing the transaction, rollback the transaction and return error if the changes in the overlay exceed a certain threshold (in bytes or number of changes)

**Comment by rahulksnv** [comment]
Have a related question: is it possible for wasm code to specify the fuel consumed "inline"?

If this were possible, something like this could work:
- Unlike pallet-contracts, the `apply_extrinsic()` path  doesn't set any gas/fuel limits before calling into wasmtime. Change this to set gas limits before calling into the `TypeFunc::call()`, like pallet-contracts
- When wasmtime calls  into the externalities, use something like  [1] to charge gas for the access. The gas charged would be proportional to the data size being `get()/put()`

[1] https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.consume_fuel

**Comment by bkchr** [comment]
I was recently thinking about introducing some kind of tracking of the PoV size and letting it return an error if we are above some limit. I assume that is what you also want?

**Comment by vedhavyas** [comment]
@bkchr Something very similar. In our case, we want to error when the StorageProof exceeds a specific limit and as result our Fraud proof carrying such storage proof will never be included.
