### ISSUE TITLE
Genesis Config builder should use the user Executor

### ISSUE THREAD

**Issue by davxy** [paritytech/polkadot-sdk#2188]
(continuation of https://github.com/paritytech/polkadot-sdk/pull/1256#issuecomment-1795927053)

After https://github.com/paritytech/polkadot-sdk/pull/1256 a new issue emerged that requires some attention.

---

Preamble: user is allowed to build an *executor* for the wasm code with a set of custom host functions (HF) to extend the *standard* set of HF contained in the `sp-io` crate.

While building the genesis storage via the new mechanisms we now instance "on the fly" a wasm executor to call into the genesis build functions of each pallet. At the moment this executor is constructed to use **only** the HF contained within the `sp-io` crate.

https://github.com/paritytech/polkadot-sdk/blob/15df7f54d2c32a94bb91f73f19552c8bcde6a9fe/substrate/client/chain-spec/src/genesis_config_builder.rs#L53

Follows that if one pallet, during `GenesisConfig::build()` calls a function which ends up calling one of the user "extra" HF the result is something like:

```
Error: Service(Client(Storage("wasm call error Execution aborted due to trap: call to a missing function env:ext_host_calls_ed_on_bls12_381_bandersnatch_sw_mul_projective_version_1
WASM backtrace:
error while executing at wasm backtrace:
0: 0x1d630c - <unknown>!sp_crypto_ec_utils::ed_on_bls12_381_bandersnatch::host_calls::extern_host_function_impls::ed_on_bls12_381_bandersnatch_sw_mul_projective::he41ac3605fcf7316
1: 0x1d5f2f - <unknown>!<sp_crypto_ec_utils::ed_on_bls12_381_bandersnatch::HostHooks as ark_ed_on_bls12_381_bandersnatch_ext::curves::CurveHooks>::ed_on_bls12_381_bandersnatch_sw_mul_projective::h018e9b5ec8cf1995
2: 0x436a0 - <unknown>!ring::find_complement_point::h9d7f92623339cd13
3: 0x55b85 - <unknown>!bandersnatch_vrfs::ring::KZG::testing_kzg_setup::h839dc63b6f1f7cb8
4: 0x12702b - <unknown>!<pallet_sassafras::pallet::GenesisConfig<T> as frame_support::traits::hooks::BuildGenesisConfig>::build::hb41556b5d2d29887
5: 0xd8857 - <unknown>!<node_template_runtime::RuntimeGenesisConfig as frame_support::traits::hooks::BuildGenesisConfig>::build::h1dd1ff684d453743
6: 0xbcbc4 - <unknown>!frame_support::genesis_builder_helper::build_config::haafd4b46db38d43e
7: 0x10cacd - <unknown>!GenesisBuilder_build_config")))
```

The example above is from Sassafras pallet which uses the HF provided by the `sp-crypto-ec-utils` crate ([here](https://github.com/paritytech/polkadot-sdk/blob/a7bd12dcfd4c7c88d5b03401c4c4923892618ad6/substrate/bin/node-template/node/src/service.rs#L24-L27)) to build some important/mandatory stuff during genesis ([here](https://github.com/paritytech/polkadot-sdk/blob/a7bd12dcfd4c7c88d5b03401c4c4923892618ad6/substrate/frame/sassafras/src/lib.rs#L300))

---

As the user **can** pass its own extra HF for its chain the ideal solution is to have a builder for genesis storage which uses the user provided executor and not construct one on the fly (as we don't know which HF the user used) or an alternative is to make everything generic over the HF, but maybe this is more annoying?

Initially I was thinking about passing the user's  `executor` to the `as_storage_builder` [here](https://github.com/paritytech/polkadot-sdk/blob/15df7f54d2c32a94bb91f73f19552c8bcde6a9fe/substrate/client/service/src/builder.rs#L145) to construct a wrapper around `ChainSpec` which also contains the user executor instance.

Unfortunately this requires the function `as_storage_builder` to be generic over the `CodeExecutor` and this would break the `ChainSpec` object safety, and thus can't be used anymore as a `&dyn ChainSpec` all over the places (e.g. Configuration).

The option to pass an `&dyn CodeExecutor` to `as_storage_builder` is problematic as well since `CodeExecutor` is not object safe.

---

Telling/documenting the user to not do stuff that may end up calling the *extra* HF during the genesis build is not appropriate (IMO) as:
1. the pallet implementor may not know if what he is doing ends up calling some host function which is not part of the ones in `sp-io`.
2. also may limit what the user wants to do to the point of making difficult (or very hacky) doing some stuff

**Comment by michalkucharczyk** [comment]
We'd need sth like this:
```
   33 /// A utility that facilitates calling the GenesisBuilder API from the runtime wasm code blob.
~  34 pub struct GenesisConfigBuilderRuntimeCaller<'a, HF = sp_io::SubstrateHostFunctions> {
   35     code: Cow<'a, [u8]>,
   36     code_hash: Vec<u8>,
~  37     executor: WasmExecutor<HF>,
   38 }
 ```

**Comment by davxy** [comment]
Closed by https://github.com/paritytech/polkadot-sdk/pull/2190
