### ISSUE TITLE
contracts: Rewrite test fixtures in Rust

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#2189]
## Motivation

Currently, all our [text fixtures in pallet-contracts](https://github.com/paritytech/polkadot-sdk/tree/master/substrate/frame/contracts/fixtures) are written in wasm assembly. With the upcoming [RISC-V support](https://github.com/paritytech/polkadot-sdk/issues/115) we want to use the same fixtures to test the new VM. In order to do that we want to rewrite them in Rust and then compile them for each target (wasm, RISC-V). This has the added benefit of making them much easier to read and write.

## The Plan

We add two new crates `pallet-contracts-tests` and `pallet-contract-uapi`. 

### `pallet-contracs-tests`

- Contains the tests which are currently in the [`tests.rs`](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/contracts/src/tests.rs) file
- Contains a directory containing all the fixtures where one `rs` file is one fixture (`#[no_std], #[no_main]` binary)
- Has a `build.rs` file which builds each test fixture to a wasm module (later we add RISC-V support)
- Fixtures depend on `pallet-contracts-uapi`

### `pallet-contracts-uapi`

This  is the pallet contracts user api. Which means this crate exposes all the host functions that a contract can import in a platform independent matter (wasm vs. RISC-V). It basically exports a set of **safe** functions to be used by contracts to interact with the environment. It serves the same function as ink!'s [`ext.rs`](https://github.com/paritytech/ink/blob/master/crates/env/src/engine/on_chain/ext.rs) file. We essentially move the code from ink! to this crate so it can be shared between different implementations.

For now, we only need to implement the most recent version of each function. When we add new versions we should keep the old one under the same name so we don't have to bump majors.

Please note that we don't implement a memory allocator or panic handler there. It is strictly for the user api. Other common code that fixtures need should be implemented in `pallet-contracts-tests`.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-5-0/5358/1
