### ISSUE TITLE
PVF: Fix `cargo test -r` building debug workers

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2194]
`cargo test -r` in `node/core/pvf` builds debug workers, but uses release workers for tests.

## Related

https://github.com/paritytech/polkadot-sdk/pull/2018/

**Comment by eagr** [comment]
Turns out we probably should still check the existence of worker binaries and only rebuild when absent. Now maybe we could tag a version and add a version check. Based on unscientific observation, cargo would rebuild the workers most of the time, which takes a long time to run the tests..

**Comment by mrcnski** [comment]
@eagr Great question. The thing is, if you're running the PVF tests, chances are high that you changed something in the workers that should be tested. So it makes sense to rebuild them on all changes, in this scenario.

The version check is for the more general case, where someone is hacking on an unrelated part of polkadot. In that case, it's very unlikely that the workers changed, so rebuilding them on every change would be a UX burden. We want to at least ensure that we're not executing artifacts prepared by a different wasmtime version, which would violate safety constraints. Other changes could of course have happened in the workers, but most of the time the workers would either immediately crash, or some internal logic changed that doesn't necessarily cause safety issues.

It's a trade-off. I for sure understand that recompiling often is annoying. So are tests that fail for unknown reasons. Let me know what you think!

**Comment by mrcnski** [comment]
Part of the problem in the second scenario is that the workers live in the same crate as `polkadot`, sharing its dependencies. So every time a dependency of `polkadot` has changed, the workers get rebuilt, even if the workers do not use this dependency themselves.

The solution would be to pull them into separate crates, but AFAICT it would be impossible to `cargo install` them in that case. I have an open [forum post](https://internals.rust-lang.org/t/provide-a-way-to-always-build-required-binaries/19403) on IRLO that is closely related to that. But, as idealistic as I am, this hasn't really been an issue in practice, so I haven't focused on it too much.

**Comment by eagr** [comment]
> The thing is, if you're running the PVF tests, chances are high that you changed something in the workers that should be tested. So it makes sense to rebuild them on all changes, in this scenario.

Most of of the time, I didn't touch the worker code, but it still happened. On the top of my head, what if we hash the worker code and tag the binary?

**Comment by mrcnski** [comment]
> Most of of the time, I didn't touch the worker code, but it still happened.

Yeah, that's related to what I said above. `polkadot` and the workers are in the same crate, so when `polkadot` gets rebuilt (because `pvf` changed, which `polkadot` depends on`), so do the workers. It's unfortunate, and requires some fixes to cargo, but the cargo team are resistant to change requests. When I have time I need to circle back and (try to) get that IRLO thread moving.

> On the top of my head, what if we hash the worker code and tag the binary?

Not sure if I understand, but it sounds a bit hacky. The "proper" way to fix it would be at the cargo level, or to move to a "better" build system (which the cargo team itself advises doing, which would be funny if it wasn't sad). But moving away from cargo would be pretty disruptive to Parity and the ecosystem.

**Comment by eagr** [comment]
> Not sure if I understand, but it sounds a bit hacky.

I've read the forum thread. Seems like a no-go on their side. I could whip something up real quick. It's definitely ad hoc, but maybe it would work.

**Comment by mrcnski** [comment]
> I've read the forum thread. Seems like a no-go on their side.

Well, it's not clear if they understood what the problem was. My next step was going to be to set up a really simple example repo with separate bin crates and challenge them to find a simple way to `cargo install` all the crates. That would demonstrate the problem.

> I could whip something up real quick. It's definitely ad hoc, but maybe it would work.

Hmm... there is already a bit too much complexity with these workers. PolkaVM [just announced](https://forum.polkadot.network/t/announcing-polkavm-a-new-risc-v-based-vm-for-smart-contracts-and-possibly-more/3811/33?u=m-cat) that they are as fast as wasmtime now, so we might anyway switch to that in the near future. It's not clear to me yet how much this will change the architecture of candidate-validation.

**Comment by eagr** [comment]
Nice to know! In that case, I'll drop that thought~
