### ISSUE TITLE
Figure out bounds and configs for MB staking/EPM

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-sdk#2200]
Figure out (theoretically and based on hard benchmark numbers) how many backers/validators could staking and EPM support if running on a parachain, with no code changes.

This can be achieved by 1) looking at the number of reads/writes that each election takes and 2) calculate based on the current benchmarks.

This should give us a good mental model of how much the staking parachain related pallets should improve the current implementation.

Ideas to figure out

- [ ] ~~Nominator Per Exposure~~ (removing as it is not related to the staking MB)  
- [x] Page Size for Snapshot (no benchs, PoV only)
- [x] Largest Unsigned submission.
- [x] Largest onchain election (ongoing)

 https://hackmd.io/KpU6KVL-QOiwRxWPY9FDdQ

**Comment by burdges** [comment]
It's tricky to do so, but in principle audits permit alterations to the runtime & memory constraints of a system parachain, including NPoS elections. 

We do not yet have validator operators yet, right?  We could do operators first too, but it requires a nicer migration story than usual.

**Comment by gpestana** [comment]
>  We could do operators first too, but it requires a nicer migration story than usual.

I think that is more relevant later on. For now, the purpose of this task is just to learn about the computation constraints of the parachain in the context of the _current_ staking system. I see this more as a way for us to learn more about PoV constraints and whatnot.
