### ISSUE TITLE
Integration of bulk assigner with core-time messages

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2207]
Bulk Assignment provider is almost there. Next up will be wiring it up with message UMP messages processing, with messages coming from the core time/broker chain.

- [x] Setup channels
- [x] Process incoming `assign_core` messages by forwarding to bulk assignment provider
- [x] Test first bulk parachain on Zombienet

**Comment by bkchr** [comment]
Also done?
