### ISSUE TITLE
How to connet to wallet

### ISSUE THREAD

**Issue by niloufar-kashefi** [paritytech/polkadot-sdk#2216]
Dear polkadot team
I made my polkadot blockchain based on substrate three month later, I recently noticed your new development (Polkadot sdk), so I decided that use this instead of previous, I need some help to connet a polkadot wallet (for example nova) to my network

**Comment by bkchr** [comment]
Hey, please reach out to Nova. This is not the right place for these questions.

**Comment by niloufar-kashefi** [comment]
> Hey, please reach out to Nova. This is not the right place for these questions.

Sure
