### ISSUE TITLE
Propose async backing parameter change on Kusama

### ISSUE THREAD

**Issue by Sophia-Gold** [paritytech/polkadot-sdk#2236]
After the runtime upgrade with async backing is activated there will be two new parameters:

```
"async_backing_params": {
	          "max_candidate_depth": 0,
	          "allowed_ancestry_len": 0
              }
``` 

These need to be set to 3 and 2 respectively in governance for async backing to be enabled.

⚠️ `scheduling_lookahead` must also be set to 2 along with this change otherwise parachain block times will degrade to worse than with sync backing! ⚠️

**Comment by alexggh** [comment]
Async backing has been enabled on both kusama and polkadot, see https://github.com/paritytech/polkadot-sdk/issues/3226
