### ISSUE TITLE
xcmPallet transfers should revert for incomplete XCM execution

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#2237]
Because it is silly to not do so and now we need to figure out how to rescue people's stuck funds https://kusama.subscan.io/extrinsic/20471678-2?event=20471678-36

The whole problem can be simplified if xtokens is used, which does the right thing https://github.com/open-web3-stack/open-runtime-module-library/blob/0abce5c717df8b47466ced37205fd961774a1eb2/xtokens/src/lib.rs#L669

**Comment by dzmitry-lahoda** [comment]
yeah, we also have stuck https://kusama.subscan.io/xcm_message/kusama-fe8f0e0b219d5008889ec6aac8d295e8aa12575a

**Comment by bkchr** [comment]
CC @franciscoaguirre @KiChjang

**Comment by KiChjang** [comment]
I've asked Bryan before about this: how exactly does the linked xtokens code revert anything?

**Comment by xlc** [comment]
The magical question mark?

Simply return a dispatch error and mark the transaction fail and everything will be reverted.

**Comment by bkchr** [comment]
Sounds like https://github.com/paritytech/polkadot-sdk/pull/1222 should help here?

**Comment by dzmitry-lahoda** [comment]
https://substrate.stackexchange.com/questions/10433/tokens-lost-when-xcm-messageprocessor-processing-failed

**Comment by KiChjang** [comment]
> The magical question mark?
> 
> Simply return a dispatch error and mark the transaction fail and everything will be reverted.

That doesn't revert anything that the XCM executor has done. I'm quite surprised that you're suggesting this -- the only solution that can work here is exactly what Basti has linked: #1222. If we can get some reviews on that PR, that would be great.

**Comment by xlc** [comment]
what? calls are transactional, I asked for this for many years and we got it. you can’t just say it doesn’t work or we have bigger problem

**Comment by KiChjang** [comment]
Please show us where we have a problem simply because we lacked a question mark operator.

**Comment by xlc** [comment]
I don't know what else do I need to show because we debugged the XCM issue together. Anyway, I will just make a PR with unit test for this.
