### ISSUE TITLE
Unreserve funds from gov v1 - Proposal proposers still have their tokens locked

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#2247]
Unreserve funds from gov v1 treasury proposals. These proposals are still present and have their funds reserved.

**Comment by liamaharon** [comment]
I had been under the impression that we needed to unlock funds which were 'stuck' in the runtime due their associated pallets being removed from the runtime with Gov V1.

Those pallets and funds to be unlocked were listed publicly here: https://github.com/paritytech/polkadot/pull/7314, and have been unlocked successfully on Kusama so far.

Given Treasury is integral to OpenGov, still in the runtimes, and those proposals are managable via the Treasurer track, I was unaware that funds parked there also needed to be released. That was a misunderstanding, sorry about that.

Treasury is still functional, so I suggest the best path forward is to submit a `batch_all` ib the `Treasurer` track to reject all these open proposals. There doesn't seem to be a need to do it via a runtime upgrade.

@rrtti and Otar could you please confirm and advise the best path forward to creating a call from the Treasury proposal for this?

**Comment by dudo50** [comment]
Thanks @liamaharon, I have suggested a while ago same thing. All funds can be released by batch call containing reject and treasury spend for adequate amount.

**Comment by liamaharon** [comment]
Referenda has been submitted: https://kusama.subsquare.io/referenda/306

If there're issues with the referenda, they belong in the Polkadot forum rather than a GH issue :)
