### ISSUE TITLE
Kusama upgrade causes XCM execution barrier

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#2266]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Bifrost is currently using the polkadot-v0.9.42 dependency, and this is the XCM Barrier configuration information.
 
```rust
pub type Barrier = (
	// Weight that is paid for may be consumed.
	TakeWeightCredit,
	// Expected responses are OK.
	AllowKnownQueryResponses<PolkadotXcm>,
	// If the message is one that immediately attemps to pay for execution, then allow it.
	AllowTopLevelPaidExecutionFrom<Everything>,
	// Subscriptions for version tracking are OK.
	AllowSubscriptionsFrom<Everything>,
	// Barrier allowing a top level paid message with DescendOrigin instruction
	AllowTopLevelPaidExecutionDescendOriginFirst<Everything>,
);
```
Bifrost will use `ReportTransactStatus` to get the execution status of XCM messages on the relay chain, but since the upgrade, it is not available, after getting the QueryResponse sent by the relay chain, it will report a Barrier error, the following is the error log of using Chopsticks.

You can see that the XCM message in the relay chain has been executed successfully.  
```json
{
    "data": {
      "amount": "(number)",
      "stash": "EckcmXbCj4huvNLP5btMFmJz8SzEt5s8hgKcL6LM8BtZeAf",
    },
    "method": "Unbonded",
    "section": "staking",
  },
  {
    "data": {
      "id": "(hash)",
      "origin": {
        "Ump": {
          "Para": "(number)",
        },
      },
      "success": true,
      "weightUsed": {
        "proofSize": "(number)",
        "refTime": "(number)",
      },
    },
    "method": "Processed",
    "section": "messageQueue",
  },
```
It will then send a QueryResponse message to Bifrost informing it that it has been successfully executed. But it fails when Bifrost wants to execute the QueryResponse message,  which hasn't happened since before the upgrade.

```json
  {
    "data": {
      "count": 1,
    },
    "method": "DownwardMessagesReceived",
    "section": "parachainSystem",
  },
  {
    "data": {
      "messageId": "(hash)",
      "outcome": {
        "Error": "Barrier",
      },
    },
    "method": "ExecutedDownward",
    "section": "dmpQueue",
  },
  {
    "data": {
      "dmqHead": "(hash)",
      "weightUsed": {
        "proofSize": 0,
        "refTime": 0,
      },
    },
    "method": "DownwardMessagesProcessed",
    "section": "parachainSystem",
  }
```

**Comment by hqwangningbo** [comment]
@KiChjang @xlc cc

**Comment by KiChjang** [comment]
This is likely because the new `WithUniqueTopic` router appends a `SetTopic` instruction right after the `QueryResponse` instruction, which causes the `AllowKnownQueryResponses` barrier to fail, as it only expects 1 and only 1 instruction.

**Comment by gavofyork** [comment]
The fix is to upgrade to XCMv3 and configure the chain to manage the `SetTopic` instruction via the `TrailingSetTopicAsId` barrier. This is detailed in the PR which introduced this functionality, 6 months ago: https://github.com/paritytech/polkadot/pull/7234

**Comment by hqwangningbo** [comment]
@KiChjang @gavofyork Thanks for the answer, we will fix it with a runtime upgrade.
