### ISSUE TITLE
Core time: Configuration Changes

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2268]
Reconsider whether configurations should even differ (likely not) and then either rename configurations to apply for bulk and on-demand or add new ones for bulk. In particular:

	pub max_availability_timeouts: u32,
	pub ttl: BlockNumber,

If we settle on having them unified (even with legacy), remove `[get_provider_config](https://github.com/paritytech/polkadot-sdk/blob/fc358fdf18c8aff62598cd3e3e072b74e32ba792/polkadot/runtime/parachains/src/assigner.rs#L176) from `AssignmentProvider` interface and read configuration directly.

Configurations to change/migrate:

- [ ] Above options as described
- [x] Rename `on_demand_cores` configuration to `coretime_cores` and change meaning to specify how many cores are controlled by coretime. (Will be all eventually.) This configuration will be set by the core time chain via `request_core_count`.

**Comment by eskimor** [comment]
It needs to be properly session buffered. An easy way to achieve this, is to simply have it as part of the configuration (which is already session buffered). This is not set in stone though, but it kinda makes sense. It is a configuration after all, just set by the coretime chain.

**Comment by eskimor** [comment]
@tdimitrov any updates on this one?

**Comment by tdimitrov** [comment]
I still haven't started working on this one. I'll do it by tomorrow.
