### ISSUE TITLE
[NFTs] `create` should emit `CollectionMaxSupplySet ` when `max_supply` has value in config

### ISSUE THREAD

**Issue by vikiival** [paritytech/polkadot-sdk#2293]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Context 

When someone creates an collection with `config.max_supply = 1`.
The chain should emit `CollectionMaxSupplySet` same as this function `set_collection_max_supply `

https://github.com/paritytech/polkadot-sdk/blob/604704a84ce690eca93fd053abec1bb0a2b0ee32/substrate/frame/nfts/src/lib.rs#L1656

https://github.com/paritytech/polkadot-sdk/blob/5f4ce8026693b537beaee3aea5161ee34bac7ace/substrate/frame/nfts/src/features/create_delete_collection.rs#L67

### Expected 

I expect that `CollectionMaxSupplySet` should be emitted then `config.max_supply` has a value.

### Steps to reproduce

[](https://user-images.githubusercontent.com/9987732/282414710-907d8b3c-a98f-4872-8b4c-142cdb58e935.png)

**Comment by bkchr** [comment]
CC @jsidorenko
