### ISSUE TITLE
MessageQueue pallet does not process message

### ISSUE THREAD

**Issue by claravanstaden** [paritytech/polkadot-sdk#2319]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When using the MessageQueue pallet to enqueue a message, and the `process_message` implementation of the enqueued message enqueues another message of a different origin, the other message is never processed. 

To illustrate:
- [enqueue message](https://github.com/paritytech/polkadot-sdk/blob/39cc95740aa03f53a0e8bfb8537f0ddb5fa3e19e/substrate/frame/message-queue/src/lib.rs#L1476) (origin: `Here` message: `first message`)
- when ☝🏻 is processed using trait [ProcessMessage](https://github.com/paritytech/polkadot-sdk/blob/39cc95740aa03f53a0e8bfb8537f0ddb5fa3e19e/substrate/frame/support/src/traits/messages.rs#L52) (method `processed_message`), enqueue another message (origin: `There` message: `another message`)
- `another message` never gets processed

This happens specifically when the other message is added to the `neighbour.prev` pointer in the message queue `ready_ring_unknit` method (when the first message is linked to the other message). 

### Steps to reproduce

Here are tests that replicate the bug:

https://github.com/paritytech/polkadot-sdk/compare/master...claravanstaden:master

**Comment by acatangiu** [comment]
cc @ggwpez

**Comment by vgeddes** [comment]
Some further background information - Clara discovered the bug while updating [Snowbridge](https://github.com/Snowfork/snowbridge) to use a bleeding-edge version of the SDK. This version includes https://github.com/paritytech/polkadot-sdk/pull/1246, which changes the XCMP subsystem to use `MessageQueue` as a message buffer.

This results in the behavior Clara described in general terms. In our case specifically, when `MessageQueue` services a message with a `Sibling(ParaId)` origin, and this message contains an `ExportMessage(dest=Ethereum)` XCM instruction, then our handler for `ExportMessage` ends up enqueuing another message with a different origin.

**Comment by gavofyork** [comment]
would be good if you could add a test to demonstrate the issue. @vgeddes @claravanstaden

**Comment by claravanstaden** [comment]
> would be good if you could add a test to demonstrate the issue. @vgeddes @claravanstaden

@gavofyork I added a test over here: https://github.com/paritytech/polkadot-sdk/compare/master...claravanstaden:master

**Comment by ggwpez** [comment]
I will fix it

**Comment by ggwpez** [comment]
Fix is here https://github.com/paritytech/polkadot-sdk/pull/2356. Waiting for feedback now on the approach, then hopefully going to audit/merge.
