### ISSUE TITLE
Cumulus's `ExportGenesisState` command does not respect custom `GenesisBuilder` implementations

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-sdk#2326]
Substrate is flexible enough that chain developers can provide their own methods for creating a genesis block. For details see the [`GenesisBlockBuilder` trait docs](https://paritytech.github.io/polkadot-sdk/master/sc_service/struct.GenesisBlockBuilder.html) and my [Stack Exchange Question](https://substrate.stackexchange.com/questions/10105/extrinsics-in-genesis-block).

Although Substrate has this feature, it is not widely used in the Ecosystem. As far as I know, the [Tuxedo](https://github.com/Off-Narrative-Labs/Tuxedo) template is the first to use a [Custom Genesis Block Builder](https://github.com/Off-Narrative-Labs/Tuxedo/blob/d6c52b857c4c9aa0515d9f6ab4639d6e0326cdac/tuxedo-core/src/genesis.rs#L52-L98). It is working great as a standalone chain. The problem comes when I try to create a parachain.

Specifically, cumulus's [`ExportGenesisState` command](https://paritytech.github.io/polkadot-sdk/master/adder_collator/cli/struct.ExportGenesisStateCommand.html) assumes that the genesis block will not contain any extrinsics. Indeed, the `generate_genesis_block` helper function [assumes no genesis extrinsics](https://github.com/paritytech/polkadot-sdk/blob/cd38ccff7ff49b8f00bbaf799b2056c97ee6e0e9/cumulus/client/cli/src/lib.rs#L197-L200).

**Comment by JoshOrndorff** [comment]
Also, why is it called "export genesis _state_"? Shouldn't it be "export genesis _header_" or _head data_ or something?

**Comment by bkchr** [comment]
I think it was called genesis state at some point at time in the `register` function.

**Comment by bkchr** [comment]
Looks like you may register the wrong header on the relay chain. Best is that you check the head data in the relay chain state.

**Comment by muraca** [comment]
I've been playing with this issue as well.
When launching the network, the output is:
`[Parachain] 🔨 Initializing Genesis block/state (state: 0xdb2f…d87b, header-hash: 0xc43b…254f)`

Once the parachain is started, the output is the following:
https://github.com/paritytech/polkadot-sdk/blob/72c453563937c36b895c543bc5e852e213a54f19/cumulus/client/collator/src/service.rs#L150-L154
`[Parachain] Could not find the header of the genesis block in the database! block_hash=0xafd7f546d317aa37b61562a9721505a5f5ae9ce57a2368e89e25f40b446eedab`

I added the following lines to retrieve the expected hash: 
```rust
tracing::error!(
    target: LOG_TARGET,
    expected_hash = ?self.block_status.block_hash(Zero::zero()),
    "We were expecting another hash.",
);
```
`[Parachain] We were expecting another hash. expected_hash=Ok(Some(0xc43be0484c645277473d541ce98d664cbdf32cf258078abc31c964d21c16254f))`
It matches the one printed at the beginning.
