### ISSUE TITLE
Core time: Rococo

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2348]
Migrate Rococo to core time. Most of these steps, will be applicable to other chains (Westend, Kusama, Polkadot) as well. Small alternations will be required. Let's have a plan for Rococo, execute, learn and then copy this ticket for other chains to do the same (as applicable).

## Checklist
- [x] coretime chain was registered as legacy parachain
- [x] coretime chain is running
- [ ] No leases with leading `None`s exist and also won't come into existence soon (auctions)?
- [ ] [Limits](https://github.com/paritytech/polkadot-sdk/blob/ed7c9e7e5c56ece37bf57d727815f72beaa317e0/cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs#L219) are high enough for migrations to succeed?
- [x] [Weight limit](https://github.com/paritytech/polkadot-sdk/blob/b088dc78d267fa615e630318737f01f28dca1b7c/polkadot/runtime/parachains/src/coretime/mod.rs#L250) is higher than actual weights (as benchmarked), but low enough to fit in a block?
- [ ] Shorten Rococo parachain leases a bit?
- [ ] relay chain runtime upgrade
- [ ] Ping community that their leases are running out and that they can buy core time now with their ROC, to keep their chains running.
- [ ] start_sales: Pass in proper last_sale configuration to have sales start at the proper time.

## Migration Details

The already existing on-demand will now be provided by the bulk/core time provider.

**Comment by bkchr** [comment]
FYI: https://github.com/paritytech/roadmap/issues/52
