### ISSUE TITLE
Nomination pools cannot chill if depositor bond is less than `MinNominatorBond`

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-sdk#2350]
Nomination pools currently have an issue whereby member funds cannot be unbonded if the depositor bonded amount is less than `MinNominatorBond`. 

E.g. Pool 72 (this is a [real scenario](https://polkadot.subscan.io/nomination_pool/72) at the time of writing)

```
MinNominatorBond: 250 DOT
---
Pool Depositor Bonded: 240 DOT 
Pool Member 1 Bonded: 200 DOT
```

Now Pool Member 1 cannot unbond the full amount (only up to 190 DOT, to maintain at least 10 DOT for the pool stash to meet `MinNominatorBond`), and gets the `InsufficientBond` error on an attempt. 

The solution for direct nominators is to chill before unbonding, but nomination pools do not currently support a call to permissionlessly chill if the depositor's bond is below `MinNominatorBond`.

For added context, `StakingInterface::chill` checks the threshold of the total bonded funds of the nominator, which equates to the total balance of a nomination pool's stash account.

It looks like we need a direct call into `Staking::chill` from the nomination pool pallet via a permissionless call, that validates the depositor's bond is less than `MinNominatorBond` prior to it calling `chill` in the staking pallet. If a pool was able to chill under this condition, members would then be able to unbond, as the pool would no longer be nominating.

**Comment by muddlebee** [comment]
I would like take a stab on this. I have never contributed before, so mught take time to figure out stuff 👀

**Comment by valentunn** [comment]
Another user is facing the same issue and cannot unstake all of the staked tokens:
https://polkadot.subscan.io/nomination_pool/31

**Comment by Ank4n** [comment]
> I would like take a stab on this. I have never contributed before, so mught take time to figure out stuff 👀

How is it going? Have you made progress?

**Comment by Ank4n** [comment]
> Another user is facing the same issue and cannot unstake all of the staked tokens: https://polkadot.subscan.io/nomination_pool/31

If it is possible to get in touch with pool creator, the best way currently is for them to top up their stake up to minimum bond.

The more long term solution is, as Ross described, having a permissionless extrinsic exposed by Pool that allows chilling of pool if the creator stake is lower than `MinimumNominatorBond`. This though has the side effect that whenever this number increases further in future, creators would need to top it up else someone can chill the pool. Given the expectation is the pool operators are actively managing the pool, this should be acceptable.

**Comment by dastansam** [comment]
hey @Ank4n @kianenigma 

I would like to work on this

**Comment by Ank4n** [comment]
> hey @Ank4n @kianenigma 
> 
> I would like to work on this

Since there is no PR yet from @muddlebee , feel free to start working on it.

**Comment by muddlebee** [comment]
go ahead. didn't get time to pick this up.
