### ISSUE TITLE
Core time: Westend

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2352]
Checklist from Rococo to be copied over, apart from those:

- [x] Change assigner from legacy to new one wrapping legacy + bulk
- [x] Write appropriate migrations (scheduler): V0Assignment -> Assignment (no on-demand handling needed)
- [ ] Test migration

**Comment by eskimor** [comment]
Commit reverting westend changes: https://github.com/paritytech/polkadot-sdk/pull/2756/commits/993b6b71bc0cb1ebc6b8eb216dacb21829ce017c

**Comment by eskimor** [comment]
Kusama Checklist: https://github.com/paritytech/polkadot-sdk/issues/2353

**Comment by eskimor** [comment]
@antonva I believe you are on this already?

**Comment by bkchr** [comment]
Done.
