### ISSUE TITLE
PVF: Incorporate wasmtime version in worker version checks

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2398]
For example, say someone downloads the node and workers at a release version, and then switches to `master` for some bug fixes. He could be running an updated node without updating the workers, but the node version hasn't changed so the version check passes. But wasmtime may have been bumped since then.

Wasmtime bumps are rare enough, that we can enforce rebuilds without impacting the dev UX. Should be simple to implement; see the new `SUBSTRATE_WASMTIME_VERSION` env var.

_Originally posted by @mrcnski in https://github.com/paritytech/polkadot-sdk/issues/1918#issuecomment-1807948600_

**Comment by s0me0ne-unkn0wn** [comment]
Closing as superseded by #3139
