### ISSUE TITLE
`chain-spec-builder` failing

### ISSUE THREAD

**Issue by NachoPal** [paritytech/polkadot-sdk#2429]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I am getting the following error:
```
Error: "getting default config from runtime should work: wasm call error Other: Exported method GenesisBuilder_create_default_config is not found"
```
when trying to build a chain_spec.

This is the command I run:
```
./target/release/chain-spec-builder create -r polkadot_runtime.wasm default /dev/stdout
```

@michalkucharczyk

**Comment by michalkucharczyk** [comment]
`polkadot` and `kusama` runtime do not have support for `genesis-builder` yet.
This PR is still pending: https://github.com/polkadot-fellows/runtimes/pull/51

**Comment by michalkucharczyk** [comment]
There is also a temporary tool that allows to get chainspecs: https://github.com/polkadot-fellows/runtimes/pull/78
