### ISSUE TITLE
Use Cargo sparse-registry

### ISSUE THREAD

**Issue by 0xmovses** [paritytech/polkadot-sdk#2496]
Doing so should significantly reduce CI build times, read more about this Cargo feature here: https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html

**Comment by ggwpez** [comment]
I think our CIs should always build with `--locked` anywhere. Maybe we should promote that to `--frozen` to also not consult the registry at all.

**Comment by bkchr** [comment]
> Maybe we should promote that to `--frozen` to also not consult the registry at all.

We need to download the crates, you can not work around this 🤷

https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html sparse registry is also the default. Also we are nowhere near being bound by the download time of the registry.

**Comment by 0xmovses** [comment]
Ah I didn't know it was the default in 1.70 👍
