### ISSUE TITLE
Polkadot: Resuscitate the `testing.md` test instructions

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2527]
This `testing.md` doc is pretty old and needs some love. I've never heard anyone mention Gurke or simnet, can that be removed?

_Originally posted by @mrcnski in https://github.com/paritytech/polkadot-sdk/pull/2058#pullrequestreview-1751027378_
            
Partially resuscitated in https://github.com/paritytech/polkadot-sdk/pull/2058.

**Comment by philoniare** [comment]
@mrcnski can I take this? 

In summary, we just need make sure that the `testing.md` is up to date and that commands mentioned there work, right?

**Comment by philoniare** [comment]
@mrcnski great, can you assign this to me?

**Comment by philoniare** [comment]
Would be great if @s0me0ne-unkn0wn could review the PR
