### ISSUE TITLE
`configure_xcm` macro

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#2544]
Thinking of how to achieve https://github.com/paritytech/polkadot-sdk/issues/2124, and thinking of the importance of XCM configuration, and the importance to make it simpler, I thought we should make a macro for it, like how we have a macro for `construct_runtime`.

The main goals are:
- Allowing a new parachain to very easily get a safe, correct XCM configuration without needing to look at other projects
- Allowing parachains to clearly specify which instructions they do and don't support

The syntax I came up with looks something like this:

```rust
configure_xcm! {
	instructions: {
		assets: { // This adds all instructions that process local assets
			AssetTransactors, // required, the main trait
			// optional
			exclude: [burn_asset],
		},
		locks: {}, // We enable locking instructions, using the defaults
		reserve_transfers: {
			is_reserve: IsReserve, // From the outside
		},
		// By not specifying them, we exclude all other instructions
	},
	barrier: {}, // Default barrier is always active, AllowTopLevelPaidExecutionFor, gives a warning otherwise unless #[allow_feeless] or something explicit like that
	weigher: {}, // Will have a default of a lot of weight per instruction, to force overwriting it
}
```

Instructions are grouped by which use the same underlying trait.
XCM Instructions are already very decoupled using many different traits, but they all need to come together in a config in the end.
With this macro, it'd be simple for developers to start with a good configuration and easily extend it from there.
It'd be easier as well to make documentation for it.

I don't know if this already happens. But sharing the XCM configuration via metadata would be good, to allow chains/UIs to know which instructions are supported and which ones are not.

**Comment by bkchr** [comment]
Closing the duplicate.
