### ISSUE TITLE
Clean up cumulus test service

### ISSUE THREAD

**Issue by skunert** [paritytech/polkadot-sdk#2567]
Followup to https://github.com/paritytech/polkadot-sdk/pull/2331.

Todos:
- [ ] Take a look if https://github.com/skunert/polkadot-sdk/tree/ec3a61ed86305e5b70ce6e466cf127addf560186/cumulus/test/service/benches/transaction_throughput.rs still works as expected.
- [ ] Check if we can get rid of https://github.com/paritytech/polkadot-sdk/pull/2331/files#r1404100488, still used by the benchmark mentioned above
- [x] Check if we can remove unused `parachain_id` param or if it breaks zombienet https://github.com/paritytech/polkadot-sdk/pull/2331/files#r1404101362

**Comment by pepoviola** [comment]
> Check if we can remove unused parachain_id param or if it breaks zombienet https://github.com/paritytech/polkadot-sdk/pull/2331/files#r1404101362

We only add the `--parachain-id` flag for `adder/undying` collators or collators, so will be ok to remove it.
