### ISSUE TITLE
Coretime: Smooth transition of legacy parachains

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2578]
1. Write a migration, creating assignments for all existing paras and set legacy core count to 0 on the relay chain. -> Easy enough.
2. Coretime chain needs a similar migration to match the relay chain state. It should happen after the relay chain got migrated, then I don't see anything that could go wrong here.
3. Coretime chain would give them a reserved core for their remaining lease.
4. Done and profit.

**Comment by eskimor** [comment]
Likely better alternative:

1. Write a migration, creating assignments for all existing paras and set legacy core count to 0 on the relay chain. -> Easy enough.
2. Coretime chain needs a similar migration to match the relay chain state. It should happen after the relay chain got migrated, then I don't see anything that could go wrong here.
3. Coretime chain would give them a reserved core for their remaining lease.
4. Done and profit.

**Comment by eskimor** [comment]
Exact configuration to be posted here (to be shared between coretime- and relaychain).

**Comment by joepetrowski** [comment]
If sharing a core round-robin is an option already, I'd go for:

1. Coretime
2. Asset Hub + Collectives
3. Bridge Hub + People

Note: would not group Asset Hub and Bridge Hub on the same core, because a surge on BH implies a surge on AH, so I think it makes more sense to put somewhat-coupled things on different cores.

**Comment by eskimor** [comment]
And we should have one assignment for on-demand as well.

1. system chains
2. lease chains
3. one assigned to pool (on-demand)
4. a few more already to throw on the market?

**Comment by eskimor** [comment]
For bootstrapping, I think it will be the easiest if we onboard/register the broker chain beforehand. With this, we can simply create assignments for all existing chains and be good, otherwise we would need to register the core time chain for the next session, which needlessly complicates the migration.

Also @bkchr is right. To keep things simple, I am just getting a core for each existing parachain. We can merge them onto one core later.

**Comment by eskimor** [comment]
Migration logic (to replicate on the Coretime chain): https://github.com/paritytech/polkadot-sdk/blob/57ffbdbd0e30767e6072dcdaffbe701134a10674/polkadot/runtime/parachains/src/assigner_coretime/migration.rs#L88

**Comment by eskimor** [comment]
Note, we do this as a three step procedure:

1. Register the coretime chain as a legacy system chain.
2. Upgrade runtime (all existing chains will be migrated), no additional cores will be available. (Core count stays the same.) - on-demand will continue to exist (as it was present before).
3. Additional cores can be created/assigned later on.

**Comment by bkchr** [comment]
> otherwise we would need to register the core time chain for the next session, which needlessly complicates the migration.

I don't see the problem? As long as we register all assignments without any time out, it isn't really important when the coretime chain will start working?

**Comment by eskimor** [comment]
> I don't see the problem? As long as we register all assignments without any time out, it isn't really important when the coretime chain will start working?

Not really a problem. It is just cleaner if it were present previously already and likely less error prone.
