### ISSUE TITLE
Rename `IntegrityTest`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#258]
as noted in https://github.com/paritytech/substrate/pull/10174, this hook has a very opaque name. Consequently, I think it has never been used as much as it should have been. TO this day, I bump into experienced substrate developers who don't know it exists, or can't really tell what it is from the name.

The first step is to rename this to `construct_runtime_check` or `on_construct_runtime()` to be more aligned with the rest of the hooks. 

The existing method should be marked as deprecated as per #182.

**Comment by wirednkod** [comment]
@kianenigma I'll jump on this one

**Comment by ggwpez** [comment]
https://github.com/paritytech/polkadot-sdk/pull/1604 concluded that the name is good for now.
