### ISSUE TITLE
Measure consensus Nakamoto coefficient

### ISSUE THREAD

**Issue by alfredonodo** [paritytech/polkadot-sdk#2588]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Measure the decentralization of the project via Nakamoto coefficient, which is the measure of the smallest number of independent entities that can act collectively to block the consensus of a blockchain.

### Request

An independent open source third party project, [nakaflow](https://nakaflow.io/), compares all major blockchains in terms of Nakamoto coefficient. It would be very interesting to add Polkadot.

### Solution

Add it to [nakaflow](https://nakaflow.io/). I do not have sufficient expertise to [do it](https://github.com/xenowits/nakomoto-coefficient-calculator/issues/16#issuecomment-1826757138).

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by bkchr** [comment]
@shawntabrizi could you maybe do this?

**Comment by shawntabrizi** [comment]
Hi @alfredonodo are you a part of the nakaflow team? I don't see your name on the contributors list of the linked repo.

I am happy to help, I could even write some javascript code for you to get the data you want, but can you be more specific about what data you need specifically?

For example, if i gave you a list of all the validator accounts, and how much stake is backing them in a staking session, is that what you are looking for?

**Comment by bkchr** [comment]
Looks like this was done.
