### ISSUE TITLE
Fellowship: Expose `add_member_to_rank`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#262]
* Integrate a "fellowship" like setup into the kitchen sink runtime included in Substrate. This would have caught many of the issues with benchmarking which were debugged in: https://github.com/paritytech/substrate/pull/12022, https://github.com/paritytech/substrate/pull/12026, and https://github.com/paritytech/substrate/pull/12026
* Expose `add_member_to_rank` extrinsic which is callable by root to help bootstrap fellowship.

**Comment by bkchr** [comment]
Closed by: https://github.com/paritytech/polkadot-sdk/pull/4877
