### ISSUE TITLE
[CI] update prdoc CI job

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2624]
Couple issues I noticed (see [example job run](https://github.com/paritytech/polkadot-sdk/actions/runs/7093791130/job/19307856477?pr=2486)):

- The link is broken: https://github.com/paritytech/polkadot-sdk/blob/master/docs/prdoc.md (should be under https://github.com/paritytech/polkadot-sdk/tree/master/docs/contributor)
- The prdoc error is not shown. I only see `PR #2486 -> ERR` which unfortunately isn't very helpful.

cc @paritytech/ci

**Comment by chevdor** [comment]
The second point is an issue for prdoc itself.
ref. https://github.com/paritytech/prdoc/issues/23

**Comment by chevdor** [comment]
The first issue was fixed in #2598
