### ISSUE TITLE
Add Force Remove Vesting for Vesting Pallet

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#269]
This is an issue for @nzt48

There is already a function inside the Vesting Pallet: 

```
	/// Remove a vesting schedule for a given account.
	fn remove_vesting_schedule(who: &T::AccountId, schedule_index: u32) -> DispatchResult {
		let schedules = Self::vesting(who).ok_or(Error::<T>::NotVesting)?;
		let remove_action = VestingAction::Remove { index: schedule_index as usize };

		let (schedules, locked_now) = Self::exec_action(schedules.to_vec(), remove_action)?;

		Self::write_vesting(who, schedules)?;
		Self::write_lock(who, locked_now);
		Ok(())
	}
```

This should be exposed through a ROOT call, so that developers and governance can have access to such things.

Steps:

* [ ] Create a new extrinsic `force_remove_vesting_schedule` which checks for the root user, and then calls this already implemented function.
* [ ] Add a test which verifies the function works.
     - Test verifies only root can call
     - Test verifies that vesting schedule is removed (and all the appropriate storage is cleaned up)
     - Test verifies that trying to remove a schedule when it doesnt exist errors
     - (probably all can be done in one unit test)
* [ ] Add a benchmark which benchmarks this new call.
* [ ] Create companion PRs for Polkadot (and Cumulus?)

**Comment by philoniare** [comment]
@shawntabrizi can I take this? Looks like there's no one actively working on it at the moment?

**Comment by gupnik** [comment]
Seems that there haven't been any updates for quite some time. So, I will go ahead and assign it to you @philoniare.

**Comment by philoniare** [comment]
@gupnik Upon closer inspection, the `force_remove_vesting_schedule` extrinsic has already been implemented in this [commit](https://github.com/philoniare/polkadot-sdk/commit/318e5969c72de5339210f5f9edd5d4be85bcde70).

I've verified that the following has already been completed:
- [x]  Create a new extrinsic force_remove_vesting_schedule which checks for the root user, and then calls this already implemented function.
- [x] Add a test which verifies the function works.
  - [x] Test verifies only root can call
  - [x] Test verifies that vesting schedule is removed
  - [x] Test verifies that trying to remove a schedule when it doesn't exist errors
- [x]  Add a benchmark which benchmarks this new call.

Please close the issue if you find it appropriate.

**Comment by gupnik** [comment]
> @gupnik Upon closer inspection, the `force_remove_vesting_schedule` extrinsic has already been implemented in this [commit](https://github.com/philoniare/polkadot-sdk/commit/318e5969c72de5339210f5f9edd5d4be85bcde70).

Great! Thanks @philoniare.

Closing this as fixed with https://github.com/paritytech/polkadot-sdk/pull/1982
