### ISSUE TITLE
How to add logs to runtime for debugging?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot-sdk#2696]
https://substrate.stackexchange.com/questions/10540/how-can-i-add-logs-to-the-runtime-for-debugging-since-execution-native-has-b

I can't seem to get enough attention on Stack Exchange, so I'm posting this question here.

**Comment by xlc** [comment]
use chopsticks and wasm override

**Comment by bkchr** [comment]
@xlc please also answer on SE.
