### ISSUE TITLE
Downgrade of the Westend transaction version

### ISSUE THREAD

**Issue by adelove-ledger** [paritytech/polkadot-sdk#2703]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Hello

The release 1.5.0 is out, but i see that the tx version of westend is 22, while on 1.4.0 it was 24, is this expected?

**Comment by bkchr** [comment]
I mean there is no requirement that the transaction version increases strictly by one, but I will ask why this happened.

We will also not downgrade.

**Comment by bkchr** [comment]
Just checked the releases. The transaction version was actually always increased by one. First time with 1.2.0 and then 1.3.0.

**Comment by adelove-ledger** [comment]
The downgrade is done, in 1.5.0 the transaction version is 22 and in 1.4.0 the transaction version is 24

**Comment by bkchr** [comment]
Ahh! Sorry I misunderstood you.

**Comment by EgorPopelyaev** [comment]
It should be fixed now

**Comment by adelove-ledger** [comment]
The release page https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.5.0 now show `tx24` indeed, but the commit is still the one from 3 days ago, will it be updated or a 1.5.1 will be released?
