### ISSUE TITLE
Bug Thread 'main' panicked at 'raise_fd_limit: error calling setrlimit: Operation not permitted (os error 1)'

### ISSUE THREAD

**Issue by nokogirisrv** [paritytech/polkadot-sdk#2744]
Logs:
`====================

Version: 1.4.0-00395a23d12

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   5: core::panicking::panic_fmt
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   6: polkadot_cli::command::run
   7: polkadot::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: main
  10: <unknown>
  11: __libc_start_main
  12: _start

Thread 'main' panicked at 'raise_fd_limit: error calling setrlimit: Operation not permitted (os error 1)', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fdlimit-0.2.1/src/lib.rs:105

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new`

**Comment by nokogirisrv** [comment]
after update and restart i have this output:
`====================

Version: 1.5.0-a3dc2f15f23

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: sc_network_sync::engine::SyncingEngine<B,Client>::run::{{closure}}
   6: tokio::runtime::task::raw::poll
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  10: <unknown>
  11: __clone


Thread 'tokio-runtime-worker' panicked at 'SelectNextSome polled after terminated', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/select_next_some.rs:32

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new

2023-12-19 01:49:54 subsystem exited with error subsystem="dispute-coordinator" err=FromOrigin { origin: "dispute-coordinator", source: SubsystemReceive(Generated(Context("Signal channel is terminated and empty."))) }`

**Comment by bkchr** [comment]
@nokogirisrv please post more logs before the crash.

**Comment by nokogirisrv** [comment]
@bkchr I also have failures report on my validating history, It is present on my history on 1kv database. Could it be cleaned, because it happens not because my fault, but because some bug? My node name is Nokogirisrv, my validator name is nokogirisrv,, I have 2 faults after this issue.

**Comment by bkchr** [comment]
I'm not running the 1kv program. Sorry! Please reach out in the correct channels.

**Comment by Noc2** [comment]
Could you create an issue here: https://github.com/w3f/1k-validators-be?

**Comment by nokogirisrv** [comment]
@Noc2 created, thanks.
