### ISSUE TITLE
Error when running validator rococo-local relay node

### ISSUE THREAD

**Issue by abhiyana** [paritytech/polkadot-sdk#2749]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Issue Summary
I am encountering an error when attempting to run a Rococo-local relay node using the parity/polkadot Docker image on my M1 Mac system. The command I used is as follows:

```bash
docker run parity/polkadot --chain=rococo-local --validator --unsafe-rpc-external --rpc-cors=all
```

### Environment
- Operating System: macOS 14.1.2 (23B92) on M1 chip
- Storage: 512 GB

### Expected Behavior
I expected the validator node to run successfully on my M1 Mac system.

### Actual Behavior
However, I encountered an error when executing the Docker command. The node runs without issues on a Linux/AMD64 system.

### Additional Information
- The system specifications include an M1 Mac with macOS 14.1.2.
- The issue is specific to the M1 Mac platform.

### Screenshot
<img width="700" alt="Screenshot 2023-12-18 at 11 31 23 AM" src="https://github.com/paritytech/polkadot-sdk/assets/47945971/7d25a60e-fde1-4f54-9514-ddd44149be10">

### Steps to Reproduce
1. Run the following Docker command on an M1 Mac:
   ```bash
   docker run parity/polkadot --chain=rococo-local --validator --unsafe-rpc-external --rpc-cors=all
   ```

**Comment by bkchr** [comment]
Please the full log out and not just a screenshot.
