### ISSUE TITLE
Extrinsic `claim.claimAttest` not working as intended [Polkadot]

### ISSUE THREAD

**Issue by Juanma0x** [paritytech/polkadot-sdk#2757]
### Problem Details
- **First Attempt:** The extrinsic was initially issued and broadcasted from a non-related account, resulting in a `badOrigin` error. [Link to the error](https://polkadot.subscan.io/extrinsic/18496149-3)
- **Subsequent Attempts:** The same extrinsic was then issued by the account claiming the tokens and by a different non-related account. Both times, the extrinsic failed to broadcast, displaying the error message: `1010: Invalid transaction: Custom Error: 1` on Polkadot-JS UI.

### Expected Behavior
The `claim.claimAttest` extrinsic should successfully execute when initiated, without displaying any error messages or showing one descriptive enough to locate and solve the origin of the issue.

**Comment by bkchr** [comment]
They are sending a signed transaction. This needs to be an unsigned transaction. Can they not use the polkadot-js claim tool?

**Comment by Juanma0x** [comment]
Thanks, Basti. Even if the first extrinsic was mistakenly signed, the second and third were definitively not signed and did not work as expected.

Until yesterday, claiming through Polkadot-JS UI wasn't an option. Jaco recently [resolved the issue](https://github.com/polkadot-js/apps/issues/10115). However, I'd like to know how to create the appropriate extrinsic if there comes a time when the Polkadot-JS UI tool is no longer accessible.

**Comment by bkchr** [comment]
> However, I'd like to know how to create the appropriate extrinsic if there comes a time when the Polkadot-JS UI tool is no longer accessible.

If polkadot-js is not working anymore, we would right now have bigger problems than doing some claims ;) That said, there will probably be ways. However, as Jaco already claims are not used that often anymore. How many are even left? 

I will close the issue, as this is not an issue with the pallet, more an usage issue.
