### ISSUE TITLE
Transaction hash repeated multiple times

### ISSUE THREAD

**Issue by YanOctavian** [paritytech/polkadot-sdk#2801]
Extrinsic ID | Date | Block | Extrinsic Hash | Result | Action
-- | -- | -- | -- | -- | --
18706130-7 | 2023/12/22 6:40 | 18706130 | 0xc006bbed36d0d66b52bd1d1564221f0b09b158a8b4659492cc71d60ab52738bf | TRUE | utility(batch_all)
18706113-4 | 2023/12/22 6:38 | 18706113 | 0xc006bbed36d0d66b52bd1d1564221f0b09b158a8b4659492cc71d60ab52738bf | TRUE | utility(batch_all)
18706106-6 | 2023/12/22 6:37 | 18706106 | 0xc006bbed36d0d66b52bd1d1564221f0b09b158a8b4659492cc71d60ab52738bf | TRUE | utility(batch_all)
18706099-6 | 2023/12/22 6:36 | 18706099 | 0xc006bbed36d0d66b52bd1d1564221f0b09b158a8b4659492cc71d60ab52738bf | TRUE | utility(batch_all)
18706080-31 | 2023/12/22 6:34 | 18706080 | 0xc006bbed36d0d66b52bd1d1564221f0b09b158a8b4659492cc71d60ab52738bf | TRUE | utility(batch_all)

</body>

</html>

```

### Steps to reproduce

Get data based on account address in subscan

**Comment by YanOctavian** [comment]
I'm not sure whether the tx hash is unique in Polkadot. If not, there must be other design ideas, but based on past experience, I think the transaction hash should be unique.

**Comment by xlc** [comment]
they are not unique and this is expected

**Comment by YanOctavian** [comment]
> they are not unique and this is expected

Got it, thank you! So how to avoid double spending?

**Comment by YanOctavian** [comment]
@xlc Thank you so much for such a quick reply. However, I want to know under what circumstances the same transaction hash will occur

**Comment by xlc** [comment]
the nonce will reset when an account is killed. an account can be killed by transferring all the funds out.

**Comment by bkchr** [comment]
Yeah as @xlc said this is expected behavior.

**Comment by davidqw** [comment]
> Yeah as @xlc said this is expected behavior.

So, do you mean no nonce is needed to build a transaction?
