### ISSUE TITLE
failed to spawn a prepare worker: TmpPath

### ISSUE THREAD

**Issue by Nexus2k** [paritytech/polkadot-sdk#2827]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I've recently moved servers and noticed a wierd memory leak that caused the server to use all available memory and the following logs I haven't seen before:

```
2023-12-28 06:26:44 failed to spawn a prepare worker: TmpPath
2023-12-28 06:26:47 failed to spawn a prepare worker: TmpPath
2023-12-28 06:26:48 ✨ Imported #21181468 (0xbf7a…1806)
```

Turns out this error indicates that the polkadot process can't write to the db folder due to me forgetting to adjust the permissions after the db snapshot restore. @mrcnski suggested to open an issue here to either check permissions on startup or make the error a bit more clear.

**Comment by acatangiu** [comment]
This is stale
