### ISSUE TITLE
PVF: does the `kill_parent_node_in_emergency` function still work?

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#2831]
I definitely tested it as non-root, but that was well before the unsharing stuff was introduced... I should re-test it and get rid of it if it's useless now.

_Originally posted by @s0me0ne-unkn0wn in https://github.com/paritytech/polkadot-sdk/issues/2643#issuecomment-1872503248_

**Comment by s0me0ne-unkn0wn** [comment]
I've done some tests and can confirm that `kill_parent_node_in_emergency()` works as expected. It is unaffected by namespace unsharing as the worker version check is performed before the unsharing takes place. The worker correctly determines the parent node's PID and sends `SIGTERM` to it; the node then exits gracefully (more or less) thanks to the global signal handler.

So, I believe I can close this issue for now.

**Comment by mrcnski** [comment]
Awesome 🚀
