### ISSUE TITLE
Audit for `pallet-broker`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#2837]
Tracking audit for `pallet-broker` (originally added in https://github.com/paritytech/substrate/pull/14568)  

Please audit the whole `frame/broker` folder, since there were some relevant changes to it in the meantime. Including:  
- https://github.com/paritytech/polkadot-sdk/pull/2811
- https://github.com/paritytech/polkadot-sdk/pull/1609
- https://github.com/paritytech/polkadot-sdk/pull/2656
- maybe more

**Comment by MarBro33** [comment]
> Tracking audit for `pallet-broker` (originally added in https://github.com/paritytech/substrate/pull/14568)  
> 
> Please audit the whole `frame/broker` folder, since there were some relevant changes to it in the meantime. Including:  
> - https://github.com/paritytech/polkadot-sdk/pull/2811
> - https://github.com/paritytech/polkadot-sdk/pull/1609
> - https://github.com/paritytech/polkadot-sdk/pull/2656
> - maybe more

**Comment by ggwpez** [comment]
Done now.
