### ISSUE TITLE
benchmarking-cli: add `--list-pallets` option

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#2844]
We often copy&paste a specific piece of bash code, á la:  
```bash
local pallets=($(
    ./target/production/polkadot benchmark pallet --list  |\
      --chain=/path/to/chain-spec.json |\
      tail -n+2 |\
      cut -d',' -f1 |\
      sort |\
      uniq
))
```
Would be better to have a `--list-pallets` that deduplicates, sorts and lists them.

**Comment by bkchr** [comment]
IMO we should also support running `benchmark all-pallets` or whatever it is called. Not sure why we don't have this :P

**Comment by dastansam** [comment]
hey @ggwpez 

I would like to work on this

**Comment by ggwpez** [comment]
> IMO we should also support running `benchmark all-pallets` or whatever it is called. Not sure why we don't have this :P

Yea... `all-pallets` sounds good as well. Normally these small things have no prio, so they never happen 😆 

>I would like to work on this

Thanks, please go ahead. Once you have some code, you can open a merge request and you can ask questions there.

**Comment by dastansam** [comment]
hey @ggwpez,

sorry, I just got time work on this. I opened a PR #3395
