### ISSUE TITLE
Packaged sp-runtime leaks std via simple-mermaid

### ISSUE THREAD

**Issue by ethernomad** [paritytech/polkadot-sdk#2866]
sp-runtime has a dependency of a fork of simple-mermaid that does not use std. However, this dependency is a git commit. Packages on crates.io are not allowed to have dependencies that are git repositories.

Somehow during publishing sp-runtime v30.0.1 has converted the simple-mermaid dependency from the forked git repository to the original package simple-mermaid. This package leaks std, preventing compilation.

```
    Compiling sp-runtime v30.0.1
  error[E0152]: duplicate lang item in crate `std` (which `simple_mermaid` depends on): `panic_impl`.
    |
    = note: the lang item is first defined in crate `sp_io` (which `sp_runtime` depends on)
    = note: first definition in `sp_io` loaded from /home/jbrown/acuity-substrate/target/debug/wbuild/acuity-runtime/target/wasm32-u
nknown-unknown/release/deps/libsp_io-99d05dfdd96735b1.rmeta
    = note: second definition in `std` loaded from /home/jbrown/acuity-substrate/target/debug/wbuild/acuity-runtime/target/wasm32-un
known-unknown/release/deps/libstd-e7d29152f2771bf2.rmeta
```

A temporary solution is to put the following lines in `Cargo.toml`:

```
[patch.crates-io]
simple-mermaid = { git = "https://github.com/kianenigma/simple-mermaid.git", rev = "e48b187bcfd5cc75111acd9d241f1bd36604344b" }
```

**Comment by ggwpez** [comment]
I just opened this to maybe remove the fork https://github.com/glueball/simple-mermaid/pull/2

@Morganamilo i assume this is done in the publisher so that the docs-rs build works?
