### ISSUE TITLE
Vision: Improve Developer Experience with better Config Traits

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#288]
There are common types defined within the config of different pallets, such as:

```
type Event: From<Event<Self>> + IsType<<Self as frame_system::Config>::Event>;

type Call: IsType<<Self as frame_system::Config>::Call>
	+ Dispatchable<Origin = Self::Origin, PostInfo = PostDispatchInfo>
	+ GetDispatchInfo
	+ FullCodec
	+ From<frame_system::Call<Self>>;

type Origin: From<RawOrigin<Self::AccountId, I>>;

etc...
```

All of these types have some complicated traits which are expected from the `construct_runtime!` macro, and often the user struggles to define all those types when doing runtime development.

We could simply wrap all of these traits in a simple to understand trait exposed in frame_support like:

```
trait FrameCall: IsType<<Self as frame_system::Config>::Call>
	+ Dispatchable<Origin = Self::Origin, PostInfo = PostDispatchInfo>
	+ GetDispatchInfo
	+ FullCodec
	+ From<frame_system::Call<Self>>
{}
```

Then simply define:

```
type Call: frame_support::FrameCall
```

or something like that.

**Comment by kianenigma** [comment]
I would say this is done with `derive_impl`'s delivery.

**Comment by shawntabrizi** [comment]
@kianenigma can you link context / solution?

this is still a common issue I found in the academy. Would love traits for storage items, callable parameters, basic numbers, etc...

**Comment by kianenigma** [comment]
True, I misjudged this based on the title.

**Comment by kianenigma** [comment]
If and when done, the author should update https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/reference_docs/frame_runtime_types/index.html as it goes into a lot of depth about how these `Runtime*` types and their trait bounds work. 

Admittedly. if knowing the above article in depth, you would not feel confused by the trait bounds, but I get that having a simple setup is necessary, especially for something like `type RuntimeEvent` which is used very very frequently.

**Comment by kianenigma** [comment]
A solution should look like this :

```
// in frame/src/lib.rs

mod trait_bounds {
    pub use frame_support::traits::{Parameter, Members};
    // TODO: and fix for instancing
    pub trait TRuntimeEvent<PalletEvent, T> = From<PalletEvent<T>> + IsType<<T as frame_system::Config>::RuntimeEvent>
    pub trait TRuntimeCall<PalletCall, T> = ..;
    // This one is a bit more tricky, as `PalletOrigin` might not exist.
    pub trait TRuntimeOrigin<PalletOrigin, T> = ..;

```

**Comment by bkchr** [comment]
Isn't this going to be solved by this: https://github.com/paritytech/polkadot-sdk/issues/3743?

Then we can get rid off all these extra `RuntimeCall`, `RuntimeEvent` etc in every pallet and just keep it in `frame_system`. We should even be able to let the macro generate this for us. Thus, users will not need to write these extra bounds at all.

**Comment by shawntabrizi** [comment]
@bkchr agree that will def solve a lot of the stuff inside the config.

But I think there is much more overall that can be improved.

From my original issue, I want to change things like:

```rust
trait FrameCall: IsType<<Self as frame_system::Config>::Call>
	+ Dispatchable<Origin = Self::Origin, PostInfo = PostDispatchInfo>
	+ GetDispatchInfo
	+ FullCodec
	+ From<frame_system::Call<Self>>
{}
```

To be a single trait which already has all the requirements we need, like:

```rust
type Call: frame_support::FrameCall
```

Again, coming from someone who does not know so deeply about all these different traits, we can def improve on things.

Another example, in the same idea, is to create more easy to use derive macros.

For example, instead of:

```rust
#[derive(Encode, Decode, MaxEncodedLen, TypeInfo)]
#[scale_info(skip_type_params(T))]
pub struct SomeStructForStorage<T: Config> {}
```

We should be able to do:

```rust
#[derive(SubstrateStorage(T))]
pub struct SomeStructForStorage<T: Config> {}
```

I think this captures what I originally intended with the issue, and as long as we use valid rust syntax and rules (not a ton of macro magic), I think this will be a better experience for everyone.

**Comment by kianenigma** [comment]
@shawntabrizi the storage thing you wished for will be solved by https://github.com/paritytech/polkadot-sdk/pull/4079

**Comment by Kanasjnr** [comment]
@shawntabrizi is this issue still available i would like to work on it

**Comment by bkchr** [comment]
@Kanasjnr maybe you want to look into finishing: https://github.com/paritytech/polkadot-sdk/pull/4079 I assume @ggwpez can guide you.

**Comment by Kanasjnr** [comment]
Okay I will look into it

**Comment by Kanasjnr** [comment]
Hey @ggwpez @bkchr @shawntabrizi ,I've been analyzing issue #4079 and here's my implementation approach:

## the Problem

Currently, storage types require verbose boilerplate:
```rust
#[derive(CloneNoBound, PartialEqNoBound, EqNoBound, RuntimeDebugNoBound, TypeInfo, Encode, Decode, DecodeWithMemTracking, MaxEncodedLen)]
#[scale_info(skip_type_params(Total))]
#[codec(mel_bound(Votes: MaxEncodedLen))]
pub struct Tally<Votes: Clone + PartialEq + Eq + Debug + TypeInfo + Codec, Total> { ... }
```

## my own Implementation

I'm planning to implement `#[frame_support::stored]` as a procedural attribute macro that:

### 1. **Parsing Strategy**
- Support three argument types:
  - `skip(T, U, ...)` - for phantom type parameters
  - `mel(S, R, ...)` - for parameters requiring MaxEncodedLen
  - `mel_bound(...)` - for custom bounds (advanced use case)

- Use `syn::parse::Parse` with custom keywords for robust parsing
- Validate that all specified parameters actually exist in the struct generics

### 2. **Code Generation**
The macro would:
- Automatically inject all necessary derives (CloneNoBound, PartialEqNoBound, etc.)
- Generate `#[scale_info(skip_type_params(...))]` for skipped params
- Generate `#[codec(mel_bound(...))]` for mel params
- Add standard trait bounds to non-skipped parameters: `Clone + PartialEq + Eq + Debug + TypeInfo + Codec`

### 3. **Implementation Location**
- Create `frame/support/procedural/src/stored.rs` for the implementation
- Register in `procedural/src/lib.rs` as `#[proc_macro_attribute]`
- Re-export from `frame-support/src/lib.rs`

## Questions Before I Start

1. **Bounds Strategy**: Should I automatically add bounds to ALL non-skipped parameters, or use static analysis to only add bounds to generics that appear in field types?

2. **Derive Set**: Is the fixed set of derives (CloneNoBound, PartialEqNoBound, EqNoBound, RuntimeDebugNoBound, TypeInfo, Encode, Decode, DecodeWithMemTracking, MaxEncodedLen) correct for all storage types?

3. **Error Messages**: Any specific validation cases I should handle beyond "parameter doesn't exist"?

4. **Testing**: Should I include integration tests beyond unit tests for the parsing logic?

Would appreciate your thoughts on these points before I dive into the implementation!

**Comment by Kanasjnr** [comment]
https://github.com/paritytech/polkadot-sdk/pull/10195

I've been able to implement this @bkchr
