### ISSUE TITLE
Signed Metadata

### ISSUE THREAD

**Issue by Slesarew** [paritytech/polkadot-sdk#291]
Currently the Signer needs trusted authority to verify correctness of metadata used. We could make this trustless if we ~require~ allow (edit 1: Signer should not be allowed to sign transactions with trivial blank metadata hash then) every transaction to include metadata hash into signed payload - this way the chain will be constantly verifying metadata validity instead of a trusted party.

This bears very little additional costs, deprecates lots of complex and confusing logic in Signer and makes automated generation of updates possible. Metadata portal might be reduced to a simple untrusted page with generator script since any attack on it will lead to Signer's DoS which is desired behavior.

**Comment by kianenigma** [comment]
I belive this, and all related issues can be closed now as https://github.com/polkadot-fellows/RFCs/blob/bkchr-merkelized-metadata/text/0078-merkleized-metadata.md is formalized.
