### ISSUE TITLE
Signatures for SignaturePayload can be re-interpreted to be signatures for distinct messages

### ISSUE THREAD

**Issue by kayabaNerve** [paritytech/polkadot-sdk#2947]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

https://github.com/paritytech/polkadot-sdk/blob/1914775bd4a2254dd3f70d8de1d70c1635e83489/substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs#L245-L262

The potential reduction, which I can't identify the reasoning for in the first place, means that a hashed message can be re-interpreted as a message itself (or an unhashed 32-byte message can be reinterpreted as the hash of a longer message, yet this requires finding a preimage).

This shouldn't practically be an issue due to the lack of 32-byte messages in the ecosystem. Extrinsic almost always has several extensions which will place its payload far beyond 32 bytes. It'd require a distinct use of SignaturePayload, which I presume unlikely.

I did follow responsible disclosure on this, as it is arguable as a critical fault in the signature as a formal object, and was told it's a non-issue I'm welcome to publicly disclose.

**Comment by kayabaNerve** [comment]
I'd presume this will be resolved with https://github.com/paritytech/polkadot-sdk/issues/2415 is.

**Comment by bkchr** [comment]
Yes, I added [this](https://github.com/paritytech/polkadot-sdk/issues/2415#issuecomment-1856536026) comment because of your report. Thank you for the report.

I don't see any reason to keep this issue open, as it is already tracked in the linked issue. You can leave there a comment if you like.
