### ISSUE TITLE
Dep error when compiling polkadot-v.1.6.0, aquamarine version used has been yanked 

### ISSUE THREAD

**Issue by kureus** [paritytech/polkadot-sdk#2961]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Aquamarine version was bumped from 0.3.2 to 0.4.0 [last week](https://github.com/paritytech/polkadot-sdk/commit/9d80735a7cccb7c52280ea057177d92e17203c51). This version was [pre release only](https://github.com/mersinvald/aquamarine/releases). And appears to have been subsequently yanked according to [crates.io](https://crates.io/crates/aquamarine/versions)

### Steps to reproduce

Compile polkadot-v.1.6.0 from src using stable rust 1.74.0

Expected output
```
      Updating crates.io index
  error: failed to select a version for the requirement `aquamarine = "^0.4.0"`
  candidate versions found which didn't match: 0.5.0, 0.3.3, 0.3.2, ...
  location searched: crates.io index
  required by package `frame-support v4.0.0-dev (/polkadot/polkadot-sdk/substrate/frame/support)`
      ... which satisfies path dependency `frame-support` (locked to 4.0.0-dev) of package `westend-runtime v1.0.0 (/polkadot/polkadot-sdk/polkadot/runtime/westend)`
      ... which satisfies path dependency `wasm-project` (locked to 1.0.0) of package `westend-runtime-wasm v1.0.0 (/polkadot/build/polkadot/production/wbuild/westend-runtime)`
  perhaps a crate was updated and forgotten to be re-vendored?
  thread 'main' panicked at substrate/utils/wasm-builder/src/wasm_project.rs:920:10:
  `cargo metadata` can not fail!: CargoMetadata { stderr: "    Blocking waiting for file lock on package cache\n    Updating crates.io index\nerror: failed to select a version for the requirement `aquamarine = \"^0.4.0\"`\ncandidate versions found which didn't match: 0.5.0, 0.3.3, 0.3.2, ...\nlocation searched: crates.io index\nrequired by package `frame-support v4.0.0-dev (/polkadot/polkadot-sdk/substrate/frame/support)`\n    ... which satisfies path dependency `frame-support` (locked to 4.0.0-dev) of package `westend-runtime v1.0.0 (/polkadot/polkadot-sdk/polkadot/runtime/westend)`\n    ... which satisfies path dependency `wasm-project` (locked to 1.0.0) of package `westend-runtime-wasm v1.0.0 (/polkadot/build/polkadot/production/wbuild/westend-runtime)`\nperhaps a crate was updated and forgotten to be re-vendored?\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ggwpez** [comment]
Are you running `cargo build` or `cargo doc`?  
It should be a doc only dependency, but i think Cargo does not understand that.

**Comment by kureus** [comment]
Running 
```RUSTFLAGS="-C target-cpu=native " cargo build --profile production --target-dir /polkadot/build/polkadot```

**Comment by ggwpez** [comment]
Does it also happen with `--locked`?

**Comment by kureus** [comment]
Digging deeper, this has been fixed [4 days ago in master](https://github.com/paritytech/polkadot-sdk/commit/38a0ac0012c6f2dfc37b46af1b015ed3a5e296a3). But this commit didn't make it into the latest [1.6 release](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.6.0)

**Comment by ggwpez** [comment]
Cannot reproduce on `commit 481165d92297d7dfd5eaf9c7f442441761fc0a12 (HEAD, tag: v1.6.0-rc3, tag: polkadot-v1.6.0)`.  
`cargo b -q`also with the `production` profile works on `1.75.0 (82e1608df 2023-12-21)`.

**Comment by aperture-sandi** [comment]
We are getting the same error...
git log reports...
`commit 481165d92297d7dfd5eaf9c7f442441761fc0a12 (HEAD, tag: v1.6.0-rc3, tag: polkadot-v1.6.0)`
just did the following to make sure we are using rust 1.75.0
```
rustup install nightly-2023-12-21
rustup target add wasm32-unknown-unknown --toolchain nightly-2023-12-21

rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```
ran build again...
`RUSTFLAGS="-C target-cpu=native" /home/<user>/.cargo/bin/cargo install --force --path . --profile production`

got same error
```
    Updating git repository `https://github.com/paritytech/polkadot-sdk`
error: failed to compile `polkadot v1.6.0 (/home/<user>/polkadot-sdk/polkadot)`, intermediate artifacts can be found at `/home/<user>/polkadot-sdk/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to select a version for the requirement `aquamarine = "^0.4.0"`
  candidate versions found which didn't match: 0.5.0, 0.3.3, 0.3.2, ...
  location searched: crates.io index
  required by package `frame-support v4.0.0-dev (/home/<user>/polkadot-sdk/substrate/frame/support)`
      ... which satisfies path dependency `frame-support` of package `frame-benchmarking-cli v4.0.0-dev (/home/<user>/polkadot-sdk/substrate/utils/frame/benchmarking-cli)`
      ... which satisfies path dependency `frame-benchmarking-cli` of package `polkadot-cli v1.1.0 (/home/<user>/polkadot-sdk/polkadot/cli)`
      ... which satisfies path dependency `polkadot-cli` of package `polkadot v1.6.0 (/home/<user>/polkadot-sdk/polkadot)`
  perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by ggwpez** [comment]
Weird. cc @coderobe @Morganamilo

**Comment by kureus** [comment]
Okay, I have enough information to know what's happening now. In short, the 0.4.0 aquamarine package is still available despite the yank but only with a `Cargo.lock` file, which must be either being ignored or not found for these errors to occur.

To explain (adding context for those not deeply familiar with rust/cargo)
- `Cargo.lock` is machine written and designed for reproducible builds, [specifying exact dependency versions with checksums](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)
- `Cargo.toml`'s are human written and specify package name and version numbers/ranges only
- `cargo-yank` [does not actually delete any data](https://doc.rust-lang.org/cargo/commands/cargo-yank.html), and the crate remains downloadable but only to pre existing lockfiles.

In the absence of a `Cargo.lock` file with a checksum for aquamarine 0.4 being used, the toml files are used and the compilation fails as that version is no longer available due to the yank. Thus @ggwpez you would need to not use a lock file to reproduce this error. 

In my case by using the `--target-dir` flag the build could not find the `Cargo.lock` file at the required stage of the build. My specific issue can be fixed by either removing that flag or, more usefully, setting the env var `WASM_BUILD_WORKSPACE_HINT` to the path of the workspace containing the lock file. 

@aperture-sandi `cargo install` [explicitly ignores the lock file](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile). Your issue should be fixed by adding the `--locked` flag.

So while the [commit in master](https://github.com/paritytech/polkadot-sdk/commit/9d80735a7cccb7c52280ea057177d92e17203c51) to move to aquamaine 0.5.0 is required for builds that don't use a lock file, the released 1.6 version will require the lock file to be used when compiling from source.

Hope that helps anyone running into this issue.

**Comment by ggwpez** [comment]
>In my case by using the --target-dir flag the build could not find the Cargo.lock file at the required stage of the build. My specific issue can be fixed by either removing that flag or, more usefully, setting the env var WASM_BUILD_WORKSPACE_HINT to the path of the workspace containing the lock file.

Oh, did not know that. Running with `--locked` while it does not find a lock file should hopefully error though.  
So i guess its resolved?  
I dont know if the WASM builder can be modified, it probably relies on the user setting that ENV var.

**Comment by kureus** [comment]
Yep resolved. Thanks for your help.

**Comment by aperture-sandi** [comment]
> @aperture-sandi `cargo install` [explicitly ignores the lock file](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile). Your issue should be fixed by adding the `--locked` flag.

Thanks for the help!  Can confirm "--locked" worked for us
