### ISSUE TITLE
Impossible to create chain spec with large balance

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#2963]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After https://github.com/paritytech/polkadot-sdk/pull/1256 `ChainSpec::from_genesis` is deprectated, but both serializing manually constructed `RuntimeGenesisConfig` explicitly and using `json!` macro fails for large balances like `u128:MAX / 2`:
```
Error("number out of range", line: 0, column: 0)
```

Same balance still works great with `ChainSpec::from_genesis`, but the way it actually does that is extremely convoluted, I was not yet able to figure out why it succeeds.

### Steps to reproduce

Try to set `u128::MAX / 2` balance for one of the accounts at genesis

**Comment by bkchr** [comment]
@nazar-pc does this fixes your issue?

**Comment by bkchr** [comment]
Yeah fine, @michalkucharczyk you want to open a pr to enable it somewhere in our stack? Maybe somewhere near the `GenesisConfig` stuff?
