### ISSUE TITLE
`reap_identity` should take batch of accounts

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#2964]
While doing the identity migration on Rococo it became apparent that a `batch` is nice to use to speed it up, but the batch must be paid for.  
So in order to have free and fast migrations, it would need to accept a `Vec` of account IDs. cc @NachoPal

**Comment by dharjeezy** [comment]
Hi @ggwpez are you talking of modifying the reap_identity function to take in vec of account ids or we introduce a new function that solely takes a vec?

**Comment by ggwpez** [comment]
I think modifying `reap_identity` is fine. Its used as one-off anyway.

**Comment by dharjeezy** [comment]
Circling back on this @ggwpez there is a `reap_identity` pallet impl function, are we modifying that too to take a vec of account_ids? or is it just the extrinsic we are modifying to take a vec?

Are we also modifying `on_reap_identity` handler to take a vec of account_ids too?

**Comment by ggwpez** [comment]
>Circling back on this ggwpez there is a reap_identity pallet impl function, are we modifying that too to take a vec of account_ids? or is it just the extrinsic we are modifying to take a vec?

Dunno, just try it out and see what works best.

>Are we also modifying on_reap_identity handler to take a vec of account_ids too?

Probably okay to stay in singular.

**Comment by ggwpez** [comment]
turns out we dont want this :(
