### ISSUE TITLE
Parachain is not producing any blocks in the LiveChain

### ISSUE THREAD

**Issue by arunjot12** [paritytech/polkadot-sdk#3030]
I'm currently working with the Polkadot relay chain version 1.1.0, and I've encountered an issue in the parachain where block production is not occurring. My configuration involves two validators in the relay chain and one collator in the parachain in the staging environment. Interestingly, when I switch the environment to local or change the chain type to local, the parachain begins producing blocks.

**Comment by bkchr** [comment]
If you want help, please provide more information on what is going wrong etc.

**Comment by arunjot12** [comment]
Hello @bkchr , I've crafted a customSpec for the Polkadot staging environment, incorporating two validators in the relay chain and one collator in the parachain. Upon attempting to connect the parachain to the relay chain in the staging environment with the chain_type set to Live, I encountered an issue where the parachain failed to produce blocks, displaying the error message 'Collation wasn't advertised to any validator.' However, when I created a new customSpec using polkadot-local with the chaintype set to Local, block production in the parachain commenced successfully. Additionally, in the staging environment, enabling the --discover-local flag in the command also resulted in the initiation of block production in the parachain.

**Comment by bkchr** [comment]
Yeah, this means that means that the relay chain nodes weren't connected to the parachain. When you use `Local`, it will enable MDNS.

**Comment by arunjot12** [comment]
But i need to connect the external parachain to it .

**Comment by bkchr** [comment]
The parachain collators are required to be able to open connections to the relay chain validators. You could open some ports in your firewall for example to expose the validators
