### ISSUE TITLE
Keep crate versions in sync with crates-io

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3032]
Local crate versions need to be kept in sync with crates-io permanencly so we can correctly bump them according to SemVer once #2490 commenced.  

cc @Morganamilo

**Comment by liamaharon** [comment]
PR for the initial sync https://github.com/paritytech/polkadot-sdk/pull/3034

Will add a new subcommand for bumping to the tool soon (and docs)

**Comment by ggwpez** [comment]
Given that we bump them via PrDoc now, we dont need this anymore. Otherwise we would have constant backports to bump the Cargo.toml version numbers.  
They should just all be set to `0.1.0` for new crates and never changed.
