### ISSUE TITLE
[FRAME/Substrate CLI] Freestanding pallet bench runner

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3045]
It should be possible to factor `benchmark pallet` out into a freestanding binary that works with any runtime.  
Then we dont have to rebuild the polkadot node with `runtime-benchmarks` features just to run them. Will also be faster for `bot bench` and in CI.

**Comment by xlc** [comment]
that will also significantly simplify downstream projects as we can just use the standard bencher instead of integrating bunch of code and configs into our repo

**Comment by bkontur** [comment]
@ggwpez What is your plan with this? I could maybe take a look next week, because I am don't like checking benchmarks for fellows manually not to break anything, I want to add it to the CI :)

**Comment by ggwpez** [comment]
I am currently working on this https://github.com/paritytech/polkadot-sdk/issues/2664, which is not *really* a pre requirement, but touches the same code.  
It would also make clear what steps need to be taken for this. So i think we can more concretely do this issue once the other one is done.

**Comment by ggwpez** [comment]
Actually this only works as long as the runtime is not using custom host functions, so we still need to keep the old way of doing it alive.  
But for at least out benchmarks it should work.
