### ISSUE TITLE
Collator with remote RPC stopped working after enacting `v1.6.0` Kusama release

### ISSUE THREAD

**Issue by pmensik** [paritytech/polkadot-sdk#3059]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We are operating a handful of collators in the Kusama ecosystem - all of them experienced a halt in block production after the upgrade but eventually recovered and started producing blocks again. However, one of them (Moonriver) never actually did and I keep seeing these messages in the collator log (nothing suspicious other than this).  
```
[Relaychain] Received finalized block via RPC: #21570139 (0x5e26…ba48 -> 0xf487…caf8)
[Relaychain] Received imported block via RPC: #21570142 (0x8450…a5b0 -> 0xcd69…63e0)
[Relaychain] Failed to handle incoming network message err=ImplicitViewFetchError(ProspectiveParachainsUnavailable)
```  
So, in the end, the collator is working fine but cannot pass blocks to the relay.
This is our systemd config file
```
ExecStart=/usr/local/bin/moonriver \
  --name Polkadotters \
  --base-path '/var/lib/moonriver' \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --collator \
  --state-pruning 256 \
  --blocks-pruning 256 \
  --port 31333 \
  --prometheus-port 9625 \
  --prometheus-external \
  --rpc-port 9923 \
  --trie-cache-size 0 \
  --db-cache 32000 \
  --chain moonriver \
#  --relay-chain-rpc-url ws://38.242.253.84:9944 \
#  --relay-chain-rpc-url ws://178.170.48.153:9944 \
  --relay-chain-rpc-url wss://rpc.dotters.network/kusama \
```
We have tried multiple RPCs (including public ones like IBP) but the message remains the same. Strange is that we have multiple collators depending on these remote RPCs but this is the only one that failed to recover after the upgrade.

### Steps to reproduce

As far as I know, we are the only ones experiencing the problem so it might be hard to reproduce.

**Comment by bkchr** [comment]
What polkadot version are you using currently? I think you are just running a too old version.

**Comment by pmensik** [comment]
@bkchr All our RPCs are up to date, I believe the public ones like IBP as well. Like I said, the strange thing is that it works with all other collators so it might be something Moonriver-specific.

**Comment by bkchr** [comment]
I'm talking about the Moonriver nodes. They are using an outdated polkadot version, leading to this issue. 

[This](https://github.com/paritytech/polkadot-sdk/pull/2223) is the pr that fixed the underlying issue here. The moonriver node needs to include this fix. It was included in Polkadot 1.4.0. 

CC @crystalin

**Comment by pmensik** [comment]
@bkchr Thanks a lot, now it's clear!

**Comment by bkchr** [comment]
Given that this is an issue in a downstream project, I'm going to close this issue.
