### ISSUE TITLE
Clean up pallet-vesting tests

### ISSUE THREAD

**Issue by emostov** [paritytech/polkadot-sdk#310]
idea: you could probably clean up tests a bit by directly setting whatever vested transfer you need on any user, rather than repeating the process of transferring from some (arbitrary) account into your desired accounts. 

Might need to be its own PR.

for example I can foresee

```
ExtBuilder::default()
	.add_vest(2, 20 * ED, ED, 10)
	.add_vest(2, 10 * ED, ED, 15)
	.build()
```

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/9202#discussion_r667876906_

Some hints:
- this would likely take the form of a method (`add_vest`) defined on [`ExtBuilder`](https://github.com/paritytech/substrate/blob/master/frame/vesting/src/mock.rs)
- The vesting schedules can likely be adding to vesting genesis config within [`build`](https://github.com/paritytech/substrate/blob/9eddaec3b8f15eec0c458e7bb3a1c16db91d8199/frame/vesting/src/mock.rs#L139)
- The new (`add_vest`) method would replace lines like https://github.com/paritytech/substrate/blob/9eddaec3b8f15eec0c458e7bb3a1c16db91d8199/frame/vesting/src/tests.rs#L122

Find me at @zeke:matrix.parity.io for further questions

**Comment by ggwpez** [comment]
Seems like busywork to me. Closing as wont fix.
