### ISSUE TITLE
Use common overseer construction codepath for polkadot node + collator

### ISSUE THREAD

**Issue by skunert** [paritytech/polkadot-sdk#3116]
Ideally we would use the same codepath for construction of the overseer for collator and polkadot node. 
This requires some investigation and fiddling around with the traits.

For a rough idea check this [comment](https://github.com/paritytech/polkadot-sdk/pull/3061#pullrequestreview-1847530265).

Derived from #3061

**Comment by maksimryndin** [comment]
@skunert @s0me0ne-unkn0wn hi! could I take this issue to investigate and try to solve? (disclaimer: I am an external contributor)

**Comment by skunert** [comment]
From my side yes, would be greatly appreciated! 👍
