### ISSUE TITLE
Runtime: Accept full chain for para on multiple cores (elastic scaling)

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3131]
We accept N candidates for N scheduled cores, if those candidates form a chain back to the last included one.

**Comment by sandreim** [comment]
It is not clear if this one refers to scheduler to assign multiple cores per para in same RCB

**Comment by alindima** [comment]
or to accepting multiple parablocks in parachains_inherent?

**Comment by eskimor** [comment]
This is about accepting multiple backed candidates in  paras_inherent, if there are multiple cores for that para.

**Comment by eskimor** [comment]
Scheduler should already be fine.

**Comment by alindima** [comment]
currently, the check for whether the backed candidate is a descendant of the current para head is done in: `<inclusion::Pallet<T>>::process_candidates`.

for this to work with multiple candidates, I think we'll need to change the format of the inherent data to contain the parent_head_hash, so that we're able to check the dependency chain and also check the PersistedValidationData hash against the one in the candidate receipt

**Comment by eskimor** [comment]
> for this to work with multiple candidates, I think we'll need to change the format of the inherent data to contain the parent_head_hash, so that we're able to check the dependency chain and also check the PersistedValidationData hash against the one in the candidate receipt

I don't think this is necessary. It seems right now we check depedency chains via `PersistedValidationData` hash [here](https://github.com/paritytech/polkadot-sdk/blob/e1c033ebe15e6de5ee6a5a81eab2dd213f09d574/polkadot/runtime/parachains/src/inclusion/mod.rs#L1223). We should be able to make persisted validation data for each provided candidate similar to [here](https://github.com/paritytech/polkadot-sdk/blob/342d7205734b776f0b5d2b141dd730c51dfb2374/polkadot/runtime/parachains/src/util.rs#L30) and then put the candidates in a table based on their persisted validation data hashes. Then we just need to lookup the hash provided in the [descriptor](https://github.com/paritytech/polkadot-sdk/blob/a9b13f7679c122be233d282444b25e32af0a5a91/polkadot/primitives/src/v6/mod.rs#L486) to find the parent.

**Comment by eskimor** [comment]
> I actually also need to change the ParachainsInherentData format due to a change of BackedCandidate primitive. Currently I am struggling to figure out how to implement this change only for Rococo runtime.

There is a hacky half-baked solution for this. If we establish the contract that provided `BackedCandidate`s are provided in order of cores, then with all _para_ cores occupied we are already golden - we know the first candidate for a para will be the lowest core for that para and so on.

Things get more tricky if there are holes and e.g. the candidate for core 1 of that para is missing, then we are off by one. We could get around this by inserting dummy `BackedCandidate`s for those missing entries. Adding these dummy candidates, apart from being hacky, is also not backwards compatible though.

**Comment by burdges** [comment]
We'll require the candidate recipets appear backed on the relay chain in order?

**Comment by sandreim** [comment]
> We'll require the candidate recipets appear backed on the relay chain in order?

That would be an optimization I guess, otherwise we should be able to establish ordering based on the parent heads.

**Comment by sandreim** [comment]
> Another possible hack 😬 : We could change the format of [`validator_indices`](https://github.com/paritytech/polkadot-sdk/blob/a9b13f7679c122be233d282444b25e32af0a5a91/polkadot/primitives/src/v6/mod.rs#L717) so the last bits in the field identify the core (if there are multiple). E.g. let say we want to support up to 4 cores per para for now, we could use 2 bits here.

I think this is by far the least intrusive method but there will still be breakage as current nodes rely on the bitfield len to identify the backing group size in client/runtime code. This will also make it subtle opt in interface. We'd probably have to introduce a temporary node side feature or runtime API to enable this only on `Rococo`.
