### ISSUE TITLE
Failed to run custom build command

### ISSUE THREAD

**Issue by mahavir-dash** [paritytech/polkadot-sdk#3147]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I was trying to add my own pallet to polkadot-runtime and i got this error.
I have added other pallets as well but gettinng error for only one pallet so this pallet has vec of struct in it's genesis config.

error: failed to run custom build command for `polkadot-runtime v1.0.0 (/Users/mahavirganapatidash/Documents/Blockchain/metamui-core/runtime/polkadot)`

Caused by:
  process didn't exit successfully: `/Users/mahavirganapatidash/Documents/Blockchain/metamui-core/target/debug/build/polkadot-runtime-5f05971808f4f430/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: env -u CARGO_ENCODED_RUSTFLAGS -u CARGO_TARGET_DIR RUSTFLAGS="-C target-cpu=mvp -C target-feature=-sign-ext -C link-arg=--export-table -C link-arg=--import-memory -Clink-arg=--export=__heap_base  " SKIP_WASM_BUILD="" "/Users/mahavirganapatidash/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/mahavirganapatidash/Documents/Blockchain/metamui-core/target/debug/wbuild/polkadot-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.77.0-nightly (e51e98dde 2023-12-31)

![Screenshot 2024-01-31 at 11 27 42 AM](https://github.com/paritytech/polkadot-sdk/assets/133201365/3fcae410-1877-4245-b73d-2c437a19061a)

### Steps to reproduce
I am using mac M2, 
I cloned polkadot-sdk and added my pallet there in runtime.
I am using cargo b -p polkadot-runtime to build the runtime only

So along with this i am getting error 
 the trait `Serialize` is not implemented for `types::Identity` for the same pallet.
 Identity is the same struct used in the genesisconfig

@koute @bkchr  please have a look at it

**Comment by liamaharon** [comment]
Hey @mahavir-dash, can you try rustc stable v1.74.0? and please provide actual steps to reproduce, including the command you're running, a repo or git diff, etc.

**Comment by mahavir-dash** [comment]
@liamaharon  I am using the polkadot-sdk repo only.

**Comment by liamaharon** [comment]
`polkadot-sdk` `master` has no package `polkadot-runtime`..

Can you provide a Git branch containing exactly the code you're trying to build?

**Comment by mahavir-dash** [comment]
@liamaharon  Yeah right, It is tag = polkadot-v1.2.0

**Comment by liamaharon** [comment]
`polkadot-v1.2.0` builds fine for me with `rustc v1.74.0`.

**Comment by mahavir-dash** [comment]
Yeah but after adding my own pallet it fails.

**Comment by liamaharon** [comment]
Please provide a Git branch or diff with exactly your code. We don't have magical access to see what changes you made :P

**Comment by liamaharon** [comment]
@mahavir-dash if you're still having issues getting your code to compile feel free to open a ticket on the Substrate StackExchange, making sure that you include all of the details required for someone to reproduce your issue including all relevant code.

**Comment by mahavir-dash** [comment]
Yeah I am creating one demo project, reproducing the same issue so that I can share that
