### ISSUE TITLE
async_backing: Investigate async backing small block time degration

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#3182]
Running on versi for 24h with https://github.com/paritytech/polkadot-sdk/pull/3170  the block times averages on 10minutes, seem to be be bit higher than the 6s expected it is not much it seems to fluctuate between 6s and 6.80s.

The reasons could be diverse, maybe the hardware is not powerful or we have some bugs somewhere.

<img width="1943" alt="Screenshot 2024-02-02 at 11 07 00" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/8559c3b6-d188-4cc7-a46d-b475ca5017bb">

**Comment by sandreim** [comment]
AFAIR I've seen similar issue during firsts succesful tests of async backing on Versi. Are you seeing any `Unexpected Statement` errors ?

**Comment by sandreim** [comment]
Looks like they are still there: https://grafana.teleport.parity.io/goto/jUBN8ytSg?orgId=1

**Comment by alexggh** [comment]
## Root-cause

The problem was caused by the fact that a single authority validator was offline, and that affected the relay chain block production times, after that was removed from the set the block production was fixed  and the average for 10 minutes was around 6.10.

<img width="1288" alt="Screenshot 2024-02-05 at 12 57 13" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/82002d55-95ad-40ac-b22b-5b87a99288e4">


The 0.10 difference is caused by the fact that at session boundaries the availability cores are cleared, so we will have a block that does not include any candidates each session(on versi the session takes 10 minutes).

Closing this as not a problem.


>AFAIR I've seen similar issue during firsts succesful tests of async backing on Versi. Are you seeing any Unexpected Statement errors 

Regarding the noticed "Unexpected statements" we've got https://github.com/paritytech/polkadot-sdk/issues/2346 for tracking, so far I think my initial analysis is right and the warning is harmless.
