### ISSUE TITLE
Deploy origin for pallet-contracts

### ISSUE THREAD

**Issue by Szegoo** [paritytech/polkadot-sdk#3196]
In some cases, it could be useful to have permissioned contract deployment on a chain.

Probably the easiest way to enable this would be to add a new type to the config, e.g.: 
```rust
type DeployOrigin: EnsureOrigin<Self::RuntimeOrigin>;
```

**Comment by bkchr** [comment]
@Szegoo I assume you would work on this? 

CC @athei

**Comment by Szegoo** [comment]
> @Szegoo I assume you would work on this?

Yes, will open a PR soon

**Comment by athei** [comment]
Yes this makes sense to me.

**Comment by bkchr** [comment]
> The contracts api assumes that the origin is an account, which might not be the case if we want to do something as I suggested in the issue description.

Can you explain what you mean?

I don't really see why we need to use `Contains` here and not `EnsureOrigin`.

**Comment by athei** [comment]
Yes, a contract assumes that any other contract has an `AccountId`. But you can can construct a `Origin::Signed` from that `AccountId` and test it against your initially suggested
```Rust
type DeployOrigin: EnsureOrigin<Self::RuntimeOrigin>;
```

**Comment by xlc** [comment]
You could add a signed extension to do whatever origin validation required. No need to modify the pallet.

**Comment by athei** [comment]
That would only work if you care about contracts deployed by a signed account but not by other contracts.

**Comment by Szegoo** [comment]
> I don't really see why we need to use Contains here and not EnsureOrigin.

For each contract we store `CodeInfo`, which contains an owner property of type `AccountId`. If we used `EnsureOrigin` the origin might not be associated with an `AccountId`. E.g. if we were to set the `DeployOrigin` to root what account would be the owner of the deployed code?

**Comment by athei** [comment]
> E.g. if we were to set the DeployOrigin to root what account would be the owner of the deployed code?

Contracts do not have owners. At least not as a concept of `pallet-contracts`. What you are referring to is probably which `Origin` does a contract constitute. As mentioned above it would be `Origin::Signed(contract_account_id)`. You could match that to your `EnsureOrigin` filter. That test would rightfully fail of you set the `DeployOrigin` to only `Root`. But the filter could also allow certain contracts to deploy with no problem. I really don't see the problem here.

You need to start getting more specific if you need further help.

**Comment by Szegoo** [comment]
> As mentioned above it would be Origin::Signed(contract_account_id)

I get that. What I was referring to is [this](https://github.com/paritytech/polkadot-sdk/blob/044d914c30e6dd16eb1231c6d9631bd53ebd3635/substrate/frame/contracts/src/lib.rs#L1077). 

I am definitely not deep into the contracts pallet, but AFAIU the deployed code has an owner: [link](https://github.com/paritytech/polkadot-sdk/blob/044d914c30e6dd16eb1231c6d9631bd53ebd3635/substrate/frame/contracts/src/wasm/mod.rs#L86). What I was asking was who would be the owner of the uploaded code if the origin is not signed?

**Comment by bkchr** [comment]
> E.g. if we were to set the `DeployOrigin` to root what account would be the owner of the deployed code?

Then you can use `EnsureRootWithSuccess` and pass some accountid that represents the root account. We already have done this somewhere, but I can right now not find it.

**Comment by athei** [comment]
> I am definitely not deep into the contracts pallet, but AFAIU the deployed code has an owner: [link](https://github.com/paritytech/polkadot-sdk/blob/044d914c30e6dd16eb1231c6d9631bd53ebd3635/substrate/frame/contracts/src/wasm/mod.rs#L86). What I was asking was who would be the owner of the uploaded code if the origin is not signed(e.g. root)?

Okay yes I get it now. I thought you were talking about instantiating a contract. But you mean uploading new code. Which of the two you want to make permissioned? Only the uploading of new code?

**Comment by Szegoo** [comment]
> Then you can use `EnsureRootWithSuccess` and pass some accountid that represents the root account. We already have done this somewhere, but I can right now not find it.

Yeah, this seems exactly like what would be needed. Since the contracts pallet assumes in multiple places that the origin has an account id associated with itself, by making this slight adjustment to my initial suggestion we can make it work: 
```rust
type DeployOrigin: EnsureOrigin<Self::RuntimeOrigin, Success = Self::AccountId>;
```

> Which of the two you want to make permissioned? Only the uploading of new code?

I think restricting both would make the most sense.

**Comment by athei** [comment]
> 
> ```rust
> type DeployOrigin: EnsureOrigin<Self::RuntimeOrigin, Success = Self::AccountId>;
> ```

Yes, but there is a shorthand for this as Basti mentioned: `EnsureRootWithSuccess`.



> > Then you can use `EnsureRootWithSuccess` and pass some accountid that represents the root account. We already have done this somewhere, but I can right now not find it.
> 
> Yeah, this seems exactly like what would be needed. Since the contracts pallet assumes in code deployment and instantiation that an account id associated with the origin, by making this slight adjustment to my initial suggestion we can make it work:
> 
> ```rust
> type DeployOrigin: EnsureOrigin<Self::RuntimeOrigin, Success = Self::AccountId>;
> ``` 

>  > Which of the two you want to make permissioned? Only the uploading of new code?
> 
> I think restricting both would make the most sense.

I think two config knobs would make sense then. You might want to allow everyone to instantiate existing code but make the upload restricted.

**Comment by pgherveou** [comment]
Seeing this a bit late,
but why can't we just leverage `frame_system::BaseCallFilter` here?

Zeigeist is doing something like this 

https://github.com/zeitgeistpm/zeitgeist/blob/22992bc631ec321eec906be6dfe07b6bc3d2dfc5/runtime/zeitgeist/src/lib.rs?plain=1#L148-L157
