### ISSUE TITLE
Creating Locks should return a Result if MaxLocks is reached

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#320]
Balances pallet does not currently enforce the `MaxLocks` limit for user accounts.

This API needs to be updated to return a result, and everywhere it is used, we need to make sure to be able to handle the error situation.

related: https://github.com/paritytech/substrate/pull/8793

**Comment by ggwpez** [comment]
Freezes are using a `BoundedVec` now: https://github.com/paritytech/polkadot-sdk/blob/e41a0e728bc300a3f384414559bb906adedc5125/substrate/frame/balances/src/lib.rs#L495
