### ISSUE TITLE
Broker: Use relay chain blocks for `leadin_length` and `interlude_length`

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#3201]
We should probably use the relay chain block numbers for tracking `leadin_length` and `interlude_length`. Relay chain block numbers are almost deterministic and more future proof.

**Comment by seadanda** [comment]
Should we also extend this to include `sale_start` too? The block numbers for the different parts of the sale are defined by the combination of the three - e.g. start of fixed period is local block `sale_start + leadin_length + interlude_length`. The `sale_start` reintroduces (/increases the amount of) non-determinism for the real-world time when each part of the sale happens.

I think it makes sense to have the whole sale measured and timed in the same units - WDYT?

**Comment by bkchr** [comment]
Yes! I mean everything that depends on these numbers should be moved as well. I didn't looked into it that closely, so I didn't mention `sale_start` here.

**Comment by gitofdeepanshu** [comment]
I can take this one.

**Comment by bkchr** [comment]
Ty @gitofdeepanshu

**Comment by Krayt78** [comment]
@bkchr i think this needs to be closed since #5656 got merged
