### ISSUE TITLE
[RPC-Spec-V2] Allow chainHead operations to be made from a single connection

### ISSUE THREAD

**Issue by lexnv** [paritytech/polkadot-sdk#3207]
The [chainHead-cli](https://github.com/lexnv/chainhead-cli/blob/master/README.md) tool proves that we can have:
- one connection to the `chainHead_folow` 
- a separate connection (on a separate process, on a different socket) that calls `chainHead_storage` with the subscription ID of the first connection; and produces the result in the first connection

To restrict this case, ensure that the subscription ID provided by the `chainHead_follow` is valid within the context of that connection only.

### Repro case
This issue can be reproduced if the user makes 2 separate connections to the same RPC server.

For the common scenario, the user would establish 2 connections via `rpc-polkadot.io`, which would most likely generate 2 connections on different servers.
However, if the user knows the IP address of the server (or targets a local-development node for testing) this could be reproduced.

cc @paritytech/subxt-team

**Comment by jsdw** [comment]
> To restrict this case, ensure that the subscription ID provided by the chainHead_follow is valid within the context of that connection only.

Sounds good to me; I'd previously assumed that subscription IDs were scoped to the connection already, and it's def safer to ensure that they are :)

> For the production environment use-case, this requires the user to make 2 separate connections to the same RPC server, which is unlikely due to our reverse-proxies. However, this is a valid use-case for testing environments.

I don't understand this sentence really?

**Comment by lexnv** [comment]
For this case to happen, the user needs 2 separate connections to the same server.

From the user perspective, this is unlikely to happen for our production nodes. For example, connecting 2 times to `rpc-polkadot.io` would most probably generate 2 connections on different nodes. 

However, if the user targets a localhost node / development node, or a node with a known IP address this behavior could be reproduced. Indeed the misleading of my issue is `testing environments` which is not entirely true; since the target node could still be in production :D will change the description a bit, thanks for pointing this out! 🙏
