### ISSUE TITLE
[FRAME Core] remove unnecessary overrides while using `derive_impl` for `frame_system`

### ISSUE THREAD

**Issue by gupnik** [paritytech/polkadot-sdk#3237]
https://github.com/paritytech/polkadot-sdk/pull/2409 moved all test runtimes to use `derive_impl` for `frame_system` by simply adding an attribute to all impls like so:

```diff
+#[derive_impl(frame_system::config_preludes::TestDefaultConfig as frame_system::DefaultConfig)]
impl frame_system::Config for Runtime {
..
}
```

This enabled the introduction of new features like `RuntimeTask` without the need to update the configs everywhere. 

However, the existing impls still continue to override the defaults for a number of types that are essentially the same as the ones provided by default config. 

https://github.com/paritytech/polkadot-sdk/pull/1790 provides a sample of how the overridden defaults could simply be removed. This issue tracks the same for all pallets:

Here's a tracking list: 
  - [x] alliance https://github.com/paritytech/polkadot-sdk/pull/1636
  - [ ] asset-conversion
  - [ ] asset-rate
  - [ ] assets
  - [ ] atomic-swap
  - [ ] aura
  - [ ] authority-discovery
  - [x] authorship https://github.com/paritytech/polkadot-sdk/pull/1790
  - [x] babe https://github.com/paritytech/polkadot-sdk/pull/1790
  - [x] bags-list https://github.com/paritytech/polkadot-sdk/pull/1636
  - [ ] balances
  - [ ] beefy
  - [ ] beefy-mmr
  - [ ] bounties
  - [ ] child-bounties
  - [ ] collective
  - [ ] contracts
  - [ ] conviction-voting
  - [ ] core-fellowship
  - [ ] democracy
  - [ ] election-provider-multi-phase
  - [ ] elections-phragmen
  - [ ] executive
  - [x] fast-unstake https://github.com/paritytech/polkadot-sdk/pull/1636
  - [ ] glutton
  - [ ] grandpa
  - [ ] identity
  - [ ] im-online
  - [ ] indices https://github.com/paritytech/polkadot-sdk/pull/1789
  - [ ] insecure-randomness-collective-flip
  - [ ] lottery
  - [ ] membership
  - [ ] merkle-mountain-range
  - [ ] message-queue
  - [x] multisig https://github.com/paritytech/substrate/pull/14453
  - [ ] nft-fractionalization
  - [ ] nfts
  - [ ] nicks https://github.com/paritytech/polkadot-sdk/pull/1801
  - [ ] nis
  - [ ] node-authorization
  - [ ] nomination-pools
  - [ ] offences
  - [ ] preimage
  - [x] proxy https://github.com/paritytech/substrate/pull/14453
  - [ ] ranked-collective
  - [ ] recovery
  - [ ] referenda
  - [ ] remark
  - [ ] root-offences
  - [ ] root-testing
  - [ ] salary
  - [ ] scheduler
  - [ ] scored-pool
  - [ ] session
  - [ ] society
  - [ ] staking
  - [ ] staking-bags-benchmarks
  - [ ] state-trie-migration
  - [ ] statement
  - [ ] sudo
  - [ ] system
  - [ ] timestamp
  - [ ] tips
  - [ ] transaction-payment
  - [ ] transaction-storage
  - [ ] treasury
  - [ ] try-runtime
  - [ ] uniques
  - [ ] utility
  - [ ] vesting
  - [ ] whitelist

**Comment by Gilt0** [comment]
Hi Gupnik,
I would be curious to help on this issue, however, I have to admit that I am a complete and absolute beginner on this repo. So I may take more time to complete...
Would you be keen to help me fix the issues?
Best wishes,
Gilt0

**Comment by gupnik** [comment]
> Hi @gupnik , I would be curious to help on this issue, however, I have to admit that I am a complete and absolute beginner on this repo. So I may take more time to complete... Would you be keen to help me fix the issues? Best wishes, Gilt0

Sure, assigned it to you.

**Comment by Gilt0** [comment]
Great thank you.

**Comment by gupnik** [comment]
> hi @gupnik ,
> 
> I created pull request: [Gilt0:issue-3237.](https://github.com/paritytech/polkadot-sdk/pull/3317)
> 
> Also:
> 
> * I have not figured out how to add the PR to  the Security Audit (PRs) - SRLabs.
> * I did not squash so that you'd see all the steps (maybe naming of commits was a little short sighted - apologies).
> * for some reason the actions fail at Review Bot and I am not sure what I need to do to fix it.
>   EDIT: it seems that the bot actually communicates with me and it has to do with clippy.
> 
> Best wishes, Gilt0

Great @Gilt0.
1. I have added the labels.
2. Works.
3. CI points to unused imports as the reason. https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5209825

<img width="985" alt="Screenshot 2024-02-14 at 2 27 28 PM" src="https://github.com/paritytech/polkadot-sdk/assets/17176722/09926509-7a24-42a4-a6ca-a81a08543d63">

**Comment by Gilt0** [comment]
Thank you for your replay @gupnik 
Currently fixing the actions error (mainly unused imports that escaped my vigilance).

**Comment by Gilt0** [comment]
Hey @gupnik 

I am stalling a little. There is an error I don't understand. I tried reverting changes on identity pallet, but it did not do anything (shooting blind as I don't really understand what is going on).

Would you have any pointers on what could be happening?

```
[2024-02-14T22:59:57Z INFO  runtime::frame-support] 🩺 Running "Beefy" try-state checks
[2024-02-14T22:59:57Z INFO  runtime::frame-support] 🩺 Running "Mmr" try-state checks
[2024-02-14T22:59:57Z INFO  runtime::frame-support] 🩺 Running "BeefyMmrLeaf" try-state checks
[2024-02-14T22:59:57Z INFO  runtime::frame-support] 🩺 Running "IdentityMigrator" try-state checks
[2024-02-14T22:59:57Z ERROR runtime] panicked at /builds/parity/mirrors/polkadot-sdk/polkadot/runtime/westend/src/lib.rs:2227:65:
    called `Result::unwrap()` on an `Err` value: Other("Detected errors while executing try_state checks. See logs for more info.")
thread 'main' panicked at cli/main.rs:325:6:
called `Result::unwrap()` on an `Err` value: Input("failed to execute TryRuntime_on_runtime_upgrade: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x73d60 - <unknown>!rust_begin_unwind\n    1: 0x11dbf - <unknown>!core::panicking::panic_fmt::he07f4fcfc0e8e78f\n    2: 0xfdb0 - <unknown>!core::result::unwrap_failed::h601a124147f65f04\n    3: 0x116ace - <unknown>!<westend_runtime::Runtime as frame_try_runtime::runtime_decl_for_try_runtime::TryRuntimeV1<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,westend_runtime::RuntimeCall,sp_runtime::MultiSignature,(frame_system::extensions::check_non_zero_sender::CheckNonZeroSender<westend_runtime::Runtime>,frame_system::extensions::check_spec_version::CheckSpecVersion<westend_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<westend_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<westend_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<westend_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<westend_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<westend_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<westend_runtime::Runtime>)>>>>::on_runtime_upgrade::h3d77c7b947511727\n    4: 0x20ff92 - <unknown>!TryRuntime_on_runtime_upgrade")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: tokio::runtime::park::CachedParkThread::block_on
   4: try_runtime::main
```

**Comment by gupnik** [comment]
Commented on the PR @Gilt0

**Comment by Gilt0** [comment]
@gupnik Ah great thank you.
