### ISSUE TITLE
[CI] Disable prdoc and label checks on master

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3240]
![Screenshot 2024-02-07 at 14 53 25](https://github.com/paritytech/polkadot-sdk/assets/10380170/c13ed3c3-4f25-4de7-838f-29d63dbee3c9)

I keep seeing these fail on master and get notifications about it. Both should only run on merge requests, not master.  
cc @paritytech/ci

**Comment by alvicsam** [comment]
Fixed in https://github.com/paritytech/polkadot-sdk/pull/3257
