### ISSUE TITLE
Queried Preimage Hash returns unrequested while it was not.

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#3278]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We have just submitted on-chain referenda, but when we submitted the preimage it did not show on the Preimage screen in UI. What is strange, we can find it in the preimage pallet and it says it was unregistered - meaning our proposal will probably fail even if approved. Could anyone check on this, please? Also, the currency for the preimage is reserved, it did not return. We would love to believe, that this is just an error with UI and everything is fine. 

Details:
Preimage: https://kusama.subscan.io/extrinsic/21799752-2
Preimage query: 0x758b3447bf2a8e9e61f3de3edf0a14e5f84fdd470eca5d1b991fbb02f6c03cd0
<img width="1372" alt="Screenshot 2024-02-09 at 10 06 08" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/4aca1c34-0353-43eb-9785-c7869e0ba774">
Proposal: https://kusama.polkassembly.io/referenda/344
Network: Kusama

EDIT: 
- Other Kusama proposals reportedly also show unrequested.
- Seen this on Polkadot proposals also, so it is probably not caused by the latest runtime update.
- When I submitted same preimage it led to error, that it already exist, despite the fact, that it shown unrequested in the UI. So probably it is only issue with the UI. Would be cool if someone could confirm us on this. Thanks!

### Steps to reproduce

Submit preimage.
Our preimage was
treasury.spendLocal

**Comment by dudo50** [comment]
It also shows unrequested here: https://kusama.subscan.io/referenda_v2/344?tab=preimage

**Comment by dudo50** [comment]
Other Kusama proposals reportedly also show unrequested.

**Comment by ggwpez** [comment]
> We have just submitted on-chain referenda, but when we submitted the preimage it did not show on the Preimage screen in UI  

The preimage page is buggy: https://github.com/paritytech/polkadot-sdk/issues/2869 and https://github.com/polkadot-js/apps/issues/10141, but nothing that we can do here.

> What is strange, we can find it in the preimage pallet and it says it was unregistered

It says un*requested*, not un*registered*. The preimage was registered successfully and is there. You can query it with `PreimageFor(0x758b3447bf2a8e9e61f3de3edf0a14e5f84fdd470eca5d1b991fbb02f6c03cd0, 43)`.

I think the governance referendum should then switch it to Requested, but maybe that does only happen after the preparation period is over.

**Comment by dudo50** [comment]
@ggwpez , not sure about switch to requested after preparation is done as other proposals that are already active still display unrequested.

Correct me if I am wrong.
Should the proposal be executed as expected if it passes and everything is set correctly then? 

Thanks for the information.

**Comment by dudo50** [comment]
We have analyzed the code and found following:
```
	/// The associated preimage has not yet been requested by the system. The given deposit (if
	/// some) is being held until either it becomes requested or the user retracts the preimage.
	Unrequested { ticket: (AccountId, Ticket), len: u32 },
	/// There are a non-zero number of outstanding requests for this hash by this chain. If there
	/// is a preimage registered, then `len` is `Some` and it may be removed iff this counter
	/// becomes zero.
	Requested { maybe_ticket: Option<(AccountId, Ticket)>, count: u32, maybe_len: Option<u32> },
```
Closing this issue now, as all our concerns were explained in code.
