### ISSUE TITLE
[CI] Require >0 major versions for published crates

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3293]
I think we should prevent 0-major versions on the `master` branch for published crates.  
This would mean that any crate must have either a valid >0 SemVer or declare `publish = false`.

Otherwise this leads to cascading transitive bumps, since every version change must be treated as breaking.

**Comment by bkchr** [comment]
Hmm? You can just bump the patch version as you would bump the minor version for >1.0.0. Not sure we need this.

**Comment by ggwpez** [comment]
Yea... but it also means that we cannot make a non-breaking patch to that crate. Which kind of defeats the purpose of SemVer.

**Comment by bkchr** [comment]
Hmm? Bumping the patch would be used for non breaking releases, but it would also include new stuff and not just some internal fixes.

**Comment by ggwpez** [comment]
But 0-major SemVer does not give [any guarantee](https://semver.org/#spec-item-4). So even a patch bump must be treated as breaking.  
Not sure if i understood what you mean.

**Comment by bkchr** [comment]
> This guide uses the terms “major” and “minor” assuming this relates to a “1.0.0” release or later. Initial development releases starting with “0.y.z” can treat changes in “y” as a major release, and “z” as a minor release. “0.0.z” releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

https://doc.rust-lang.org/cargo/reference/semver.html

**Comment by ggwpez** [comment]
I see 🫠 yea then we can keep 0.x versions i guess.  
Hope the tooling works with it though.

**Comment by liamaharon** [comment]
I think we should consider enforcing at least 0.1.0 and not allow prerelease suffixes in stable.

Otherwise it's impossible to make a compatible bump, so when you bump dependents after updating a crate you get a huge cascading tree of breaking version changes.

**Comment by ggwpez** [comment]
Yes suffices should be forbidden, see https://github.com/paritytech/polkadot-sdk/issues/3338. Otherwise i dont care anymore if we use 0.0.1, 0.1.0 or whatever,
