### ISSUE TITLE
Parachain Auctions: Is it intended behaviour that an account can bid on a lease for a different paraid?

### ISSUE THREAD

**Issue by JelliedOwl** [paritytech/polkadot-sdk#3312]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I'm not sure if this is a bug or a feature...

A few months ago, I bid, with my paraid account, on a Kusama slot auction but accidentally entered the wrong paraid.  The bid was accepted, which surprised me. Is this intentionally behaviour?  It seems like an opportunity for someone to mess up someone else's future auctions by bidding on random single slots for them.  Or potentially make it difficult for them to retire their paraid.

I haven't checked if the bid can be placed by ANY account or just an account holding a paraid.

### Steps to reproduce

See the history on this account (my paraid with this account is 2113):
https://kusama.subscan.io/account/F69ngQSVQmsKo6fiVNo5RaLHMdPyWNhH4HHihkQkpDsHnjj?tab=proxy_extrinsic

<img width="1193" alt="Screenshot 2024-02-13 at 16 16 20" src="https://github.com/paritytech/polkadot-sdk/assets/80860490/81955076-b3c4-4f91-a2c7-203b502536d9">

**Comment by bkchr** [comment]
Yeah looking into the code, this is fine. The tokens will be locked in the `bidders` account. So, I can see here no issue.

**Comment by JelliedOwl** [comment]
This is a potential issue though in an attack a bit like a DoS.  Say a parachain currently has a lease for 30-38.  Someone else could maliciously bid to win lease 43 for that paraid. If they do, the owner of that paraid would then have to have to bid, separately, for 39-42 and 44-45, locking two amounts for the leases.

Unless either of these is true:
a) you can't bid for lease that isn't consecutive with the current lease for a paraid (so they couldn't vote for 43 without also voting for 39-42) or:
b) a bid of 100KSM for leases 39-42 and 100KSM for 43-45 would only lock a total of 100KSM.

I'm not sure about either of those?

**Comment by JelliedOwl** [comment]
Of course, even if this is an issue now, it might go away when moving the chains to core time payments.

**Comment by bkchr** [comment]
> If they do, the owner of that paraid would then have to have to bid, separately, for 39-42 and 44-45, locking two amounts for the leases.

Looking at the code and the docs I don't think that this could happen.

https://github.com/paritytech/polkadot-sdk/blob/12e5e19c2033383fc914bcc286ad16ae565d4734/polkadot/runtime/common/src/auctions.rs#L269-L270

**Comment by JelliedOwl** [comment]
Despite that documentation comment - and at the risk of missing some nuance in the Rust code that I don't fully understand - I think `handle_bid()` only enforces that the bid doesn't overlap the current leases the paraid holds and is within the range of slots for the current auction.

I don't think there's actually anything to enforce "only as long as all active bids overlap each other", and I'm not even sure that that means.

**Comment by JelliedOwl** [comment]
Anyway, I'm happy to park this as "Probably no-one is going to mess with this on-chain and, if they do, governance can resolve it".

**Comment by bkchr** [comment]
> I don't think there's actually anything to enforce "only as long as all active bids overlap each other", and I'm not even sure what that means.

I think what it means is that you can only bid multiple times, if all bids are for the same leases. But yeah, I also did not see any particular code that rejects any bidding for non overlapping leases or similar.
