### ISSUE TITLE
Add `max_rank()` method in `RankedMember` trait

### ISSUE THREAD

**Issue by Doordashcon** [paritytech/polkadot-sdk#3315]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

currently working on adding the `try-state` hook to [`pallet-core-fellowship`](https://github.com/paritytech/polkadot-sdk/pull/3276), we set the maximum ranked member count to be a constant 9(i.e. `const RANK_COUNT: usize = 9;`), I suspect as new collectives get added this would not be the case.

### Request

```rust
/// Ranked membership data structure.
pub trait RankedMembers {
	...

	/// The maximum rank possible in this membership organisation.
	fn max_rank() -> Self::Rank;
}
```

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
Sounds reasonable.
