### ISSUE TITLE
password-protected keystore with sc_keystore

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [paritytech/polkadot-sdk#3320]
I tried to use a password-protected keystore with `LocalKeystore` from `sc_keystore` with this naive approach:

```rust
let suri = rpassword::prompt_password("SURI: ")?;
let keypair = pair_from_str(&suri)?;
let password = rpassword::prompt_password("Password: ")?;
let password = secrecy::Secret::new(password);
let keystore =
	sc_keystore::LocalKeystore::open(project_dir.data_dir(), Some(password))?;
keystore.insert(KeyTypeId(*b"user"), &suri, &keypair.public())?;
```

But when looking in the keystore file, I get the SURI in clear:

```sh
cat .local/share/mytool/7573657296723102a2e339276775717781cbf445953362f7cc65df7e9be5bce5ee21c570
"drill pledge public bunker involve nose vanish buddy day puppy coast patrol"%   
```

If this is the intended behavior, I think it's worth documenting in https://docs.rs/sc-keystore/latest/sc_keystore/struct.LocalKeystore.html#method.open

**Comment by bkchr** [comment]
> But when looking in the keystore file, I get the SURI in clear:

If you load this SURI, you will find out that this is not the SURI of your private key. The actual SURI is `drill pledge public bunker involve nose vanish buddy day puppy coast patrol///YOUR_PASSWORD`.

https://github.com/paritytech/polkadot-sdk/blob/a17b49a44fd6471a3498df7e58be32768925015d/substrate/primitives/core/src/crypto.rs#L949-L950

**Comment by Hugo-Trentesaux** [comment]
I still think that the doc of the `open` method of `LocalKeystore` could be more than one line (https://docs.rs/sc-keystore/latest/src/sc_keystore/local.rs.html#49). In particular, the `password` argument is not mentioned.

**Comment by davxy** [comment]
@Hugo-Trentesaux what is the implementation of your `pair_from_str`?

Because if you generated the keypair **without** the password (as you suspect) you also end with a problem.
Ergo: the password you used to open the keystore doesn't affect that key you generated. 
If you try to sign using the pair you manually generated will not correspond to the one that your keystore will reference when using the same `public()`.

Example
```rust
		let suri = "drill pledge public bunker involve nose vanish buddy day puppy coast patrol";
		let (keypair, _): (sr25519::Pair, _) = Pair::from_phrase(&suri, None).unwrap(); // No password specified for key gen
		let password = String::from("pass");
		let keystore = LocalKeystore::open(Path::new("/tmp/password"), Some(password.clone().into())).unwrap();

		let keytype = KeyTypeId(*b"user");
		keystore.insert(keytype, &suri, &keypair.public()).unwrap();

		let res = keystore.sr25519_sign(keytype, &keypair.public(), b"message");
		assert!(res.is_err());   // `keypair.public()` is not the same as the one the keystore will try to use (which is that one augmented with the pass)
```

If you indend to use a `password` for your keystore you need to construct your secret in one of these two ways:

### Option 1 - Generate the key directly using the keystore methods

No need to `insert()` the key as it is directly generated within the keystore
```rust
		let public = keystore.sr25519_generate_new(keytype, None).unwrap();
		let sig = keystore.sr25519_sign(keytype, &public, b"message").unwrap().unwrap();
		assert!(sr25519::Pair::verify(&sig, b"message", &public));
```

### Option 2 - Generate the key ouside the keystore but with the password

The password you use should match the one used when you open the keystore
```rust
		let (keypair, _): (sr25519::Pair, _) = Pair::from_phrase(&suri, Some(&password)).unwrap();
```

**Comment by bkchr** [comment]
> Because if you generated the keypair **without** the password (as I suspect) you end up with a problem.

I have totally overseen this :see_no_evil: Maybe the best would be we return an error in `insert` if a password is set?

**Comment by bkchr** [comment]
I mean it is not the best solution at all, but we also don't have that many possibilities.

**Comment by davxy** [comment]
> Maybe the best would be we return an error in insert if a password is set?

Yeah. Basically we have two options:
- option 1) fail the `insert` if a password is set in the keystore. But this is not super ideal as the user is allowed to generate the key outside the keystore AND with a password. But if you don't plan to insert it in the keystore doesn't make much sense to have generated this key with the password in the first place.
- option 2) Keep the things as is but document that if you manually insert a password (using `insert`) the key should have been generated using the same password. AND also test it internally. We can do that.

### Option 2

(pseudo code)
```
	fn insert(&self, key_type: KeyTypeId, suri: &str, public: &[u8]) -> Result<()> {
	    if Pair::from_suri(suri, self.password()).public() != public() {
	       return Err
	    }
	    normally insert
	}
```

I will personally try it. If is good I come with a PR

**Comment by davxy** [comment]
Nope. We need the specific `Pair` type to do this... I'll think about it

**Comment by bkchr** [comment]
> * option 2) Keep the things as is but document `insert()` such that if you manually insert a key then this should have been generated using the same password used by the keystore when has been opened

The problem is that if a node operator is using the `author_insertKey` RPC they will not find out about this that easily :see_no_evil:

**Comment by Hugo-Trentesaux** [comment]
> @Hugo-Trentesaux what is the implementation of your `pair_from_str`?

You are right, I forgot to mention that. I do not want to override the password:

```rust
Sr25519Pair::from_string(secret, None)
```

> The problem is that if a node operator [...]

I also forgot to mention the context: I intended to use this crate not in the context of a node, but in a wallet. That's why I need the user to be able to insert exactly the mnemonic he wants, including derivation scheme.

The general idea is:
- high entropy → mnemonic → KDF → keypair
- mnemonic + low entropy user password → KDF → (other) keypair

My intent was to store the high entropy mnemonic in a file encrypted with low entropy user password as you would do with `ssh`.

> @Hugo-Trentesaux are these docs better for explaining the internals?

Yes, with this doc I was able to identify that this crate was not what I was looking for.

----

(bonus)

If you are curious of what I finally used, I chose `rage` crate which is a beta Rust implementation of AGE. With armor feature, I come to something like this:

```sh
$ cat ~/.local/share/vault/5DfhGyQdFobKM8NsWvEeAKk5EQQgYe9AydgJ7rMB6E1EqRzV
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCBscTQxMCsyWGpRU00zS1Qx
dDJKQVVRIDEzCk4ySWdubXljMkdPQlJERWpuZUpEekg4NGdtSmVHZWhpVCs3Ky8r
QWpnRTAKLS0tIHRQMFA3ZG9LRENtSncyTTkrQVFPZjJyTW9DZzFDdFVCckN3VDE0
UkJYMEUKcGlmGWxGDOkfsdqL2JuN8thkQPpMJItmkAs3JfzGt/s=
-----END AGE ENCRYPTED FILE-----
```

And this can be encrypted using ssh keys, which is convenient.
