### ISSUE TITLE
Expose Genesis Hash to Runtime

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/polkadot-sdk#3344]
This is either a support or a feature question. 

Is it possible to retrieve the chains genesis hash in the runtime? 

Usecase: 

`NetworkId::ByGensis(..)`

**Comment by bkchr** [comment]
`frame_system::BlockHash::<T>::get(0)` this gives you the genesis hash.

**Comment by mustermeiszer** [comment]
Thanks, and sorry for the noise!

**Comment by bkchr** [comment]
No problemo ;) You used the issue tracker in the correct way :D
