### ISSUE TITLE
[ci] build-runtimes-polkavm job doesn't work

### ISSUE THREAD

**Issue by alvicsam** [paritytech/polkadot-sdk#3352]
The job is [broken](https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5230166) for a few weeks. Should we disable it until it's fixed?

cc @koute @paritytech/ci

**Comment by koute** [comment]
Unless I screwed/misunderstood something up this job was working when I merged it in https://github.com/paritytech/polkadot-sdk/pull/3209.

No; let's not disable it. I'll fix it.

While we're at it, do you know why this job doesn't show up on GitHub in the checks list above the "Add a comment"? Wouldn't this make possible to merge PRs which break the job? How can I make it show up?

**Comment by alvicsam** [comment]
Hm, it's interesting. It seems that it runs only on master branch. I'll also take a look.

**Comment by alvicsam** [comment]
@koute [this PR](https://github.com/paritytech/polkadot-sdk/pull/3354) is now merged and I can see the job in PR pipeline. As soon as you fix it we can mark it as `Required` in GitHub.

**Comment by koute** [comment]
@alvicsam Okay, thanks for the help!

PR with a fix is up: https://github.com/paritytech/polkadot-sdk/pull/3363
