### ISSUE TITLE
Reduce log output of beefy pallet (>100k chars)

### ISSUE THREAD

**Issue by ScepticMatt** [paritytech/polkadot-sdk#3407]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Beefy (on Kusama 1.7.1) causes a huge amount of log output by printing a large list of addresses.

### Request

Stop printing full list of addresses (see attachments)
[Loading BEEFY .txt](https://github.com/paritytech/polkadot-sdk/files/14345113/Loading.BEEFY.txt)
[Round 21959912 concluded final.txt](https://github.com/paritytech/polkadot-sdk/files/14345114/Round.21959912.concluded.final.txt)

### Solution

Print statistics about BEEFY instead of the full list

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
None of these messages should be printed by info logs. They have exactly 0 value for an operator. They can be degraded to debug messages.
