### ISSUE TITLE
Broker pallet should expose `sale_price` through runtime api

### ISSUE THREAD

**Issue by Szegoo** [paritytech/polkadot-sdk#3413]
Frontends should not be required to reimplement the logic for determining the sale price of cores, as this approach is unreliable and changes in pricing logic could make things break. 
Instead, it should be possible to directly query the price from the runtime.

**Comment by bkchr** [comment]
Generally we can add it, but it isn't really required to have this declared centrally. The runtime api can just be declared and implemented next to the runtime.
