### ISSUE TITLE
Consider moving the "order on-demand" extrinsics

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3425]
Right now it is routed directly to the "on demand assigner" pallet, which can be considered an implementation detail. Probably a good idea to move this to the the "toplevel" coretime interface pallet.

it is a bit late for Kusama, but if we want that we should do it before going for Polkadot in order to avoid breakage later on.

**Comment by seadanda** [comment]
This could be done at the same time as implementing the coretime credits, implementing the new extrinsics (credits bought on broker can be exchanged for on-demand coretime). This could replace the existing on demand assigner extrinsics as the "right" way to do it compliant with RFC-1

We can then separately disable/remove/call filter (?) the on demand assigner extrinsics on Kusama which allow buying on-demand coretime directly with KSM

**Comment by eskimor** [comment]
Status @antonva - I think we agreed to just rename the pallet?
