### ISSUE TITLE
HRMP Error - "Unsupported" when opening HRMP channel on local network

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#3436]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After consulting with @pepoviola if the issue is not related to the Zombienet config we both concluded, that it is not.

When opening HRMP channels between two localhost Parachains (Parachain template Parachains) we receive an error Unsupported on both of them but the operation on the Relay chain completes correctly. It even stores HRMP channels to storage. When we send HRMP message from one chain to the other chain we receive messageQueue.ProcessingFailed with error Unsupported also (Meaning, that the HRMP channels did not open correctly). 

We use ParaSudoWrapper pallet to open messages through Sudo.

Please fix this issue as our work depends on HRMP channels working.
<img width="711" alt="image" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/534bb2c9-0392-4b57-aca1-913e0d95532e">

### Steps to reproduce

```cd Polkadot && cargo build release```
```cargo b -r -p parachain-template-node```       

download zombienet binary
launch network via the following config:
https://github.com/ParaSpell-Research-Foundation/polkadot-sdk-nft-pallet/blob/master/binaries/config.toml

launch via following command
```./zombienet-macos -p native -c 1 spawn config.toml```

with parasudowrapper open hrmp channel between parachain 1000 and 1001. Observe error message on any of mentioned Parachains

**Comment by bkchr** [comment]
Maybe @ggwpez you have some idea?

**Comment by pepoviola** [comment]
I can reproduce it locally and upload the logs here. You want to enable a particular log target/level? 
Thanks!

**Comment by ggwpez** [comment]
`runtime=debug` maybe it helps.

**Comment by ggwpez** [comment]
Seeing a ton of panics in the collator log myself with `no space left in the unincluded segment`.  
Dunno if that affects it.

**Comment by ggwpez** [comment]
It logs `[Parachain] XCM message execution error: Barrier` in `xcm::process-message` log target.  
So i think its not the MQ pallet.

**Comment by franciscoaguirre** [comment]
I can take a look into it after some other work

**Comment by dudo50** [comment]
@franciscoaguirre any news in regards to this issue? Many thanks for your information.

**Comment by franciscoaguirre** [comment]
@dudo50 Managed to get around to look at this.

I reproduced the issue building the binaries and running zombienet as you described.
I don't know what message you were sending from one chain to another after establishing the HRMP channel so I tried a few different ones.

The HRMP channel is being setup correctly.
The issue is the XCM configuration is not set up in a useful way for development, which is presumably what you want to do right now.
This would be more suitable as a stackexchange question.

If you look at the barrier in `cumulus/parachain-template/runtime/src/xcm_config.rs` (`type Barrier = ...`), you'll see a very common configuration which is to allow computed origins (which means adding `DescendOrigin`, which lets you use things like `polkadotXcm.send`) and allow messages from every origin as long as they intend to pay for fees (`AllowTopLevelPaidExecutionFrom<Everything>`).
It also has an `AllowExplicitUnpaidExecutionFrom<T>` barrier, which means some origins don't need to pay for fees.

So there are two ways of fixing this:
1. Change the barrier to have `AllowExplicitUnpaidExecutionFrom<Everything>` or `AllowUnpaidExecutionFrom<Everything>` for development. The first one will require you add the `UnpaidExecution` instruction on top of every message you send. Remember to remove this for a live chain!
2. Fix all the issues required to pay fees.

The easiest one is the first one, and that will already solve your problem.
The second one requires adding `HashedDescription<DescribeFamily<DescribeAllTerminal>>` to `LocationToAccountId` and funding the sovereign account in order to pay for fees.

Let me know if this fixes your issue.

**Comment by dudo50** [comment]
Hey @franciscoaguirre unfortunately this did not fix the issue. You can see I commited changes here: https://github.com/ParaSpell-Research-Foundation/polkadot-sdk-nft-pallet/commit/94e701570ad0e8472f98e865ac2e331498076fb5

But the issue with "unsupported" still remains - 
<img width="701" alt="Snímka obrazovky 2024-03-05 o 21 12 04" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/b1e622b4-7802-45c9-ac65-14d8f730ad86">

First unsupported (bottom one) is from opening HRMP channel and second is from sending XCM instruction from other Parachain.

Please let me know if there is something else I can try to fix this problem.

**Comment by dudo50** [comment]
@franciscoaguirre , I compiled both Polkadot (release) and Parachain template launched via zombienet config above and then tried to open HRMP channel via sudo:
<img width="1466" alt="Snímka obrazovky 2024-03-05 o 22 32 27" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/0df4f1f7-4229-458c-94b5-f0b89e2f7d0b">

**Comment by franciscoaguirre** [comment]
@dudo50 I get the same unsupported error on the parachains when I make the call on the relay chain to establish the hrmp channel. I hadn't realized.

However, the channel is set up and when I send a message from 1000 to 1001 it arrives successfully.

The channel is set up (had to wait a little bit):

![photo1709718748](https://github.com/paritytech/polkadot-sdk/assets/4390772/40b1375a-86f1-4ebb-9dda-c27a5787f2ce)

I receive `Unsupported` on chain 1000 but also send a message to 1001 and it works:

![photo1709718709](https://github.com/paritytech/polkadot-sdk/assets/4390772/c7991447-069e-47b7-a396-84eea293e661)

Parachain 1001 receives it:

![photo1709718725](https://github.com/paritytech/polkadot-sdk/assets/4390772/3671dc53-bd54-4020-8aca-c01274804d55)

**Comment by dudo50** [comment]
@franciscoaguirre I see, thank you for investigating. Why my custom XCM message does not get processed with unsupported error as well? I included the config you suggested but no change unfortunately.

**Comment by franciscoaguirre** [comment]
What's the XCM you're sending that's giving unsupported? Have you checked that the channel is set up? Chain state -> hrmp -> hrmpChannels

**Comment by franciscoaguirre** [comment]
The `Unsupported` you get when you open the channel seems to be coming from [here](https://github.com/paritytech/polkadot-sdk/blob/475e7a147676a4e7a9d255ddc7969dd35ea22882/polkadot/runtime/parachains/src/hrmp.rs#L1454).
The `Unsupported` might come from a Barrier error.

Have you tried changing the barrier and sending a message that passes it? Just set it to allow all to test

**Comment by franciscoaguirre** [comment]
@dudo50  Barrier errors seem to transform into `Unsupported`: https://github.com/paritytech/polkadot-sdk/blob/475e7a147676a4e7a9d255ddc7969dd35ea22882/polkadot/xcm/xcm-builder/src/process_xcm_message.rs#L105C1-L105C6

Try sending a different message

**Comment by dudo50** [comment]
> What's the XCM you're sending that's giving unsupported? Have you checked that the channel is set up? Chain state -> hrmp -> hrmpChannels

The instruction can be found here: https://github.com/ParaSpell-Research-Foundation/polkadot-sdk-nft-pallet/blob/94e701570ad0e8472f98e865ac2e331498076fb5/cumulus/parachain-template/pallets/xnft/src/lib.rs#L326C1-L327C1

Yes they are open correctly I can query that through Relay chain just fine.

**Comment by franciscoaguirre** [comment]
@dudo50 I see you added `AllowExplicitUnpaidExecutionFrom<Everything>`, that means your message has to be:
- UnpaidExecution
- Transact
Instead of only just Transact
Try it

**Comment by dudo50** [comment]
Could you ellaborate how to form that call with Unpaid Execution please? I am unsure if I understand correctly where to put it and how to put it there.

**Comment by franciscoaguirre** [comment]
@dudo50 Sure, there are two options:

- You add the `UnpaidExecution` instruction:
```rust
	Xcm(vec![UnpaidExecution { weight_limit: Unlimited, check_origin: None }, Transact {
		origin_kind: OriginKind::Native,
		require_weight_at_most: Weight::from_parts(1_000_000_000, 64 * 1024),
		call: <T as Config>::RuntimeCall::from(Call::<T>::mint_collection_received {
			collection_name: collection_with_hash_for_xcm.collection_name,
			collection_description: collection_with_hash_for_xcm.collection_description,
			origin_parachain_id: 1000.into(),
			owner: recipient.clone(),
		})
		.encode()
		.into(),
	}]),
```

- You substitute `AllowExplicitUnpaidExecutionFrom<Everything>` with `AllowUnpaidExecutionFrom<Everything>`, this will let you not have to add the `UnpaidExecution` instruction all the time

**Comment by dudo50** [comment]
@franciscoaguirre  it did work! Thank you! However it did not trigger the function it was supposed to trigger for some reason.. Do you know what might be the problem?
<img width="1083" alt="Snímka obrazovky 2024-03-06 o 12 14 23" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/8330212f-a1ee-42aa-9073-c56aa8a4d032">

**Comment by franciscoaguirre** [comment]
@dudo50 glad to hear your issue is resolved. For the transact not working, try checking the logs, `xcm=trace` works like a charm.
Also, try with other extrinsics to try to find the problem.
I hope that's helpful.

**Comment by franciscoaguirre** [comment]
I also see this issue is a continuation of #3195. The issue is the same.

**Comment by bkontur** [comment]
> I also see this issue is a continuation of #3195. The issue is the same.

yes, we also discussed paid vs unpaid execution here: https://github.com/paritytech/polkadot-sdk/issues/3195#issuecomment-1938735679

and also here is another duplicate: https://substrate.stackexchange.com/questions/10950/error-bad-origin-on-custom-xcm-integration

@dudo50 Can you please close all other issues and leave just (this) one?

**Comment by dudo50** [comment]
Closing this in favor of new issue as content of this issue was resolved.
