### ISSUE TITLE
P2P: Make `Behaviour` partially generic for consumers of Substrate

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/polkadot-sdk#3482]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Currently, we are playing around extending our nodes p2p capabilities. The current possibilities are working mostly pretty well and thanks for that. But if we wanted to write our own p2p network behaviour for the underlying `Swarm`, then we are blocked. We need that as we want to play around having ipfs support for some internal storage that we are extending the nodes with. 

Note: Not sure if from a networking perspective that is even possible, but we should be able to be connected to multiple p2p networks at the same time, right? 

### Request

Substrate already provides some possibilities here, by allowing to define custom notification/request-response protocols on the p2p layer. But I think the best would be if consumers of Substrate would be able to extend the underlying `libp2p::Behaviour`. 

Something like 

```rust
#[derive(NetworkBehaviour)]
#[behaviour(out_event = "BehaviourOut")]
pub struct Behaviour<B: BlockT, Extension: NetworkBehaviour> {
	/// All the substrate-specific protocols.
	substrate: Protocol<B>,
	/// Periodically pings and identifies the nodes we are connected to, and store information in a
	/// cache.
	peer_info: peer_info::PeerInfoBehaviour,
	/// Discovers nodes of the network.
	discovery: DiscoveryBehaviour,
	/// Generic request-response protocols.
	request_responses: request_responses::RequestResponsesBehaviour,
        /// Custom NetworkBehaviour of consumers
        extension: Extension
}
```

### Solution

Allow to pass the `Extension` network behaviour as a generic to the Substrate side. 

* `sc_network::NetworkService::new(params: Params<B, Extension>) -> Result<Self, Error> {...})`

I am not sure how much of a refactor this would be, but from my first research it seems doable.

### Are you willing to help with this request?

Yes!

**Comment by altonen** [comment]
We've been working on making Polkadot SDK generic over the p2p library: https://github.com/paritytech/polkadot-sdk/pull/2944

What you're proposing is probably possible even after that PR has been merged but I don't know if adding more features for the libp2p backend is in line with the long term goals of `sc-network`

**Comment by mustermeiszer** [comment]
Thanks. Then I will see where this lands. Looks like a nice change!
