### ISSUE TITLE
 Bind to IPv6 addresses if available

### ISSUE THREAD

**Issue by olanod** [paritytech/polkadot-sdk#3488]
[Original issue by @geigerzaehler:](https://github.com/paritytech/substrate/issues/5645)
> If not explicilty set a node binds only to IPv4 addresses. This results in some usability issues. For example I cannot connect to the HTTP or Websocket RPC API endpoints if I use the host `localhost` if that host name resolves to `::1`. Similarly, if I use `--unsafe-rpc-external` I cannot reach the RPC API from other machines over IPv6. The same applies to the P2P connection.
>
> I’d suggest binding to `::1` if we’re also binding to `127.0.0.1` and to bind to `::` if we’re also binding to `0.0.0.0`

**Comment by olanod** [comment]
I have some IPv6 only nodes that would benefit from this feature, the current workaround is to have a reverse proxy that can bind to an IPv6 address and forward traffic to the RPC node bound to the IPv4 address.

**Comment by bkchr** [comment]
Cc @niklasad1

**Comment by niklasad1** [comment]
We can enable both ipv4/ipv6 sockets on the JSON-RPC, shouldn't be that hard :)
