### ISSUE TITLE
Improve error reporting for FRAME Macros

### ISSUE THREAD

**Issue by gupnik** [paritytech/polkadot-sdk#3489]
Generally within FRAME, the macro expansion exits as soon as some condition fails without generating rest of the code. This produces a cascade of errors resulting in poor dev experience.

Though it is not possible to fix it everywhere, a number of scenarios could be improved by aggregating all errors during the parsing phase and making the expansion phase infallible - but adding the aggregated errors along with the expansion. 

https://github.com/paritytech/polkadot-sdk/pull/3478 serves as a good example. 

CC: @bkchr @kianenigma

**Comment by kianenigma** [comment]
related: #334

**Comment by gupnik** [comment]
> but isn't this a duplicate of #213?

Wasn't aware of it. Will close this one.
