### ISSUE TITLE
Issue with `quick-start` page. Incorrect link

### ISSUE THREAD

**Issue by korir248** [paritytech/polkadot-sdk#3493]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

In this section of the docs, one is guided on how to add a pallet, `pallet-utility` but the [link](https://github.com/paritytech/polkadot-sdk.git) provided has no branch named `polkadot-v1.0.0` as we are instructed to use the same branch name as the other pallets. 

### Steps to reproduce

Tried adding the following line to my Cargo.toml as per the documentation instructions
```toml
pallet-utility = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-vX.Y.Z" }
```
![Screenshot from 2024-02-27 18-02-03](https://github.com/paritytech/polkadot-sdk/assets/62384233/0d0b1114-b94e-42b5-bb34-cc581f56c42c)

**Comment by bkchr** [comment]
I could not find the mentioned docs.
