### ISSUE TITLE
Add `claim_assets` extrinsic to `pallet-xcm` and make it available in next runtime release

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot-sdk#3495]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

If an XCM execution fails or ends with leftover assets, these will be trapped.
In order to claim them, a custom XCM has to be executed, with the `ClaimAsset` instruction.
However, arbitrary XCM execution is not allowed everywhere yet and XCM itself is still not easy enough to use for users out there with trapped assets.

### Request

Add new extrinsic in `pallet-xcm` to allow users to easily claim their assets, without concerning themselves with writing arbitrary XCMs.

Backport the solution to polkadot-sdk v1.7.0, release patched `pallet-xcm` crate, add it to https://github.com/polkadot-fellows/runtimes to make it available with [upcoming v1.2.0 runtimes release](https://github.com/polkadot-fellows/runtimes/issues/140).

### Solution

- [x] https://github.com/paritytech/polkadot-sdk/pull/3403
- [x] backport and release it as part of [upcoming v1.2.0 runtimes release](https://github.com/polkadot-fellows/runtimes/issues/140)

### Are you willing to help with this request?

Yes!

**Comment by bkontur** [comment]
Merged to the fellows main as a part of https://github.com/polkadot-fellows/runtimes/pull/187

What about backport to 1.8.0?

**Comment by acatangiu** [comment]
I am generally against unneeded/unrequested backports. We could do it lazily when someone requests it. We know that for system runtimes we don’t need it in 1.8

**Comment by acatangiu** [comment]
Fixed in https://github.com/polkadot-fellows/runtimes/pull/187

**Comment by bkontur** [comment]
> I am generally against unneeded/unrequested backports. We could do it lazily when someone requests it. We know that for system runtimes we don’t need it in 1.8

yes, agree, but if we want to release next polkadot 1.3.0 just with 1.8.0 (without 1.9.0) we will need to backport anyway

**Comment by decentration** [comment]
i think i need this, i have an issue that requires claiming 1499 DOT that just got trapped in Polkadot chain, the call i have curated cannt be called because it would exhaust block limits. can someone give me a pointer?

https://substrate.stackexchange.com/questions/11228/assettrapped-i-teleported-1499-dot-from-polkadot-to-assethub-but-it-has-not-arr

**Comment by acatangiu** [comment]
Yes, you need this, also answered on SE.
[Runtimes 1.2.0](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.0) was just released. Once upgraded on-chain, you'll have access to the `claim_assets` extrinsic.
