### ISSUE TITLE
Add Recurring Payments to the Treasury pallet

### ISSUE THREAD

**Issue by rrtti** [paritytech/polkadot-sdk#352]
Add a call that sets up in motion repeating payments following certain conditions. The treasury would keep funding it according to the budget until there was a motion to cancel it. This could potentially be used on social contract designs for maintaining services in Kusama.

The call would include:
- a Claimer address, authorized by the motion to claim the amount; 
- an amount to be paid each TimeSlot;
- a TimeSlot, defined as the block number/s in which the claimer is authorized to get the amount, 
- an ExpirationTime, defined as a block number after which the Claimer is not authorized to get the amount any longer for the period being and needs to wait to the next TimeSlot or open a new motion; 
- a TimeCap, defined as the max time the recurring payment is set up for. After this, the Council should review via a new motion. 
- a Cancellation call, defined as a motion to cancel the recurring payment.

**Comment by shawntabrizi** [comment]
Infinitely reoccurring payments do not exist, but my understanding is that with the latest `spend` logic, you could get approved for N spends, which are spaced out every M blocks, and it would basically replicate the re-occuring spend behavior for a finite timeline.

If there are any issues with the recipients of the payments, the future pre-approved spends can be canceled. 

This is all taking advantage of the `valid_from` parameter of `spend`. cc @muharem

**Comment by xlc** [comment]
It doesn't make a lot of sense of making fixed amount recurring payment of DOT due to price fluctuation.
A simple alternative is just make a big bounty, and have curator make payment periodically. It requires manual work but the DOT amount can be adjusted by conditions, which could be DOT price, KPI etc.

**Comment by joepetrowski** [comment]
We can close this, solved by https://github.com/paritytech/polkadot-sdk/pull/1333
