### ISSUE TITLE
Test P<>K bridge-init calls using chopsticks

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#3522]
We should test the bridge-init calls using chopsticks before actually executing them

Submitting the calls and checking the effects on the storage would be a first step.

With chopsticks we won't be able to run the relayer, since chopsticks doesn't come with the grandpa subscriptions and many RPCs. So as a second step it would be nice if we could take the forked chains and run them in zombienet somehow.

**Comment by serban300** [comment]
We can simulate an approved preimage in chopsticks with something like this:

```
const number = (await api.rpc.chain.getHeader()).number.toNumber()
// TODO: fill in
const extrinsic: HexString = "0x...";
const data = hexToU8a(extrinsic)
const hash = blake2AsHex(data, 256)

await api.rpc('dev_setStorage', {
    Preimage: {
      PreimageFor: [
        [
          [[hash, data.byteLength]],
          u8aToHex(compactAddLength(data))
        ]
      ],
      StatusFor: [
        [
          [hash],
          {
            Requested: {
              count: 1,
              len: data.byteLength,
            },
          },
        ],
      ],
    },
    Scheduler: {
      Agenda: [
        [
          [number + 1],
          [
            {
              call: {
                Lookup: {
                  hash: hash,
                  len: data.byteLength,
                },
              },
              origin: {
                system: 'Root'
              },
            },
          ],
        ],
      ]
    },
  });

await api.rpc('dev_newBlock', {count: 1});
```

**Comment by serban300** [comment]
Looks like there is this tool that can be used for forking-off chains: https://github.com/hack-ink/subalfred 
And here is an example on how to use it: https://github.com/hack-ink/subalfred/blob/main/example/cmd/state/src/main.rs

Trying to experiment with it a bit. The plan would be to:
- fork the chains with `chopsticks`
- execute the preimages
- fork-off the chopsticks chains with `subalfred`
- start the forked-off chains in zombienet

**Comment by xlc** [comment]
If you can list all the RPCs used by relayer, we maybe able to provide a mock implementation in Chopsticks

**Comment by serban300** [comment]
@xlc thank you, it would be great if you could provide mock implementations in chopsticks. As far as I can tell there are only 2 additional RPCs that we would need  apart from what is already available (@svyatonik please correct me if I'm wrong):
- `grandpa_subscribeJustifications`
- `state_getReadProof`

Do you think this would be doable ?

**Comment by svyatonik** [comment]
The full set of **RPC calls** we use is quite large: https://github.com/paritytech/parity-bridges-common/blob/polkadot-staging/relays/client-substrate/src/rpc.rs#L37-L170 (everything except BEEFY).

**Comment by xlc** [comment]
I think it is doable. However, Chopsticks is only a mocking client that doesn't actually finalize blocks using grandpa/beefy protocol so that it cannot provide real justifications. 

There are two possible solutions:

1. Add a new feature to specify signing keys to Chopsticks so it can generate valid justifications.
2. Modify relayer to accept mock justifications.

Let me know what do you think.

Also opened a tracking issue at Chopsticks https://github.com/AcalaNetwork/chopsticks/issues/681

**Comment by serban300** [comment]
> I think it is doable. However, Chopsticks is only a mocking client that doesn't actually finalize blocks using grandpa/beefy protocol so that it cannot provide real justifications.
> 
> There are two possible solutions:
> 
>     1. Add a new feature to specify signing keys to Chopsticks so it can generate valid justifications.
> 
>     2. Modify relayer to accept mock justifications. This will be useful to fork mainnet and run tests with it. As it is not possible to get real justifications from mainnet fork.
> 
> 
> Let me know what do you think.
> 
> Also opened a tracking issue at Chopsticks [AcalaNetwork/chopsticks#681](https://github.com/AcalaNetwork/chopsticks/issues/681)

Thanks for the answer ! Moved the discussion to https://github.com/AcalaNetwork/chopsticks/issues/681

**Comment by serban300** [comment]
Closing this issue since the Polkadot <> Kusama bridge has been initialized
