### ISSUE TITLE
`#[disable_frame_system_supertrait_check]` doesn't seem to work as expected

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#3535]
I expect to be able to write a simple pallet where the config doesn't depend on frame_system::Config like this:

```rust
#[frame_support::pallet]
pub mod pallet {
	use super::*;

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::config]
	#[pallet::disable_frame_system_supertrait_check]
	pub trait Config: 'static {}
}
```

Instead, it fails to compile

<img width="1147" alt="Screenshot 2024-03-01 at 11 28 28" src="https://github.com/paritytech/polkadot-sdk/assets/16665596/f2cba6f0-463d-4609-9f39-caac63de0a2d">

See my branch to reproduce https://github.com/liamaharon/substrate-node-template/blob/liam-disable-supertrait-issue/pallets/template/src/lib.rs

Is there something wrong with my pallet, or is this a bug with the macro?

**Comment by kianenigma** [comment]
I was initially tripped by this too, but I think it is all correct. 

My mistake was also to naively think that `frame` actually allows you to avoid `frame_system`. It does not. Having `T: frame_system::Config` is 100% mandatory. All the code generated for things like `Hooks`, `PalletInfo` and more is unavoidably reliant on the existence of `frame_system`. 

What `disable_frame_system_supertrait_check ` is to just syntactically hide this. 

For example, you can have things like: 

```
trait MyOpinionatedSystem: frame_system::Config {}
```

Or, if you tightly couple a pallet, and the other pallet is already bounded by `frame_system::Config`, you don't need to name `: frame_system::Config` again.  

Can you post this in SE as well please, if no similar previous question exists? And I will asap write https://github.com/paritytech/polkadot-sdk-docs/issues/76

**Comment by liamaharon** [comment]
OK this makes a tonne of sense, thanks! 

I've updated the documentation to address this in https://github.com/paritytech/polkadot-sdk/pull/2638. Not sure if a SE post is required if it's explained in the docs, but happy to create one if you think it would still be valuable :)

**Comment by gupnik** [comment]
We already do have a pallet in tests without `frame_system config` using that macro: https://github.com/paritytech/polkadot-sdk/blob/b0741d4f78ebc424c7544e1d2d5db7968132e577/substrate/frame/support/test/src/lib.rs#L40

It exposes a prelude and adds a few items in the config. I imagine the similar changes would help here. If so, agreed that it would be good to get the docs updated.

**Comment by liamaharon** [comment]
If this is possible, could `#[pallet::disable_frame_system_supertrait_check]` add the necessary items from config for the dev so they don't need to do it themselves? Then it should function like we initially thought?

**Comment by bkchr** [comment]
> Then it should function like we initially thought?

As you already found out, this is not the purpose of this macro. The linked "pallet" is also a test and nothing that should be repeated in the real world. FRAME expects that every runtime has the system pallet and that the config is a super trait. This is backed deeply into the entire FRAME macro machinery etc and nothing we want/can change.
