### ISSUE TITLE
Pass warp sync target block to parachain node's `SyncingEngine` during initialization

### ISSUE THREAD

**Issue by dmitry-markin** [paritytech/polkadot-sdk#3537]
Currently, warp sync target block header is passed to parachain node syncing via oneshot channel, which is later polled in `SyncingEngine`:
https://github.com/paritytech/polkadot-sdk/blob/650886683d42de45fbcb92645d988248dda6dbba/substrate/client/network/sync/src/engine.rs#L659-L667
and passed all the way down to `WarpSync`:
https://github.com/paritytech/polkadot-sdk/blob/650886683d42de45fbcb92645d988248dda6dbba/substrate/client/network/sync/src/strategy/warp.rs#L290-L301

This is cumbersome, requires checks for the correct phase of syncing, leads to bugs like https://github.com/paritytech/polkadot-sdk/issues/3496, and should be reworked to pass the target block header as a parameter during the initialization of `SyncingEngine`.

**Comment by nazar-pc** [comment]
This PR should resolve this I think: https://github.com/paritytech/polkadot-sdk/pull/5431
