### ISSUE TITLE
Can a node generate multiple session keys for different validators? 

### ISSUE THREAD

**Issue by YuXiaoCoder** [paritytech/polkadot-sdk#3538]
The problem is as the title suggests, I want to be a Validator for KSM, can anyone help me，Also, if a node can run more than one validator, what is the recommended maximum number to run?

**Comment by burdges** [comment]
https://substrate.stackexchange.com/ or the matrix channels are better forums for questions like this.  Ask there for what is currently supported, but..

Afaik, there are no carefully analyizes of the relationship between stake being honest and nodes being honest, so afaik right now nobody knows what effect one person running multiple nodes has upon network security in any blockchain project.  It's likely not good from a theory perspective, so imho it's not worth maintaining the technical capability for a node to be multiple validators.  We coud otoh permit one relay chain node coupled with collators on multiple parachains.

**Comment by YuXiaoCoder** [comment]
Thank you very much. I understand.
