### ISSUE TITLE
add a new parachain for : the proof of trust

### ISSUE THREAD

**Issue by gogo2464** [paritytech/polkadot-sdk#3548]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

I would like to create a game engine based on polkadot that alternates parachain usage for different purpose.

I need to use a proof of trust for small transaction (eg authenticated p2p like with decentralized hosting).

### Request

implementing small world routing in a new polkadot parachain https://freenetproject.org/assets/papers/lic.pdf

check out the doc here: https://freenet.org/

### Solution
create a parachain for a freent like hosting.

### Are you willing to help with this request?

Yes!

**Comment by burdges** [comment]
It's unclear what this means, small world routing typically operates without centralized entities, but blockchains exist to simulate a centralized entity.  

Anyways https://forum.polkadot.network/ or one of the matrix room sound like better venus for this conversation.

**Comment by gogo2464** [comment]
it means there is a blockchain like for each website. Hopefully, there is one blockchain for each website. no need to download the data of other website designed to be used for other peoples.

Are you present on elements?

**Comment by burdges** [comment]
Yes we're mostly all on element, but the forum is a good fit if you want to explain something.

**Comment by gogo2464** [comment]
can I get your nick on elements please? I would like to talk before sending too unclear info on the issue.

**Comment by ThemasterHaker** [comment]
hii peps

**Comment by gogo2464** [comment]
hi

**Comment by ThemasterHaker** [comment]
What ?

**Comment by gogo2464** [comment]
> It's unclear what this means, small world routing typically operates without centralized entities, but blockchains exist to simulate a centralized entity.
> 
> Anyways https://forum.polkadot.network/ or one of the matrix room sound like better venus for this conversation, since this parachains live in other repositories, not here.

freenet use blockchains. I coded contracts for. They need it. The only difference is there dev prefer to speak of p2p instead of web3 to avoid confusion.

Can we continue on elements/ discord please?

**Comment by bkchr** [comment]
@burdges said, please create a thread in the forum.
