### ISSUE TITLE
Migrate parachain swaps to Coretime + cancel auctions

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3552]
Teams bid for one para id, only to swap it later on for another one. This is not supported by Coretime, thus they will have a lease on Coretime for the "wrong" para and can not use it. To fix this, I am suggesting the following:

- [x] Register an [OnSwap handler](https://github.com/paritytech/polkadot-sdk/blob/12ce4f7d049b70918cadb658de4bbe8eb6ffc670/polkadot/runtime/common/src/paras_registrar/mod.rs#L134), which will send an XCM to the coretime chain informing it about the swap.
- [x] Implement a swap extrinsic on the Coretime chain to do the swap, as requested by the relay chain.
- [x] Cancel auctions on runtime upgrade, should be [this call](https://github.com/paritytech/polkadot-sdk/blob/bb8ddc46c1e3dcc6f30340b39c1fdb2d07472041/polkadot/runtime/common/src/auctions.rs#L302).
- [x] Test on Zombienet
- [ ] Register functionality on Polkadot

**Comment by bkchr** [comment]
And then for how long will we keep this functionality around? 

If we inform teams early that they need to swap before the upgrade, what would be the issue? I mean if the lease would not have started, we already refund it. This means that we only speak about leases that are already started, so teams could directly switch. Thus, I don't see any reason why we should implement this `OnSwap` stuff.

**Comment by eskimor** [comment]
> And then for how long will we keep this functionality around?

Worst case as long as there are leases.

> If we inform teams early that they need to swap before the upgrade, what would be the issue? I mean if the lease would not have started, we already refund it. This means that we only speak about leases that are already started, so teams could directly switch. Thus, I don't see any reason why we should implement this OnSwap stuff.

The leases might have started already ... although this means, if they perfectly time it they could do the swap before the migration. 😬  For swaps that only become relevant later, you are right the to be swapped para will be refunded.

So in total, people have to fear the migration less: It can not happen that you missed the coretime launch and suddenly your planned swap no longer works. Given the simplicity of making this friction free, I don't see why we would not want to do this. Developer Experience is priority.

**Comment by bkchr** [comment]
Because we add useless code that at some point we need to remove again. We are adding code that increases the likelihood of adding bugs etc. While we could just inform the less than 10 teams to do the swap before the upgrade. Coordinating this takes for sure less time than writing all this code etc.

**Comment by eskimor** [comment]
The code is already written and is trivial and we have to remove quite a lot of code anyways once leases expired. If automation is that easy, I would always go for automation - it is less error prone. Coordinating those teams is definitely more likely to fail, then this simple piece of code - also it is just a better experience, if things just work.

I really want to provide as smooth of an experience as possible. Don't break things, if there is no need. The Coretime upgrade in itself is disruptive enough. Teams are already worried a lot.

**Comment by tdimitrov** [comment]
Reopening because it's still not enabled on Polkadot

**Comment by eskimor** [comment]
Added to Polkadot runtime.
