### ISSUE TITLE
Why is `ExtendedPeerInfo` private in `release-polkadot-v1.6.0`?

### ISSUE THREAD

**Issue by Ali-Usama** [paritytech/polkadot-sdk#3556]
I was working on a custom consensus mechanism for Substrate on branch `release-polkadot-v1.2.0`, but there was a conflict with some of the dependencies due to which I had to upgrade it to the `release-polkadot-v1.6.0`, and I noticed that [ExtendPeerInfo](https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.2.0/substrate/client/network/common/src/sync.rs#L52) was moved from `sc-network-common` to `sc-network-sync` in [this](https://github.com/paritytech/polkadot-sdk/pull/1912) PR. 

The issue that I'm facing is the `ExtendedPeerInfo` struct is now under the [`types`](https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.6.0/substrate/client/network/sync/src/lib.rs#L31) module which is private so I can't access its components. 

I wanted to ask if this was intentional and if there's any other way to access that struct?

**Comment by altonen** [comment]
The idea is to get rid of `sc-network-common` because it doesn't serve a purpose anymore and if `sc-network-sync` is the only crate that use `ExtendedPeerInfo`, then that's the right place. 

This could have been a simple oversight during refactoring but is there a particular reason you need access to `ExtendedPeerInfo`?

cc @dmitry-markin

**Comment by Ali-Usama** [comment]
> This could have been a simple oversight during refactoring but is there a particular reason you need access to `ExtendedPeerInfo`?

Yes, I was using it to get a list of connected peers in `release-polkadot-v1.2.0` but it's not accessible in `release-polkadot-v1.6.0`. If it's a simple oversight, are there any plans to get it fixed soon enough?

**Comment by altonen** [comment]
Do you want to open a PR, making `types` public? Otherwise I'll try and fix it at some point this week

**Comment by bkchr** [comment]
Can you not just copy this type? Is this type somewhere returned by a function?

**Comment by Ali-Usama** [comment]
> Can you not just copy this type? Is this type somewhere returned by a function?

I can't copy it because I'm using [this](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/network/sync/src/service/syncing_service.rs#L59) `PeerInfo` command which expects the `ExtendedPeerInfo` to be coming from `sc-network-sync` instead of my local copy. 

```
 if response.send(self.handler.peers_info()).is_err() {
    |                             ---- ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `sc_network_sync::types::ExtendedPeerInfo<B>`, found `ExtendedPeerInfo<B>`
    |                             |
    |                             arguments to this method are incorrect
```
