### ISSUE TITLE
Bump backing timeout to 2.5s

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3565]
With asynchronous backing it is expected for PoVs to take up to 2 seconds in execution. The backing timeout, which is a hard timeout is currently set to exactly those 2s. Even if in memory validation is faster than block production, this seems too tight to be practical. To ensure good performance with 2s blocks, we should be more lenient with the backing timeout.

- [ ] Bump backing timeout to 2.5s
- [ ] Bump approval checking execution timeout to 15s (12s + 3s)
- [x] Bump no-show timeout to 18s (15s worst case execution + 3s availability fetching) - already the case
- [x] Bumps should not do any harm to chains which are still on synchronous backing 

# Rollout

We should bump the approval and no-show timeout first, then once enough validators have upgraded, backing timeout comes next.

**Comment by eskimor** [comment]
Status on this one?

**Comment by ordian** [comment]
In the works, hope to publish something next week.

**Comment by ordian** [comment]
After looking at the code again, it seems that no code changes are required.
`no_show_duration` is [computed](https://github.com/paritytech/polkadot-sdk/blob/d0ebb850ed2cefeb3e4ef8b8e0a16eb7fb6b3f3e/polkadot/node/core/approval-voting/src/import.rs#L466) based on the config param `no_show_slots`, which is currently set to 3 on Polkadot and Kusama
<details>
<img width="867" alt="Screenshot 2024-04-02 at 11 12 35" src="https://github.com/paritytech/polkadot-sdk/assets/4211399/5b2bf726-178c-4cc5-b095-5dedceda9aef">
<img width="867" alt="Screenshot 2024-04-02 at 11 11 44" src="https://github.com/paritytech/polkadot-sdk/assets/4211399/801a6de4-b49f-4015-a8fd-3e1cc67c2a75">
</details>
This translates to 6 * 3 = 18s no-show timeout.

Backing and approval voting timeouts are now configured via runtime (ExecutorParams). I'll prepare a motion for Kusama and then Polkadot to set both in one go.
