### ISSUE TITLE
subsystem-bench: Remove `benchmark_name` from `BenchmarkUsage`

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#3601]
Since we print regression test results manually every time, we don't need to use `benchmark_name` inside `BenchmarkUsage`. We can just put the name inside `println!`.
https://github.com/paritytech/polkadot-sdk/blob/475e7a147676a4e7a9d255ddc7969dd35ea22882/polkadot/node/subsystem-bench/src/lib/usage.rs#L24-L28

**Comment by olaitanade** [comment]
Hi @AndreiEres, I'd like to work on this issue. Can you assign to me? Thanks.

**Comment by AndreiEres** [comment]
@olaitanade Sure, looking forward to your PR!
