### ISSUE TITLE
Incorrect core mask on coretime-rococo

### ISSUE THREAD

**Issue by Szegoo** [paritytech/polkadot-sdk#3614]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When querying the regions from the Rococo Coretime chain I noticed that four regions have the core mask of 'UUUUUUUUUU', which is not a valid value, as core masks are represented in hex.

### Steps to reproduce

The RegionId of one such region:
```
{
      begin: 117,870
      core: 64
      mask: UUUUUUUUUU
}
```

Can be checked with PJS.

![Screenshot 2024-03-07 at 7 10 53 PM](https://github.com/paritytech/polkadot-sdk/assets/73715684/603c9ac9-9514-40c5-9ecc-2272356f61c5)

**Comment by bkchr** [comment]
CC @seadanda

**Comment by ggwpez** [comment]
Did you try querying raw storage? Unicode `UUUUUUUUUU` is exactly an 50% interlaced 80bit mask of `b01010101010101010101010101010101010101010101010101010101010101010101010101010101`.  
Maybe PJS is being stupid and just tries to decode as UTF8 first.
