### ISSUE TITLE
create multiple different multisigs from same set of signatories & threshold

### ISSUE THREAD

**Issue by chungquantin** [paritytech/polkadot-sdk#3618]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

My team stores fund on multisigs on Polkadot and use this feature frequently. And I notice there is an odd design in the deterministic multisig private key generation. Because the generated key is deterministic and is a computation outcome of the provided signatories and threshold, one set of signatories and theshold could not own more than one multisigs due to the mentioned mechanism. 

### Request

I have not read the source code of the multisig pallet thoroughly to understand if there is any reason behinds that deterministic private key. What I recommend is every multisig private key generated by the same set could be different.

### Solution

Let's say the current logic is: 
```
P_multisig = P(Sig_A) + P(Sig_B) + ... + P(Sig_N) + threshold
```
And I think it is possible by just adding an extra incremental ID to the generation method: 
```
P_multisig = P(Sig_A) + P(Sig_B) + ... + P(Sig_N) + threshold + ID
```
Correct me if this feature request does not make sense. Hope some experts can help to resolve my request. Thanks!

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
We can not add a function for every possible combination of things that exist. In your case you just need to write one helper function on the application layer to achieve what you want by combining these two pallets. I don't see any reason for creating a dedicated function for this that will then do the same, but just on the "backend" layer.

**Comment by chungquantin** [comment]
@bkchr Yes I understand this can be solved on the application layer, but as I have reviewed other protocols and participated into designing the multisig functionalities before, I find it is a bit odd to only generate one multisig key with the same set of signatories and threshold. And imagine if every application built on top of the multisig pallet have to reimplement the feature themself. 

Because this is not something major and a tune that makes this pallet DevEx better, I think it is not a bad idea to consider an option.

**Comment by bkchr** [comment]
I mean not everyone needs to reimplement this. Someone could build one library that abstracts over this and you get the same results.
