### ISSUE TITLE
Sanity check consistency of public APIs (best effort)

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#362]
We should best effort try and patch any inconsistencies of the Substrate public api. This includes, but is not limited to:

* Function Names
* Function Parameters and order
* Variable Names
* Structure and Custom Type names
* Event Names and parameters
* Error Names
* etc...

To be more explicit, we should avoid situations where two different traits expose functions with different names when their behavior is the same. i.e. one trait has `remove_account` and the other has `delete_account`.

We should avoid situations where the same variable is referenced with different variable names. For example `caller` vs `sender` in a public API.

We should make sure that the order of items in events are logical. i.e. we want to avoid:

* `UsersBecameFriends(BlockNumber, User1, User2)`

* `UsersAreNotFriendsAnymore(User1, User2, BlockNumber)`

This task is truly endless and I imagine will be full of opinions, so it is important to note that this is **best effort**.

Let's just fix up what we can.

**Comment by JoshOrndorff** [comment]
For some reason I got notified about this today. Is it still actionable? I'm comfortable closing this and letting new issues arise in more relevant context instead.

**Comment by ggwpez** [comment]
We moved all issues - sorry for the deluge of notifications @JoshOrndorff.  

But i am also in favour of closing it. Shawn if you have concrete examples of this, then please re-open.
