### ISSUE TITLE
[NFTs] Some types are made private but it shouldn't

### ISSUE THREAD

**Issue by SailorSnoW** [paritytech/polkadot-sdk#3631]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We are developing precompiles for the NFTs pallet and we need to call `pay_tips` dispatchable.
It require us to pass some `ItemTip` objects, but we cannot deal with the type `ItemTip` as struct properties are made public only for the pallet_nfts crate with `pub(super)`.

Is it a voluntary design choice and so can we have an explanation on this ?

Previous types was fine, public visibility was not only for the crate.

### Steps to reproduce

Try to create the type in an external crate:

`pallet_nfts::ItemTip<CollectionId, ItemId, AccountId, Balance> { collection: Default::default(), ... }`

giving error:
`error: cannot construct `pallet_nfts::ItemTip<CollectionId, ItemId, AccountId, Balance>` with struct literal syntax due to private fields`

**Comment by ggwpez** [comment]
Yes looks odd. Could you maybe open a Merge Request to fix it?  
Could be that there are more types suffering from this issue.
