### ISSUE TITLE
[Westend] Ensure staking election works in absence of a signed solution

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#3671]
Same as https://github.com/paritytech/polkadot/issues/7193, reopening in light of https://github.com/paritytech/polkadot-sdk/pull/3646.

Merklized metadata RFC: https://github.com/polkadot-fellows/RFCs/pull/78

Can we setup OCW that it does not submit solution every once a while?

**Comment by kianenigma** [comment]
I am still in favor of removing this constant from the metadata and removing the parent PR. Based on what I read, it is not used int the metadata.

**Comment by bkchr** [comment]
Removed the constants.
