### ISSUE TITLE
Make polkadot behave correctly if node changes peer-id at restart

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#3673]
During the investigation for https://github.com/paritytech/polkadot-sdk/issues/3314 we discovered there is a number of validators that change their PeerId at every restart, that seems not work properly right now. 

## Work-arrounds

1. Don't change PeerId at every restart, the peer-id is saved on disk next to the databse in the `network` folder, so you can simply reuse that by always providing `--base-path` argument and making sure the network folder is present where you restart the node.
2. If you restarted already, key rotations would fix the issue.

## [WIP] Things that need fixing

In general all the assumptions where we think we have just one PeerID per AuthorithyId are breaking this on a quick scan by me and @bkchr:

With kusama size nodes won't be able to connect to nodes if they aren't in the reserved set.
https://github.com/paritytech/polkadot-sdk/blob/809d46657f588ff938ca2e9fa1208e7ff21f33fe/polkadot/node/network/protocol/src/peer_set.rs#L95-L96

Some places where the assumption that just one peerID per authority exist.

https://github.com/paritytech/polkadot-sdk/blob/809d46657f588ff938ca2e9fa1208e7ff21f33fe/polkadot/node/network/gossip-support/src/lib.rs#L408

https://github.com/paritytech/polkadot-sdk/blob/a756baf3b211efc57ca4a0089b7ceba4c20b9f12/polkadot/node/network/statement-distribution/src/v2/mod.rs#L451

Another thing that I observed that is probably off while testing on versi is that `ConnectToResolvedValidators` gets called sometime with the new address and sometimes with old-address.

**Comment by bkchr** [comment]
The first link is not really a problem. Just more the explanation why these people could not connect to all the other validators.

https://github.com/paritytech/polkadot-sdk/blob/809d46657f588ff938ca2e9fa1208e7ff21f33fe/polkadot/node/network/gossip-support/src/lib.rs#L327-L352

This function needs to be called multiple times per session. Currently we don't call this once and if a validator address was not known at this point, we will never resolve it in this session.

**Comment by alexggh** [comment]
> The first link is not really a problem

Messed up the links, fixed it in the description.

**Comment by alexggh** [comment]
Looked a bit more closer at `Kademlia` DHT and the biggest problem for this use-case seem to be is that both records will continue living in the DHT on different nodes, so on any given node any of the following might be true:

1.  When querying the DHT a node discovers only the old record.
2. When querying the DHT a node discovers only the new record.
3. When querying the DHT a node discovers both the new record and the old record, but because they are sequentially advertised to authority-discovery only the last one will be saved. We can probably mitigate this, by modifying authorithy-discovery to save both of them and expire the old-record at a later data.


Both 1) & 3) will happen until the old record TTL is met which currently is 36 hours, after that the new record will be the only one in the network.

## Why does this happen

The way `Kademlia` DHT works is that it uses the PeerId as a key for determining on which nodes records need to be replicated the receiving  nodes will do replication as well every 60 minutes. The replication factor is 20.
So, regularly both the old records and new records will continue living in the network on different nodes until the old one expires.

## What can we do ?

At least as far as I can tell this behaviour is entrenched in the `Kademlia` DHT protocol, we can probably reduce the window the old entry lives by playing with record_ttl(36h), record_replication_interval(1),  record_publication_interval(24h), but there will still be a window where this happens. 

So, I'm inclined to think changing the network key(PeerID) while a node is in the active set should not be considered a safe operation, to perform, hence what I'm proposing is:
 - Modify the behaviour of polkadot executable to not auto-generated the network key(PeerID) if none is provided and exit with error (Kudos to @s0me0ne-unkn0wn for giving me the idea)
 - Add an explicit flag for auto-generating the network key at startup with proper documentation that this is not a safe operation to do while the node is in the active set and what will happen.
 
 @bkchr @dmitry-markin @eskimor Thoughts ?

**Comment by bkchr** [comment]
Here are my notes from last week that I wanted to put into an issue actually:

>  I think one problem exists in authority discovery: https://github.com/paritytech/polkadot-sdk/blob/a6713c55fd5082d333518c3ca13f2a4294726fcc/substrate/client/authority-discovery/src/worker/addr_cache.rs#L77-L86 and https://github.com/paritytech/polkadot-sdk/blob/a6713c55fd5082d333518c3ca13f2a4294726fcc/substrate/client/authority-discovery/src/worker.rs#L571-L572.
	 If the validator exists with multiple peerids in the DHT (because of the restart), we maybe get multiple DHT events with different peerids. We should keep different peerids around. Maybe store when we received them the last time. We also should not take the maximum number of addresses solely based on the addresses, we should have addresses per `peer_id` and then have a max number of `peer_ids` and `addresses`.

> 	 https://github.com/paritytech/polkadot-sdk/blob/a6713c55fd5082d333518c3ca13f2a4294726fcc/substrate/client/network/src/discovery.rs#L784-L790 Another issue is this properly. Here we should not end directly with quorum of 1. Instead we should probably fetch all the values.

This assumes the same as you are writing. However, I would like to try to optimize the current implementation given the points above. We can also go further and extend the record with a timestamp to find out which one is newer. We also don't verify the data in the DHT storage. The verification is only done in the authority discovery. This means that the DHT may could still contain invalid values.



> * Modify the behaviour of polkadot executable to not auto-generated the network key(PeerID) if none is provided and exit with error

Could be done as well, but should only be done for validators. Generally we probably need to improve docs around this stuff. There also exists `generate-node-key` to generate a key. Maybe we should just require that `--node-key` is passed when `--validator` is set.

**Comment by alexggh** [comment]
> Another issue is this properly. Here we should not end directly with quorum of 1. Instead we should probably fetch all the values.

Ok, I see what you mean, so basically if we let the query continue we could probably end up discovering both more often than not and have them both stored in authorithy-discovery.  Let me check how that behaves.

**Comment by alexggh** [comment]
Posted a draft PR with all the plumbing that would need to happen to make this a bit better than the way it currently is: https://github.com/paritytech/polkadot-sdk/pull/3786, let me know what you guys think, don't be nitpicky it is in a very rough form :D.

**Comment by dmitry-markin** [comment]
> So, I'm inclined to think changing the network key(PeerID) while a node is in the active set should not be considered a safe operation, to perform, hence what I'm proposing is:

I don't understand why people regenerate the PeerIDs of validators in the first place. Obviously, a validator should have the actual database, so the contents of `--base-path` should be preserved across restarts. Why they remove the network key file then?

Generally I'm for not-regenerating PeerIDs of the validators without a sound reason (is there one?)

> Modify the behaviour of polkadot executable to not auto-generated the network key(PeerID) if none is provided and exit with error (Kudos to @s0me0ne-unkn0wn for giving me the idea)

May be make this default for validators only? This would change the interface and force operators to update their procedures, but we can print a nice error message if somebody starts a validator without network key file present.

> Add an explicit flag for auto-generating the network key at startup with proper documentation that this is not a safe operation to do while the node is in the active set and what will happen.

IMO, this should be an explicit cli command like `generate-network-key` that has to be invoked separately, otherwise the operators would just plug this `--auto-generate-network-key` option and keep everything as before.

**Comment by lexnv** [comment]
Likewise, we could fix this in the CLI and require validators to use `--node-key` with some improved documentation.

> We can also go further and extend the record with a timestamp to find out which one is newer. We also don't verify the data in the DHT storage.  

I think this sounds like a reasonable solution to me. We'd need to extend the `DHT::ValueFound` event with the kademlia record expiry time:

https://github.com/paritytech/polkadot-sdk/blob/e88d1cb79315792a3dbccb6bdef2543093ecaf5b/substrate/client/network/src/discovery.rs#L475-L478

Then, in the authority-discovery, we could store only the most recent records, since we know that older records might contain stale addresses. While at it, we could also have a look at the `MAX_ADDRESSES_PER_AUTHORITY` and adjust it as Basti suggested 🙏

**Comment by alexggh** [comment]
> I think this sounds like a reasonable solution to me. We'd need to extend the DHT::ValueFound event with the kademlia record expiry time:

I've been down that road, it won't work because expiry is actually a function of the distance from the key to the node answering the request: https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L1816.  Expiry doesn't tell how old the record is because if you get it from nodes farther from the key they would have a close expiry they should not store the record for too much time.

**Comment by alexggh** [comment]
> I don't understand why people regenerate the PeerIDs of validators in the first place. Obviously, a validator should have the actual database, so the contents of --base-path should be preserved across restarts. Why they remove the network key file then?

In this case a large validator set >50, were mount individually the keystore and db in their pod, so they missed persisting the network:
```
.local/share/polkadot/chains/ksmcc3/db
.local/share/polkadot/chains/ksmcc3/keystore
```

**Comment by alexggh** [comment]
> IMO, this should be an explicit cli command like generate-node-key that has to be invoked separately, otherwise the operators would just plug this --auto-generate-node-key option and keep everything as before.

I was thinking to name it more like --i-know-i-m-getting-0-rewards-but-auto-generate-node-key :D

**Comment by alexggh** [comment]
PR to not allow auto generate of network key unless it is explicitly required: https://github.com/paritytech/polkadot-sdk/pull/3852.

**Comment by alexggh** [comment]
Problem mitigated with: https://github.com/paritytech/polkadot-sdk/commit/6720279fb3aac12ad525785d2366cdf30da4d78c
