### ISSUE TITLE
Remove AvailabilityBitfieldsStorage

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#3675]
[This storage](https://github.com/paritytech/polkadot-sdk/blob/2431001ec012334226bc181d69a754c49f168328/polkadot/runtime/parachains/src/inclusion/mod.rs#L367) seems to be only ever written to, never read. We should kill it.

- [ ] Remove code
- [ ] Write migration killing the storage

**Comment by burdges** [comment]
We write directly into the transposed core bitfields prumably.

**Comment by alindima** [comment]
Good catch!

> We write directly into the transposed core bitfields prumably, which makes sense.

correct. we directly track the availability bits on the pending candidate storage
