### ISSUE TITLE
Generate `StorageValue` key at compile time

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#372]
For `StorageValue` we can hash the key at compile time and can omit this at runtime.

**Comment by kianenigma** [comment]
Closed in the above PR.

**Comment by liamaharon** [comment]
@kianenigma did it really close it? This issue seems to ask for generalised compile time computation, where the above PR seemed to only do it for pallet storage key prefix

**Comment by bkchr** [comment]
The pr is doing it for the pallet and storage key prefix. I think this is what I wanted in 2019 :P
