### ISSUE TITLE
[FRAME] `RemoteExternalities` should only require `Hasher`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3737]
`RemoteExternalities`, `OnlineConfig` and `Mode` (maybe more) types in `frame-remote-externalities` require `Block` while only using its Hasher 🙄  This makes it more difficult to use and is entirely unnecessary. Should be refactored to only require `Hasher`/`HashOutput` where needed.

The only spot where we currently still need a `Header`, is on the `Builder` to access the `ChainApi`. IMHO this could be changed as well, since just loading the latest block hash should not require a header type, but it is outside of the scope for this issue.

(This issue does require some Rust knowledge about how trait bounds work)

**Comment by lean-apple** [comment]
May I work on this ?

**Comment by ggwpez** [comment]
> May I work on this ?

Sure 👍
