### ISSUE TITLE
statement-distribution high cpu usage 

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#3744]
This looks like a bug, the nodes aren't even in active set and still we see this usage pattern:

<img width="855" alt="Screenshot 2024-03-19 at 14 23 41" src="https://github.com/paritytech/polkadot-sdk/assets/54316454/3fee6f9d-abd9-46f5-8bac-213438f369b6">

https://grafana.teleport.parity.io/goto/UfZem2JIR?orgId=1

**Comment by alexggh** [comment]
Interestingly enough after nodes have been restarted for upgrading to 1.9.0, statement-distribution looks unused.

<img width="2530" alt="Screenshot 2024-03-20 at 15 05 52" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/da68e9d3-b8ad-40d5-866c-815773e12dea">

This feels like a small leak, unfortunately we don't have metrics going back, I'll keep on eye on the metric over-time to confirm it.

**Comment by alexggh** [comment]
This seems to have happened again on one of our kusama validators after a few weeks

<img width="2534" alt="Screenshot 2024-04-18 at 12 57 27" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/86153a8f-66d6-4865-8e43-14742046c53a">

I don't think it is a leak, looking at this dashboards it seems like we are doing a lot of polling somewhere, notice how the average poll time actually goes down and the number of them increases.

<img width="2541" alt="Screenshot 2024-04-18 at 13 02 05" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/1ece2296-c180-4fbc-ac81-8468d8f48bf0">

<img width="2541" alt="Screenshot 2024-04-18 at 13 03 01" src="https://github.com/paritytech/polkadot-sdk/assets/49718502/32b77c52-959c-4b07-b1f3-b6704d1a77de">


I suspect something is off with this `next_retry` and wakesup very often https://github.com/paritytech/polkadot-sdk/blob/76719da221d33117aadf6b7b9cc74e4fbeb25b34/polkadot/node/network/statement-distribution/src/lib.rs#L130, 
although I don't have the data to back it up nor did I found any logic error that might get us into this state.

**Comment by alexggh** [comment]
And the fix: https://github.com/paritytech/polkadot-sdk/pull/4192/files

**Comment by sandreim** [comment]
Fixed by https://github.com/paritytech/polkadot-sdk/pull/4192
