### ISSUE TITLE
bench syntax v2: run test in single functions

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#376]
The v2 benchmark tests are running in one single function instead of one function per bench case.  

Current output:
```pre
test benchmark_tests::test_benchmarks ... ok
```

Output that we want:
```pre
test benchmarking::bench_sort_vector ... ok
test benchmarking::bench_accumulate_dummy ... ok
test benchmarking::bench_set_dummy_benchmark ... ok
```

It is probably using this wrong expansion arm here:  
https://github.com/paritytech/substrate/blob/2e535bac47f48d816f94b105715e09dc57ed52b0/frame/benchmarking/src/v1.rs#L541

instead of:  
https://github.com/paritytech/substrate/blob/2e535bac47f48d816f94b105715e09dc57ed52b0/frame/benchmarking/src/v1.rs#L508

**Comment by JuaniRios** [comment]
Would like to have this as well in our codebase at Polimec

**Comment by sam0x17** [comment]
This will most likely be a top priority for me once #1343 is done

**Comment by pandres95** [comment]
@ggwpez I already started solving this issue.

**Comment by pandres95** [comment]
@ggwpez PR's ready for review.
