### ISSUE TITLE
XCM builder pattern safe should allow clear_origin before buy execution

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#3770]
The [XCM builder pattern](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/procedural/src/builder_pattern.rs) provides builders for making XCM messages:
- builder
- builder_unpaid
- builder_unsafe

These builders just restrict the instructions you can use at the start, they force some instructions before others.
The first is meant to be used by regular extrinsics and rust clients.
The second is meant to be used by system functions.
The third is meant to be used for tests, teaching, tinkering and sometimes when the others do not allow you to do what you need.
I found a case of this that should be easy to solve.

Right now we can't do the following:
```rust
Xcm::<()>::builder()
  .reserve_asset_deposited(..)
  .clear_origin(..) // <- This is the problem
  .buy_execution(..)
  .deposit_asset(..)
  .build();
```
We need to use the `builder_unsafe` variant for it to work.

It is a perfectly safe idea to allow at least one `clear_origin` between an instruction that loads the holding register and one that pays for fees.
The solution is to implement the `clear_origin` method in the type `XcmBuilder<Call, LoadedHolding>` in `polkadot/xcm/procedural`.

**Comment by orgr** [comment]
Hi @franciscoaguirre, I just opened a PR
I'd be happy for any feedback, thanks
