### ISSUE TITLE
[FRAME] Pallet storage items should be public

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3787]
Since we are removing getters, it would be useful to make the storage items of all pallets public.  
Otherwise it is not easily possible to test stuff where accessing another pallets' storage would be useful.

I guess we could issue a warning on private storage items, but maybe that is too opinionated for everyone.

**Comment by liamaharon** [comment]
Good pick up, yeah I can't think of a good reason for storage to ever be private/inaccessible.

**Comment by gupnik** [comment]
There might be a few instances where we want to restrict direct access to the underlying storage and instead only allow the public APIs to modify it. For example, something like `bags-list` should only be modified via these APIs to ensure that the linked storage items stay in sync.

One of the motivations for pallet splitting work was to make this encapsulation better, but making these public by default would take us even farther. 

Can we only these public for tests if that's the primary reason here?

**Comment by ggwpez** [comment]
>Can we only make these public for tests if that's the primary reason here?

Tests and benchmarks, yes. I guess we could just modify the visibility for those features?

**Comment by rainbow-promise** [comment]
Hello @ggwpez is there an instance of this?

**Comment by ggwpez** [comment]
I think we went with just making all storage items pub, no need to shield them.  
Most MRs that did this also removed the getters, should be worthwhile to do both at once: https://github.com/paritytech/polkadot-sdk/issues/3326

**Comment by ggwpez** [comment]
Actually going to close in favour of https://github.com/paritytech/polkadot-sdk/issues/3326
