### ISSUE TITLE
Generalize node test helpers

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#38]
Stuff like `wait_n_finalized_blocks` is now part of Substrate, Polkadot and Cumulus, always in a slight variation.  
Other candidates are `wait_n_finalized_blocks_from`, `wait_n_finalized_blocks` or `find_ws_url_from_output`, that seem useful in multiple projects.  

We could probably generalize the implementations to be more maintainable instead of copy & pasting it.

**Comment by 0xmovses** [comment]
Picking this up.

**Comment by 0xmovses** [comment]
`wait_n_finalized_blocks_from` doesn't seem to exist in the monorepo. Seems like this refactor has already been done. `wait_n_finalized_blocks_from`, seems useful as a standalone function.
