### ISSUE TITLE
[FRAME] Remove deprecated calls from treasury pallet

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#3800]
As part of the deprecation process https://github.com/paritytech/polkadot-sdk/issues/138 the next call needs to be removed:
- pallet_treasury.propose_spend
- pallet_treasury.reject_proposal
- pallet_treasury.approve_proposal

Scope: 
- remove deprecated calls;
- set explicit coded indexes for `Error` and `Event` enums, remove unused variants and keep the same indexes for the rest; 
- remove unused `Config`'s type parameters;
- remove irrelevant tests and adopt relevant using old api;
- remove banchmarks for removed calls;

mentor: @muharem

**Comment by chungquantin** [comment]
Hi, I am keen on working on this issue

**Comment by chungquantin** [comment]
@muharem I have created a PR for this issue. Could you please help me to review? There is only only task I am not sure. 
> set explicit coded indexes for Error and Event enums, remove unused variants and keep the same indexes for the rest;
I am trying to find an example of other people works for explicit coded indexes used in this codebase but could not find one. Could you suggest me an approach for this?

**Comment by muharem** [comment]
@chungquantin just commented, let me know if something not clear yet

**Comment by shawntabrizi** [comment]
I would like to also include these changes into any new release of the treasury pallet: https://github.com/paritytech/polkadot-sdk/pull/3970/files

So that we have only one set of breaking changes to the treasury pallet.
