### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by kuchta** [paritytech/polkadot-sdk#3832]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

I can't follow news for https://polkadot.network/blog

### Request

Implement RSS support for the blog

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by bkchr** [comment]
Wrong repo. 

https://polkadot.network/contact/ maybe you find here someone to contact.
