### ISSUE TITLE
Mark `Currency` `#[deprecated]`

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#3836]
No, I mean actually adding a `#[deprecated]` to `trait Currency`.

_Originally posted by @kianenigma in https://github.com/paritytech/polkadot-sdk/pull/2802#discussion_r1537805153_

**Comment by xlc** [comment]
any particular reason to force everyone switch off Currency trait if it has been worked perfectly fine?

**Comment by liamaharon** [comment]
This won't force anyone to stop using it, legacy codebases will be able to continue using `Currency` with `#[allow(deprecated)]`. 

This is just to warn devs that the traits will no longer be maintained, and `fungible` should be preferred when writing new token related logic.

**Comment by xlc** [comment]
A trait doesn't really need maintenance? And deprecation usually means it will be removed in future.
I don't really want to migrate existing code that uses Currency trait perfectly fine to use the new fungible. It takes time and may need to be re-audited and for pretty much no benefits.

**Comment by asiniscalchi** [comment]
It seems that employing an Adapter might be a strategic approach to circumvent the need for recoding preexisting code. 

This method would enable to bridge the gap between the current `Currency` implementations and the new `fungible` interface, allowing for a smoother transition with minimal disruption to existing systems.

**Comment by asiniscalchi** [comment]
Maybe an Adapter Pattern might help:
`type Currency = CurrencyAdapter<Fungible>`
