### ISSUE TITLE
CI not running all subsystem tests

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#3884]
Uncovered this while working on https://github.com/paritytech/polkadot-sdk/pull/3879 that touches collation-generation. As it can be seen on that PR all CI tests are passing, but when I run locally with cargo test, they fail.

I believe some recent changes in this area might be the culprit: https://github.com/paritytech/polkadot-sdk/blob/master/.gitlab/pipeline/test.yml#L28

I have fixed the failing tests in https://github.com/paritytech/polkadot-sdk/pull/3883

Ouput of running `collation-generation` tests on master via `cargo test --profile=release -p polkadot-node-collation-generation`

```
failures:
    tests::distribute_collation_for_free_cores_with_async_backing_enabled_and_elastic_scaling::case_1
    tests::distribute_collation_for_free_cores_with_async_backing_enabled_and_elastic_scaling::case_2
    tests::distribute_collation_for_free_cores_with_async_backing_enabled_and_elastic_scaling::case_3
    tests::distribute_collation_for_occupied_core_with_async_backing_enabled::case_1
    tests::distribute_collation_for_occupied_core_with_async_backing_enabled::case_2
    tests::distribute_collation_for_occupied_cores_with_async_backing_enabled_and_elastic_scaling::case_1
    tests::distribute_collation_for_occupied_cores_with_async_backing_enabled_and_elastic_scaling::case_2
    tests::distribute_collation_for_occupied_cores_with_async_backing_enabled_and_elastic_scaling::case_3
    tests::no_collation_is_distributed_for_occupied_core_with_async_backing_disabled::case_1
    tests::no_collation_is_distributed_for_occupied_core_with_async_backing_disabled::case_2

test result: FAILED. 10 passed; 10 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

🙈

**Comment by ordian** [comment]
do we want to run tests with and w/o `elastic-scaling-experimental` feature?

**Comment by sandreim** [comment]
I think it makes sense to do so.

**Comment by ggwpez** [comment]
There was a similar report here, not sure if related: https://github.com/paritytech/polkadot-sdk/issues/3845
