### ISSUE TITLE
Cleanup `String::from_utf8` usage in the pallet benchmarking

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#389]
👉 Good issue for newcomers (please dont pick up when you already have experience).

The state machine that is used in the `benchmark pallet` command returns a `[u8]` instead of a string.  
This slice is then stored and converted to a string *every time* its needed somewhere.  
It would be nice to instead directly convert it and then store the string. This would get rid of a many `String::from_utf8(…).expect("Encoded from String; qed")`.

**Comment by philoniare** [comment]
@ggwpez can I take this on?

**Comment by ggwpez** [comment]
Yes! Note that we cannot entirely use `String`, since it get passed through the WASM-Host barrier and that only allows `Vec<u8>` so it can only be converted after being in the std code.

**Comment by philoniare** [comment]
Got it, appreciate the tip, will keep it in mind
