### ISSUE TITLE
Allow Nomination pool configuration changes with StakingAdmin.

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#3894]
`set_config` should be set by StakingAdmin instead of root.

**Comment by iMac7** [comment]
Hi @Ank4n 
I'm a newcomer to this repo, not as new to the polkadot ecosystem. I like to pick up issues to give me a starting point to look around, this one looks promising :) 

Just a few noob questions (to you or assigned mentor).
Is this done in `/substrate` (pallet issue) or `/polkadot` or other folder? 
Where can I find the nomination pool config?
How would I test this locally? Assume I have cloned the repo and installed all dependencies. Nothing more satisfying that running a tiny blockchain on my pc  :smile:

**Comment by Ank4n** [comment]
Hey @iMac7 thanks for your interest. Sorry I have already worked on it so this is unfortunately not up for mentor. But I hope you find another good first issue.
