### ISSUE TITLE
Migration issues with async backing turned on

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#3932]
Because async backing will make the parachain's out-of-block time become 6s, which will break the time-related code. For example pallet-vesting. or other custom pallets.
I wonder if there will be a unified migration solution? Or is it only possible to manually store migrations one by one.

**Comment by bkchr** [comment]
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/3268
