### ISSUE TITLE
[pallet-balances] burn extrinsic

### ISSUE THREAD

**Issue by Dinonard** [paritytech/polkadot-sdk#3943]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

On Ethereum we have `0x0000000000000000000000000000000000000000` designated address for _burning_ ETH.

To my knowledge, there's no similar thing provided by the _polkadot-sdk_.

### Request

Add a new extrinsic call (or two) to the `pallet-balances`, similar to `transfer_allow_death/keep_alive` calls, which would burn the user specified amount.

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
Sounds reasonable to me! Feel free to open a pr.

**Comment by Dinonard** [comment]
Here's the PR: https://github.com/paritytech/polkadot-sdk/pull/3964

**Comment by Dinonard** [comment]
Can you maybe take a look at the PR when you get the chance? Thanks!
