### ISSUE TITLE
PRDoc crate semver

### ISSUE THREAD

**Issue by Morganamilo** [paritytech/polkadot-sdk#3984]
So we can properly version bump with the next release we need to know what kind of changes were made to these crates. Can authors of the following PRs update the PRdoc to specify `patch`, `minor` or `major`. See example here: https://github.com/paritytech/polkadot-sdk/blob/9d052b7e09d7aecf039b96cf6267e05b9b01c0ae/prdoc/pr_2119.prdoc#L10

@eskimor @dharjeezy @ordian @k-gunjan @muraca @PraetorP @s0me0ne-unkn0wn @JuaniRios @asiniscalchi @ermalkaleci @bkchr 

- [ ] #3190 
- [ ] #3246 
- [x] #3302: https://github.com/paritytech/polkadot-sdk/pull/3985
- [ ] #3350 
- [ ] #3471
- [ ] #3607
- [ ] #3654
- [ ] #3696
- [ ] #3817
- [ ] #3844 
- [ ] #3849
- [ ] #3850

**Comment by asiniscalchi** [comment]
https://github.com/paritytech/polkadot-sdk/pull/3817 was tagged as R0-silent so I imagine PRdoc was not needed here

**Comment by bkchr** [comment]
> #3817 was tagged as `R0-silent` so I imagine PRdoc was not needed here

I mean it is not very important to appear in the release notes. However, the `sp-api-macro` change is actually something that requires a minor bump. Maybe you could create a pr and make the prdoc only about this change with a minor bump for this crate?

**Comment by ggwpez** [comment]
We dont yet have CI checks that assert that the Prdoc bumps are correct.  
So we cannot confidently use this to version it - yet. But it would still be good to have the tools in place to do so.

**Comment by bkchr** [comment]
So, @ggwpez we don't yet need to have the correct bumps in the prdoc yet? Any idea when CI etc tooling will be ready?

**Comment by ggwpez** [comment]
> So, ggwpez we don't yet need to have the correct bumps in the prdoc yet?

Yea, looks like we were not ready for it yet. Reverted here https://github.com/paritytech/polkadot-sdk/pull/3987

>Any idea when CI etc tooling will be ready?

No. I think @Morganamilo is working on an extension for the parity-publish to detect breaking changes though.

**Comment by asiniscalchi** [comment]
> > #3817 was tagged as `R0-silent` so I imagine PRdoc was not needed here
> 
> I mean it is not very important to appear in the release notes. However, the `sp-api-macro` change is actually something that requires a minor bump. Maybe you could create a pr and make the prdoc only about this change with a minor bump for this crate?

Hope it fits : https://github.com/paritytech/polkadot-sdk/pull/3995

**Comment by s0me0ne-unkn0wn** [comment]
Maybe create a single co-authored PR instead of a bunch of one-liners?

**Comment by ggwpez** [comment]
We dont need it for this Release, its causing too much noise now to ping dozens of ppl. Sorry about this.
