### ISSUE TITLE
Require crate bumps in prdocs

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3989]
Before we re-apply https://github.com/paritytech/polkadot-sdk/pull/3987, we should have:
- [x] FAQ for devs on what / how to do bumping
- [x] Announcement in the General chat before enabling
- [x] This check to ensure that the bumps are somewhat sane: https://github.com/paritytech/polkadot-sdk/issues/3292

**Comment by bkchr** [comment]
> * Announcement in the General chat before enabling

External contributors also need to be informed. This means, it needs to be done in a way that if you are an external or an internal developer, you find out the same way. It makes no sense to have some internal "comms" and then external people are just confused on what they need to do.

**Comment by ggwpez** [comment]
Crate bumps are now required in the prdocs.

>External contributors also need to be informed. This means, it needs to be done in a way that if you are an external or an internal developer, you find out the same way. It makes no sense to have some internal "comms" and then external people are just confused on what they need to do.

Done now in the forum and contributor docs inside the repo.
