### ISSUE TITLE
CI: Lychee link checker broken

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#4041]
https://github.com/paritytech/polkadot-sdk/actions/runs/8614094963/job/23606817661?pr=4027

A lot of forbidden errors like:
```
Run /home/runner/work/_actions/lycheeverse/lychee-action/c3089c702fbb949e3f7a8122be0c33c017904f9b/entrypoint.sh
✗ [403] https://etherscan.io/block/11090290 | Failed: Network error: Forbidden
```

**Comment by AndreiEres** [comment]
Seems like we mostly have problems with 403 on https://substrate.stackexchange.com. There is only one 404 in [my last failed job](https://github.com/paritytech/polkadot-sdk/actions/runs/8629981508/job/23655287423?pr=4054)

## 404
### Errors in substrate/client/network/types/src/peer_id.rs

* [404] [https://www.ietf.org/id/draft-multiformats-multihash-07.html#name-the-multihash-identifier-re](https://www.ietf.org/id/draft-multiformats-multihash-07.html#name-the-multihash-identifier-re) | Failed: Network error: Not Found


## 403
### Errors in docs/sdk/src/reference_docs/frame_origin.rs

* [403] [https://substrate.stackexchange.com/questions/10992/how-do-you-find-the-public-key-for-the-medium-spender-track-origin](https://substrate.stackexchange.com/questions/10992/how-do-you-find-the-public-key-for-the-medium-spender-track-origin) | Failed: Network error: Forbidden

### Errors in docs/sdk/src/reference_docs/trait_based_programming.rs

* [403] [https://substrate.stackexchange.com/questions/2228/type-casting-to-trait-t-as-config](https://substrate.stackexchange.com/questions/2228/type-casting-to-trait-t-as-config) | Failed: Network error: Forbidden

### Errors in docs/sdk/src/reference_docs/frame_pallet_coupling.rs

* [403] [https://substrate.stackexchange.com/questions/922/pallet-loose-couplingtight-coupling-and-missing-traits](https://substrate.stackexchange.com/questions/922/pallet-loose-couplingtight-coupling-and-missing-traits) | Failed: Network error: Forbidden

### Errors in substrate/primitives/runtime/docs/sdk/src/polkadot_sdk/mod.rs

* [403] [https://substrate.stackexchange.com/](https://substrate.stackexchange.com/) | Cached: Error (cached)

### Errors in substrate/primitives/runtime/docs/sdk/src/reference_docs/frame_pallet_coupling.rs

* [403] [https://substrate.stackexchange.com/questions/922/pallet-loose-couplingtight-coupling-and-missing-traits](https://substrate.stackexchange.com/questions/922/pallet-loose-couplingtight-coupling-and-missing-traits) | Cached: Error (cached)

### Errors in docs/sdk/src/reference_docs/frame_offchain_workers.rs

* [403] [https://substrate.stackexchange.com/questions/11058/how-can-i-create-ocw-that-wont-activates-every-block-but-will-activates-only-w/11060#11060](https://substrate.stackexchange.com/questions/11058/how-can-i-create-ocw-that-wont-activates-every-block-but-will-activates-only-w/11060#11060) | Failed: Network error: Forbidden

### Errors in docs/sdk/src/polkadot_sdk/mod.rs

* [403] [https://substrate.stackexchange.com/](https://substrate.stackexchange.com/) | Failed: Network error: Forbidden

### Errors in substrate/primitives/runtime/docs/sdk/src/reference_docs/frame_system_accounts.rs

* [403] [https://substrate.stackexchange.com/questions/263/what-is-the-meaning-of-the-account-provider-sufficients-and-consumer](https://substrate.stackexchange.com/questions/263/what-is-the-meaning-of-the-account-provider-sufficients-and-consumer) | Cached: Error (cached)

### Errors in substrate/primitives/runtime/docs/sdk/src/reference_docs/frame_offchain_workers.rs

* [403] [https://substrate.stackexchange.com/questions/11058/how-can-i-create-ocw-that-wont-activates-every-block-but-will-activates-only-w/11060#11060](https://substrate.stackexchange.com/questions/11058/how-can-i-create-ocw-that-wont-activates-every-block-but-will-activates-only-w/11060#11060) | Cached: Error (cached)

### Errors in substrate/primitives/runtime/docs/sdk/src/reference_docs/frame_origin.rs

* [403] [https://substrate.stackexchange.com/questions/10992/how-do-you-find-the-public-key-for-the-medium-spender-track-origin](https://substrate.stackexchange.com/questions/10992/how-do-you-find-the-public-key-for-the-medium-spender-track-origin) | Cached: Error (cached)

### Errors in prdoc/1.6.0/pr_1677.prdoc

* [403] [https://substrate.stackexchange.com/questions/10039/boxed-argument-of-a-dispatchable/10103#10103](https://substrate.stackexchange.com/questions/10039/boxed-argument-of-a-dispatchable/10103#10103) | Failed: Network error: Forbidden

### Errors in docs/sdk/src/reference_docs/frame_system_accounts.rs

* [403] [https://substrate.stackexchange.com/questions/263/what-is-the-meaning-of-the-account-provider-sufficients-and-consumer](https://substrate.stackexchange.com/questions/263/what-is-the-meaning-of-the-account-provider-sufficients-and-consumer) | Failed: Network error: Forbidden

### Errors in substrate/primitives/runtime/docs/sdk/src/reference_docs/trait_based_programming.rs

* [403] [https://substrate.stackexchange.com/questions/2228/type-casting-to-trait-t-as-config](https://substrate.stackexchange.com/questions/2228/type-casting-to-trait-t-as-config) | Cached: Error (cached)
