### ISSUE TITLE
polkadot-parachain v1.10.0 breaks collating on polkadot system chains

### ISSUE THREAD

**Issue by stakeworld** [paritytech/polkadot-sdk#4067]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After updating polkadot-parachain from 1.9.0 to 1.10.0 the collator stops producing blocks and in the logs throws the following error every 6 seconds: 
`Apr 10 13:35:06 polkadot-parachain[1787724]: 2024-04-10 13:35:06 [Relaychain] failed to handle new activations err=Runtime(NotSupported { runtime_api_name: "para_backing_state" })`

`Apr 10 13:35:13 polkadot-parachain[1787724]: 2024-04-10 13:35:13 [Relaychain] failed to handle new activations err=Runtime(NotSupported { runtime_api_name: "para_backing_state" })`

Reverting the relay chain (polkadot) to 1.9.0 didn't fix, reverting polkadot-parachain to 1.9.0 fixed the problem.

### Steps to reproduce

Updating polkadot and polkadot-parachain to 1.10.0 on an active collator

**Comment by stakeworld** [comment]
Also I notice some strange double last blocks in collators list were two collators have the same last block? Not sure if it is related.
![image](https://github.com/paritytech/polkadot-sdk/assets/106294967/5e73c073-4bca-4631-a7d2-9c1c572fe791)

**Comment by PierreBesson** [comment]
I confirm this is happening to Parity collators running 1.10.

**Comment by sandreim** [comment]
https://github.com/paritytech/polkadot-sdk/pull/3795 broke it. The missing API is introduced by async backing which is unfortunately present on Polkadot. I will work on a fix. In the mean time, it should be fine to switch back to `polkadot-parachain`

**Comment by eskimor** [comment]
I believe integration tests are in the works somewhere? Would they cover things like this in the future?

**Comment by sandreim** [comment]
> I believe integration tests are in the works somewhere? Would they cover things like this in the future?

We'd need to pull polkadot runtime from fellowship repo and have a zombienet test in this repo.

**Comment by sandreim** [comment]
Fix is in hotfix release v1.10.1
