### ISSUE TITLE
[NPoS] Staking: Users can delegate their fund to a target which can nominate on their behalf.

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#408]
This is first part of enabling funds of nomination pool delegators to be reusable for governance.

A delegator account should be able to delegate their funds to a delegatee account. The delegatee account can nominate validators using the funds of the delegator account. The funds of delegator should be locked in-place in delegator's account. Staking pallet will need to build a delegation ledger that will bookkeep the delegations. As first iteration, we should allow delegations only for direct nominations . 

The slashes should be applied lazily. As long as more funds are staked than pending slashes, staking pallet should be happy. But it should not allow more funds to be withdrawn than pending slashes. Effectively, the balance of a delegated nominator is `delegated_balance - pending_slashes`. This value should always be zero or greater.

Nomination pool will use the above primitive to allow users to delegate their funds to the pool. The pool account would be the direct nominator. The pool is also responsible for managing rewards and slashes if applicable. 

In future, the same primitives can be used to build different implementations/strategies around slashing and rewards for a pool. 

Some more details on the approach
https://hackmd.io/JXvBdTcHTZmwpEZzNst8mA?edit

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/opengov-improvements-on-the-technical-level/6578/3

**Comment by Ank4n** [comment]
complete with https://github.com/paritytech/polkadot-sdk/pull/3905
