### ISSUE TITLE
Coretime: Fix renewal rights for leases expiring in period 0

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#4107]
Parachains whose leases would expire in period 0, will continue to have a lease until the end of period 1, but will not have renewal rights to extend it further. We should pass the necessary motions to grant those rights on Kusama and fix it in code for Polkadot.

- [ ] Pass necessary motions on Kusama
- [x] Fix code for Polkadot to make it a non-issue there.

**Comment by seadanda** [comment]
This can be considered complete with the upgrade to `1002002`, as the motions on Kusama were superseded by the runtime upgrade and sales restart
