### ISSUE TITLE
Migration from v3::Location to v4::Location for ForeignAssets

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#4128]
ForeignAssets in the asset hubs use XCM Locations.
They don't use VersionedLocation, they are fixed to v3::Location.
When we introduced XCMv4, we left the assets using v3::Location instead of moving them to v4::Location, since they needed a migration.
We should migrate them.

**Comment by acatangiu** [comment]
To be clear, migrate to `VersionedLocation`
