### ISSUE TITLE
Changing PVF execution environment parameters only affecting execution shouldn't trigger artifact re-compilation

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot-sdk#4132]
Changing parameters like max. memory pages or execution timeouts has nothing to do with the artifact preparation but still causes re-compilation of every single artifact, resulting in liveness issues on production networks. The parameters should be split into groups that may intersect and only trigger the re-compilation if a preparation-related parameter has changed.

**Comment by eskimor** [comment]
Also, if we need to change them, we should announce that this is happening. Let's add documentation explaining the effects on parachain block times and finality.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/async-backing-development-updates/6176/9
