### ISSUE TITLE
The Polkadot Official Docker Image for the v1.10.1 release is not available

### ISSUE THREAD

**Issue by arcenik** [paritytech/polkadot-sdk#4166]
On https://hub.docker.com/r/parity/polkadot/tags the last image is v1.10.0

**Comment by klestrong** [comment]
Not sure if this has been resolved for you, but it seems they're using a different image repo, parity/polkadot-parachain.  It's not labeled (Polkadot Official Docker Image), but still maintained by Parity.  After some digging, I found Polkadot version 1.10.1 in the below Parity image repo.
https://hub.docker.com/r/parity/polkadot-parachain/tags
