### ISSUE TITLE
Update Wiki - Disabling

### ISSUE THREAD

**Issue by Overkillus** [paritytech/polkadot-sdk#4173]
Update: https://wiki.polkadot.network/docs/maintain-guides-how-to-chill

**Comment by DrW3RK** [comment]
@Overkillus You can create Wiki-related issues here: https://github.com/w3f/polkadot-wiki/issues One of us from the Tech Ed team will pick it up if you provide context on what needs to be updated.

**Comment by CrackTheCode016** [comment]
Also - is this in reference to the change in https://github.com/paritytech/polkadot-sdk/pull/3453?

**Comment by Overkillus** [comment]
Being handled in https://github.com/w3f/polkadot-wiki/pull/5825

**Comment by Overkillus** [comment]
> Also - is this in reference to the change in [#3453](https://github.com/paritytech/polkadot-sdk/pull/3453)?

Nope. This is in relation to the new Disabling Overhaul which in short:
- makes disabling stricter
- removes ImOnline offences
- removes involuntary chilling (which was not binding anyway)

See [State of Disabling #4359](https://github.com/paritytech/polkadot-sdk/issues/4359) for a comprehensive list of updates.
