### ISSUE TITLE
Create a convenient way to look up a `DispatchError` in RPC

### ISSUE THREAD

**Issue by hhamud** [paritytech/polkadot-sdk#4181]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Clearer Pallet Errors

### Request

A DispatchError will refer to a pallet and a member of the pallet's Error enum by index:

DispatchError: {"module":{"index":123,"error":456}}

I was wondering how I would write a tool that grabs the error from the metadata. I can't find any documentation about how DispatchError transforms the data into its error numbers. I have already asked this in the subtratestack and commenters claim that this cannot be done.

Lets say that I am trying to propagate an error from a library that I use within a pallet that has an error that is transformed into a dispatchError of which I am trying to wrap around.

```Rust
fn call() --> Result<transaction, DispatchError> {
// error happens here which gets propagated
let e = e.message().map_err(|e:TransactionFailed| Error::<T>::TransactionFailed(e))
// carries on
}

let trans = l.call(...).map_err(|e:dispatchError| RpcError::TransactionFailed(e))

```

### Solution

Anything that makes it easier to decode dispatcherrors

### Are you willing to help with this request?

Yes!

**Comment by ggwpez** [comment]
You using JS or Rust?

```js
const error = api.registry.findMetaError(
    new Uint8Array([/* Pallet Index */ Number(0),  /* Error Index */Number(2)])
);
console.log(error.name)
```

**Comment by hhamud** [comment]
> You using JS or Rust?
> 
> ```js
> const error = api.registry.findMetaError(
>     new Uint8Array([/* Pallet Index */ Number(0),  /* Error Index */Number(2)])
> );
> console.log(error.name)
> ```

Sorry I meant within the rust node itself. I want to emit more descriptive error messages via RPC rather than getting the user to do it themselves using the polkadot-js
