### ISSUE TITLE
[tests] Remove hard-coded error indices in pallet-xcm tests

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#4237]
Follow up on https://github.com/paritytech/polkadot-sdk/pull/3867 to remove hard-coded indices like https://github.com/paritytech/polkadot-sdk/blob/d0ebb850ed2cefeb3e4ef8b8e0a16eb7fb6b3f3e/polkadot/xcm/pallet-xcm/src/tests/assets_transfer.rs#L826

cc @chungquantin

**Comment by chungquantin** [comment]
🫡

**Comment by chungquantin** [comment]
@ggwpez I have created a PR to resolve this issue

**Comment by bkontur** [comment]
looks like this was fixed by https://github.com/paritytech/polkadot-sdk/pull/4248
