### ISSUE TITLE
Regression: Identity judgements fail on Kusama

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-sdk#4245]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Calling provideJudgement now fails on Kusama, whether the call is done thru a Proxy or directly from the Registrar.

See tx:
https://kusama.subscan.io/extrinsic/0x480c6f91d4b463f773450376018e614723f44df17ef020de660f7fa03df6ed03

### Steps to reproduce

As registrar, send provideJudgement on an account that has been verified.
The target account in this call is `DG6egJCfrcNPMSFYihxxPxtWvMwq3GR5k3pUS4pHouamuTv`.

**Comment by bkchr** [comment]
> Block Identity pallet calls in the Relay Chain;
https://forum.polkadot.network/t/people-chain-launch-and-identity-migration-plan/5930

Generally this repo is not for issues inside the Polkadot/Kusama runtimes. They should be posted inside of: https://github.com/polkadot-fellows/runtimes
