### ISSUE TITLE
runtimes are currently centralised

### ISSUE THREAD

**Issue by gilescope** [paritytech/polkadot-sdk#4246]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

At the moment `set_code` only allows one runtime (blob of code) at a time to be set per chain per version.

Many point to this as a point of centralisation.

If instead for each version, a map of `runtime-flavour => runtime` were stored (i.e. store several independent implementations of the same runtime). A validator could choose their favourite flavour of runtime to use from the map. If 4 runtimes were used and one had a bug then the chain would still progress (assuming equal weightings).

4 different runtimes might seem expensive to produce, but even before independent runtimes are created, we could have the same source code built by 4 different teams, and potentially using different rust compilers (gcc is coming along, as is cranelift).

**Comment by bkchr** [comment]
Not something we want to support.

**Comment by gilescope** [comment]
I'm fine with 'not something we want to support at this time.', but I'd hope that we'd be potentially open to support this direction in the future should people want to invest the time and effort to go down this path.

It's great that a parachain can choose to change to be self sovereign. Whether anyone takes that option is another question, but that the option is there is a big selling point. To me this is similar - I would expect most chains not to bother with having multiple runtimes, but having this option squashes a lot of centralisation FUD against chains with on-chain runtimes.

**Comment by bkchr** [comment]
> but having this option squashes a lot of centralisation FUD against chains with on-chain runtimes.

This is a just a stupid argument. They can just upgrade to whatever they want. It is not more centralized than having one bitcoin client or all nodes calling into the same implementation for execution.

**Comment by gilescope** [comment]
Agreed that what we have today is no worse than Bitcoin in respect to one codebase (and obviously in many dimensions is better). Is it intrinsically essential to the protocol that there's only ever one implementation of a particular runtime version?
