### ISSUE TITLE
Investigate usage of `xcm::v4`

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#4297]
I found two cases for investigation:

for coretime stuff
- I think we should change to `v4` to `lastest` to avoid unnecessary problems when adding v5
```
use xcm::v4::{send_xcm, Instruction, Junction, Location, OriginKind, SendXcm, WeightLimit, Xcm};
``` 
for `query_acceptable_payment_assets`
- `if !matches!(xcm_version, 3 | 4)` or `Ok([VersionedAssetId::V4(`, I think we should use also `VersionedAssetId::from` for latest

**Comment by seadanda** [comment]
There should be no issues replacing this on the coretime side
