### ISSUE TITLE
Runtime API for `LocationToAccountId` Conversion

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#4298]
We use this type to convert locations in the system to local `AccountId`s on a chain. Quite often we want to do this conversion in applications or just for debugging, so it would be nice to expose an API to query how a chain will convert a location. Examples:

- Recent case with Phala and sibling vs. Relay sovereign account
- In [this referendum](https://kusama.subscan.io/referenda_v2/370), the beneficiary was specified as `(1, PalletInstance(18))` as it is more expressive to show that you are transferring the funds to the control of a pallet in the system and not some random account. But it's difficult to actually find this account now.

**Comment by bkontur** [comment]
@joepetrowski  implemented here: https://github.com/paritytech/polkadot-sdk/pull/4857, please take a look:
Input:
 - `location:  VersionedLocation`
 - `ss58_prefix` - optional, if none the runtime's `SS58Prefix` is used or you can specify what ever output you need
 
Output:
 - account_id bytes
 - ss58_address + ss58_version

---

Example bellow is for:
```
Location::parent()

account_id:  0x506172656e740000000000000000000000000000000000000000000000000000

12pPnA1aFic3ibBh9xMwssM1779vfrJBxqD4mDy8d18r4g95
8c439Yye1UmsebA4VEyFmcRkbJDj2vi9mmCNucS5rjLM2RU
EPiJ96P2JMW2hzcy27zdfsrQ5SWnDZELiKKzbFjYiKpdR9y
5Dt6dpkWPwLaH4BBCKJwjiWrFVAGyYk3tLUabvyn4v7KtESG
```

You can also verify it with https://polkadot.subscan.io/tools/format_transform or
```
~/parity/polkadot-sdk$ ./target/debug/subkey inspect 0x506172656e740000000000000000000000000000000000000000000000000000
Secret Key URI `0x506172656e740000000000000000000000000000000000000000000000000000` is account:
  Network ID:        substrate
  Secret seed:       0x506172656e740000000000000000000000000000000000000000000000000000
  Public key (hex):  0xd0a0794e564f0843dd0920a6356fda3e768a6c674317a638d37a30d39f6aa574
  Account ID:        0xd0a0794e564f0843dd0920a6356fda3e768a6c674317a638d37a30d39f6aa574
  Public key (SS58): 5GnFVFSzFTbXv7QcKJcEa8ArTYvjZaRMxbcEH4cvBmD4Hx4w
  SS58 Address:      5GnFVFSzFTbXv7QcKJcEa8ArTYvjZaRMxbcEH4cvBmD4Hx4w
```

![image](https://github.com/paritytech/polkadot-sdk/assets/8159517/81b467ce-fd49-41ee-8ee8-6bc0569f5477)
