### ISSUE TITLE
Assets Events for `Deposited` and `Withdrawn`

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#4308]
We have events for balances when they are deposited or withdrawn from an account. A lot of services like block indexers rely on these for account balance computation rather than reading on-chain state. We should provide the same events for assets so that they can use the same logic in integration.

Assigning @liamaharon but could also be a good mentor/first issue.

**Comment by liamaharon** [comment]
@pandres95 will take it :)
