### ISSUE TITLE
Validators entering the active set are slow on validation because PVF artifacts are not compiled

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#4324]
PVF artifacts are cleanup every 24h if unused: https://github.com/paritytech/polkadot-sdk/blob/f34d8e3cf033e2a22a41b505c437972a5dc83d78/polkadot/node/core/pvf/src/host.rs#L296

So, when nodes join the active set for the first time or they have been out of the active set for 24 hours, they won't the PVF artifacts ready for approving or backing blocks so they will have to compile all PVFs the first time they need to execute a block from each parachain. 

Each PVF compilation will take around  3 seconds or more and compiling all polkadot PVFs will take around 3 minutes, hence why the validator will cause no-shows on the approval-voting and will probably fail to get some of the backing points if the PVF of the parachain is not compiled yet.

This is a transient problems since all the PVF should be compiled after around 3-4 minutes, however this problem could probably be relatively easy to fix by proactively compiling the PVFs before the node become actives.

**Comment by sandreim** [comment]
Good idea, nodes should be able to know that already by checking the next session keys.

**Comment by s0me0ne-unkn0wn** [comment]
I had another idea lost somewhere in discussions: instead of invalidating the cache after 24h, make it size-bounded and only remove the stalest artifact if the cache size overflows. Not 100% sure but sounds like it's somewhat easier to implement than the lookahead compilation.

**Comment by alexggh** [comment]
> I had another idea lost somewhere in discussions: instead of invalidating the cache after 24h, make it size-bounded and only remove the stalest artifact if the cache size overflows

That would work for nodes that enter and live the active set, however it won't work for the situation where the node is simply a fresh node that just joins the active set.

**Comment by s0me0ne-unkn0wn** [comment]
> > 
> 
> That would work for nodes that enter and live the active set, however it won't work for the situation where the node is simply a fresh node that just joins the active set.

Fair enough, but that's just a single no-show. Running a validator from scratch is not something that happens very often, I believe.
Maybe we could implement both? Mine would save them some CPU for the price of some storage, and yours would address all the remaining corner cases.

**Comment by alexggh** [comment]
> Maybe we could implement both? 

Yes, implementing both makes sense.
