### ISSUE TITLE
Specify listen address for RPC service

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#4331]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

https://github.com/AcalaNetwork/Acala/issues/2743

### Request

Should allow user to specify listen address for RPC service

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
CC @niklasad1

**Comment by niklasad1** [comment]
Yes, I agree we should support this.

The question is really whether we should support several listening addresses such [ipv4, ipv6] that came up in another issue IIRC but as first step we could make it `--rpc-listen-addr <SocketAddr>`
