### ISSUE TITLE
Persistent Bonding State Issue with Zero Existential Deposit

### ISSUE THREAD

**Issue by benefacto** [paritytech/polkadot-sdk#4340]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We are building a new layer 1 using Frontier EVM alongside pallet_staking. We are using a custom Substrate token as its native token. We have set our existential deposit to zero to prevent dusting. However, we've identified an issue related to storage writes in the staking process, specifically with the `Self::bonded` entry. According to the [documentation](https://paritytech.github.io/polkadot-sdk/master/pallet_staking/struct.Pallet.html#method.bonded), this entry is not cleared unless the balance falls below the existential deposit and is removed as dust. With an existential deposit of zero, these entries are never cleaned, which leads to a situation where stakers remain indefinitely bonded with a stake of zero after they chill and unbond. This results in unnecessary storage overhead and potential unknown issues.

**Expected behavior:**
After an account is fully unbonded, it should not remain in a bonded state if it has a zero stake.

**Actual behavior:**
Accounts remain bonded with zero stake due to the non-removal of `Self::bonded` because the existential deposit is zero.

**Potential impact:**
This could lead to increased storage overhead and might cause other unknown issues in network behavior or staking mechanics.

### Steps to reproduce

1. Extend the [frontier node template](https://github.com/polkadot-evm/frontier/tree/master/template) by configuring `pallet_staking`.
2. Follow the staking, validating, chilling, and unbonding process with any account. Example steps:
   - Bond an account with a minimum stake value and set it as a validator.
   - After some operations and era transitions, chill and unbond the account.
   - Check the bonded state of the account after unbonding is completed.
   - The account remains bonded with a stake of zero which is not the expected behavior.

**Comment by kianenigma** [comment]
cc @Ank4n @gpestana

**Comment by Ank4n** [comment]
Yes, seems staking pallet has not been written with expectation that ED can be zero. 
Fix is to do a `<=` check with ED or an explicit zero check (safer as it is noop for runtimes with `ed > 0`).
