### ISSUE TITLE
Coretime auto renew

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#4351]
Currently parachains that want to renew their slot need to do this every sale in the first week. They can also do this afterwards, but then all cores could already have been sold. It would be nice to support an auto renew. Parachains could opt-in to this auto renew and then only would need to ensure that the account for doing the auto renew has enough funds.

Basically the following transaction should be added:

```
fn enable_auto_renew(core, target_account)
```

First time this is called, the core should be renewed automatically (maybe it was already and we need to check "the future") and then the core & account is to some list. When rotating the sales this list should be iterated and all cores should be automatically renewed.

**Comment by bkchr** [comment]
CC @seadanda

**Comment by itsbirdo** [comment]
Would be a welcome improvement based on feedback from several teams

**Comment by Szegoo** [comment]
Would like to work on this over the weekend if available.

**Comment by Szegoo** [comment]
> fn enable_auto_renew(core, target_account)

This should be a two step process, otherwise a parachain could set any account as target without requiring the `target_account`'s approval for this. Another option would be, assuming this is called with the parachain's sovereing account is to set the target to the sovereign account. 

@bkchr did you have something else in mind maybe?

**Comment by bkchr** [comment]
> @bkchr did you have something else in mind maybe?

No. Just didn't thought enough :D Probably the best is to not have `target_account` at all. Just take the account that signed the transaction as payment account.

**Comment by Szegoo** [comment]
> Just take the account that signed the transaction as payment account.

But this can be just any account? For example, I could set myself as the payment account, drain my account, and then upon the next renewal, it would fail. 

Given that the broker pallet is quite abstract, it doesn't assume that cores are assigned to parachains. But would it be acceptable to assume each 'task' has an account associated with it? (basically each parachain has its sovereign account)

I would probably add a new type to the broker pallet config which would implement conversion from `TaskId` to `AccountId`. We could reuse the `LocationToAccountId` implementation such that we convert `Parachain(TaskId)`. And then this account would be used for payment.
