### ISSUE TITLE
Benchmark issue

### ISSUE THREAD

**Issue by Daanvdplas** [paritytech/polkadot-sdk#4376]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When executing benchmarks I missed a '-' before the 'extrinsic' flag. So in stead of: `... --extrinsic=`

I had: `... -extrinsic=`

The error that is outputted is: `Error: Input("No benchmarks found which match your input.")`

This is not really clear and took me a while to figure out.

### Steps to reproduce

I ran `./target/release/bfg-node benchmark pallet --chain=test --wasm-execution=compiled --pallet=pallet_brands --steps=50 --repeat=20 --json --template ./scripts/frame-weight-template.hbs --output=./ -extrinsic=`

See the above for what the problem was.

**Comment by bkchr** [comment]
This is an improvement that should be done in `clap`. Nothing that we can fix here.
