### ISSUE TITLE
OnTransfer Hook

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot-sdk#4379]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Some business logic may necessitate this, such as recording the volume on-chain.

### Request

To execute additional operations when users perform `Balances::transfer` or `Asset::transfer`.

### Solution

I'm not sure if adding this hook is the best approach, or if there are more elegant methods.

```rs
Config {
  ..
  OnTransfer: OnTransfer
}

fn transfer() {
  T::OnTransfer(from, to, amount)?;
  ..
}
```

Or add to the `fungible_*` traits.

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
Duplicate of: https://github.com/paritytech/polkadot-sdk/issues/2563

I left a proposal for a possible implementation: https://github.com/paritytech/polkadot-sdk/issues/2563#issuecomment-1915408620

If you are interested to work on this, please comment there. Thank you!
