### ISSUE TITLE
How Parachain Integrate Polkadot,Kusama and System Parachian Runtimes?

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#4382]
Because of BridgeHub, snowbridge launch, now parachain want to write integration test to test cross-chain functionality, similar to https://github.com/polkadot-fellows/runtimes/tree/main/integration-tests/emulated, but the version of parachain's Polkadot-sdk must be the same as the version of [runtimes](https://github.com/polkadot-fellows/runtimes/tree/main) in order to use xcm-emulator, is there any good way?

**Comment by xlc** [comment]
use chopsticks 
https://github.com/AcalaNetwork/e2e-tests

**Comment by bkchr** [comment]
Yeah as @xlc said, use chopsticks :)
