### ISSUE TITLE
Assets Cookbook

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#4390]
We probably need a collection of examples performing common asset related tasks, similar in spirit to the xcm cookbook.

e.g. how to calculate and pay a tx fee via the asset conversion pallet on Asset Hub.

Examples should be written in both Rust + JavaScript.

**Comment by acatangiu** [comment]
closing in favor of https://github.com/paritytech/polkadot-sdk/issues/5207
