### ISSUE TITLE
Mark nomination-pool funds as deactivated

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#440]
As a follow-up, all funds locked in nomination pools also have to be marked as deactivated now. 

The migration will be `O(pool_count)`. Each pool would look at its bonded account `ledger.total` and mark that as deactivated.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/issues/12813#issuecomment-1336405691_

**Comment by kianenigma** [comment]
We now have the nomination pool funds tracked in a storage item (https://github.com/paritytech/polkadot-sdk/pull/1322). All that is left to do is to make sure this amount of funds is marked as deactivated upon each update. 

Marking @gpestana as the mentor.

**Comment by Doordashcon** [comment]
> I want to still pursue this as a PR to track TVL of Pools.

@kianenigma does this mean to track the TVL of individual pools?

**Comment by xlc** [comment]
why the funds in nomination pool are inactive?

**Comment by Doordashcon** [comment]
I am guessing pool funds can be reactivated when required to be used in governance? 

This accurately sums the active balance in the eco.

**Comment by xlc** [comment]
what exactly does active mean? tokens that can be used for governance?

**Comment by Doordashcon** [comment]
> what exactly does active mean? tokens that can be used for governance?

from this [PR](https://github.com/paritytech/substrate/pull/12813), that seems to be the case.

**Comment by xlc** [comment]
I am not sure if it says anything explicitly about how this applies to Polkadot so I need a proper confirmation.

**Comment by kianenigma** [comment]
> I am not sure if it says anything explicitly about how this applies to Polkadot so I need a proper confirmation.

The explanation provided is correct. The funds are not usable in governance and are therefore inactive. I am going to close this actually, as it is not really needed soon. https://github.com/paritytech/polkadot-sdk/pull/2680 is not that far anymore.
