### ISSUE TITLE
[Pools] Follow up issues/improvements for Pools open gov integration

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#4404]
Tracker ticket of improvements that can be made and/or unresolved issues found in https://github.com/paritytech/polkadot-sdk/pull/3905.

- [ ] (Priority: Medium) Provide a way to reap agent/delegator when account falls below ED (such as due to slashing). 

    In case of fully slashed pool, we might end up in a situation where delegator is reaped from `pallet-delegated-staking` but remains forever in pools. Worked on here (probably not a straightforward fix and affects `TransferStake` pools as well): https://github.com/paritytech/polkadot-sdk/tree/ankan/np-reap-fix

- [x] (Priority: Low): Improve Delegation staking apis. We have `register` but no `unregister`. This could be part of the above issue where we provide `unregister` and that is the only way pool accounts are reaped.
- [x] (Priority: High) Bot and runtime apis for helping with applying pending slashes. https://github.com/paritytech/polkadot-sdk/issues/4630
- [x] (Priority: High) Script for permissionlessly migrating all nominator delegations.
- [x] Fuzz (https://github.com/paritytech/polkadot-sdk/issues/424) + Remote ext tests (https://github.com/paritytech/polkadot-sdk/issues/4629) for DelegateStake adapter.
- [x] Runtime apis for delegation based NP: https://github.com/paritytech/polkadot-sdk/pull/4537.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/any-update-on-voting-while-staking-in-a-pool/8589/3

**Comment by rainbow-promise** [comment]
Hello @Ank4n

> * [ ]  (Priority: Low): Improve Delegation staking apis. We have `register` but no `unregister`. This could be part of the above issue where we provide `unregister` and that is the only way pool accounts are reaped.

Already solved with [this](https://github.com/paritytech/polkadot-sdk/blob/ba38d31d8e7c12025e4de385c2a4d6372ee7c23b/substrate/frame/delegated-staking/src/lib.rs#L325)?

**Comment by Ank4n** [comment]
> Hello @Ank4n
> 
> > * [ ]   (Priority: Low): Improve Delegation staking apis. We have `register` but no `unregister`. This could be part of the above issue where we provide `unregister` and that is the only way pool accounts are reaped.
> 
> Already solved with [this](https://github.com/paritytech/polkadot-sdk/blob/ba38d31d8e7c12025e4de385c2a4d6372ee7c23b/substrate/frame/delegated-staking/src/lib.rs#L325)?

Hi, thanks for your interest. This is already [done](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/staking/src/lib.rs#L544), was not updated here. :(

**Comment by Ank4n** [comment]
Closing this as the only remaining task has an independent issue for it
https://github.com/paritytech/polkadot-sdk/issues/5009
