### ISSUE TITLE
Unable to destroy Nomination Pools

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#4440]
First reported for Pool [231](https://polkadot.subscan.io/nomination_pool/231).

When the owner tries to `withdraw_unbonded`, they get a [`Token: Frozen error`](https://polkadot.subscan.io/extrinsic/20587037-3?event=20587037-55). 

The issue seems to have started since the [last polkadot runtime upgrade](https://polkadot.subsquare.io/referenda/648?tab=timeline).

## Issue
The pool seems to have an extra consumer reference. The pool is expected to have two consumer references
- explicit consumer increment by pallet-staking.
- applying lock on ledger increments consumer.

but most of the pool including `#231` has 3 references. The destruction of pool fails when it tries to transfer all the remaining amount from pool account to the owner specifically on [this condition](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/system/src/lib.rs#L1659). Since it has one remaining consumer, it cannot kill the account and expects ED to remain in the pool account.

**This issue affects almost all the current pools if they try to destroy.**

## Cause
This PR seems to have led to this issue: https://github.com/paritytech/polkadot-sdk/pull/1976.
Earlier, applying a lock would increase consumer by 2, and similarly decrease by 2 when removed.

With the above fix, consumer references are only increased by 1. The older accounts with an extra consumer reference though are now in a bad state and cannot be killed.

## Solution
There seems to be no easy way to detect on-chain which accounts have an extra consumer reference. For pool accounts, we could expect to only have 2 consumers and potentially this can be fixed in a migration.

A better solution would be fixing for all the accounts that have this extra reference.
The issue is mentioned and tracked at #2037.

### Update
We could explicitly kill account when pools are destroyed. This can be either by force consumer decrement or a separate (new) fungible api that transfers and kills account.

**Comment by kianenigma** [comment]
I suggest exploring a more short-sighted solution, even if it involved using governance, to fix all the current and prospect pools, even if a more systematic solution cannot be found. Not being able to destroy the pool implies a greater economic damage (500+ DOT) vs. an account (1, 0.01 DOT depending on the chain).
