### ISSUE TITLE
readiness and liveness endpoints for service health monitoring

### ISSUE THREAD

**Issue by gilescope** [paritytech/polkadot-sdk#4443]
Re-awakening: https://github.com/paritytech/substrate/issues/1017

Stale PR here: https://github.com/paritytech/substrate/pull/14314

What's the current thoughts on having a readiness endpoint? Without an 'official' endpoint people will create ad-hoc checks rather than all collaborate on making one good check.

(If this is already implemented we can close this, but nothing came up on the search)

**Comment by bkchr** [comment]
CC @niklasad1
