### ISSUE TITLE
Audit `safe-mode` and `tx-pause`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#4445]
Pallets introduced in https://github.com/paritytech/substrate/pull/12092 do need audit.

**Comment by ggwpez** [comment]
already done

**Comment by wischli** [comment]
Hey @ggwpez. According to this issue, both pallets have been audited. However, the docs state they have not been audited. I suppose the docs are outdated?
* safe-mode: https://github.com/paritytech/polkadot-sdk/blob/ac98bc3fa158aa01faa3c0f95d10c8932affbcc2/substrate/frame/safe-mode/src/lib.rs#L24
* tx-pause: https://github.com/paritytech/polkadot-sdk/blob/ac98bc3fa158aa01faa3c0f95d10c8932affbcc2/substrate/frame/tx-pause/src/lib.rs#L24

Assuming both have been audited, can you point me to the audit report please? I'd also love to know the first SDK version in which they have been officially audited. Thank you in advance!

**Comment by ggwpez** [comment]
I am removing the warnings now https://github.com/paritytech/polkadot-sdk/pull/5114 and pinged the security team if they have some report, normally i would assume not, but we wanted to have some proper audit tracking for a while now.
