### ISSUE TITLE
`transfer_all` Call in Assets Pallet

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#4517]
With the ability to pay fees in assets, there is demand from some users to be able to "pay fees with and transfer all", completely killing the balance of the asset on the account. We should add this `transfer_all` call to the Assets pallet to make this easier without needing to calculate fees/exchange rates to determine transferrable amount.

@pandres95 ?

**Comment by pandres95** [comment]
I'll take it.😁
