### ISSUE TITLE
CI: Prevent the introduction of `git =` dependencies

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#4553]
Release is currently blocked since we added some git dependencies recently: https://github.com/paritytech/merkle-mountain-range/issues/3  

Should add a CI check that prevents their addition.

**Comment by Morganamilo** [comment]
This would fit into to `parity-publish check` command that already runs in CI

**Comment by ggwpez** [comment]
Now done by https://github.com/paritytech/polkadot-sdk/blob/master/.github/scripts/deny-git-deps.py.
