### ISSUE TITLE
asset-hub-rococo: `Extrinsic exceeds total pov size`

### ISSUE THREAD

**Issue by skunert** [paritytech/polkadot-sdk#4559]
Asset hub rococo stopped producing blocks today a few hours after the upgrade to 1.12.0.
[logs](https://grafana.teleport.parity.io/explore?schemaVersion=1&panes=%7B%22iy4%22:%7B%22datasource%22:%22P3572579027B246FE%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bchain%3D%5C%22asset-hub-rococo%5C%22%7D%20%7C~%20%60present%7Cexceeds%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P3572579027B246FE%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)

In the logs we see that the reported PoV size is too large:
```
DEBUG tokio-runtime-worker runtime::system: [Parachain] Extrinsic exceeds total pov size: 5156.3271484375kb, limit: 5120kb
```

I introduced the check that is failing just recently https://github.com/paritytech/polkadot-sdk/pull/4326.

Usually this would just lead to an extrinsic not getting included in a block. But here block production is complaining about `set_validation_data` not being in the block. This means that the inherent does not get included. Since they get included in the block first, the working thesis is that we are using too much weight during `on_initialize` already.

Next investigation steps:
- Patch runtime with debug logs indicating which pallet is using too much weight
- Try to reproduce error locally by using `--wasm-overrides`

**Comment by bkchr** [comment]
Okay we found the problematic line of code: https://github.com/paritytech/polkadot-sdk/blob/5dc522d02fe0b53be1517f8b8979176e489a388b/substrate/frame/session/src/lib.rs#L556

With the recent changes to also take the transaction size into account when ensuring that we don't run over the block size limit, this broke the asset hub parachain. IMO the best solution would be that the `CheckWeight` always allows inherents, even if they probably run over the block size limit.
