### ISSUE TITLE
Pallets should not return `max_block` as weight in `on_initialize`

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#4573]
With the changes to `CheckWeight` that also take the transaction size into account, we have discovered [this bug](https://github.com/paritytech/polkadot-sdk/issues/4559). The underlying problem is the usage of `max_block` as return in `on_initialize`. We should check all the pallets and fix this problematic pattern.

Pallets to fix (non exhaustive list):
- [ ] `pallet-session`

**Comment by xlc** [comment]
we keep rediscovering the same bug https://github.com/paritytech/polkadot-sdk/issues/184

**Comment by bkchr** [comment]
Looks like I should have used the search :see_no_evil:
