### ISSUE TITLE
Cannot produce blocks on time after switching to async backing

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot-sdk#4589]
Origin post: https://substrate.stackexchange.com/questions/11530/cannot-produce-blocks-on-time-after-switching-to-async-backing

**Comment by alexggh** [comment]
Could you give us  a bit more details about your setup and logs
1. What polkadot version are you running ?
2. Which relaychain have you test this against ?
3. What are you seeing on your collators
4. At what rate did your parachain produce blocks before upgrade and after the upgrade.

**Comment by AurevoirXavier** [comment]
1. polkadot-v1.1.0
2. Rococo
3. The log looks pretty normal, but it seals the same block multiple times, likely due to different collators racing. I can post more logs later.
4. It used to be 12s; now it's 18s. I have 3 collators, and I think the increase to 18s is because of two missing slots.

**Comment by alexggh** [comment]
`polkadot-v1.1.0` is this a typo ?

**Comment by AurevoirXavier** [comment]
> `polkadot-v1.1.0` is this a typo ?

Sorry, https://github.com/paritytech/polkadot-sdk/tree/release-polkadot-v1.1.0.

**Comment by alexggh** [comment]
`polkadot-v1.1.0` predates full async-backing support unfortunately there were a lot of fixes since then for async backing I would recommend upgrading to something newer.

**Comment by AurevoirXavier** [comment]
> `polkadot-v1.1.0` predates full async-backing support, unfortunately there were a lot of fixes since then for async backing I would recommend upgrading to something newer.

Which version do you recommend? We don't want to use the latest one.

**Comment by AurevoirXavier** [comment]
We decided to use async backing because of

<img width="971" alt="image" src="https://github.com/paritytech/polkadot-sdk/assets/16152305/75563005-5e1c-44f7-8d8e-acb967b03890">

**Comment by alexggh** [comment]
`polkadot-v1.1.0` https://github.com/paritytech/polkadot-sdk/tree/release-polkadot-v1.1.0 was created on `Sep 6, 2023`, so it is really old.

> Which version do you recommend? We don't want to use the latest one.

I would recommend you use the latest one, however if you have a specific not to use that one, you can go as back as `polkadot-v1.8` bare in mind that we are already on `polkadot-v1.12`.

**Comment by AurevoirXavier** [comment]
Since we rely heavily on Moonbeam, they are currently using version `polkadot-v1.7.2`.

Thanks for your help. This issue might be invalid with the latest code, so let's close it for now.
