### ISSUE TITLE
Improve documentation of `CRV2` to `frame_support::runtime`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#4622]
- make it not be `ignore`
- Explain `DisableCall` and `DisableUnsigned` more explicitly? 
- Provide link that this is the new version of `frame_support::construct_runtime`
- Provide an explanation about the differences between the two, other than pallet ordering (eg. missing features). 

Question: @gupnik Is it an intentional choice that you can only disable these two pallet parts, but not any of the other ones? why only these two where chosen?

**Comment by gupnik** [comment]
> Question: @gupnik Is it an intentional choice that you can only disable these two pallet parts, but not any of the other ones? why only these two where chosen?

This follows from @bkchr's comment here: https://github.com/paritytech/polkadot-sdk/issues/232#issuecomment-1691692946
