### ISSUE TITLE
Building on Windows is broken due to symbolic link

### ISSUE THREAD

**Issue by conr2d** [paritytech/polkadot-sdk#4625]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

#3087 added the symbolic link pointing to `docs` to`substrate/primitives/runtime`, but on Windows (tested on Windows 10), symbolic link cannot be recognized, so the following line causes file not found error during compiling Substrate.

https://github.com/paritytech/polkadot-sdk/blob/89604daa0f4244bc83782bd489918cfecb81a7d0/substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs#L60

### Steps to reproduce

Compile `sp-runtime` on Windows.

**Comment by bkchr** [comment]
We don't really support Windows. However, if you have a fix, we are happy to accept your pr that fixes the issue.
