### ISSUE TITLE
Browser extensions can't sign extrinsics in v1.2.5

### ISSUE THREAD

**Issue by michalisFr** [paritytech/polkadot-sdk#4659]
Doing some testing on Rococo I discovered that all browser extensions can't sign extrinsics, probably because they can't decode the `SignedExtension` with the merkleized metadata.

For example, here's the message from the Polkadot-JS browser extension:
![Screenshot 2024-05-31 at 1 25 44 PM](https://github.com/paritytech/polkadot-sdk/assets/45905709/1d295257-9c70-4859-ad22-b4075241cce6)
and all other extensions (Talisman, Subwallet, Polkagate, Fearless) fail to sign in similar fashion.

A Polkadot Vault account imported in the Polkadot-JS extension fails to decode the QR code generated by the extension with this error:
![error](https://github.com/paritytech/polkadot-sdk/assets/45905709/b2aafe3c-66c7-41b7-8cae-ee7d1e6c6ed4)

Just to note, both the extensions and Polkadot Vault have the latest Rococo metadata.

Similarly, the Rococo faucet has stopped working with error:
`Error: Unsupported signed-extension: CheckMetadataHash`
and Subwallet mobile and dashboard also can't sign transactions.

On the other hand, accounts created or imported directly on Polkadot-JS apps can sign extrinsics normally. The same goes for a Polkadot Vault imported directly on Polkadot-JS apps.

**Comment by bkchr** [comment]
@TarikGul shouldn't that have been fixed by PJS already? I mean I know that you fixed it, but maybe not yet released it to the UI?

**Comment by bkchr** [comment]
Yeah the other teams are also informed. I again tried to reach out to Jaco so that we get access rights to the extension.

**Comment by valentunn** [comment]
Hey everyone, Valentin from Nova here. As for Nova Wallet & Polkadot Vault status:
1. We have finished the work related to `CheckMetadataHash` - the development build is compatible with latest Rococo. Waiting for finalization of Ledger apps configuration before releasing to production
2. Latest version of Polkadot Vault is able to decode & sign the transaction with `CheckMetadataHash` enabled. Tested in Nova<>Vault and PJS-UI-Vault pairings

**Comment by mustermeiszer** [comment]
Will all those fixes still allow for backward compatability - i.e. will chains without the `CheckMetadataHash` in their `SignedExtension` still work with the wallets?

**Comment by valentunn** [comment]
> Will all those fixes still allow for backward compatability - i.e. will chains without the `CheckMetadataHash` in their `SignedExtension` still work with the wallets?

Yes, it's backwards compatible

**Comment by bkchr** [comment]
> Will all those fixes still allow for backward compatability - i.e. will chains without the `CheckMetadataHash` in their `SignedExtension` still work with the wallets?

Yes. As all signed extensions, they are optional. Wallets can use the metadata to detect which signed extensions are enabled in the runtime to add the required data to the transactions.

**Comment by bkchr** [comment]
> In theory, yes. But this issue is probably the best proof for that to not always work. ^^

No, you misunderstood the issue. We upgraded Rococo to test out ledger etc. However, not all wallets and especially the PJS extension where ready to detect this new extension. It needs to be said that the extension was ENABLED on Rococo, while if you don't do anything, the extension will not be enabled. As the wallets don't know the extension, they fail to sign the extrinsics. 

You were asking about backwards compatibility, aka can the wallets detect that the extension is not there and still sign the extrinsics correctly. The answer to this is yes ;) I hope it is now more clear.

**Comment by mustermeiszer** [comment]
Yes, that is much clearer. So all wallets only sign what is there? I could remove one `Extra` and PJS would still be able to sign?

**Comment by SBalaguer** [comment]
@michalisFr, update on the list you provided before:

| Interface                                                               | Initial Status | Current Status | Publicly Deployed |
|-------------------------------------------------------------------------|----------------|----------------|-------------------|
| Accounts directly on PJS-UI                                             | Ok             | Ok ✅           | Yes            |
| Accounts in Polkadot Vault imported directly in PJS-UI                  | Ok             | Ok ✅           | Yes             |
| Accounts in PJS extension                                               | Not Ok         | Not Ok         | -                 |
| Accounts in Polkadot Vault imported in PJS extension                    | Not Ok         | Not Ok         | -                 |
| Accounts in Polkadot Vault imported in Subwallet extension              | Not Ok         | Ok ✅           | No                |
| Accounts in Polkadot Vault imported in Talisman extension               | Not Ok         | Ok ✅           | No                |
| Accounts in Subwallet extension                                         | Not Ok         | Ok ✅           | No                |
| Accounts in Talisman extension                                          | Not Ok         | Ok ✅           | No                |
| Fearless, Polkagate extensions                                          | Not Ok         | Not Ok         | -                 |
| Accounts in Subwallet mobile or managed through the Subwallet dashboard | Not Ok         | Checking...    |                   |
| Accounts in NovaWallet                                                  | Not Ok         | Ok ✅           | No                |
| Rococo faucet                                                           | Not Ok         | Ok ✅           | Yes               |

Some comments:
- PJS Extension: we are currently working on a solution to it, but it will not be available in the very short term. Using Nova, Talisman and Subwallet is recommended.
- Non-publicly deployed solutions (yet): Teams are working on these and will be releasing them together with the Kusama Runtime Upgrade: https://kusama.subsquare.io/referenda/406

**Comment by bkchr** [comment]
> Yes, that is much clearer. So all wallets only sign what is there? I could remove one `Extra` and PJS would still be able to sign?

Yes! For that we put the information about the used signed extensions into the metadata. This way, all wallets (not just PJS) can fetch this information and construct transactions correctly. This already works this way since some years.

**Comment by wischli** [comment]
> @michalisFr, update on the list you provided before:
> 
> Interface	Initial Status	Current Status	Publicly Deployed
> Accounts directly on PJS-UI	Ok	Ok ✅	Yes
> Accounts in Polkadot Vault imported directly in PJS-UI	Ok	Ok ✅	Yes
> Accounts in PJS extension	Not Ok	Not Ok	-
> Accounts in Polkadot Vault imported in PJS extension	Not Ok	Not Ok	-
> Accounts in Polkadot Vault imported in Subwallet extension	Not Ok	Ok ✅	No
> Accounts in Polkadot Vault imported in Talisman extension	Not Ok	Ok ✅	No
> Accounts in Subwallet extension	Not Ok	Ok ✅	No
> Accounts in Talisman extension	Not Ok	Ok ✅	No
> Fearless, Polkagate extensions	Not Ok	Not Ok	-
> Accounts in Subwallet mobile or managed through the Subwallet dashboard	Not Ok	Checking...	
> Accounts in NovaWallet	Not Ok	Ok ✅	No
> Rococo faucet	Not Ok	Ok ✅	Yes
> Some comments:
> 
> * PJS Extension: we are currently working on a solution to it, but it will not be available in the very short term. Using Nova, Talisman and Subwallet is recommended.
> * Non-publicly deployed solutions (yet): Teams are working on these and will be releasing them together with the Kusama Runtime Upgrade: https://kusama.subsquare.io/referenda/406

AFAICT, this list is outdated at this point? If so, could you update it please. I was able to sign with Talisman using a Chopsticks fork with WASM override.

**Comment by SBalaguer** [comment]
> could you update it please @SBalaguer

Updated @wischli :)

**Comment by wischli** [comment]
> > could you update it please @SBalaguer
> 
> Updated @wischli :)

Thanks a lot! Could you elaborate on the two partially deployed interfaces? We would like to launch this feature ASAP, i.e. next week shortly after it is enabled on Polkadot.

**Comment by SBalaguer** [comment]
@wischli, PJS Extension is not yet released on Firefox, and it's being checked by the Mozilla team still. It might take a bit more time until we get there, as the extension has not been updated in over 2 years. 

So what you can expect as full support right now on the new extrinsic format is the biggest wallets, plus PJS Extension on Chrome. As to supporting signing with the new Ledger App, what you can expect from day 0 (aka from July 1st) is full support on Talisman, Subwallet and Nova Wallet.

**Comment by clangenb** [comment]
As far as I know this can be closed now. @bkchr
