### ISSUE TITLE
Replace env_logger with sp_tracing

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#4660]
### Description of bug

`env_logger` working with `gum` seems to be skipping logs includes `CandidateHash`

### Steps to reproduce

Minimal test case: 
```rust
fn main() {
	env_logger::builder()
		.filter(None, log::LevelFilter::Info)
		.try_init()
		.unwrap();

	let a: i32 = 7;
	let hash = polkadot_primitives::Hash::repeat_byte(0xFA);
	let candidate_hash = polkadot_primitives::CandidateHash(hash);
	gum::info!(target: "bar", a, "xxx");
	gum::info!(target: "bar", a, ?hash, "xxx");
	gum::info!(target: "bar", a, ?hash, ?candidate_hash, "xxx");
}
```

Output:
```
[2024-05-31T12:03:56Z ERROR bar] xxx a=7
[2024-05-31T12:03:56Z INFO  bar] xxx a=7 hash=0xfafafafafafafafafafafafafafafafafafafafafafafafafafafafafafafafa
```

The third line with a candidate hash is absent. 

### What to do

We use `env_logger` only in tests, so it's better just to replace it with `sp_tracing`.

**Comment by alindima** [comment]
> But what about env_logger. As I see we use it only in tests, maybe it's better to replace it with sp_tracing and add a note somewhere about this bug?

I agree it'd be good to replace env_logger with sp_tracing where possible. Not sure what's the root-cause of this bug

**Comment by AndreiEres** [comment]
Updated issue, seems like a good first one

**Comment by Safrout1** [comment]
I would like to take this on, I will start with doing the replacement in all test files, should it be replaced somewhere else?

**Comment by AndreiEres** [comment]
> I would like to take this on, I will start with doing the replacement in all test files, should it be replaced somewhere else?

That's great! Let's start with tests but it would be great to understand where else we have it, maybe you can post a list here?

**Comment by Safrout1** [comment]
very very dumb question, what is the process to make a pull request here? is it a fork then a pull request from the fork? asking because I do not have permission to add a new branch here.

**Comment by AndreiEres** [comment]
@Safrout1 Yes, you have to do it over your own fork

**Comment by Safrout1** [comment]
@AndreiEres This is a draft pull request with one file only (for now), is this what we intend to do here, if yes, I will add all the other files: https://github.com/paritytech/polkadot-sdk/pull/5065
