### ISSUE TITLE
Parchains scheduler: ttl value is off

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#4695]
[This check](https://github.com/paritytech/polkadot-sdk/blob/f9e077a916a99db66d93630235b611def27bf2e3/polkadot/runtime/parachains/src/configuration.rs#L433) is nice, but in reality ttl should never be larger either as it then would allow one parachain to starve the other in a core sharing scenario.

We should just derive ttl from the lookahead directly and deprecate the ttl configuration.

The idea here was that collations can be backed out of order, but we don't actually do that and also agreed that it is a bad idea, with very little gain, but added complexity.

- [ ] Deprecate/remove ttl configuration value
- [ ] Ignore its value and instead make it always equal claim queue length
- [ ] Fix [this check](https://github.com/paritytech/polkadot-sdk/blob/9dfe0fee74ce1e4b7f99c1a5122b635aa43a1e5f/polkadot/runtime/parachains/src/scheduler.rs#L406) to `<=`.
- [ ] Test that backing in a core sharing fashion works, even if one para does not provide collations.
- [ ] Test that classic synchronous backing (12s block times) continues to work.

**Comment by eskimor** [comment]
In reality because of [this](https://github.com/paritytech/polkadot-sdk/blob/9dfe0fee74ce1e4b7f99c1a5122b635aa43a1e5f/polkadot/runtime/parachains/src/scheduler.rs#L406) the correct TTL value is even one less than the lookahead. So we should also fix line 406 to be `<=`.

**Comment by sandreim** [comment]
Closing in favor of https://github.com/paritytech/polkadot-sdk/issues/4776 which removes the TTL completely.
