### ISSUE TITLE
IPFS-hosted PJS not working

### ISSUE THREAD

**Issue by dcolley** [paritytech/polkadot-sdk#4703]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

It seem the deployment of the IPFS-hosted PJS is missing some files/config?

![image](https://github.com/paritytech/polkadot-sdk/assets/1845970/96a32ca8-857c-49eb-b261-3abb2d5abbbc)

After selecting an IBP endpoint, the app tries to contact `wss://kusama-rpc.publicnode.com`
![image](https://github.com/paritytech/polkadot-sdk/assets/1845970/2319a77b-1464-4f41-9067-b0ec73bcd47c)

### Steps to reproduce

Visit: https://ipfs.io/ipns/polkadot.dotapps.io/?rpc=wss%3A%2F%2Fsys.ibp.network%2Fstatemine#/accounts
Attempt a teleport
Check the console logs

**Comment by bkchr** [comment]
Please move the issue to the polkadot-js repos. Ty!

**Comment by dcolley** [comment]
Thanks, raised https://github.com/polkadot-js/api/issues/5900
