### ISSUE TITLE
New `#[runtime]` should be real rust Rust for assigning a type

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#4723]
The new `#[runtime]` macro is great, but the assignment of pallet types is awkward since the type is assigned to a crate name:

```
/// Mandatory system pallet that should always be included in a FRAME runtime.
#[runtime::pallet_index(0)]
pub type System = frame_system;
```

This is just not what would be valid in Rust.

Instead, we should simply update this to point to the `Pallet<T>` object, which is actually what is happening:

```
/// Mandatory system pallet that should always be included in a FRAME runtime.
#[runtime::pallet_index(0)]
pub type System = frame_system::Pallet<Runtime>;
```

This makes this line of code more accurate for what `System` or any pallet type represents, and also more in alignment with real Rust.

cc @gupnik @kianenigma

**Comment by gupnik** [comment]
> Instead, we should simply update this to point to the `Pallet<T>` object, which is actually what is happening:

Yeah, I had considered it but realised that this would mean an addition of `::Pallet<Runtime>` to all pallets without much benefit to the user. I wasn't sure if it was worth it, but happy to realign if we all agree that this is the correct way forward.

**Comment by shawntabrizi** [comment]
I think these extra characters are near zero overhead, but in fact having a user use the type `System`, in ways like `System::set_code()` in a test, and not realizing that `type System = frame_system::Pallet<Runtime>` is quite bad.

And, in the interest of having all substrate macros be as close to real rust as possible, it is also better that we just have it make sense that a struct is being assigned to a type.

Anyway, glad to know this will be a simple change.

**Comment by kianenigma** [comment]
Supporting both is a good compromise to make sure it is not a breaking change for existing users.
