### ISSUE TITLE
Number of simultaneously running parachains with one relaychain

### ISSUE THREAD

**Issue by f33r0** [paritytech/polkadot-sdk#4731]
Hello, I have encountered a problem that I can't launch more than two parachains registered in one chainspec. In the registration field, you can see all three, but in fact, only two work, the last third one cannot correctly import block 1 and endlessly reports its import. 

**Question**: are there any parameters in the chainspec that limit the number of parachains per relaychain?

relaychain chainspec: `rococo-local`
parachains: `karura-local`, `polkadot-local`, `asset-hub-rococo-local`

**Comment by eskimor** [comment]
How many validators does your relay chain have? Also some log output might be helpful. Can you share the polkadot js chain state output for paraScheduler -> claimQueue please?

**Comment by eskimor** [comment]
With two validators you can not have more than 2 cores/parachains at the same time. Simply spawning at least one more validator should resolve your issue.

**Comment by eskimor** [comment]
The easiest way to run test networks is [Zombienet](https://github.com/paritytech/zombienet).

**Comment by pepoviola** [comment]
Hi @f33r0, ping me if you need help with the zombienet setup. Running this network should be straight forward.
Thx!

**Comment by eskimor** [comment]
Vastly backwards compatible. Most of the time you just want to upgrade to get bug fixes/support for features like asynchronous backing.
