### ISSUE TITLE
Subkey doesn't build with +nightly flag, type annotations needed for Box

### ISSUE THREAD

**Issue by JamesArthurHolland** [paritytech/polkadot-sdk#4748]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Version used:
```
cargo 1.81.0-nightly (b1feb75d0 2024-06-07)
```

Time library won't compile 

```
error[E0282]: type annotations needed for `Box<_>`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.27/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

### Steps to reproduce

```
cargo +nightly build --package subkey --release
```

**Comment by ggwpez** [comment]
Seems like a bug in nightly then? I would recommend using stable Eust, as our CI only runs the tests with that.

**Comment by JamesArthurHolland** [comment]
Stable rust doesn't work either. I'm using alpine and it can't dynamically load clang, which I believe is an alpine issue.

**Comment by ggwpez** [comment]
Hm, okay. It does build with `nightly-2024-03-14` though, so maybe there is another one that is a bit newer and still works.
