### ISSUE TITLE
release `substrate-wasm-builder` with feature `metadata-hash` for polkadot-v1.12.0

### ISSUE THREAD

**Issue by clangenb** [paritytech/polkadot-sdk#4749]
It seems that the `substrate-wasm-builder` featuring https://github.com/paritytech/polkadot-sdk/pull/4619 has not been released with polkadot-v1.12.0. May I ask for such a release?

**Comment by clangenb** [comment]
@bkchr sorry for tagging you directly, but I think this is your domain :D

**Comment by ggwpez** [comment]
Yes we are also waiting for 1.11 release.

**Comment by clangenb** [comment]
I will close this one, as v1.13.0 will have it.
