### ISSUE TITLE
Query Fee Details no longer works on Westend and Kusama

### ISSUE THREAD

**Issue by trevor-crypto** [paritytech/polkadot-sdk#4770]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The RPC call - `payment_queryFeeDetails` and state call `TransactionPaymentApi_query_fee_details` are no longer working.

On Westend, it appears that the state call is no longer available, but the RPC call still remains, but ultimately calls the same code which is no longer there, but the RPC call is still present.

The error is as follows:

```
Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:\nerror while executing at wasm backtrace:
    0: 0x71d10 - <unknown>!rust_begin_unwind
    1: 0xc920 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
    2: 0x2664af - <unknown>!TransactionPaymentApi_query_fee_details")
```

Is there another endpoint that is available but undocumented, where fees can be calculated?

Thanks

**Comment by bkontur** [comment]
@serban300 Just in case, isn't it the same issue we had yesterday? That extrinsic should include `CheckMetadataHash` extension stuff?

**Comment by bkontur** [comment]
@trevor-crypto How did you trigger that calls? And how did you prepare data for those calls?

**Comment by bkontur** [comment]
@trevor-crypto and how or where do you construct `xt_hex_prefixed: &str`? Could you please point me to that code?

**Comment by trevor-crypto** [comment]
@bkontur Sure.

You first [construct the extrinsic](https://github.com/trevor-crypto/pdotc/blob/1704c46f53479b0c166c25cbdb787897495c074f/src/pallets/balances.rs#L12).

Then the [extrinsic is encoded ](https://github.com/trevor-crypto/pdotc/blob/1704c46f53479b0c166c25cbdb787897495c074f/src/lib.rs#L158)

Then you can [convert it to hex](https://github.com/trevor-crypto/pdotc/blob/1704c46f53479b0c166c25cbdb787897495c074f/src/lib.rs#L149)

Take a look at the [examples](https://github.com/trevor-crypto/pdotc/blob/master/examples/client.rs) for more details.

The code was and is still working for the chains that haven't been updated, which is why I think this was a breaking change.

**Comment by bkontur** [comment]
I think your `GenericExtra` could be the problem: https://github.com/trevor-crypto/pdotc/blob/master/src/lib.rs#L123-L134
it does not count with new `CheckMetadataHash` extension, which was added to the Westend: https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.11.0/polkadot/runtime/westend/src/lib.rs#L797C35-L797C52

We had to fix the same for our BridgeHubKusama yesterday, our fix: https://github.com/paritytech/parity-bridges-common/pull/3011/files#diff-46585d86003b12fcb45eacb4c7b2b45aa64d497ed66dae036144e2d38f4abeb4R36-R49

**Comment by trevor-crypto** [comment]
@bkontur Thanks! This does seem to be the issue. I've verified using PolkadotJS for now.

Quite the misleading error message!
