### ISSUE TITLE
Crowdloan not participating in Auction

### ISSUE THREAD

**Issue by SBalaguer** [paritytech/polkadot-sdk#479]
## Context
Auction paritytech/polkadot#45 started on Polkadot at [block 16_291_326](https://polkadot.subscan.io/block/16291326?tab=event&event=16291326-0). At that moment in time, two crowdloans were running: paraID 3338 and paraID3340. Both crowloands had an `ending_block` that was smaller than the Last Block of Auction 45, however greater than the start of the `ending_period` for Auction 45.

The moment that `start_period` of Auction 45 started, paraID's 3338 Crowdloan managed to place a bid. Noteworthy, all the blocks in `start_period` of any auction do not count to the actual candle stick auction mechanism.

![image](https://github.com/paritytech/polkadot/assets/10047147/f4bdd01c-08ab-4e53-b25f-4f3868b5ffe7)

## The Issue
At [block 16_2913_26](https://polkadot.subscan.io/block/16291326?tab=event&event=16291326-0) the `ending_period` of Auction 45 started, however none of the active crowdloans could place a bid. The action of placing a bid for both crowdloans would error out with `ConsumerRemaining`, as can be seen [here](https://polkadot.subscan.io/block/16305326?tab=event&event=16305326-0) for paraID 3340 and [here](https://polkadot.subscan.io/block/16305326?tab=event&event=16305326-1) for paraID 3338.

It is my understanding (but this could be wrong), that this Event is being triggered from the [`on_initialize` function](https://github.com/paritytech/polkadot/blob/894fef606a7a07ddb0ea3c2561145d21a53206c5/runtime/common/src/crowdloan/mod.rs#L357) from the Crowdloan Pallet.

After this, [several attempts](https://polkadot.subscan.io/event?address=&module=crowdloan&event=all&startDate=&endDate=&startBlock=16305326&endBlock=16308776&timeType=block&version=9420) were made by contributors to contribute to the crowdloan to see if that could potentially nudge _something_ and make the crowdloan bid. None of them were successful until:
- [This contribution](https://polkadot.subscan.io/extrinsic/16308580-3?event=16308580-43) for paraID 3340
- [This contribution](https://polkadot.subscan.io/extrinsic/16308775-3?event=16308775-55) for paraID 3338 

## Expected Behavior
The expected behavior was for the crowdloans to participate on the auction the moment the `ending_period` of the auction started.

After the nudge stated before, both crowdloans managed to place a bid and are competing in the auction.

## Related links
The following are some functions identified while trying to understand the issue.
- [on_initialize on Crowdloan Pallet](https://github.com/paritytech/polkadot/blob/894fef606a7a07ddb0ea3c2561145d21a53206c5/runtime/common/src/crowdloan/mod.rs#L335)
- [place_bid on Auctions Pallet](https://github.com/paritytech/polkadot/blob/894fef606a7a07ddb0ea3c2561145d21a53206c5/runtime/common/src/auctions.rs#L423)
- [ConsumerRemaining error on Substrate Runtime Primitives](https://github.com/paritytech/substrate/blob/70c0547f40daa8b550ef1a849514d07c385f963e/primitives/runtime/src/lib.rs#L550C10-L550C10)
- [ConsumerRemaining error on Substrat Frame System](https://github.com/paritytech/substrate/blob/70c0547f40daa8b550ef1a849514d07c385f963e/frame/system/src/lib.rs#L1145)

**Comment by kianenigma** [comment]
placing the bid will eventually lead to a problematic line of code that will attempt to reserve  all of the free balance in the crowdloan account. This was acceptable prior to https://github.com/paritytech/substrate/pull/12951 and no longer is. 

The fix, as the PR says, should be to increment the providers of any crowdloan account (assuming some sort of deposit is taken).

For example, this is the account of CL66 before and after their first successful bid. 

<img width="1697" alt="Screenshot 2023-09-06 at 18 31 13" src="https://github.com/paritytech/polkadot-sdk/assets/5588131/93fd1722-f3f8-44c9-87d4-175076ad8152">

If this is the correct patch, more important than the patch itself is to see why no unit tests in this pallet caught the issue, and make sure one is added. 

As a bonus, you can then look at the other pallets using `ReservableCurrency` and making sure they have a similar-ish test.

**Comment by gupnik** [comment]
I was able to setup a UT that reproduces this issue and it only happened if we were not incrementing the providers while creating the crowdloan. In the crowdloans that caused the issue, we could see only 1 provider before the bid which would make it fail when the entire amount is tried to be reserved.

However, the new ones already had 2 providers. So, it seems that the previous crowdloans were created before the change went live (and hence did not have the increment of the providers at creation). 

![new](https://github.com/paritytech/polkadot-sdk/assets/17176722/9a116655-59c8-4c23-a6bf-e2908d5397c2)

More info around the dates confirming that erroneous crowdloan was indeed created before the release:

- The erroneous crowdloan was created here:
<img width="969" alt="1" src="https://github.com/paritytech/polkadot-sdk/assets/17176722/40e1d271-9c79-4b20-a7d6-8e4fbf5e2aa4">

- https://github.com/paritytech/substrate/pull/12951 got included in this release:
<img width="967" alt="2" src="https://github.com/paritytech/polkadot-sdk/assets/17176722/2072a9fb-092e-4477-800c-909f0f88998d">

- The code got updated here:
<img width="976" alt="3" src="https://github.com/paritytech/polkadot-sdk/assets/17176722/b2868009-478f-4d93-bb2e-34955992de1d">
