### ISSUE TITLE
Pruning (State and Blocks Pruning)

### ISSUE THREAD

**Issue by andreclaro** [paritytech/polkadot-sdk#4801]
Hello Parity team,

I have the following questions regarding the pruning features:
1. `This setting can only be set on the first creation of the database` - Is this still true? 
2. Does the above statement also apply to `--blocks-pruning`? 
3. Any idea on how much storage saving do we expect to see if we only save 1 month worth of blocks (state and blocks bodies) compare with an archive node?

https://github.com/paritytech/polkadot-sdk/blob/ae0b3bf6733e7b9e18badb16128a6b25bef1923b/substrate/client/cli/src/params/pruning_params.rs#L30C1-L32C81

Thanks!

**Comment by bkchr** [comment]
> 1. `This setting can only be set on the first creation of the database` - Is this still true?

Partly, yes.



> 2\. Does the above statement also apply to `--blocks-pruning`?

No.



> 3\. Any idea on how much storage saving do we expect to see if we only save 1 month worth of blocks (state and blocks bodies) compare with an archive node?

Depends on the age of the chain etc. As the archive node is storing everything, the factor will increase over time.

**Comment by CumpsD** [comment]
In the docs I saw a non archive node also stores all history, just doesnt make it available to query, right? What would happen if you do --state-pruning 256 and --blocks-pruning 256? Would it make the size of a db manageable? Or still grow a lot over time?
