### ISSUE TITLE
numerical pruning value fail to parse

### ISSUE THREAD

**Issue by alindima** [paritytech/polkadot-sdk#4828]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When passing a numerical value to --state-pruning or --blocks-pruning (like 1000) to polkadot-parachain built from master, it fails with:

```
error: invalid value '1000' for '--blocks-pruning <PRUNING_MODE>'
[possible values: archive, archive-canonical, <NUMBER>]
```

Seems to have been broken by: https://github.com/paritytech/polkadot-sdk/pull/4810

I added some debug logs here: https://github.com/paritytech/polkadot-sdk/blob/6daa939bc7c3f26c693a876d5a4b7ea00c6b2d7f/substrate/client/cli/src/params/pruning_params.rs#L104 and this function is never called

### Steps to reproduce

build polkadot-parachain from latest master
run `polkadot-parachain --blocks-pruning 1000`

**Comment by alindima** [comment]
CC @bkchr

**Comment by bkchr** [comment]
Ahh 🙈🙈👀 fixing it.
