### ISSUE TITLE
Get rid of `libp2p` dependency in `sc-authority-discovery`

### ISSUE THREAD

**Issue by dmitry-markin** [paritytech/polkadot-sdk#4859]
`libp2p` types in authority-discovery should be replaced with network backend agnostic types from `sc-network-types`.

**Comment by gotnoshoeson** [comment]
I'll have a go at this one

**Comment by gotnoshoeson** [comment]
So I can remove the libp2p dependency but I'm not quite sure how/where to replace with sc-network-types. I don't see libp2p being used anywhere in the sc-authority-discovery directory.

**Comment by bkchr** [comment]
If it is not being used, then the pr would just be about removing the crate and that's it ;)

**Comment by alexggh** [comment]
> So I can remove the libp2p dependency but I'm not quite sure how/where to replace with sc-network-types. I don't see libp2p being used anywhere in the sc-authority-discovery directory.

You have to look for re-exported types as well for example the KademliaKey from here: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/authority-discovery/src/worker.rs#L45C30-L45C41.

**Comment by eagr** [comment]
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/authority-discovery/src/worker.rs#L171-L190

`Worker` is a public interface of `sc-authority-discovery`, which is relying on `Record` from libp2p. It seems to me ridding libp2p and replacing the type would be a breaking change. That right?

**Comment by dmitry-markin** [comment]
I don't see these types used in the public API, i.e., in [sc_authority_discovery::service::Service](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/authority-discovery/src/service.rs).

As for the types used internally (for example, in `DhtEvent::ValueFound`) — those should be replaced by network-backend-agnostic types put into `sc-network-types`.

**Comment by ndkazu** [comment]
Hello! Started working on this issue, and would like to get a first feedback to see if I'm on the right track:
https://github.com/paritytech/polkadot-sdk/pull/5842

**Comment by ndkazu** [comment]
Working now on removing `libp2p` from all the tests in `sc-authority-discovery`.

**Comment by ndkazu** [comment]
@dmitry-markin , @bkchr : removed `libp2p` dependencies from `sc-authority-discovery`. Review needed.

**Comment by dmitry-markin** [comment]
Done in https://github.com/paritytech/polkadot-sdk/pull/5842.

**Comment by dmitry-markin** [comment]
> So 2 issues out of 2 completed, what will be the next step @dmitry-markin? 👀

I don't have anything specific in mind. May be you can find something you like in the issues?
