### ISSUE TITLE
`AllowKnownQueryResponses` broken with new xcm router wrapper `WithUniqueTopic` 

### ISSUE THREAD

**Issue by JuaniRios** [paritytech/polkadot-sdk#4868]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The new `WithUniqueTopic` wrapper on the XCM Router appends a `SetTopic` at the end of any xcm message sent.

The `AllowKnownQueryResponses` allows messages that only have 1 instruction, `QueryResponse`.

This means that if you submit a query through XCM, and the destination uses the `WithUniqueTopic` router, your barrier will reject all responses.

Proposed fix:
- Expect either 1 message containing the response, or 2 with the last one being the topic.

I can submit a fix soon

### Steps to reproduce

- Send a message containing a query, like `QueryPallet` to a chain containing the `WithUniqueTopic` router.
- See in the logs how your barrier is rejecting the response.

**Comment by JuaniRios** [comment]
@franciscoaguirre

**Comment by bkontur** [comment]
@JuaniRios you need to wrap your barriers with [`TrailingSetTopicAsId`](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/xcm-builder/src/barriers.rs#L219), which is counter-part to `WithUniqueTopic`, you can try it e.g.:
```
TrailingSetTopicAsId<AllowKnownQueryResponses<..>>
```
There is also a [test](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/xcm-builder/src/tests/routing.rs#L26) for `TrailingSetTopicAsId`.

We wrap all our barriers with `TrailingSetTopicAsId`, e.g. https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/xcm_config.rs#L266

**Comment by JuaniRios** [comment]
@bkontur That's what I was looking for, thanks!
