### ISSUE TITLE
Finalization hangs in 1.13

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/polkadot-sdk#4903]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After upgrading Substrate from 1.10.1 to 1.13.0, now when finalizing a large-ish range of blocks `2056100..=2071630`, it seems to just hang. By "hang" I mean 30 minutes+ (didn't wait much longer yet, it is already ridiculous).

I see this message in logs:
> 2024-06-27T18:09:43.043948Z  WARN Consensus: sp_blockchain::backend: The distance between leafs and finalized block is large. Finalization can take a long time.

Which comes from https://github.com/paritytech/polkadot-sdk/pull/4721 that was supposed to introduce some optimizations.

Seems like a significant problem. I see one of the threads using 100% of CPU, but it is tokio's anonymous thread, so I'm not yet sure what it is and what it is doing.

cc @shamil-gadelshin

**Comment by bkchr** [comment]
Yeah the underlying problem is still: https://github.com/paritytech/polkadot-sdk/pull/3962

For a proper solution we need to record when a fork started. This way we don't need to do costly tree route.

**Comment by shamil-gadelshin** [comment]
Am I correct that the problem comes from calculating the `enacted` part of the `tree_route`? @skunert @arkpar @bkchr 

If this is the case - we can calculate only a `retracted` part separately for displaced branches on finalization which will remove the issue.

**Comment by bkchr** [comment]
The problem is more that we need to calculate the route between the last finalized block and every leaf. The retracted blocks are probably not such a big problem, because the leaves are probably around the head of the chain and thus, the retracted blocks are probably not that much.

But you are using some different consensus which I don't know in detail and you may have more, longer forks?

**Comment by shamil-gadelshin** [comment]
```
/// Tree route from R1 to En. Retracted is [R1 - R3], Common is C, enacted [E1 - En]
///   <- R3 <- R2 <- R1
///  /
/// C
///  \-> E1 -> E2 -> ... -> En
```

I understood the problem as such:
1. When we sync from genesis and finalize the tip - finalization invokes the fork calculation (displaced_leaves_after_finalizing) that invokes `tree_route` for each leaf.
2. `tree_route` calculates both `retracted` and `enacted` parts and the `enacted` part for each leaf is very long.

However, during the [fork pruning](https://github.com/paritytech/polkadot-sdk/blob/30cdf5dac8b8074a63d686477d1795494099a6be/substrate/client/db/src/lib.rs#L1862) we don't need to calculate the `enacted` part. If we calculate only `retracted` part either separately or by extending `tree_route` parameters - we won't invoke costly and redundant calculations for each leaf. 

Please, correct me if I'm missing something.

**Comment by skunert** [comment]
@shamil-gadelshin The first attempt to fix this will give you insight into the problem: https://github.com/paritytech/polkadot-sdk/pull/4721

Basically if we finalize a distance of 10_000 blocks and 3 leafs, we calculate the tree route between the leafs and the finalized block 10k times for each leaf. The first fix attempt made some assumptions that don't seem to hold.

As @bkchr said, the best fix would be to store the fork root and don't compute the displaced forks by tree route.

**Comment by nazar-pc** [comment]
I started looking into where slowness comes from and found that it is `displaced_leaves_after_finalizing`, which finds `12980` leaves and processes them at a rate of a few per second.

I see that `displaced_leaves_after_finalizing` and `tree_route` that is called from there both have a bunch of unoptimzed allocations (no reserved capacity), but the slowest piece of code seems to be this block:
```rust
	while to.number > from.number {
		to_branch.push(HashAndNumber { number: to.number, hash: to.hash });

		to = backend.header_metadata(to.parent)?;
	}
```

Judging by the fact that `from` and `to` are set to `leaf_hash` and `finalized_block_hash` accordingly, this does A LOT of duplicated calls to the same function with the same arguments over and over again. Just ridiculous amount. Above loop along takes ~190ms to complete on my machine.

This test was trying to finalize ~82k of blocks at once.

All of it can also be heavily parallelized, though not sure if it is a welcome thing in this context.

**Comment by nazar-pc** [comment]
I tried increasing `LRU_CACHE_SIZE` to 100k just to see what happens and it improved iteration of above loop by an order of magnitude immediately.

I'll look at optimizing those functions next, looks like there are some low-hanging fruits there.

**Comment by nazar-pc** [comment]
I'll send a PR later today or tomorrow with fix for this issue, in the meantime since I seem to touch code introduced back in 2019 I'm wondering if `undo_finalization` is still needed. It is not used, there are no tests for it and I'm wondering if there is a sane reason to ever call it at all.

**Comment by nazar-pc** [comment]
PR with fix: https://github.com/paritytech/polkadot-sdk/pull/4922
There are also next steps in there that would be great to get feedback on.
