### ISSUE TITLE
Make Westend Inflation Parameterize-able

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#4907]
Move the inflation forumula of westend to closely resemble what is the intended outcome of https://github.com/polkadot-fellows/runtimes/pull/364.

This allows us and the community to already test `pallet-parameters`. 

The actual inflation function doesn't matter much. Important is to make some part of it configurable by the `pallet-parameters`. It would be best if it almost matches what is intended to go into Polkadot/Kusama so we can test everything. 

Will be tipped :)

**Comment by marcuspang** [comment]
Hi @kianenigma, I would like to take up this issue if possible!

**Comment by kianenigma** [comment]
Available! Please share a draft PR early on so we can collaborate :)
