### ISSUE TITLE
Test `polkadot-node-core-pvf::it all_security_features_work` fails on 6.x kernel without landlock.

### ISSUE THREAD

**Issue by alvicsam** [paritytech/polkadot-sdk#4951]
Hi, I'm currently moving CI from Gitlab to Github and we are using GKE nodes with `cos_containerd` OS. As I recently found out, kernel in this OS doesn't have syscalls related to landlock. But the `polkadot-node-core-pvf::it all_security_features_work` test [fails](https://github.com/paritytech/polkadot-sdk/actions/runs/9743492692/job/26889919035#step:4:5636) because it assumes that the kernel has the feature. I also tried [this script](https://gist.github.com/alvicsam/b14e10e1fc8a9aedb0fe3923ef5e4e48) to check if the kernel has the necessary syscalls but the script says `Landlock is not supported on this system`. When this test is running on a system with a 5.10 kernel I don't see this problem. I have 2 questions related to this:

1. Could the test be fixed so that it correctly detects that the kernel has necessary syscalls?
2. How critical is to run this test on a non-restricted kernel? I am asking because there is an intention to replace wasmtime with polkaVM.

cc @s0me0ne-unkn0wn 
cc https://github.com/paritytech/ci_cd/issues/939

**Comment by s0me0ne-unkn0wn** [comment]
Currently, the test just checks if the kernel version is greater or equal to 5.13, and if yes, it presumes the landlock should be there. In principle, it's legit, but, as we can see, not in every case.

We could check if the kernel on the machine running the test really has landlock compiled in, and in that case, it shouldn't fail.

However, both the old and the proposed behaviors share a problem: the test is not deterministic; that is, it tests different things on different machines.

I'll try to fix the behavior. If it's found to be a non-trivial change, I'll disable the test altogether, as we cannot really tell what it's testing anyway.
