### ISSUE TITLE
substrate-wasm-builder bug in backport update to 1.1.0

### ISSUE THREAD

**Issue by alexxxkny** [paritytech/polkadot-sdk#4953]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I started getting compact wasm as WASM_BINARY instead of compact.compressed one. I believe that the reason is this backport update #4585. `compact_wasm_file` function returns `(wasm_compact_path, wasm_compact_compressed_path)` [here](https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.1.0/substrate/utils/wasm-builder/src/wasm_project.rs#L811). But parent function receive this as `(compressed, compact_blob_path)` [here](https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.1.0/substrate/utils/wasm-builder/src/wasm_project.rs#L206). Therefore compressed and compact paths are switched.

If you also depend on release-polkadot-v1.1.0 branch and are experiencing the same you can set substrate-wasm-builder to v12.0.0 from crates.io like this `substrate-wasm-builder = { version = "12.0.0" }`

**Comment by bkchr** [comment]
Ty for raising this @alexxxkny! I pushed a commit to the branch that fixes this!
