### ISSUE TITLE
Omni-node: TODOs

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#4966]
Opening this issue in order to track all the todos that we uncover related to omni-node and that we can't address on the spot. 

1. Metadata checks:
- if possible we should check if the runtime has all the RuntimeApis that are required. For example [the basic ones](https://github.com/paritytech/polkadot-sdk/blob/f7dd85d053dc44ee0a6851e7e507083f31b01bd3/cumulus/polkadot-parachain/src/common/mod.rs#L31-L37)
- also would be nice to check if the RPCs that are exposed are supported by the runtime. See this comment: https://github.com/paritytech/polkadot-sdk/pull/4916#discussion_r1666468216 

2. Remove the benchmark commands from polkadot-parachain: see comments [1](https://github.com/paritytech/polkadot-sdk/pull/5027#discussion_r1684300641), [2](https://github.com/paritytech/polkadot-sdk/pull/4916#discussion_r1665589880), [3](https://github.com/paritytech/polkadot-sdk/pull/4805#discussion_r1643895204): Here we need to wait for the CI `bot bench` commands to be migrated to omni-node first:
- https://github.com/paritytech/polkadot-sdk/pull/4405
- https://github.com/polkadot-fellows/runtimes/pull/379

**Comment by kianenigma** [comment]
Closing in favor of https://github.com/paritytech/polkadot-sdk/issues/5564 and https://github.com/paritytech/polkadot-sdk/issues/5565
