### ISSUE TITLE
Substrateinterface block info fetching bug

### ISSUE THREAD

**Issue by GeorgeVSV** [paritytech/polkadot-sdk#4975]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I currently face  issues with fetching block information  via  polkadot websocket endpoint (using substrateinterface lib in Python) for  blocks with specific transaction type, here are few samples:

Block  number : 21473809
Transaction type : convictionvoting (remove_vote)
Error  text:  ValueError: Index '20'' not present in Enum type mapping

Block  number : 21473810
Transaction type : balances (transfer_allow_death)
Error text:  RemainingScaleByteEmptyException: Decoding <GenericExtrinsic> - Current offset: 108 / length: 148

I would be grateful for any help

### Steps to reproduce

ENDPOINT= "wss://rpc.polkadot.io"
endpoint = substrateinterface.SubstrateInterface(url=ENDPOINT)
block_info = endpoint.get_block(block_number=21473810)
block_info

**Comment by bkchr** [comment]
Please open a bug in the relevant repo for the python interface.
