### ISSUE TITLE
Pallet without `try-runtime` feature flag produces a compiler warning

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#5092]
Ran into this while making some tutorial content:

```sh
warning: unexpected `cfg` condition value: `try-runtime`
  --> src/lib.rs:11:12
   |
11 |     #[pallet::pallet]
   |               ^^^^^^
   |
   = note: expected values for `feature` are: `default`, `std`
   = help: consider adding `try-runtime` as a feature in `Cargo.toml`
   = note: see <https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rustc-check-cfg> for more information about checking conditional configuration
   = note: `#[warn(unexpected_cfgs)]` on by default

warning: `pallet-kitties` (lib) generated 1 warning
```

This is reproducible by taking a pallet without `try-runtime` feature in the `Cargo.toml`, and then running:

```sh
cargo +nightly build
```

The solution can be to add `try-runtime = []` in the features, but probably better this is fixed within the macros and pallet code.

**Comment by gui1117** [comment]
I'm on it.

Also we could introduce 2 new attribute macros in `frame-support`:
* `#[cfg_feature_try_runtime]`
* and `#[cfg_feature_runtime_benchmarks]`.

User could use them to have some code discarded/included depending on whether `frame-support` has `try-runtime` or `runtime-benchmarks` features.

This would allow people not to have to bother adding `try-runtime` nor `runtime-benchmarks` in their `Cargo.toml` for their pallet.
And avoid some miss when configuring the runtime as well.

If I'm correct runtime crate would only need:
```toml
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
]
```
