### ISSUE TITLE
Missing the Polkadot People Chain chain-spec

### ISSUE THREAD

**Issue by josepot** [paritytech/polkadot-sdk#5112]
As of today the Polkadot People Chain chain-spec is nowhere to be found on this repo. Would it be possible to add it [into the same directory](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/parachains/chain-specs) where all the other system-chain-specs are? 🙏 

Also, FWIW if [RFC-8](https://github.com/polkadot-fellows/RFCs/blob/main/text/0008-parachain-bootnodes-dht.md) was implemented, then we wouldn't need this chain-spec 😉

**Comment by wirednkod** [comment]
It exists here: https://github.com/paseo-network/runtimes/tree/main/chain-specs
But is it something that should exist into the polkadot-sdk repo? 
@bkchr or @ggwpez  maybe you can give some insight?

**Comment by josepot** [comment]
> It exists here: https://github.com/paseo-network/runtimes/tree/main/chain-specs But is it something that should exist into the polkadot-sdk repo? @bkchr or @ggwpez maybe you can give some insight?

I'm afraid that you got mixed up, those are the chain-specs of Paseo. This issue is about the chain-spec of the Polkadot People Chain.

**Comment by wirednkod** [comment]
🤦🏽 Ufff... too many parallel things going on. Thank you for straighting this up @josepot

**Comment by seadanda** [comment]
Hi @josepot. The Polkadot People chainspec was included as an asset in the Fellows runtime 1.2.6 release here: https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.6

The hardcoded system parachain chain specs will soon be removed from `polkadot-parachain` and so chainspecs for new system parachains will not been added there. They will be found alongside their first released wasm in the fellowship repo from now on.

**Comment by josepot** [comment]
> The Polkadot People chainspec was included as an asset in the Fellows runtime 1.2.6 release here: https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.6

Thanks! Although, those bootnodes are all from Parity... where can we get a more complete list of bootnodes?

> They will be found alongside their first released wasm in the fellowship repo from now on

This would make a lot of sense if RFC-8 had ben implemented, as we could obtain the list of parachain bootnodes from the relay-chain. However, until that's not a reality, then we will need some sort of "authoritative" place for retrieving the bootnodes of the parachains.

**Comment by josepot** [comment]
> RE the bootnodes, there are five community invulnerables here but none marked as boot nodes at launch. I think usually the community add theirs afterwards in PRs like [this one](https://github.com/paritytech/polkadot-sdk/pull/4234). This is another point for keeping the chain specs somewhere which can be edited and changes tracked.

Exactly, yes. Thanks! This is exactly what I meant.

> For the Polkadot Coretime Chain I'll also gather some of these community boot nodes before launch.

🙌
