### ISSUE TITLE
Remove legacy substream handshake decoding from `Protocol`

### ISSUE THREAD

**Issue by altonen** [paritytech/polkadot-sdk#514]
https://github.com/paritytech/substrate/pull/13725#discussion_r1150260899
https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L434

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-5-0/5358/1
