### ISSUE TITLE
[CI] Check for getting-started script

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#5144]
The [getting-started](https://github.com/paritytech/polkadot-sdk/pull/4879) script should have a check in a Debian docker container (at least) to ensure that it wont completely break.  
MacOs docker would also be nice, if possible. We dont need to run this every time, just every week or so is fine.  

@apopiak are you interested in adding this maybe?

**Comment by kianenigma** [comment]
To begin with, `curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/paritytech/polkadot-sdk/master/scripts/getting-started.sh` is missing a `| bash` :D

**Comment by ggwpez** [comment]
We have CI checks for this now here https://github.com/paritytech/polkadot-sdk/blob/master/.github/workflows/check-getting-started.yml
