### ISSUE TITLE
network/litep2p: Publishes empty addresses at startup

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#5147]
https://grafana.teleport.parity.io/goto/V-MQGUXSR?orgId=1

When starting a node with litep2p enabled I see in the logs that it publishes on the DHT addresses which are not valid 

```
Publishing authority DHT record peer_id='12D3KooWSogJN9vDNkkpNFMAdDAB5XGUGaM5T8tDsB1F4x8vV2de' addresses='[]'
Publishing authority DHT record peer_id='12D3KooWKKotwpDtVqi7rZyKEovpVdDqiV9LuwVu1b3KTZgbXZw4' addresses='[]'
```

Nodes publish a few seconds later valid addresses, so this errors might be harmless, but they still need to be investigated.

cc: @paritytech/networking

**Comment by lexnv** [comment]
It looks like we rely on the Identify protocol to obtain the observed address.

When we receive a response via the identify info, we get the observed address and populate the `external_addresses`:

https://github.com/paritytech/polkadot-sdk/blob/18db502172bdf438f086cd5964c646b318b8ad37/substrate/client/network/src/litep2p/mod.rs#L919-L924

We only report back addresses that have been confirmed at least 5 times, although I believe the confirmation can come from the same peer multiple times:

https://github.com/paritytech/polkadot-sdk/blob/18db502172bdf438f086cd5964c646b318b8ad37/substrate/client/network/src/litep2p/discovery.rs#L445-L458

Definetly something to look into, this might be the reason why some validators are failing to connect.
I've also observed that libp2p can discover addresses much faster than litep2p, I think it relies on other mechanisms that we can look into

**Comment by lexnv** [comment]
Yep, it sounds good to me, exactly my plan (although I picked 2 confirmations instead of 3) :D

**Comment by alexggh** [comment]
Whatever solution we come up with, can we also make sure it fixes this case as well ?
