### ISSUE TITLE
Rework the event system of `sc-network`

### ISSUE THREAD

**Issue by altonen** [paritytech/polkadot-sdk#515]
Move notification-related functionality from `Peerset`/`NetworkWorker` to the protocol implementations and allow protocols to directly communicate with `Notifications`.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-5-0/5358/1
