### ISSUE TITLE
Old version support ("polkadot-v1.0.0") (as the tut said)

### ISSUE THREAD

**Issue by zzz6519003** [paritytech/polkadot-sdk#5171]
as the tut, https://docs.substrate.io/tutorials/collectibles-workshop/03-create-pallet/

what should I do if I want to use
```
[dependencies]
frame-support = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-v1.0.0"}
frame-system = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "polkadot-v1.0.0" }
```

**Comment by gui1117** [comment]
it should be added the Cargo.toml of your crate.

what is the question?

**Comment by zzz6519003** [comment]
Thx for reply, can’t find the url.

install fail cuz link broken, no branch name called this

**Comment by ggwpez** [comment]
1.0 was still released before we had the mono-repo in the old [substrate](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0) repo.  

Adding these crates with a specific branch is very old school, i will try to update that tutorial. Nowadays we have the [`polkadot-sdk`](https://docs.rs/crate/polkadot-sdk/latest), [docs](https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/reference_docs/umbrella_crate/index.html) (umbrella) crate, that bundles all other crates with compatible versions.

**Comment by ggwpez** [comment]
The work-around is to either use the new versions from `crates-io`, or use the `polkadot-sdk-frame` crate to simplify the process.  
Either way, some more up-to-date docs are here https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/your_first_pallet/index.html. It also mentions some templates that you can use to get started.

If you still want to use this older tutorial, try:
```toml
frame-support = { version = "36.0.0", default-features = false }
frame-system = { version = "36.0.0", default-features = false }
```

**Comment by zzz6519003** [comment]
The guide is awesome, but it’s not like a step-by-step tut.

thx for saving my day!

**Comment by zzz6519003** [comment]
after I change it to 
```
frame-support = { version = "36.0.0", default-features = false }
frame-system = { version = "36.0.0", default-features = false }
```
the code in tut is like
```
#![cfg_attr(not(feature = "std"), no_std)]

pub use pallet::*;

#[frame_support::pallet(dev_mode)]
pub mod pallet {
    use frame_support::pallet_prelude::*;
    use frame_system::pallet_prelude::*;

    #[pallet::pallet]
    #[pallet::generate_store(pub(super) trait Store)]
    pub struct Pallet<T>(_);

    #[pallet::config]
    pub trait Config: frame_system::Config {
    }
}
```

it get
- ```
unresolved import `pallet`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B2%5D?2#file%3A%2F%2F%2FUsers%2Fmac%2FDevelop%2Fblockchain%2Fsubstrate-node-template%2Fpallets%2Fcollectibles%2Fsrc%2Flib.rs)
```
- it can't find pallet::generate_store & pallet::pallet

**Comment by zzz6519003** [comment]
[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "codec/std",
  "scale-info/std",
]

**Comment by ggwpez** [comment]
We have a minimal example pallet here: https://github.com/paritytech/polkadot-sdk/blob/02e50adf7ba6cc65a9ef5c332b3e2974c8d23f48/templates/minimal/pallets/template/src/lib.rs#L14  

It does use the `frame` crate though, but maybe it helps. The line with the `generate_store` should be removed.

**Comment by zzz6519003** [comment]
sweet as Jesus, btw what is shell pallet

**Comment by ggwpez** [comment]
A "shell" like nothing inside. Just a blank pallet.

Happy that it worked 😄
