### ISSUE TITLE
network/litep2p: Kusama validator throws high number of MemoryStore warnings

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#5187]
The parity's kusama validator that is enabled with litep2p throws the following warning.

https://grafana.teleport.parity.io/goto/51vOfG9Sg?orgId=1

```
discarding a DHT record, because maximum memory store size reached max_records=1024
discarding a DHT record, because maximum memory store size reached max_records=1024
discarding a DHT record, because maximum memory store size reached max_records=1024
discarding a DHT record, because maximum memory store size reached max_records=1024
discarding a DHT record, because maximum memory store size reached max_records=1024
discarding a DHT record, because maximum memory store size reached max_records=1024
```

cc: @paritytech/networking

**Comment by lexnv** [comment]
The kusama validator was running for quite a long time, which inevitably resulted in many DHT records to store. For the first implementation, we evicted expired records on the `.get()` and for the `.put()` we simply returned on capacity.
This runs into problems when the `.get()` is never called although the record is expired.
A better solution for this would be to make space on the `.put()` of records: if we have reached capacity, evict records which are expired. One approach could be by storing records by expiry time, or by traversing the memory store on capacity


(older) Tracking issue in litep2p:
- https://github.com/paritytech/litep2p/issues/81

Will treat this with a higher priority

**Comment by alexggh** [comment]
> The kusama validator was running for quite a long time

Actually, this started happening immediately after it got restarted to a version containing this warning, so it might be something else.
```
2024-07-30 15:02:16.235 | 2024-07-30 12:02:16.206  INFO main sub-libp2p: Local node identity is: 12D3KooWLXZ2UWMy8QBpGEY1u4x4TdXpa5TVdBhaxkujKU9RvRub
```

**Comment by lexnv** [comment]
Yep, that's a bit odd. The PR that added the warning is adding the `RecordValidationMode::Manual` for substrate. Might be related 🤔

**Comment by lexnv** [comment]
This might have surfaced another issue, both libp2p and litep2p are using the same config of max 1k entries.

The implementation difference is that litep2p actively logs warnings when reaching capacity, while libp2p reports back an error which is logged here with debug:

https://github.com/paritytech/polkadot-sdk/blob/d993f59ab2ae400b125959008725e88dca7d3322/substrate/client/network/src/discovery.rs#L470-L491

Thinking of it, I wonder if we see a similar behavior on libp2p: meaning, we ignore records soonis (3h from the logs) after we start the node. These data points lean towards increasing the memory capacity of our record sore (both in libp2p iff confirmed and litep2p)

**Comment by alexggh** [comment]
My guess is this is the problem: https://github.com/paritytech/litep2p/blob/a49afe1a0c69a40b2bfac7f38fefed3df0fc08ca/src/protocol/libp2p/kademlia/mod.rs#L681, we shouldn't store any resolved key into the store, kusama has more than 1000 authorithies, as far as I can tell libp2p does not store them on query resolve, so it does not suffer from the same problem.

**Comment by lexnv** [comment]
Fix for this issue:
- https://github.com/paritytech/litep2p/pull/190

The fix gives us some breathing room to focus on other issues, until we tackle the memory store optimization: https://github.com/paritytech/litep2p/issues/81
