### ISSUE TITLE
Error: NetworkKeyNotFound

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#5211]
using `parity/polkadot-parachain:1.15.0`

```
root@03d37361194a:/# polkadot-parachain --base-path=/acala/data/Collator2  --chain /mandala.json  --collator -- --chain /rococo-mandala.json
Error: NetworkKeyNotFound("/acala/data/Collator2/chains/mandala-tc9/network/secret_ed25519")
```

I was trying to purge the node and I simply deleted `/acala/data/Collator2/chains/mandala-tc9` but now getting this error.
Looks like it errored when no collator key found but it shouldn't be a fatal issue?

**Comment by xlc** [comment]
ok found this

https://github.com/paritytech/polkadot-sdk/blob/6daa939bc7c3f26c693a876d5a4b7ea00c6b2d7f/substrate/client/cli/src/error.rs#L84-L93

it should log those messages

**Comment by alexggh** [comment]
It means that your node was missing the network key which is meant to be generated once and persisted across restarts, this was introduced for polkadot authorities to prevent accidental change of it,  but we concurred here https://github.com/paritytech/polkadot-sdk/pull/4957 that is desirable for any type of authorities as well.

It is weird `polkadot-parachain` doesn't show you the full error, `polkadot` definitely shows it, so I'll look into fix the error output.

**Comment by alexggh** [comment]
> It is weird `polkadot-parachain` doesn't show you the full error, `polkadot` definitely shows it, so I'll look into fix the error output.

Fix for this: https://github.com/paritytech/polkadot-sdk/pull/5214

**Comment by ozgunozerk** [comment]
@alexggh 

I encountered the same error, and tried the suggestions in the PR #5214 :

- [Preferred] Separately generate the key with: <NODE_BINARY> key generate-node-key --default-base-path
    - error: `unexpected argument 'key' found` -> if `key` refers to a variable, it should have been `<KEY>` but I guess that's not the reason I'm getting the error.
- [Unsafe] Pass --unsafe-force-node-key-generation and make sure you remove it for subsequent node restarts
    - has no effect and I'm still getting the original error of: `Error: NetworkKeyNotFound`


We are on `polkadot-stable-2407-1` tag. Do you have any educated guess on the reasons for the errors I'm getting above?

**Comment by alexggh** [comment]
> We are on polkadot-stable-2407-1 tag. Do you have any educated guess on the reasons for the errors I'm getting above?

@ozgunozerk Can you copy paste the commandline your are using for generating the keys and starting the node ?

**Comment by ozgunozerk** [comment]
@alexggh thanks a lot for the fast response!

This one for the `--unsafe-force-node-key-generation`:
```
./target/release/evm-template-node \
    --alice \
    --collator \
    --force-authoring \
    --chain raw-parachain-chainspec.json \
    --base-path storage/alice \
    --port 40333 \
    --rpc-port 8844 \
    -- \
    --execution wasm \
    --chain /var/folders/kl/404s241d4_93gz8mh4cg4cz80000gn/T/zombie-1b41a5961e22a4fcb9e3e5505a504b2e_-17088-eQJ75Xy4S8Jj/bob/cfg/rococo-local.json \
    --port 30343 \
    --rpc-port 9977 \
    --unsafe-force-node-key-generation
```
-> `Error: NetworkKeyNotFound`
    
And this one for the `key`:
```
./target/release/evm-template-node key generate-node-key --default-base-path
```
-> `unexpected argument 'key' found`

I also tried running the node executable by only providing `key`:
```
./target/release/evm-template-node key 
```
-> `unexpected argument 'key' found`

**Comment by alexggh** [comment]
```
./target/release/evm-template-node \
    --alice \
    --collator \
    --force-authoring \
    --chain raw-parachain-chainspec.json \
    --base-path storage/alice \
    --port 40333 \
    --rpc-port 8844 \
    --unsafe-force-node-key-generation \   #### You just insert and unsafe here and you should be unblocked.
    -- \
    --execution wasm \
    --chain /var/folders/kl/404s241d4_93gz8mh4cg4cz80000gn/T/zombie-1b41a5961e22a4fcb9e3e5505a504b2e_-17088-eQJ75Xy4S8Jj/bob/cfg/rococo-local.json \
    --port 30343 \
    --rpc-port 9977 \
    --unsafe-force-node-key-generation
```
