### ISSUE TITLE
Add support for ECDSA public key serialization (compressed/uncompressed)

### ISSUE THREAD

**Issue by conr2d** [paritytech/polkadot-sdk#5218]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

An ECDSA public key can be represented in either compressed (33 bytes) or uncompressed (65 bytes) form. While functions such as `sp_io::crypto::secp256k1_ecdsa_recover()` and `sp_io::crypto::secp256k1_ecdsa_recover_compressed()` facilitate public key recovery, there is currently no method available for converting a public key between these forms.

### Request

Introduce a method to serialize an ECDSA public key into either compressed or uncompressed form.

### Solution

Add a function to `sp_io::crypto` with the following signature:
```rs
fn secp256k1_pubkey_serialize(pubkey: &[u8], compressed: bool) -> Result<Vec<u8>, ()>;
```
This function will accept a public key and a boolean flag indicating whether the output should be in compressed form, returning the serialized public key accordingly.

### Are you willing to help with this request?

Yes!

**Comment by burdges** [comment]
I'm unsure how this comes up, but you should probably invoke an external rust crate like https://docs.rs/libsecp256k1 or https://docs.rs/secp256k1/ or https://docs.rs/k256 directly.

**Comment by conr2d** [comment]
- `ecdsa_verify`
- `ecdsa_verify_prehased`
- `ecdsa_batch_verify`
- `secp256k1_ecdsa_recover`
- `secp256k1_ecdsa_recover_compressed`

All of the above host functions can be implemented using a combination of `verify_prehased`, `recovery_prehased`, and `serialize`. I’m not fully aware of the rationale behind providing these specific functions, and I understand that the existing host functions cannot be removed due to the need to verify old blocks. However, it would have been preferable if these three functions had been provided from the beginning.
