### ISSUE TITLE
[XCM]: Remove NetworkIds for testnets

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot-sdk#5241]
Implement RFC https://github.com/polkadot-fellows/RFCs/pull/108

**Comment by programskillforverification** [comment]
So, it is specified only like `Bygenesis("d4e56740f87....")`?

**Comment by franciscoaguirre** [comment]
> So, it is specified only like `Bygenesis("d4e56740f87....")`?

Yes

**Comment by programskillforverification** [comment]
I will work on this.
