### ISSUE TITLE
Is there a build guide for this? why don't we open discussion for this repo? thx!

### ISSUE THREAD

**Issue by zzz6519003** [paritytech/polkadot-sdk#5251]
```[tasklist]
### Tasks
- [ ] build guide
- [ ] discussion for this repo
```

**Comment by ggwpez** [comment]
Depends on what you want to build: parachain, pallet, node, solochain...

The best that we currently have are the links in the README: https://github.com/paritytech/polkadot-sdk?tab=readme-ov-file#-documentation

> why don't we open discussion for this repo?

We have have SE https://substrate.stackexchange.com/ for technical questions and GitHub for Bugreports. Matrix for chatting and the forum and RFC for other stuff. Dont think it makes sense to split the conversion up even more - we are not that many people - the more communication channels there are the less helpful they become.
