### ISSUE TITLE
How can I enable the proof size recorder during runtime pallet testing?

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/polkadot-sdk#5276]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Request

I have written a question here: https://substrate.stackexchange.com/questions/11808/how-can-i-enable-the-proof-size-recorder-during-runtime-testing.

After [RFC-0043-Host function to provide the storage proof size to runtimes.](https://polkadot-fellows.github.io/RFCs/approved/0043-storage-proof-size-hostfunction.html#rfc-0043-introduce-storage_proof_size-host-function-for-improved-parachain-block-utilization), the proof_size can be accessible on the runtime side. I want to utilize this feature to refactor the project I'm working on, but I'm stuck at writing test cases.

After some investment in the polkadot-sdk, it seems the current `TestExternalities` doesn't support proof-reordering. I have tried to replace the backend in the TestExternalities with one that supports the proof recorder, but it doesn't work as intended. I'm raising this issue to seek ideas about the reason behind this. @skunert @bkchr 

### Are you willing to help with this request?

Yes!

**Comment by skunert** [comment]
Hi,

your problem is most likely that you are only writing the state. Only reads will go into the storage proof. Try reading a value ans see if that works.

As a general note, incorporating this host function in your runtime comes with some tradeoffs. Some clients like Smoldot will return no value for this call. Since they will call `validate` on your transactions, make sure transaction validity does not depend on the output of the hf. We integrated it mostly for the specific use case of  storage weight reclaiming.

**Comment by gui1117** [comment]
Depending in what you test for you could take inspiration on this code https://github.com/paritytech/polkadot-sdk/blob/12539e7a931e82a040e74c84e413baa712ecd638/cumulus/primitives/storage-weight-reclaim/src/lib.rs#L200

**Comment by boundless-forest** [comment]
> Only reads will go into the storage proof. 

Would you be able to clarify the reason for this?  For the relay chain, to verify the parachain execution, does it need all the storage it accessed, including both written and read ones? Why does the storage proof only contain the read ones? @skunert 

I also find something in https://substrate.stackexchange.com/questions/6920/does-runtimeapis-storage-accesses-counts-towards-pov-when-called-from-rpc-and-no, 

> "The storage proof (which is part of the Pov) is only collected while building a block. Each storage read that occurs in this process is included in the storage proof."
