### ISSUE TITLE
pallet_section not work for storage

### ISSUE THREAD

**Issue by open-junius** [paritytech/polkadot-sdk#5320]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

For the pallet which include many storage, we try to use the pallet_section to put some storage in separate file. but we get the compilation error as "error[E0425]: cannot find value `entries` in this scope".

### Steps to reproduce

source code: https://github.com/opentensor/subtensor/tree/junius-try-storage-macro/pallets/subtensor

steps:
1. git clone https://github.com/opentensor/subtensor
2. cd subtensor
3. git checkout junius-try-storage-macro
4. cd pallets/subtensor
5. cargo build

**Comment by sam0x17** [comment]
just wanted to bring some attention to this @gupnik / @kianenigma looks like storages don't work with `pallet_section`. I played around with it a little bit experimentally and I'm fairly certain it is an issue with `pallet_section`

**Comment by kianenigma** [comment]
Thanks for the report! 

@gupnik is OOO for the next 2 weeks, but I am sure he will attend to this when he's back.

**Comment by eagr** [comment]
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/procedural/src/pallet/expand/storage.rs#L912-L914

looks like the `entries` in the `#( #entries_builder )*` expansion won't be able to reference the `entries` defined outside, which is expected with the proc macro hygiene
