### ISSUE TITLE
How do we get block finalization for blockchains with a permanent gap?

### ISSUE THREAD

**Issue by shamil-gadelshin** [paritytech/polkadot-sdk#5323]
We use Substrate framework for our blockchain and encounter a problem with block finalization. It seems Substrate doesn't support a use case with a permanent block gap created by some form of fast sync.

Take `Client.apply_finality_with_block_hash` from `sc-service` crate for example: it uses `tree_route` method several times which will fail when we try to finalize a recent block received by sync (it will try to obtain a path to the last finalized block which will be the genesis and fail on missing blocks between genesis and some recent block having a permanent gap created by some form of fast sync).
Substrate solves it by downloading the gap and finalizing blocks after that (all the block headers will be present in the db). But what if in our case we don't need to download even headers?

How do we get block finalization having a permanent block gap?

Here is the related issue: https://github.com/paritytech/polkadot-sdk/issues/5119 (edited)

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@shamil-gadelshin 
Best Regards.

**Comment by bkchr** [comment]
Sounds like this is a duplicate of your own issue: https://github.com/paritytech/polkadot-sdk/issues/4407?

**Comment by shamil-gadelshin** [comment]
> Sounds like this is a duplicate of your own issue: #4407?

It's more like a subtask than a duplicate. We discovered it recently and the finalization problem was not mentioned in #4407

**Comment by shamil-gadelshin** [comment]
Substrate already has a way to deal with such cases. `BlockImportParams.finalized` resolves the issue!
