### ISSUE TITLE
chain-spec-builder convert-to-raw discards everything but the storages

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#5412]
It rebuilds a chainspec and discards all the details such as id, name, properties etc from the original chainspec.
Those info should be kept and only the `genesis` section should be modified.

**Comment by skunert** [comment]
Yes, this a problem with current chain-spec-builder, tracked here: https://github.com/paritytech/polkadot-sdk/issues/4873

Will close this as duplicate, a PR is in the works which will be merged soon hopefully: https://github.com/paritytech/polkadot-sdk/pull/4889

**Comment by michalkucharczyk** [comment]
shall be fixed in https://github.com/paritytech/polkadot-sdk/pull/4889
