### ISSUE TITLE
Subsystem benchmark memory profiling

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#5425]
It would be great to have this working along with CPU profiling. We could use it to investigate performance as well as memory leaks.

**Comment by AndreiEres** [comment]
We profile cache misses using valgrind. Could add more reports using other instruments from valgrind. But what exactly we need and for which cases?

**Comment by alexggh** [comment]
These are the steps that I've been playing with: https://www.magiroux.com/rust-jemalloc-profiling/, I'll follow with a PR to integrate it in subsystem-bench.

Most likely the same thing would have been achieved with valgrind instrumentation.

**Comment by alexggh** [comment]
Added support in https://github.com/paritytech/polkadot-sdk/pull/5522
