### ISSUE TITLE
Westend People is lacking the Proxy pallet

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-sdk#5453]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Unlike [Kusama People](https://github.com/polkadot-fellows/runtimes/blob/main/system-parachains/people/people-kusama/src/lib.rs#L600) and [Polkadot People](https://github.com/polkadot-fellows/runtimes/blob/main/system-parachains/people/people-polkadot/src/lib.rs#L565), the [westend people](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/people/people-westend/src/lib.rs#L420-L456) chain does not include the `Proxy` pallet. So does also [rococo people](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/people/people-rococo/src/lib.rs#L420-L456).

Obviously, the issue is not security on those chains but having the Proxy pallet allows testing on the testnets of scenarii that are in place with Proxy on the production chains.

### Steps to reproduce

Try setting a proxy on the `westend people` chain.

**Comment by seadanda** [comment]
Can confirm, it's also not on `people-rococo, coretime-(westend|rococo)`.
