### ISSUE TITLE
[subsystem-bench] approval-voting bench: network increased

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#5463]
<img width="998" alt="image" src="https://github.com/user-attachments/assets/eb2ebf37-a394-425f-aa8c-9475eea2e540">

https://paritytech.github.io/polkadot-sdk/bench/approval-voting-regression-bench/

@alexggh Could you look if it works as expected. If it's ok, we can just adjust our baseline to the new value, otherwise it fails every run in CI.

**Comment by alexggh** [comment]
> Could you look if it works as expected. If it's ok, we can just adjust our baseline to the new value, otherwise it fails every run in CI.

Yes, it works as expected if you looks the uber small spike appeared here: https://github.com/paritytech/polkadot-sdk/pull/4772 and here https://github.com/paritytech/polkadot-sdk/pull/5042, where we basically modified the benchmarks to send a few more messages.

I'll update the benchmark.
