### ISSUE TITLE
Use maximum allowed response size for request/response protocols

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#5503]
... related to https://github.com/paritytech/polkadot-sdk/issues/5334

The maximum response size for fetching PoVs and collations is hardcoded and needs to be updated before we can increase the on-chain maximum pov size:
https://github.com/paritytech/polkadot-sdk/blob/7e7c33453eeb14f47c6c4d0f98cc982e485edc77/polkadot/node/network/protocol/src/request_response/mod.rs#L220

We should remove the hardcoding and use the limit in substrate networking:
https://github.com/paritytech/polkadot-sdk/blob/717bbb24c40717e70d2e3b648bcd372559c71bd2/substrate/client/network/sync/src/block_request_handler.rs#L92

**Comment by eskimor** [comment]
As mentioned by @dmitry-markin in #5334 : We should indeed double-check timeout values whether they are still fine.
