### ISSUE TITLE
JSON-RPC messages arrive out of order

### ISSUE THREAD

**Issue by josepot** [paritytech/polkadot-sdk#5512]
The `chainHead` subscription implementation is not fully compliant with the JSON-RPC specification, as messages occasionally arrive out of order. This can cause inconsistencies in the event handling process. Below is an example demonstrating this issue:

```json
{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"newBlock","blockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a","parentBlockHash":"0xd0a64ca092b6ae44620ae99b3d6cf66664f2eaab8da5d8637304516fd29822f0","newRuntime":null}}}
{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"bestBlockChanged","bestBlockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a"}}}
{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"bestBlockChanged","bestBlockHash":"0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d"}}}
{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"finalized","finalizedBlockHashes":["0xb1796a1e2d6ef0d4ea4ae8c8a6126689389c336f2ee460356b47de5515559ca3"],"prunedBlockHashes":[]}}}
{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"newBlock","blockHash":"0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d","parentBlockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a","newRuntime":null}}}
```

In this sequence, the third message (`bestBlockChanged` with `bestBlockHash` `0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d`) should logically be the last one, as it refers to a block that has not yet been received via the `newBlock` event.

This issue was identified by @ryanleecode while working with the RPC endpoint `wss://westend-people-rpc.polkadot.io`, which is believed to be running the latest version of the node. The issue was originally reported in [this Polkadot-API issue](https://github.com/polkadot-api/polkadot-api/issues/671#issuecomment-2316164217).

According to the [JSON-RPC spec](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_v1_follow.html#usage), the order of these messages is critical to ensure correct event processing.

cc @jsdw @lexnv @bkchr

**Comment by jsdw** [comment]
Noted; we're having a look!

**Comment by jsdw** [comment]
@josep, by any chance do you have the ability to produce those logs with timestamps? Knowing which events were sent together (or close) might help narrow down the code path, as might a few lines of extra context at the end of those logs :) No worries if not though as we will be trying to reproduce the issue locally anyway!

**Comment by josepot** [comment]
> @Josep, by any chance do you have the ability to produce those logs with timestamps?

yeah, the [original logs](https://github.com/ryanleecode/papi-test-671/blob/master/test7.log) that Ryan captured using the `polkadot-api/logs-provider` have the timestamps:

```
1-2024-08-28T17:29:10.088Z->>-{"jsonrpc":"2.0","id":"1-38","method":"chainHead_v1_unpin","params":["w2bkfzBzOuXeldcS",["0xb70b2af07a93a3c038b0824eda7a388845c881370d51032ad405be0ff1fb0699"]]}
1-2024-08-28T17:29:10.195Z-<<-{"jsonrpc":"2.0","result":null,"id":"1-38"}
1-2024-08-28T17:29:12.219Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"newBlock","blockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a","parentBlockHash":"0xd0a64ca092b6ae44620ae99b3d6cf66664f2eaab8da5d8637304516fd29822f0","newRuntime":null}}}
1-2024-08-28T17:29:12.224Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"bestBlockChanged","bestBlockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a"}}}
1-2024-08-28T17:29:18.234Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"bestBlockChanged","bestBlockHash":"0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d"}}}
1-2024-08-28T17:29:18.237Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"finalized","finalizedBlockHashes":["0xb1796a1e2d6ef0d4ea4ae8c8a6126689389c336f2ee460356b47de5515559ca3"],"prunedBlockHashes":[]}}}
1-2024-08-28T17:29:18.237Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"w2bkfzBzOuXeldcS","result":{"event":"newBlock","blockHash":"0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d","parentBlockHash":"0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a","newRuntime":null}}}
```

**Comment by lexnv** [comment]
Have modified the [chainHead-cli tool](https://github.com/lexnv/chainhead-cli) to subscribe to the chainHead follow method and panic in case a best block is received before a new block:

```rust
RUST_LOG=info cargo run -- subscribe
```

I can't seem to reproduce this for around ~10 minutes, but will keep this running. 

Looking at the logs, this seems to happen after the `initialized` event indeed. Thanks a lot for the details here Josep! 🙏 

One thing worth considering here would be changing the subscription stream of new blocks:

https://github.com/paritytech/polkadot-sdk/blob/cc7ebe054038186c8a7409f54c4008ddc82a5ad0/substrate/client/api/src/client.rs#L64-L74

We currently use `import_notification_stream`, instead of `every_import_notification_stream` but that needs a closer look

**Comment by lexnv** [comment]
I was able to reproduce the issue with the `chainHead-cli`.

```
2024-08-29T10:57:36.275176Z  INFO chainhead_cli: Raw event: RawValue({"bestBlockHash":"0x2f08058c7e373b9c6165db91cd3f3bb75037e0b298dcb8c3e481af9d41a9eef0","event":"bestBlockChanged"})
2024-08-29T10:57:36.275231Z  INFO chainhead_cli: BestBlock event: BestBlock { event: "bestBlockChanged", bestBlockHash: "0x2f08058c7e373b9c6165db91cd3f3bb75037e0b298dcb8c3e481af9d41a9eef0" }
2024-08-29T10:57:36.275245Z  INFO chainhead_cli:  block entry Entry(VacantEntry("0x2f08058c7e373b9c6165db91cd3f3bb75037e0b298dcb8c3e481af9d41a9eef0"))
thread 'main' panicked at src/main.rs:251:25:

                        (best vacant) Expected block entry occupied with New state
```

I believe the culprit comes from:
https://github.com/paritytech/polkadot-sdk/blob/cc7ebe054038186c8a7409f54c4008ddc82a5ad0/substrate/client/rpc-spec-v2/src/chain_head/chain_head_follow.rs#L564-L585

Will try to reproduce locally to gain some extra insights.

**Comment by josepot** [comment]
> I can't seem to reproduce this for around ~10 minutes, but will keep this running.
> 
> Looking at the logs, this seems to happen after the `initialized` event indeed. Thanks a lot for the details here Josep! 🙏

I'm pretty sure that this only happens when a new block is discovered that belongs to a new fork and that block also happens to now be the best-block. So, yeah, that's why this can take a very long time to reproduce.

In the logs you can see exactly that happening first block `0xb2499db97650a723e2e3adeac3393cd395827db5aeef4512f4ab8c6a925a278a` gets announced and 5ms later it's announced as the best block, then the problematic message appears (10ms later) stating that the best block block is now `0xa5770d656f360a3cb1aa8be285ecec748e7063b1317eddc9f36db3dc8a78573d`. What happens next is interesting, though: 3ms later 2 messages arrive first one message announces a new finalized block, and then we get the message that announces the `newBlock` event of the problematic block.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-api-updates-thread/7685/15
