### ISSUE TITLE
Transfer gossiping messages from background tasks straight to event listeners

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot-sdk#554]
At the moment, each notification received from the network sends a message on a channel whose destination is the network worker. The network worker then reads from that channel and sends out events to various listeners grabbed via `NetworkService::event_stream`.

The problem is that this channel is already quite overloaded, and we should ideally try to reduce the traffic on this point of contention.

Instead, we should somehow make background tasks directly send notifications to the various listeners.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-5-0/5358/1
