### ISSUE TITLE
Make the notification protocols handshake message configurable through the API

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot-sdk#556]
At the moment, the handshake is hard-coded to be empty. After https://github.com/paritytech/substrate/pull/5665, it is hard-coded to be a single byte containing the `Role` of the node.

The intent, however, is to make this configurable by whatever code has registered a notifications protocol.

The difficult part in this is to figure out a good API for this.
I also don't think it's possible before paritytech/substrate#5670, because it is possible for the legacy substream to be opened before the notifications substream.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-5-0/5358/1
