### ISSUE TITLE
`polkadot-omni-node`: re-namings

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#5566]
- [x] Rename existing `polkadot-parachain` to `polkadot-omni-node`, and the existing `polkadot-parachain-lib` to `polkadot-omni-node-lib`. 
- [x] Remove any hardcoded chain-spec from `polkadot-omni-node`
- [x] Then, Create a new `polkadot-parachain` that is now an instantiation of `polkadot-omni-node-lib` with system chain specs hardcoded. 

A continuation of: https://github.com/paritytech/polkadot-sdk/issues/3944

It would be good to do this sooner rather than later to prevent breaking the names any longer.

**Comment by serban300** [comment]
Performed the renamings as part of #5915 

Left to do: 
- [ ] Publish the polkadot-omni-node binary
