### ISSUE TITLE
`polkadot-omni-node` Meta: Tutorials and reference docs. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#5568]
> You can see all related issues to omni-node, highlighted below [here](https://github.com/orgs/paritytech/projects/157). Forum post [here](https://forum.polkadot.network/t/polkadot-parachain-omni-node-gathering-ideas-and-feedback/7823/23)

Final outcome of the project should be as follows:

1. `polkadot-omni-node` binary, a white-labeled omni-node binary. This will be capable of running most parachains that don't do node side customization. 
2. `polkadot-omni-node-lib`, allowing teams to build their own omni-node. This enables a team 

> And, a `polkadot-parachain`, which is an instantiation of `polkadot-omni-node-lib` with system parachains chain specs hardcoded. This is mainly for backwards compatibility with existing infrastructure, see [here](https://github.com/paritytech/polkadot-sdk/issues/5210#issuecomment-2307052074).

The unique property of `polkadot-omni-node` is that it is a node that does not have any dependency on existing runtime, it ingests a chain-spec or a wasm file, and works based off this. 3 other tools have this property: 

1. `chain-spec-builder`
2. `frame-omni-bencher`
3. `try-runtime-cli`.

The main user story of omni-node-drive-development is then as follows: 

- Use a template that merely provides a runtime and a wasm file as the outcome. 
- Use `polkadot-omni-node --dev` for local testing.
- Use `chain-spec-builder` to generate your chain-spec file
- Use `frame-omni-bencher` to do benchmarking
- Use `try-runtime-cli` to do testing. 
- Use `zombienet` and/or `chopsticks` for further types of deployment. 
- Use `polkadot-omni-node --chain spec.json` as final way to deploy a parachain. 

This should be documented in a reference doc in polkadot-sdk, and advertised to external documentation teams. 

---

### EVM Support 

..**via frontier is not something that we foresee at the moment**, and instead would like to suggest using: 
- [Bodhi.js](https://github.com/AcalaNetwork/bodhi.js/) for `pallet-evm`
- for `pallet-contract`, `revive`, see https://github.com/paritytech/revive-ethereum-rpc

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-parachain-omni-node-gathering-ideas-and-feedback/7823/23
