### ISSUE TITLE
Fragment chain test might not use proper candidates list

### ISSUE THREAD

**Issue by kamilsa** [paritytech/polkadot-sdk#5617]
https://github.com/paritytech/polkadot-sdk/blob/986e7ae4f29f804ee4dc89aaf52984d6eda5bd0b/polkadot/node/core/prospective-parachains/src/fragment_chain/tests.rs#L1433-L1439

It is observed that in the given snippet of code used in the test of fragment chains functionality a shuffled list of candidates is created but is never actually used below in the test.

Please check if this test works properly (cc @alindima @iceseer)

**Comment by alindima** [comment]
good catch, thanks! indeed, I missed using the shuffled candidates list. I fixed this locally and the test passes. I'll fix it soon.
