### ISSUE TITLE
Replace `lazy_static` with `OnceLock`

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#5641]
We should be able to replace all `lazy_static` usages with `OnceLock` from the Rust standard library. This will bring us less dependencies. [The lazy_static README](https://github.com/rust-lang-nursery/lazy-static.rs?tab=readme-ov-file#standard-library) gives an example on how to do this.

**Comment by programskillforverification** [comment]
I would like to work on this, please assign to me

**Comment by bkchr** [comment]
Done

**Comment by programskillforverification** [comment]
@bkchr For some parts, maybe `LazyLock` is better option. It's not convenient to init static global var.
