### ISSUE TITLE
`CandidateValidationMessage::ValidateFromChainState` isn't used in production

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#5643]
We use it in examples and malus. If we cut it, it can simplify the logic. 
cc @s0me0ne-unkn0wn

**Comment by s0me0ne-unkn0wn** [comment]
CC @ordian @pepyakin 

I don't see any obstacles to removing it, but neither do I remember the reason for introducing it in the first place, so it would be good to have more eyes on it. I wonder when it was removed? Most probably it was used in disputes and maybe approvals. @alexggh @alindima do you remember removing it from there?

**Comment by alexggh** [comment]
> @alexggh @alindima do you remember removing it from there

Nope, but I always thought it was added for malus.

**Comment by ordian** [comment]
It seems to be removed in the initial async backing impl, in particular https://github.com/paritytech/polkadot/pull/5557. I don't recall the reason for it though, but it seems like it's not really needed anymore for production.
