### ISSUE TITLE
[Tracker] [Nomination Pools] Enabling Opengov voting support for Nomination Pool members

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#5659]
**This issue has been moved to [polkadot-fellows/runtimes](https://github.com/polkadot-fellows/runtimes/issues/455).**

[stable2409](https://github.com/paritytech/polkadot-sdk/issues/5583) release contains fixes post which Nomination Pool can switch to `DelegateStake` strategy. This will then allow Nomination Pool members to vote in opengov with their pooled funds.

## Timeline
- Linked [SDK Release](https://github.com/paritytech/polkadot-sdk/issues/5583): Planned on Sept 25, 2024.
- Kusama and Polkadot runtime upgrade is expected to happen within one month of SDK release. ETA: Oct 25, 2024.

## Checklist
- [ ] Runtime config changes and migration for Kusama and Polkadot. Refer [westend runtime changes](https://github.com/paritytech/polkadot-sdk/pull/3905/files#diff-5264d812f7aadfc486efffd3322b11c8dee5e8ddf2e77e0a9e70b573f3d2afddR1373).
- [ ] Migrate all pool members permissionlessly post runtime upgrade.

**Comment by Ank4n** [comment]
**This issue has been moved to [polkadot-fellows/runtimes](https://github.com/polkadot-fellows/runtimes/issues/455).**

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/changes-for-nomination-pool-members-and-opengov-participation/9651/9
