### ISSUE TITLE
Make NAT traversal more user-friendly

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-sdk#567]
During office hours today, we (re) realized that getting nodes to connect from behind routers is a bit of a pain for a user who is just looking to join a network.

One option is to use upnp. I had a good experience with that at rchain ([their upnp code](https://github.com/rchain/rchain/blob/ea966c7bd23e3c4f3d9cb872f5b6f7ae77acc6a7/comm/src/main/scala/coop/rchain/comm/UPnP.scala))

@folsen mentioned there are other solutions too.

I don't have strong feelings about which solution we use, or that it has to happen fast, but it would be one fewer hurdle for beginner and intermediate users.

**Comment by JoshOrndorff** [comment]
FWIW, It's 5 years later, and I still can't easily start a blockchain network at a meetup or an online workshop because of this issue. I always need a bootnode on some centralized aws-like thing for the users to connect too.

It isn't _that_ hard to set up now that I have experience, but it really undermines the whole "decentralized" point.

**Comment by bkchr** [comment]
Yes :) I mean it is a nice to have and I get where you are coming from. If we follow this route, we could speak about discovering nodes via bluetooth, mesh networks and whatever. However, Substrate is currently not build with this in mind. 

For local area networks we have MDNS that works quite okayish.

**Comment by aohan237** [comment]
> Yes :) I mean it is a nice to have and I get where you are coming from. If we follow this route, we could speak about discovering nodes via bluetooth, mesh networks and whatever. However, Substrate is currently not build with this in mind.
> 
> For local area networks we have MDNS that works quite okayish.

i think every node is equal to find and connect is the "decentralized" core, otherwise the whole web3 is built on a lie
