### ISSUE TITLE
bot bench: Allow passing feature flags

### ISSUE THREAD

**Issue by xermicus** [paritytech/polkadot-sdk#5714]
`pallet-revive` requires the `riscv` feature for benchmarks. We don't want to add it to `runtime-benchmarks` as that will require everybody else to have the rve toolchain installed. So we'd need a way to pass flags to the bot, however this doesn't seem to be supported currently? I imagine something like this should work: https://github.com/paritytech/polkadot-sdk/pull/5675#issuecomment-2343547579

**Comment by athei** [comment]
Just always enabling the `riscv` feature when benchmarking is good enough. That should be easier to implement than adding another command to parse.

**Comment by athei** [comment]
Is there any progress on this? Sorry don't want to be pushy but we can't really run benchmarks without this.

**Comment by mordamax** [comment]
@athei sorry for delay, will be done today 👌
