### ISSUE TITLE
StorageMap remove does not clear the key

### ISSUE THREAD

**Issue by dvcpull** [paritytech/polkadot-sdk#5717]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Lets say we have a StorageMap like this

```
	#[pallet::storage]
	pub type ItemsToProcess<T: Config<I>, I: 'static = ()> = StorageMap<
		_,
		Blake2_128Concat,
		BlockNumberFor<T>,
		BoundedVec<u32, T::MaxItemsToProcess>,
		ValueQuery,
	>;
```

Lets say we insert a key and remove it later like this
```
ItemsToProcess::<T>::insert(1, vec![].try_into().unwrap());

...

ItemsToProcess::<T>::remove(1);
```

When running test, this test fails (even after the removal of key, the contains key returns true)

```
assert!(!ItemsToProcess::<T>::contains_key(1))

```

This is inconsistent with searching for a random key, like this where it returns false correctly

```
assert!(ItemsToProcess::<T>::contains_key(123))

```

**Comment by ggwpez** [comment]
Why was it closed?
