### ISSUE TITLE
API `fn try_append` is missing for StorageNMap

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#5722]
Storage Map has `try_append` for pushing to a bounded vec: https://crates.parity.io/frame_support/pallet_prelude/struct.StorageMap.html#method.try_append

Storage N Map is missing this API: https://crates.parity.io/frame_support/pallet_prelude/struct.StorageNMap.html

**Comment by rainbow-promise** [comment]
Hey @shawntabrizi, I would like to take this on!

**Comment by CJ13th** [comment]
Sorry for the confusion @rainbow-promise, I saw this one via email notification and started working on it before I realised someone else had expressed interest. Hopefully we haven't duplicated our efforts! @shawntabrizi I have submitted a pull request for this here #5745 if you wouldn't mind  taking a look?

**Comment by shawntabrizi** [comment]
@CJ13th please do notify in the github issue next time :)

but no harm i think. maybe @rainbow-promise if you are interested you can do a code review along with us?

**Comment by rainbow-promise** [comment]
> @CJ13th please do notify in the github issue next time :)
> 
> but no harm i think. maybe @rainbow-promise if you are interested you can do a code review along with us?

Happy to @shawntabrizi and no problem @CJ13th, many other issues available.
