### ISSUE TITLE
Limit the amount of memory a contract can use

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#5725]
So far we only limit the size of the contract blob. However, the contract can declare static memory that is not included in the blob (zero initialized sections). The contract can also use sbrk to allocate more memory dynamically.

We need to limit both of those angles to make sure a contract can't drive the runtime oom.

Because the way how memory allocation will change in the future within PolkaVM we will go for this approach

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/pull/5726
- [ ] https://github.com/koute/polkavm/issues/167
```

cc @koute We need a config knob in PolkaVM to disable sbrk. Trapping on this instruction should be fine.

**Comment by Nathy-bajo** [comment]
Hi @athei 
Can I take a stab at this?
