### ISSUE TITLE
Dependency mismatch while upgrading parachain project to new sdk version.

### ISSUE THREAD

**Issue by Daanvdplas** [paritytech/polkadot-sdk#5751]
The last upgrades (1.13 - stable) we have done for our parachain projects have all been suffering the fact that we had to update certain packages in the `Cargo.lock` file. This is a tedious effort and bad developer experience.

Is there a way we can prevent this? It seems like this shouldn't be the case as prior upgrades didn't require this.

**Comment by bkchr** [comment]
Can you please explain in more detail what your problem was? I don't get it based on the current description. Sorry

**Comment by bkchr** [comment]
I can still not really follow. Next time the best would be that you directly report these issues, maybe some crate was not released properly or whatever. However, if you don't exactly know how you solved your issues, we can also not fix them. Sorry.

**Comment by Daanvdplas** [comment]
Will make a proper issue next time. Apologies for wasting your time!

**Comment by bkchr** [comment]
You didn't wasted my time :) Better to ask than us not improving this!
