### ISSUE TITLE
Add `GenesisConfig` presets for templates runtimes (minimal and solochain)

### ISSUE THREAD

**Issue by iulianbarbu** [paritytech/polkadot-sdk#5790]
The runtime should start exposing at least a `development` genesis-config, which should be used for testing omni nodes started based on chain-specs generated for templates runtime.

**Comment by bkontur** [comment]
@iulianbarbu I have also similar issue for other missing runtimes: https://github.com/paritytech/polkadot-sdk/issues/5704, you can take it, if you want :)
