### ISSUE TITLE
directory aware testing

### ISSUE THREAD

**Issue by Jan-Jan** [paritytech/polkadot-sdk#5810]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

At the moment if I run `cargo test` in the `polkadot-sdk/templates/solochain` it runs the test for the whole monorepo, instead of just running the tests specific to that directory (i.e. that you would get with `cargo test -p pallet-template`).

This directory aware testing would make it easier for noobs to contribute to the SDK (since a smaller, more targeted test set would run to specifically test their changes).

### Request

Create directory aware testing for each of the "components"/"sub-repos"

### Solution

Disclaimer: I have no idea how to implement this, but would be happy to learn.

### Are you willing to help with this request?

Yes!, Maybe (please elaborate above)

**Comment by ggwpez** [comment]
It could be done with a cargo extension, or possibly a cargo alias.  
Or we do it as part of this: https://github.com/paritytech/polkadot-sdk/issues/5192 (all in one solution) maybe you could kickstart this if you want? Does not look like anyone picked it up yet.

**Comment by bkchr** [comment]
This is a `cargo` related question. We are not writing `cargo`. Also this is quite a niche question and can be solved with a simple `find . -name Cargo.toml -exec cargo test --manifest-path {} \;` script.
