### ISSUE TITLE
Fix flaky zombienet tests `0005-parachains-disputes-past-session` 

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#5844]
`0005-parachains-disputes-past-session` is flaky and it should be fixed, can be reproduced locally by running the test in a loop.

E.g of failures: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7438523

**Comment by pepoviola** [comment]
@alexggh are you running locally with the native provider?

**Comment by pepoviola** [comment]
> > @alexggh are you running locally with the native provider?
> 
> yes.

Oks, so those failures aren't related to the resources in `k8s` 👍

**Comment by alexggh** [comment]
> > > @alexggh are you running locally with the native provider?
> > 
> > 
> > yes.
> 
> Oks, so those failures aren't related to the resources in `k8s` 👍

No, definitely something off in the main logic of the test @Overkillus  thoughts ?

**Comment by alexggh** [comment]
This is a duplicate of https://github.com/paritytech/polkadot-sdk/issues/578.
