### ISSUE TITLE
Remove usage of AccountKeyring

### ISSUE THREAD

**Issue by programskillforverification** [paritytech/polkadot-sdk#5858]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/keyring/src/lib.rs#L34
Compared with `AccountKeyring`, `Sr25519Keyring` and `Ed25519Keyring` are more intuitive.
When both `Sr25519Keyring` and `Ed25519Keyring` are required, using `AccountKeyring` bring confusion. There are two `AccountKeyring` definitions, it becomes more complex if export two `AccountKeyring` from frame.

### Request

remove all `AccountKeyring`, re-export `Sr25519Keyring` and `Ed25519Keyring` from `frame` so that don't need extra use `sp-keyring`

### Are you willing to help with this request?

Yes!

**Comment by bkontur** [comment]
Do you plan to do it as a part of  https://github.com/paritytech/polkadot-sdk/pull/5804?

**Comment by programskillforverification** [comment]
> Do you plan to do it as a part of #5804?

Yes.

**Comment by kianenigma** [comment]
If it is going to be part of the PR, I suggest either not creating a new issue that is going to be immediately closed, or please semantically link this issue to 5804 so that it will get closed when the PR is merged.

**Comment by programskillforverification** [comment]
> If it is going to be part of the PR, I suggest either not creating a new issue that is going to be immediately closed, or please semantically link this issue to 5804 so that it will get closed when the PR is merged.

I see. Now, maybe I plan to create new PR due to effect too many files.
