### ISSUE TITLE
Latest release contains clashing subdependencies

### ISSUE THREAD

**Issue by louismerlin** [paritytech/polkadot-sdk#5870]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When importing the latest released version of `kitchensink-runtime` as a dependency, Cargo finds clashing subdependencies: `primitive-types` versions 0.12.2 and 0.13.1 are incompatible, and both are present in the dependency tree.

See the error logs for more details.

[error.log](https://github.com/user-attachments/files/17190035/error.log)

### Steps to reproduce

Create a new Rust project with Cargo:
```
cargo new kitchensink-import-test
```
Append this line to the `Cargo.toml`:
```
kitchensink-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2409", features = ["std"] }
```
Try to build the project:
```
cargo +nightly build
```
You should get the same output as I provided.

**Comment by bkchr** [comment]
`cargo update -p ethabi-decode --precise 1.0.0` this fixes your issue. We need to upgrade here in the repo so that this doesn't happen anymore.

**Comment by ggwpez** [comment]
The offending `ethabi-decode` version should also be yanked now: https://github.com/Snowfork/ethabi-decode/pull/12  
I think we dont need to backport a version ping for that to `stable2409` since cargo should not pick up the yanked version anymore.  

Is it fixed for you?

**Comment by louismerlin** [comment]
Everything works on my end, thanks a lot for the support!
