### ISSUE TITLE
Missing Native Executable After Rust Version Upgrade

### ISSUE THREAD

**Issue by TabishVision** [paritytech/polkadot-sdk#5877]
We recently upgraded our Rust version from **nightly 2024-02-18** (with `rustc 1.78.0`) to **stable-x86_64-apple-darwin (default) rustc 1.81.0 (eeb90cda1 2024-09-04)** while working on our private Substrate node. After the upgrade, we encountered issues with missing native executables.

#### Steps to Reproduce

1. Upgrade Rust to version **1.81.0**.
2. Attempt to build the project with the command:
   ```bash
   SKIP_WASM_BUILD=1 cargo build --release
   ```
3. Observe that the native executable is generated, but the following error occurs:
   ```
   Error: Input("Development wasm not available")
   ```

#### Expected Behavior

The native executable should compile and run without errors, even when skipping WASM builds.

#### Actual Behavior

- The native executable is missing from `./target/release/<executable>` after the upgrade.
- When attempting to compile without WASM, we receive an error related to the availability of the Development WASM.

#### Additional Information

- We are using Substrate and related dependencies that might have changed between the versions.
- The project was compiling successfully before the upgrade to Rust 1.81.0.

#### Questions

1. Has there been any significant change in the dependencies or project structure between Rust versions that could affect the build process?
2. Are there any recommended steps to resolve the issue of the missing native executable and the WASM-related error?

Thank you for your assistance!

**Comment by bkchr** [comment]
If you update the compiler, just once compile without skipping the WASM build. There wasn't anything changed. Maybe the `OUT_DIR` changed and thus, it did not reused the existing build wasm files. 

As I said, just recompile and it is fine.
