### ISSUE TITLE
Probably incorrect one test of disputes

### ISSUE THREAD

**Issue by xDimon** [paritytech/polkadot-sdk#5900]
In the test [participation_with_onchain_disabling_confirmed](https://github.com/paritytech/polkadot-sdk/blob/b16237ad6f019667a59b0e3e726f6ac20e2d0a1c/polkadot/node/core/dispute-coordinator/src/tests.rs#L2739) I see two opposing votes - valid from baker and invalid from **disabled** validator. But although second validator named as **disabled**, his index is not return in result of query disabled validator ([query returns empty list](https://github.com/paritytech/polkadot-sdk/blob/b16237ad6f019667a59b0e3e726f6ac20e2d0a1c/polkadot/node/core/dispute-coordinator/src/tests.rs#L2739)). It seems as mistake in test. Without that test looks like as regular scenario of dispute escalation.

**Comment by xDimon** [comment]
cc @ordian

**Comment by ordian** [comment]
Indeed, good catch! Luckily, the corrected test still passes :)
