### ISSUE TITLE
Bounty Pallet: approve bounty with curator call

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#5928]
Part of https://github.com/paritytech/polkadot-sdk/issues/5500

### Goal: 
Approve bounties and curators with a single referendum.

### Solution:
Introduce `approve_bounty_with_curator(..)` call that would behave as a batch of the existing `approve_bounty` and `propose_curator` calls.

**Comment by davidk-pt** [comment]
Implemented
