### ISSUE TITLE
Expose NFTs and Uniques structs

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#5959]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

We are in the middle of building universal cross-chain pallet that allows you to bridge between nfts and uniques, so it doesn't matter which pallet your parachain implements. We are running into issue where storage structs of pallet nfts and uniques are private. Exposing them wouldn't cause any problems and will help us finish the pallet.

### Request

Expose structs in NFTs and Uniques pallets.

### Solution

I have attached PR that solves this: https://github.com/paritytech/polkadot-sdk/pull/6087

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
The `Item` storage is already public. This means you can already access all the data you need without requiring these getters.

**Comment by dudo50** [comment]
@bkchr accessing that storage from another pallet is not possible however because data in item struct are private.

Or is there any workaround I may be missing? Could you share snippet towards it? Thanks!

**Comment by dudo50** [comment]
@bkchr , to demonstrate what I meant, here is an example snippet:
```
let mut metadata = None;
if pallet_nfts::ItemMetadataOf::<T, I>::contains_key(&current_collection, &current_asset) {
	metadata = pallet_nfts::ItemMetadataOf::<T, I>::get(&current_collection, &current_asset);
	metadata = metadata.unwrap().data;
}
```
Results into following error:

```
error[E0616]: field `data` of struct `ItemMetadata` is private
   --> templates/parachain/pallets/xcnft/src/lib.rs:956:34
    |
956 |                 metadata = metadata.unwrap().data;
    |                                              ^^^^ private field
```

**Comment by bkchr** [comment]
Ahh! Yeah I only checked the storage items.

I think making these fields public is a better pr!

**Comment by dudo50** [comment]
@bkchr ,

Looking at the code:

```
/// Information about the item's metadata.
#[derive(Clone, Encode, Decode, Eq, PartialEq, RuntimeDebug, Default, TypeInfo, MaxEncodedLen)]
#[scale_info(skip_type_params(StringLimit))]
pub struct ItemMetadata<Deposit, StringLimit: Get<u32>> {
	/// The balance deposited for this metadata.
	///
	/// This pays for the data stored in this struct.
	pub(super) deposit: Deposit,
	/// General information concerning this item. Limited in length by `StringLimit`. This will
	/// generally be either a JSON dump or the hash of some JSON which can be found on a
	/// hash-addressable global publication system such as IPFS.
	pub(super) data: BoundedVec<u8, StringLimit>,
}
```

The item details struct is public as well as storage

```
	/// Metadata of an item.
	#[pallet::storage]
	pub type ItemMetadataOf<T: Config<I>, I: 'static = ()> = StorageDoubleMap<
		_,
		Blake2_128Concat,
		T::CollectionId,
		Blake2_128Concat,
		T::ItemId,
		ItemMetadata<ItemMetadataDepositOf<T, I>, T::StringLimit>,
		OptionQuery,
	>;
```

This leads me to a question - am I doing something wrong when trying to access these fields?

**Comment by dudo50** [comment]
@bkchr , I understood, as pointed in the comment, however, isn't it private to pallet_nfts for some reason? If it isn't then I will happily open PR that will expose these functions tommorow first thing in the morning.

Thanks in advance!

**Comment by dudo50** [comment]
@bkchr ,

I have opened a new PR that exposes structs as you requested:
https://github.com/paritytech/polkadot-sdk/pull/6087

I have tested it with build and run tests on it.

I have also updated the code of my pallet to interact with storage directly now, and it all works well.

Let me know if any other changes are required from me.

Thanks!

With kind regards,
Dudo

**Comment by dudo50** [comment]
@bkchr,
I have also run into same issues in pallet_uniques. Have updated PR exposing some structs in Uniques also. Also metadata storage for both collection and items were private there too, switched them to public.

This allows us to finish cross-chain NFT pallet that allows you to transfer collection and nfts between parachains, which can have different NFT pallets **universally**.

Please let me know if there is anything else needed in regards to PR attached to this Issue.

Many thanks!

Dudo
