### ISSUE TITLE
Parachain P2P bandwidth usage

### ISSUE THREAD

**Issue by rvalle** [paritytech/polkadot-sdk#596]
Hi!

We run an analytic indexing service. We run many archive nodes, and are planning for more.

We are currently looking at how to minimize p2p bandwidth usage.

On relay chain nodes we have been very successful. By using p2p parameters 2 in/out and connecting to reserved only nodes we get the bandwidth to be around 150Kbps, which is in line with the reported bandwidth used for sync. 

On parachain nodes, we see no way to go below 5 Mb/s, witch is 30x the p2p bandwidth of the Relay chain. 

This does not make any sense, I think there is something wrong.

We run the parachain node with similar p2p parameters and RPC to relay chain node, as follows: 

```
     --chain statemine
     --node-key xxxxx
      --relay-chain-rpc-url ws://ft8:9944 
      --out-peers 2 
      --in-peers 2 
      --in-peers-light 1 
      --max-parallel-downloads 1 
      --no-mdns 
      --no-private-ipv4 
      --reserved-only 
      --reserved-nodes RRRRRRR
      --reserved-nodes RRRRRRR
```

As the parachain fetches Relay blocks via RPC from a local node, there should not be any P2P traffic on that front. And the parachain (statemine) has way less activity than the relay chain. Yet P2P bandwidth usage is 30x that of a relay chain node.

Does not make any sense. 

We use docker containers to run these nodes, and the bandwidth can be measured with `iftop` a portrange filter can be added to measure the bandwidth of p2p  ` iftop -i eth1 -f portrange 30000:40000` for example.

**Comment by altonen** [comment]
@rvalle 

Have you upgraded your node or is this still happening?

**Comment by rvalle** [comment]
Thanks for following up @altonen 

Yes, bandwith usage has improved.

**Comment by altonen** [comment]
> Thanks for following up @altonen
> 
> Yes, bandwidth usage has improved.

Thanks for letting us know
