### ISSUE TITLE
Metadata V16: Have a vec of supported extrinsic versions

### ISSUE THREAD

**Issue by jsdw** [paritytech/polkadot-sdk#5980]
<=V15 metadatas contain a single extrinsic version field (set to 4 currently).

With V5 extrinsics coming, and runtimes that can support either V4 or V5 extrinsics, we should extens this to be a vec of the extrinsic versions that the runtime supports. This allows dApps/client libsto inspect that vec to understand whether they are able to construct a valid extrinsic for it.

**Comment by jsdw** [comment]
(I think this might already be done in the code, but wanted to make sure either way with the issue)

**Comment by bkchr** [comment]
https://github.com/paritytech/frame-metadata/pull/82#discussion_r1759829183

**Comment by lexnv** [comment]
Added this to [frame-metadata pr](https://github.com/paritytech/frame-metadata/pull/82/files#diff-f37e220a086df34a79724e6c39847334c03fe634544eef13c2308eeea6dad8f2R188-R189). It should be exposed in the enablement of V16-unstable [PR here](https://github.com/paritytech/polkadot-sdk/pull/5732/files#diff-412df6b3e2bce109162f65606ced885d1cfc6b6e1965b1e8df192044a18fa883R170).

I think its good to have this issue around to not forget about it, next steps here: release frame-metdata crate, merge associated types (https://github.com/paritytech/polkadot-sdk/pull/5274) and then the enablement PR
