### ISSUE TITLE
`#[feeless_if(..)]` breaks when used in a `#[pallet_section]`

### ISSUE THREAD

**Issue by sam0x17** [paritytech/polkadot-sdk#5981]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Right now one of the bugs with `#[pallet_section]` is if the external pallet section has a `#[feeless_if(..)]` anywhere in it, for some reason this causes a string of compile errors. A recent example is here but it is quite easy to reproduce: https://github.com/opentensor/subtensor/actions/runs/11215301673/job/31172208884#step:6:1609

I imagine this has something to do with how `feeless_if` is implemented interfering in some way with the `macro_magic` `import_tokens_attr` call. In theory this sort of thing should never happen so my guess is there is something weird going on in the parsing/expansion code for `feeless_if`, but I have not had a chance to look at it in depth.

debugging steps I would take would be:
* check out the parsing/expansion code for `#[feeless_if(..)]`, see if you can print something to the terminal from there and use bisection to figure out where the compile error is originating from

### Steps to reproduce

* make a new pallet, dev mode is fine
* define an external `#[pallet_section]`
* import that section using `#[import_section]`
* in this pallet section, use `#[feeless_if(..)]`
* you will get a compile error saying "expected a value" with a span pointing to the `#[pallet::pallet]` macro invocation site.

**Comment by eagr** [comment]
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/procedural/src/pallet/expand/call.rs#L260

looks like the `origin` in the expansion resolves to the wrong thing. similar to #5320, but for the opposite reason
