### ISSUE TITLE
Bug in backport branch `release-polkadot-v1.1.0` causes compilation error when `metadata-hash` feature is enabled

### ISSUE THREAD

**Issue by PanGan21** [paritytech/polkadot-sdk#5989]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When compiling our node using the `release-polkadot-v1.1.0` branch of the Polkadot SDK, with Rust 1.70 and the `metadata-hash` feature enabled, the compilation fails with the following error related to the visibility of the `MetadataExtraInfo` struct in the `substrate-wasm-builder` crate:
```
error[E0446]: crate-private type `MetadataExtraInfo` in public interface
  --> /Users/username/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/e51a91f/substrate/utils/wasm-builder/src/metadata_hash.rs:48:1
   |
48 | pub fn generate_metadata_hash(wasm: &Path, extra_info: MetadataExtraInfo) -> [u8; 32] {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can’t leak crate-private type
   |
  ::: /Users/username/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/e51a91f/substrate/utils/wasm-builder/src/builder.rs:26:1
   |
26 | pub(crate) struct MetadataExtraInfo {
   | ----------------------------------- `MetadataExtraInfo` declared as crate-private
```
The same issue occurs when trying to compile the Polkadot SDK on the `release-polkadot-v1.1.0` branch with the `metadata-hash` feature for the `westend-runtime` package.
This bug impacts the Energy Web X parachain, as we are unable to compile the SDK with the necessary features for ledger support.

Related to: https://github.com/paritytech/polkadot-sdk/pull/4585 https://github.com/paritytech/polkadot-sdk/pull/4274

Follow up questions:
- Can this be fixed so that the Energy Web X Parachain can support ledger integration?
- Which other backport branches, if any, are affected by this issue so we don't have to come back to this issue once we upgrade?

### Steps to reproduce

1. Checkout to the `release-polkadot-v1.1.0` branch of the Polkadot SDK.
2. Ensure that Rust 1.70 is used.
3. Try to compile the westend-runtime with the metadata-hash feature:
`cargo build --locked -p westend-runtime --features metadata-hash`

**Comment by bkchr** [comment]
You need to update your `rustc` and then the issue should be fixed.

**Comment by PanGan21** [comment]
After pulling the latest commit and using rustc: 1.80 I can confirm that the issue is fixed.
I hope that next `release-polkadot-v1.x.x` branches do not contain the same issue.

Thank you for the quick fix @bkchr .
