### ISSUE TITLE
approval-voting: approvals gossip and lazy signature checks optimizations

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#604]
## Problem ##

The overhead from gossip and signature check is significant as we scale the number of validators and parachains. An analysis of the overhead of current gossip topology and performance characteristics of approval vote signature checks can be found in https://github.com/paritytech/polkadot-sdk/issues/732  . The gist of it:
- 15K messages coming in from peers
- 938 assignments checked in 379ms
- 1373 approvals checked in 338 ms
- the rest(~250ms) book-keeping and forwarding message to the network bridge.

## Potential solution ##

We introduce a fast path which relies on the fact that we can be optimistic when sending and lazy when processing approval vote messages:
- no gossip, validators send approvals to all connected peers on the `Validation` peerset.
- no need to check signatures of the approvals if the sending peer is also the originator of the message

This fast path also works if the system is loaded with disputes since we check the vote signatures before pushing them on-chain for slashing the offenders so we still don't need to check them at receive time unless they arrive via gossip. The only drawback is that we won't be able to apply reputation changes for any bad approval signatures detected late.

### Slow path ###

We will revert to using gossip when approval checking is lagging by using the already existing implementation of `approval-distribution` aggression such that all validators send all messages to all peers in the X and Y dimensions of the topology. In such scenarios we perform signature checks only for approvals received from non originators.

## Concerns ##
 - it might be possible that we send an approval to a peer before it learns the assignment via gossip (slow path will help, or otherwise we could buffer orphan approvals + DoS protection)

**Comment by alexggh** [comment]
Will not implement because we are taking other optimization avenues.

**Comment by burdges** [comment]
> 938 assignments checked in 379ms
> 1373 approvals checked in 338 ms

Is this simply the time spent on signature checks?

How can there be (so many) more approvals than assignments?

How can checking the approvals signatures be so much slower per signatures?  VRFs should cost like 2x what the approvals do.

If the first is no, and approvals counds block execution too, then maybe the third comes from the parablocks being nearly empty.

**Comment by alexggh** [comment]
> Is this simply the time spent on signature checks?

It was all the time spent in check_and_import_assignment and check_and_import_approval, it isn't just the signature checks it is other bookkeeping as well.

> How can there be (so many) more approvals than assignments?

It was just some snapshot at specific moment in time. 

I would consider this measurements kind of obsolete now since a lot of optimisations already went in, this is the alternative path we want to work on now https://github.com/paritytech/polkadot-sdk/issues/1617.
