### ISSUE TITLE
[v0.9.43] Expose both 9933 and 9944 ports

### ISSUE THREAD

**Issue by yli-onf** [paritytech/polkadot-sdk#609]
I'm upgrading nodes to v0.9.43. I removed `--rpc-port=9933` and replaced `--ws-port=9944` with `--rpc-port=9944`, but an external call to port 9933 was not available (screenshot): 
<img width="1211" alt="Screenshot 2023-06-19 at 1 09 39 PM (1)" src="https://github.com/paritytech/polkadot/assets/137024984/b571f3b9-7241-41cc-a695-b1eca43d63d8">
Is there a way to expose both 9933 and 9944 for backward compatibility reason? If so, which parameter can I use?

**Comment by chevdor** [comment]
@Szymongib The fix was mentioned in this [releasenotes](https://github.com/paritytech/polkadot/releases/tag/v0.9.43).
The PR was breaking but mentioned as low prio so indeed not easy to spot. 
FYI we are working on a better way to provide more accurate descriptions of changes, stay tuned,

**Comment by niklasad1** [comment]
yeah, it was my fault I should have added a warning when starting up the node the `port 9944` will be removed soon....

It wasn't the intention for the beginning but was the only reasonable way forward.
