### ISSUE TITLE
XCM Deposit is not Unreserved after Closing XCM Channel

### ISSUE THREAD

**Issue by albertov19** [paritytech/polkadot-sdk#6101]
It is clear that when a team inits open or accepts an XCM channel, there is a deposit (currently 10  DOT) for each action:

- Init Open: https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1470-L1478
- Accept: https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1534-L1542 

Nevertheless, I don't see this balance being unreserved when the XCM channel is closed -> https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1593

Any reasons?

**Comment by bkontur** [comment]
`close_channel` does not close channel :), it just creates a request for closing `HrmpCloseChannelRequests`,
and the real closing is done on new session or something like that here:
https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1123-L1137

and there in the `close_hrmp_channel` is also `unreserve` calls.

So the real closing is done here: https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1137C5-L1137C23

**Comment by bkontur** [comment]
so, iiuc, when a team closes an HRMP channel, they receive their funds back in the new session

**Comment by albertov19** [comment]
Thanks for clarifying! That makes sense, maybe it would also make sense to reserve the balance when the actual channel is established then.

But it is clear! Thanks!

**Comment by bkontur** [comment]
> maybe it would also make sense to reserve the balance when the actual channel is established then.

I don't think so. The establishment is done asynchronously in the new session in [`process_hrmp_open_channel_requests`](https://github.com/paritytech/polkadot-sdk/blob/d5b96e9e7f24adc1799f8e426c5cb69b4f2dbf8a/polkadot/runtime/parachains/src/hrmp.rs#L1056). What if the relevant parachains don't have enough balance at that time? Potentially, those requests could hang indefinitely, and we need to handle that case (maybe with a timeout). I guess, it would complicate things, and perhaps there are other reasons why it isn't done this way.
Additionally, I think it's also a form of spam protection that para teams must pay a deposit on the `hrmp_init_open_channel` / `hrmp_accept_open_channel` extrinsics.
