### ISSUE TITLE
Clippy shows`unreachable-patterns` in `#[frame_support::pallet]` after update to Rust 1.81.0

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#6127]
During the update of Rust in runtimes, many warnings about `unreachable-patterns` in `#[frame_support::pallet]` appeared, as noted in https://github.com/polkadot-fellows/runtimes/pull/473. These warnings were silenced, but it is better to fix the bug in the macros.

```
error: unreachable pattern
   --> relay/kusama/src/governance/origins.rs:22:1
    |
22  | / pub mod pallet_custom_origins {
23  | |     use crate::{Balance, GRAND, QUID};
24  | |     use frame_support::pallet_prelude::*;
...   |
[19](https://github.com/polkadot-fellows/runtimes/actions/runs/11389304108/job/31688274427#step:7:20)6 | |     }
197 | | }
    | |_^ matches no values because `governance::origins::pallet_custom_origins::Call<T>` is uninhabited
    |
    = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types
    = note: `-D unreachable-patterns` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unreachable_patterns)]`
```

**Comment by bkontur** [comment]
I encountered the same issue [here](https://github.com/paritytech/subxt/pull/1814) when we were using `cargo +nightly clippy` in [bridges repo CI](https://github.com/paritytech/parity-bridges-common/pull/3059/commits/783806d258fbc98ecee988965685ee46c7d57439). This warning seems to be related to `+nightly`, which is likely why we haven't seen it in the `polkadot-sdk` repo - most, if not all, CI jobs were switched from `+nightly` to `stable` at some point (not sure why and I cannot find that PR).

Now, `polkadot-fellows` uses [`cargo +nightly clippy`](https://github.com/polkadot-fellows/runtimes/blob/main/.github/workflows/clippy.yml#L37). Shouldn't we switch and align that to stable as well? Giving it a try here: https://github.com/polkadot-fellows/runtimes/pull/489

Anyway, if we can fix it regardless of stable or +nightly, let's do it.

**Comment by bkchr** [comment]
@AndreiEres could you reproduce this on master? (I tried and failed) As I said already in the pr, there was already a similar issue that is now closed: https://github.com/paritytech/polkadot-sdk/issues/5697

**Comment by AndreiEres** [comment]
- Stable: `cargo clippy -p pallet-alliance`  shows no warnings
- Latest nightly: `cargo +nightly clippy -p pallet-alliance` shows warnings but not `unreachable pattern`
- CI nightly: `cargo +nightly-2024-09-11 clippy -p pallet-alliance` shows `unreachable pattern`
```
warning: unreachable pattern
   --> substrate/frame/system/src/lib.rs:672:12
    |
672 |     #[pallet::call]
    |               ^^^^ matches no values because `frame_support::Never` is uninhabited
    |
    = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types
    = note: `#[warn(unreachable_patterns)]` on by default
```

I suppose we can be OK with current situation, and since in runtimes we moved to a stable rust in CI we can close the issue. 
@bkchr, @bkchr WDYT?
