### ISSUE TITLE
Publish substrate-test-runtime-client alongside releases

### ISSUE THREAD

**Issue by drewstone** [paritytech/polkadot-sdk#6132]
Is there a reason the `substrate-test-runtime-client` is not published alongside releases? If I'm correct it is the only dependency on projects like Frontier that prevent that from publishing versioned releases/to creates.

**Comment by bkchr** [comment]
Basically the same as this answer: https://github.com/paritytech/polkadot-sdk/issues/5937#issuecomment-2395407051
