### ISSUE TITLE
`zombienet-bridges-*` test failures

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#6161]
The bridge zombienet tests are failing. 
For example:
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7607843
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7609603

We need to investigate this.

**Comment by bkontur** [comment]
I think it should be related to the: https://github.com/paritytech/polkadot-sdk/issues/6133

**Comment by pepoviola** [comment]
I updated the `NODE_OPTIONS` [here](https://github.com/paritytech/polkadot-sdk/pull/6139) to set `max-old-space-size=8192` and add the `tag` to run this job in the zombienet's cluster.

**Comment by serban300** [comment]
> I updated the `NODE_OPTIONS` [here](https://github.com/paritytech/polkadot-sdk/pull/6139) to set `max-old-space-size=8192` and add the `tag` to run this job in the zombienet's cluster.

Thanks ! This will probably fix the error above. Anyway, I see that other runs fail with:
```
Setting up the rococo side of the bridge. Logs available at: /tmp/bridges-tests-run-jK9AK/logs/rococo-init.log
Setting up the westend side of the bridge. Logs available at: /tmp/bridges-tests-run-jK9AK/logs/westend-init.log
Timeout waiting for file /tmp/bridges-tests-run-jK9AK/rococo.env: 600 seconds
```

So setting up the bridge times out. This is probably related to something else. Looking into it.

**Comment by serban300** [comment]
This is where it started failing: https://github.com/paritytech/polkadot-sdk/pull/6039

The problem is that the process of setting up the bridge is unsuccessful. For example for the Rococo side it fails here:
```
Input params: 
Generating hex-encoded call data for:
	type: check
	rpcEndpoint: --
	output: 
	inputArgs: 
Checking nodejs installation, if you see this everything is ready!
  calling force_create_foreign_asset:
      relay_url: ws://127.0.0.1:9942
      relay_chain_seed: //Alice
      runtime_para_id: 1000
      runtime_para_endpoint: ws://127.0.0.1:9910
      asset_multilocation: {
  "parents": 2,
  "interior": {
    "X1": [
      {
        "GlobalConsensus": "Westend"
      }
    ]
  }
}
      asset_owner_account_id: 5He2Qdztyxxa4GoagY6q1jaiLMmKy1gXS7PdZkhfj8ZG9hk5
      min_balance: 10000000000
      is_sufficient: true
      params:
Input params: {
  "parents": 2,
  "interior": {
    "X1": [
      {
        "GlobalConsensus": "Westend"
      }
    ]
  }
} 5He2Qdztyxxa4GoagY6q1jaiLMmKy1gXS7PdZkhfj8ZG9hk5 true 10000000000
Generating hex-encoded call data for:
	type: force-create-asset
	rpcEndpoint: ws://127.0.0.1:9910
	output: /tmp/tmp.I7imOIN4m4
	inputArgs: {
  "parents": 2,
  "interior": {
    "X1": [
      {
        "GlobalConsensus": "Westend"
      }
    ]
  }
},5He2Qdztyxxa4GoagY6q1jaiLMmKy1gXS7PdZkhfj8ZG9hk5,true,10000000000
Generating forceCreateAsset from RPC endpoint: ws://127.0.0.1:9910 to outputFile: /tmp/tmp.I7imOIN4m4 based on assetId: {
  "parents": 2,
  "interior": {
    "X1": [
      {
        "GlobalConsensus": "Westend"
      }
    ]
  }
}, assetOwnerAccountId: 5He2Qdztyxxa4GoagY6q1jaiLMmKy1gXS7PdZkhfj8ZG9hk5, isSufficient: true, minBalance: 10000000000
2024-10-21 18:02:31        REGISTRY: Unknown signed extensions StorageWeightReclaim found, treating them as no-effect
2024-10-21 18:02:31        API/INIT: RPC methods not decorated: chainHead_v1_body, chainHead_v1_call, chainHead_v1_continue, chainHead_v1_follow, chainHead_v1_header, chainHead_v1_stopOperation, chainHead_v1_storage, chainHead_v1_unfollow, chainHead_v1_unpin, chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties, transactionWatch_v1_submitAndWatch, transactionWatch_v1_unwatch, transaction_v1_broadcast, transaction_v1_stop

<--- Last few GCs --->

[483712:0x713f3d0]   287966 ms: Mark-Compact 4233.8 (4327.4) -> 3978.8 (4072.9) MB, 61329.24 / 0.00 ms  (average mu = 0.007, current mu = 0.004) allocation failure; GC in old space requested
[483712:0x713f3d0]   288020 ms: Scavenge 4010.5 (4088.9) -> 4012.2 (4090.9) MB, 15.00 / 0.00 ms  (average mu = 0.007, current mu = 0.004) allocation failure; 
[483712:0x713f3d0]   288036 ms: Scavenge 4012.2 (4090.9) -> 4010.5 (4105.1) MB, 16.45 / 0.00 ms  (average mu = 0.007, current mu = 0.004) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

```

I don't think the nodejs heap size is the issue here. Checking.

**Comment by pepoviola** [comment]
Yes, I try increasing the size of the heap (2x) and I get the same error, something is leaking and consuming memory. I also check with Tarik about recent changes in `pjs` but they don't receive any performance issue. 
Also, worth noting that this other test `zombienet-polkadot-smoke-0004-coretime-smoke-test` (https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7596992) also is failing with a similar js oom error.

Thanks!

**Comment by serban300** [comment]
Now the Rococo -> Westend transfer works. The Westend -> Rococo transfer fails:
https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7620163

Doesn't seem related to the signed extensions. Investigating

**Comment by serban300** [comment]
Looks like the issue was introduced by https://github.com/paritytech/polkadot-sdk/pull/5461

Investigating why
