### ISSUE TITLE
parachain build error with polkadot-stable2407-3, as patched crates are missing vendoring

### ISSUE THREAD

**Issue by clangenb** [paritytech/polkadot-sdk#6185]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I had to downgrade a few crates after upgrading to 2024-3 with psvm because the crates haven't been found. The affected crates can be seen here, https://github.com/ajuna-network/ajuna-parachain/commit/13c02b8b20e908e6551114e49933c84d5d354e56.

Downgrading them fixes the issue.

### Steps to reproduce

1. Get a parachain
2. run `psvm -v polkadot-stable2407-3`
3. cargo tree -i -p sp-core

**Comment by xlc** [comment]
related: https://github.com/polkadot-fellows/runtimes/issues/493

I raised this issue somewhere (can't find it anymore, I guess I asked someone in one of the Element room), but essentially the patch are not published to crates.io, which is very bad.

**Comment by clangenb** [comment]
Hmm, I see. I agree that this should be fixed. Otherwise, the only one who benefit from patches are node operators or devs who depend on the git source of the polkadot sdk. But the latter don't need to care about releases in the first place. Thanks for answering.

I will close this issue though in favor of https://github.com/paritytech/polkadot-sdk/issues/6206, as the underlying issue is the same.
