### ISSUE TITLE
Introduce `ConstUint` to replace `ConstU*` for convenient runtime configuration

### ISSUE THREAD

**Issue by conr2d** [paritytech/polkadot-sdk#6193]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

The current approach in Substrate runtime configuration requires defining separate types (`ConstU8`, `ConstU16`, `ConstU32`, etc.) for constants that represent basic unsigned integer types. This results in repetitive code and limits flexibility.

### Request

Consider the proposed introduction of `ConstUint` in `Solution` section.

### Solution

https://github.com/conr2d/polkadot-sdk/blob/const-uint/substrate/primitives/core/src/const_uint.rs

I have introduced a new type, `ConstUint`, which implements the `Get` trait for the basic unsigned number types (`u8`, `u16`, `u32`, `u64`, `u128`, and `usize`). This allows for more flexibility in handling constants in configuring runtimes.

**Registered default config:**
```patch
// Example from pallet_balances::pallet::config_preludes::TestDefaultConfig
#[register_default_impl(TestDefaultConfig)]
impl DefaultConfig for TestDefaultConfig {
  type Balance = u64;
  // The ConstU64<1> is replaced by ConstUint<1>.
-  type ExistentialDeposit = ConstU64<1>;
+  type ExistentialDeposit = ConstUint<1>;
  /* ... other configurations ... */
}
```

**Derived config example:**
```rs
#[derive_impl(pallet_balances::config_preludes::TestDefaultConfig)]
impl pallet_balances::DefaultConfig for TestDefaultConfig {
  type Balance = u128;
  // Even though we've changed the Balance type from u64 to u128,
  // no need to specify ConstU128<1> for ExistentialDeposit, as ConstUint covers it.
  // type ExistentialDeposit = ConstU128<1>;
}
```

### Benefits

- Compile-Time Error Handling
  If the default constant value is out of range for the newly configured type, it will be caught at compile time, preventing potential runtime errors.

- Simplification of Type Definitions:
  `ConstUint` reduces the need for multiple `ConstU*` types, making the configuration simpler and less repetitive.

### Next Steps

If this feature is acceptable, I will proceed with creating a pull request for it. Currently, `ConstUint` is added to `sp-core`, but I would appreciate your feedback on whether it would be better to move it to `parity-common/bounded-collections`, in line with other `ConstU*` types.

### Are you willing to help with this request?

Yes!

**Comment by bkchr** [comment]
Generally this is a nice idea!

> I would appreciate your feedback on whether it would be better to move it to `parity-common/bounded-collections`, in line with other `ConstU*` types

Yes, please do it this way.

**Comment by conr2d** [comment]
I'll continue the work once the new version of the `bounded-collections` crate is published.

**Comment by bkchr** [comment]
@conr2d would be nice if you prepare a pr to bump the version.
