### ISSUE TITLE
Correct chain names for assethub on polkadot and kusama for dev environment

### ISSUE THREAD

**Issue by BuddyGlas** [paritytech/polkadot-sdk#6225]
I'm totally confused, please help me understand.
I need to get the sources of spec files of assethub for polkadot and kusama respectively.
Running the commands:
```
./polkadot-parachain build-spec --chain asset-hub-polkadot-local
./polkadot-parachain build-spec --chain asset-hub-kusama-local
```
but I get an error in response:
```
Error: Input(‘Error opening spec file `asset-hub-polkadot-local`: No such file or directory (os error 2)’)
```
same for statemine-local and statemint-local

If I don't use the -local suffix, I get specs in RAW format, which I don't need. I need the source.
So how to run assethub on polkadot and kusama for dev environment?

**Comment by bkchr** [comment]
`cargo run -p chains-spec-generator -- --chain asset-hub-kusama-local > asset-hub-kusama.json`

**Comment by BuddyGlas** [comment]
@bkchr My heartfelt thanks to you!
