### ISSUE TITLE
PVF worker version mismatch during development

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot-sdk#626]
During the development process, if the code of the `polkadot-node-core-pvf-worker` package is changed, it can lead to a worker version mismatch error on the next run. Probably caused by the `polkadot-node-code-pvf` package not being recompiled and is keeping the old version. Should be fixed as it impedes development.

This does not affect either production or CI builds, as well as any other clean builds.

Some additional details are available here: https://github.com/paritytech/polkadot/pull/7253#issuecomment-1555014422

**Comment by mrcnski** [comment]
Haven't hit a version mismatch yet, nor received more reports about it. :] And [this PR](https://github.com/paritytech/polkadot-sdk/pull/1495) makes the check more lenient:

> now we won't get a node/worker version mismatch between releases (during development). Workers should still get rebuilt on every commit so breakages should be rare, but we just won't enforce that, which is fine for most dev.

Please re-open if there are more reports!
