### ISSUE TITLE
approval-voting: enable v2 assignments

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#628]
Once https://github.com/paritytech/polkadot/pull/6782 is merged both v1/v2 will be supported. The plan is to enable v2 assignment generation once enough validators have upgraded but only for Kusama and the other testnets. Once we rule out any issues we should also enable on Polkadot.

**Comment by alexggh** [comment]
Assignment v2 are enabled on kusama, next will be Polkadot.

**Comment by alexggh** [comment]
Enabled on polkadot with: https://polkadot.subsquare.io/referenda/888.
