### ISSUE TITLE
Invalid warning for parachain node

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#6280]
```
WARNING: No public address specified, validator node may not be reachable.
          Consider setting `--public-addr` to the public IP address of this node.
          This will become a hard requirement in future versions.
WARNING: No public address specified, validator node may not be reachable.
          Consider setting `--public-addr` to the public IP address of this node.
          This will become a hard requirement in future versions.
```

got this warning with using omni parachain node from stable2409 branch, which is false positive. it is kind of a blocker before we would like to push this version out for all Acala node operators
and it got printed twice, implying the validator flag is also enabled for the relaychain part, which is wrong

**Comment by skunert** [comment]
cc @lexnv

**Comment by lexnv** [comment]
Will prioritize this right away, sorry for the inconvenience
