### ISSUE TITLE
Register parachain bootnodes on the relay chain

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#629]
I was thinking a bit about UX of parachains in general and especially when it comes to on-demand parachains. In theory, if you set up a good incentivization model, it could become possible to create an on-demand parachain without actually running any collators (yourself). You could just write the code, then start selling token on some already existing chain in the ecosystem. Then organizations could exist, whose business it is to run collator infrastructure. They could buy those tokens, spawn up collator nodes for that new chain, transfer those tokens over to the new chain and start validating/collating - earning block rewards as usual. 

The original author and other users can then "just" connect and profit. They could be using light clients to do so, so no RPC nodes would be required, but even in full p2p fashion we do need boot nodes. What we could do here, is provide the means to register boot nodes for a parachain on the relay chain in a permission less manner: Anyone willing to pay some deposit (amount determined by the one who registers the PVF), can register a boot node for the parachain. 

Obviously, a registered boot node could be garbage, but this is what the deposit is for. Amount of garbage addresses should be limited fairly well by this, on top of that a slashing mechanism can be in place, either by the PVF registering account or more decentralized by some account controlled by the parachain itself, which can then use on-chain governance to remove a boot node (and slash the deposit).

With this we should be able to discover and make use parachains as soon as we have some connection to the relay chain. Deploy an on-demand parachain would now be as straight forward as deploying a smart contract: All you need to do is: Write the code!

**Comment by ordian** [comment]
Is this superceded by https://github.com/paritytech/polkadot-sdk/issues/1825?

**Comment by tomaka** [comment]
I wasn't aware of this issue!

#1825 and the RFC are less ambitious than this issue, so feel free to close or not.

**Comment by eskimor** [comment]
Yes, let's close.
