### ISSUE TITLE
Incorrect compiler error message about a trait import

### ISSUE THREAD

**Issue by Yung-Beef** [paritytech/polkadot-sdk#6303]
I'm trying to hash something with `BlakeTwo256::hash_of(data).into()`, it told me I needed to add `use frame::primitives::BlakeTwo256;` and then said hash_of wasn't in scope and I should add `use polkadot_sdk_frame::traits::Hash`. 

However, that doesn't exist, and I need `use frame::traits::Hash`.

I believe this is related to issue [3813](https://github.com/paritytech/polkadot-sdk/pull/3813) and possibly concerns lines 53-64 [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/support/procedural/tools/src/lib.rs), but I could not find where the compiler error is being generated from.

**Comment by ggwpez** [comment]
Can you post the whole error message please? The error is possibly generated by the compiler.

**Comment by Yung-Beef** [comment]
`error[E0599]: no function or associated item named `hash_of` found for struct `BlakeTwo256` in the current scope
   --> src/tests.rs:504:40
    |
504 |         let new_dna: [u8; 32] = BlakeTwo256::hash_of(&unique_payload).into();
    |                                              ^^^^^^^ function or associated item not found in `BlakeTwo256`
    |
    = help: items from traits can only be used if the trait is in scope
help: trait `Hash` which provides `hash_of` is implemented but not in scope; perhaps you want to import it
    |
14  + use polkadot_sdk_frame::traits::Hash;
    |
` @ggwpez

**Comment by Yung-Beef** [comment]
I know the package is named `polkadot_sdk_frame` and it's renamed or something inside the crate, is the compiler not able to understand that? If I try `use polkadot_sdk_frame::traits::Hash;` I get
```
error[E0433]: failed to resolve: use of undeclared crate or module `polkadot_sdk_frame`
  --> src/tests.rs:21:5
   |
21 | use polkadot_sdk_frame::traits::Hash;
   |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `polkadot_sdk_frame`

```

**Comment by gui1117** [comment]
Do you have a branch to look at to reproduce?
