### ISSUE TITLE
Create CI workflow that checks README.docify.md's are in sync with README.mds

### ISSUE THREAD

**Issue by iulianbarbu** [paritytech/polkadot-sdk#6331]
https://github.com/paritytech/polkadot-sdk/pull/5954 will introduce a README.md generated from a README.docify.md. We used `docify::compile_markdown!` inside the `lib.rs` of the `staging-chain-spec-builder` crate.

We must search for README.docify.md in the repo, and run `cargo build --features generate-readme` in the dir of the file (assuming it is related to a crate). If the `git diff` shows some output for the `README.md`, then the file update wasn't pushed on the branch, and the workflow should fail.

**Comment by virajbhartiya** [comment]
Can I work on this?

**Comment by iulianbarbu** [comment]
Hey @virajbhartiya ! Thanks for the interest and sure, you can look into it. Will assign this to you in the meantime.
