### ISSUE TITLE
Update polkavm to the upstream toolchain version

### ISSUE THREAD

**Issue by jarkkojs** [paritytech/polkadot-sdk#6335]
## Overview

1. Bump the polkavm(-*)? dependency everywhere.
2. This will require you to update the executor as it is using polkavm to execute runtimes.(first link)
3. Update the wasm-builder to use an upstream toolchain (as I did in 6266 for the fixtures). This produces the artifacts used by the executor.

Ideally, wasm-builder could be used to build the test fixtures. However, that is not feasible because it allows only one crate per package. Therefore, a separate build script was implemented in #6266 them.
 
## Relevant Paths

- https://github.com/paritytech/polkadot-sdk/tree/master/substrate/client/executor/polkavm
- https://github.com/paritytech/polkadot-sdk/tree/master/substrate/utils/wasm-builder
- https://github.com/paritytech/polkadot-sdk/tree/master/polkadot/node/core/pvf
- https://github.com/paritytech/substrate/blob/master/utils/wasm-builder/README.md

## Toolchains

- Old: **riscv32ema-unknown-none-elf**
- New: **riscv32emac-unknown-none-polkavm**

## Test Case

```
cd polkadot/node/core/pvf
cargo test
```

**Comment by jarkkojs** [comment]
The first thing I did:

```
$ git grep -l riscv32ema-unknown-none-elf | xargs sed -i 's/riscv32ema-unknown-none-elf/riscv32emac-unknown-none-polkavm'
```

**Comment by jarkkojs** [comment]
@koute Is that a legit test case? I saw that runners set up in `src/testing.rs` by default set `SKIP_WASM_BUILD`.

**Comment by koute** [comment]
> @koute Is that a legit test case? I saw that runners set up in `src/testing.rs` by default set `SKIP_WASM_BUILD`.

I'm not entirely sure what you're asking about here, but, the way to test it would be essentially something like this (writing this from memory, so not 100% sure if this still works):

```
SUBSTRATE_RUNTIME_TARGET=riscv SUBSTRATE_ENABLE_POLKAVM=1 RUST_LOG=polkavm=debug cargo run --release -p staging-node-cli
```

Basically, setting `SUBSTRATE_RUNTIME_TARGET=riscv` will make the `wasm-builder` crate build a RISC-V runtime instead of a WASM runtime, and `SUBSTRATE_ENABLE_POLKAVM=1` will allow the executor to load that blob (by default this code path is disabled). With this you should be able to use a normal node client to run a local test chain using it.

**Comment by jarkkojs** [comment]
> > @koute Is that a legit test case? I saw that runners set up in `src/testing.rs` by default set `SKIP_WASM_BUILD`.
> 
> I'm not entirely sure what you're asking about here, but, the way to test it would be essentially something like this (writing this from memory, so not 100% sure if this still works):
> 
> ```
> SUBSTRATE_RUNTIME_TARGET=riscv SUBSTRATE_ENABLE_POLKAVM=1 RUST_LOG=polkavm=debug cargo run --release -p staging-node-cli
> ```
> 
> Basically, setting `SUBSTRATE_RUNTIME_TARGET=riscv` will make the `wasm-builder` crate build a RISC-V runtime instead of a WASM runtime, and `SUBSTRATE_ENABLE_POLKAVM=1` will allow the executor to load that blob (by default this code path is disabled). With this you should be able to use a normal node client to run a local test chain using it.

Thank you! At least it is in the right direction.
