### ISSUE TITLE
Nomination pools Runtime API: Get a pool stash and reward address

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-sdk#6358]
A good use case for a runtime API is to fetch a pool's stash and reward address. E.g. `poolAddresses(poolId)`.

In Dapps we are currently using code similar to the following for determining a pool's stash and reward address, which adds complexity and deals with low level binary operations and magic constants - this is not too Dapp developer friendly:

```
  const createAccount = (poolId: BigNumber, index: number): string => {

    return api.registry
      .createType(
        'AccountId32',
        u8aConcat(
          ModPrefix,
          poolsPalletId,
          new Uint8Array([index]),
          bnToU8a(new BN(poolId.toString()), U32Opts),
          EmptyH256
        )
      )
      .toString();
  };
```

This seems to be a low hanging fruit to improve the developer experience for pools.

**Comment by kianenigma** [comment]
cc @re-gius this can be prototyped on top of #4722
