### ISSUE TITLE
Review for registering PNA on Ethereum

### ISSUE THREAD

**Issue by yrong** [paritytech/polkadot-sdk#6378]
### Sudo call for registering WND on Ethereum

```
0x630004000100a90f040c2f00000602070008d6e82982ee360038530a0401000c574e440c574e440c2000
```

**Comment by yrong** [comment]
### Transfer WND to ethereum from AH

```
0x1f0204020109079edaa8020400010300302f0b71b8ad3cf6dd90adb668e49b2168d652fd0404010000070010a5d4e800000000
```

**Comment by bkchr** [comment]
I think this was solved for you in the support chat?

**Comment by yrong** [comment]
### Transfer WND from Ethereum to AH  

https://sepolia.etherscan.io/tx/0xa5678c9c6c90d0086ba744c8131a5011496bc4fbc6c22dbec8f8fbc3b2c236f5

https://assethub-westend.subscan.io/xcm_message/westend-0b7392a01047380b1b930aa8081e403e5ca7dd82

**Comment by yrong** [comment]
> I think this was solved for you in the support chat

Yeah, can be closed. Not a issue just for review by others.
