### ISSUE TITLE
on chain Heartbeats without external_addresses

### ISSUE THREAD

**Issue by rvalle** [paritytech/polkadot-sdk#646]
Hi

We are detecting a growing number of Heartbeats in the Kusama network that come with null external_addresses.

Here is [an example](https://kusama.subscan.io/extrinsic/17649388-3).

We currently use that information to perform decentralization analytics and I believe the network requires the validators to issue HBs in order to get active, however, is the external_addresses list validated somehow?

**Comment by bkchr** [comment]
The information do not exist anymore.
