### ISSUE TITLE
transfer_allow_death - emitting an empty Deposit event

### ISSUE THREAD

**Issue by Dinonard** [paritytech/polkadot-sdk#6469]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

In case `transfer_allow_death` does not kill the account, and empty `Deposit` event is emitted.
E.g.: https://polkadot.subscan.io/extrinsic/23395862-2

I believe it's because of the lack of _is-zero_ check here:
https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/transaction-payment/src/payment.rs#L160

Can someone please confirm this is not intentional?

**Comment by bkchr** [comment]
By empty you mean the `deposit == 0` event? IMO reasonable to not send this, as you are proposing.

**Comment by Dinonard** [comment]
Yes, I meant it's zero. Should have been more clear, my bad.

I'll prepare a PR to change this then. 🙂

**Comment by bkchr** [comment]
Ty!
