### ISSUE TITLE
pallet broker: some benchmarks are weightless for kitchensink runtime. Resulting in substrate weight being 0

### ISSUE THREAD

**Issue by gui1117** [paritytech/polkadot-sdk#6474]
`enable_auto_renew` and `disable_auto_renew` benchmarks result in `Weightless` when run against the kitchensink runtime. And also when run against the mock runtime.

It is not very ideal as we use kitchen sink to get some default weight and some general idea of the cost of the pallet calls.

You can see the weight info resulting from CI here: https://github.com/paritytech/polkadot-sdk/pull/6418/commits/4dfe581539971010fb462ae1987cdb0a2a2ff734#diff-394c3120033a81905e5460398ad0d7245d7143d21069aeffb3cdf07b41eccc18

I believe it is weightless since: https://github.com/paritytech/polkadot-sdk/pull/4424

@Szegoo 
@seadanda

**Comment by seadanda** [comment]
Yea the benchmark is broken - the prices are too low for the purchases. Working on a fix.
