### ISSUE TITLE
Remove collation-generation subsystem from validator nodes

### ISSUE THREAD

**Issue by alindima** [paritytech/polkadot-sdk#6476]
As the title says: https://github.com/paritytech/polkadot-sdk/blob/a1af8ed63668fc4a553776e381a12d165e7462f8/polkadot/node/service/src/overseer.rs#L298

Collation-generation is only needed for collators

**Comment by burdges** [comment]
We'd do a validator DKG by having validators make blocks on a parathread, but this could always be brought back for that.

**Comment by bennethxyz** [comment]
Taking this on1

**Comment by ndkazu** [comment]
Hello,
If I understood correctly the assignment is basically removing  `.collation_generation` from `/polkadot/node/service/src/overseer.rs)` since collator does not seem to use the builder. is that right ?

**Comment by ndkazu** [comment]
Hello, I removed `collation_generation` from validator nodes, and the tests seem to be ok. Please check the linked PR.

**Comment by ndkazu** [comment]
> Hello, I removed `collation_generation` from validator nodes, and the tests seem to be ok. Please check the linked PR.

Tests are still failing, I will keep searching...

**Comment by ndkazu** [comment]
> > Hello, I removed `collation_generation` from validator nodes, and the tests seem to be ok. Please check the linked PR.
> 
> Tests are still failing, I will keep searching...but basically, I am trying to understand how to use the `orchestra-proc-macro` crate.

`collation_generation` removed for validators, all tests are good, & CI is OK ⇨ **Ready for approval**.
I  However have to admit that I still don't fully understand the  use of the `orchestra-proc-macro` crate :disappointed: .
I guess I will keep reading the doc together with the Polkadot-sdk until it clicks... :thinking:
