### ISSUE TITLE
network/libp2p: Peerset bug trying to add an already reserved node

### ISSUE THREAD

**Issue by lexnv** [paritytech/polkadot-sdk#6598]
```
2024-11-21 16:21:42.807  WARN tokio-runtime-worker peerset: Trying to add an already reserved node 12D3KooWLgeWvXXrS4H6p626s2E4H7V2UvkfxgcHTBkyQZ4vCwBT as reserved on SetId(3).
```

Grafana link: https://grafana.teleport.parity.io/goto/KHDabd7NR?orgId=1.

cc @paritytech/sdk-node

**Comment by dmitry-markin** [comment]
This is indeed harmless and IIRC I made it `warn` for node operators to notice when adding already reserved nodes manually. As we abuse the reserved nodes mechanism for other protocol peer set following, this warning is not informative.
