### ISSUE TITLE
JSON-RPC: `chainHead_v1_storage` `started` event is missing `discardedItems` property

### ISSUE THREAD

**Issue by josepot** [paritytech/polkadot-sdk#6683]
The `started` event of the `chainHead_v1_storage` operation is not spec compliant because is missing [the `discardedItems` property](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_v1_storage.html#started).

**Comment by josepot** [comment]
Ping @jsdw @IkerAlus @lexnv

**Comment by lexnv** [comment]
Substrate implementation should no longer discard items because we rely entirely on backpressure, I'll have a quick look over the code, thanks for reporting this 🙏

**Comment by josepot** [comment]
> Substrate implementation should no longer discard items because we rely entirely on backpressure, I'll have a quick look over the code, thanks for reporting this 🙏

even if it doesn't discard them, the `discardedItems` property should still be present and its value should be `0`.

**Comment by lexnv** [comment]
Yep exactly, I think we missed this during a refactoring, will patch it 🙏
