### ISSUE TITLE
Make sure `block_number` and `now` are elastic scaling compatible

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#6719]
Those two host functions depend on the block number. With elastic scaling this gets mixed up. We need to make sure that those host functions use the relay chain block when making calculations.

**Comment by kianenigma** [comment]
Taking a quick look at your code in `trait Ext` and `Stack`, the impl is simple enough -- We have access to `T: Config` everywhere, and we can easily wire this into the relay chain timestamp and block number, as we have done in many other pallets and places like `BlockNumberProvider` etc.

But what is your exact requirement? you want these two functions to always return the relay? or have two new sets of functions?

Need to double-check if the timestamp is in the inherent, but if not it is trivial to add.

**Comment by kianenigma** [comment]
For block number, this is more or less all you need: 

```diff
diff --git a/substrate/frame/revive/src/exec.rs b/substrate/frame/revive/src/exec.rs
index b23d7e4e60..454b7f7e04 100644
--- a/substrate/frame/revive/src/exec.rs
+++ b/substrate/frame/revive/src/exec.rs
@@ -899,8 +899,9 @@ where
 			origin,
 			gas_meter,
 			storage_meter,
+			// TODO: also ensure that the timestamp is provided as the relay.
 			timestamp: T::Time::now(),
-			block_number: <frame_system::Pallet<T>>::block_number(),
+			block_number: T::BlockNumberProvider::current_block_number(),
 			first_frame,
 			frames: Default::default(),
 			debug_message,
diff --git a/substrate/frame/revive/src/lib.rs b/substrate/frame/revive/src/lib.rs
index 1dee1da03b..14fbe80f12 100644
--- a/substrate/frame/revive/src/lib.rs
+++ b/substrate/frame/revive/src/lib.rs
@@ -149,6 +149,12 @@ pub mod pallet {
 		/// The time implementation used to supply timestamps to contracts through `seal_now`.
 		type Time: Time;
 
+		/// Means to provide a custom block-number that is passed on the contracts.
+		///
+		/// common implementations could be a local block number (analogous to
+		/// `frame_system::block_number()`) or a relay chain block number.
+		type BlockNumberProvider: BlockNumberProvider;
+
 		/// The fungible in which fees are paid and contract balances are held.
 		#[pallet::no_default]
 		type Currency: Inspect<Self::AccountId>
```

for timestamp, it is actually not part of the data that is passed to the parachain inherent, so we need to add it. 

https://github.com/paritytech/polkadot-sdk/blob/478857933b031e5d703a8c9a1ed6047918ef4d90/polkadot/primitives/src/v8/mod.rs#L661-L672

I have explored how this type can be made extensible in https://github.com/paritytech/polkadot-sdk/issues/6235.

In any case, @re-gius can help with the block number part, and then together with someone from the node team (cc @skunert) we can explore having AH collators also include the relay chain's timestamp as part of the mandatory inherent.

**Comment by xlc** [comment]
this doesn’t make much sense to me. it will be helpful to expose an additional relay block number but not making sense to make default block number as relay block number. same for timestamps.

**Comment by athei** [comment]
You suggest `BLOCKNUMBER` and `TIMESTAMP` opcodes should reference the parachain block as they do now?  My thinking was that when parachains under the same relay chain communicate block numbers it would be beneficial if they agree on what it means by default.

**Comment by xlc** [comment]
maybe it can help but not really. you have to propose some use cases and requirements before deciding an implementation

**Comment by athei** [comment]
Then I think we should just not do this and keep it the way it is. Thanks for clearing this up.
