### ISSUE TITLE
Disable all host functions which are not needed for launch

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#6720]
We should reduce the attack surface as much as possible. This means any host function which is not available in revive at launch should be disabled. Later, we can re-enable them (if part of Solidity) or convert to a pre-compile.

**Comment by davidk-pt** [comment]
Can I take this?

**Comment by athei** [comment]
Yes sure. You have to basically go through the recompiler and find out which functions are not used by it. You then just remove the `[version(0]]` attribute to deactivate them. Please note that after https://github.com/paritytech/polkadot-sdk/pull/6759 the attribute name changes to `[stable]`.

@xermicus in which source file to find the list of used host functions?

**Comment by athei** [comment]
@davidk-pt Feel free to self assign the issue when you are about to start with it. Thanks :)

**Comment by davidk-pt** [comment]
Let me know if I understood this correctly https://github.com/paritytech/polkadot-sdk/pull/6844 , I basically diffed two lists, from the C file and what is available in `substrate/frame/contracts/src/wasm/runtime.rs` file
