### ISSUE TITLE
`approval-voting`: consider removing`candidate_index` from `ApprovalDistributionMessage` message

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#675]
https://github.com/paritytech/polkadot/blob/master/node/primitives/src/approval.rs#L76

This is redundant because the network message wrapping the certificate also [contains the corresponding `candidate_index`](https://github.com/paritytech/polkadot/blob/master/node/network/protocol/src/lib.rs#L492) which can be mapped to the `core_index` . We can still perform the validity check against the `core_index` obtained from the VRF output.

Related:
https://github.com/paritytech/polkadot/pull/6782#discussion_r1155214000

**Comment by eskimor** [comment]
@sandreim are we actually planning to do this? If not, maybe just leave a comment in the code that this is redundant and can be removed once we change the message format for any other reason. If the comment is right in the struct, we will not forget in case we ever need to change this and will do it then. In that case we could close this ticket :-)

**Comment by sandreim** [comment]
I don't think this will be done in the near future.
