### ISSUE TITLE
polkadot 0.9.40-a2b62fb872b Validator Issues / ram and peers issues / lost sync / chilled

### ISSUE THREAD

**Issue by SimonKraus** [paritytech/polkadot-sdk#679]
The latest medium-priority release caused problems on many validator instances.
A lot of validators got chilled since updating.

I'll just try to sum up the problems reported by various operators for visibility and to get decision-making going.

- Peering gone wild
Even waiting nodes that don't participate in consensus see a rapid increasement of peers to 700+ ignoring the `--in-peers` and `--out-peers` 

- Number of TCP connections
![TCP conns](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/pGBfDxDeGRxoGZYoHNbkXSae)

- Ram consumption
Consumed Ram clearly increased with this release and spikes in Ram usage caused the node to crash 
![RAM graph](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/BdcdJDhUYyatTdWdPIMkwXBT)

- Stops syncing
There are reports of nodes just stopping to sync the chain without any identifiable problem. 
Some operators noticed problems on one machine but had none on the second identical build.

- UnboundedChannelPersistentlyLarge
message = Channel mpsc_import_notification_stream on node localhost:9616 contains more than 200 items for more than 5 minutes. Node might be frozen.

- `Mar 24 06:13:04 worker02 polkadot[429783]: 2023-03-24 06:13:04 (offchain call) Error submitting a transaction to the pool: Transaction pool error: Too low priority (18446744073709551615 > 18446744073709551615)`

- `Mar 24 06:13:04 worker02 polkadot[429783]: 2023-03-24 06:13:04 Ran out of free WASM instances`

- `Mar 24 06:13:09 worker02 polkadot[429783]: 2023-03-24 06:13:09 Got a bad assignment from peer hash=0x65d2558f1c946ba12867777cfdcbb0182e944e511c2d3a0b3de9b1fa9d79b6b8 peer_id=PeerId("12D3KooWBy4Mhc9j4GJxZfKjettapQbsGr8z5wVNHXPgrYnnU4RH") error=Unknown block: 0x65d2558f1c946ba12867777cfdcbb0182e944e511c2d3a0b3de9b1fa9d79b6b8`

Many of the 1KV validators have downgraded because of the problems which caused them invalid for program participation.

**Comment by bkchr** [comment]
Stale.
