### ISSUE TITLE
Support a file logging option

### ISSUE THREAD

**Issue by dnjscksdn98** [paritytech/polkadot-sdk#6821]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [ ] This is not a support question.

### Motivation

Currently, there is no execution option to enable file logging. For example storing `stdout` or `stderr` to a certain text file. Without this option, it's quite difficult to examine past logs. It seems that Geth already have an option like this. https://geth.ethereum.org/docs/fundamentals/logs

### Request

I suggest an execution option that takes a path to a certain text file, for example, `--log-path <file path>`. When enabled it will sequentially store logs occurred by the node. Log rotation should also be included to prevent massive log file size.

### Are you willing to help with this request?

Yes!

**Comment by alindima** [comment]
> https://geth.ethereum.org/docs/fundamentals/logs

Geth here just suggests redirecting the output to some file of your choice using the classic `>>` terminal syntax.

I think doing all of this, especially rotating logs, is out of scope for polkadot and can be easily done with external tooling

**Comment by bkchr** [comment]
Yeah why not just use the normal tooling that your distribution etc provides for this? It already supports all the features you are requesting.

**Comment by dnjscksdn98** [comment]
Thanks for quick responses. I'll look around for it then 👍
