### ISSUE TITLE
chain-spec-builder: Automatically cross check `--para-id` flag with `ParachainInfo` genesis state.

### ISSUE THREAD

**Issue by skunert** [paritytech/polkadot-sdk#6861]
Currently we do no check for correctness of para IDs in the chain-spec-builder.

## Example
Executing this command will create a simple chain spec.
```
chain-spec-builder create -p 300 -c polkadot --runtime my_runtime.compact.compressed.wasm named-preset development
```
Ecerpt from `chain_spec.json`:
```json
{
   ...
   "para_id": 300
   "genesis": {
      ...
      "runtimeGenesis": {
         ...
         "parachainInfo": {
            "parachainId": 1000
         }
      }
   }
}
```
There is a clear mismatch between the genesis state of the parachain info pallet and the para id in the client spec. This is expected, as the genesis state is coming from the runtime. 

## Solution
The `chain-spec-builder` could make an exception for the `ParachainInfo` crate and automatically align the para ids. I can not think of a use-case where it makes sense to have a mismatch there. We can print out a log that highlights that the Id has been adjusted.

**Comment by bkchr** [comment]
The proper solution for the problem is this https://github.com/paritytech/polkadot-sdk/issues/2116 plus this https://github.com/paritytech/polkadot-sdk/issues/75.

No hacky solution around making the chain spec generator do things it should not be doing.
