### ISSUE TITLE
Kusama XCM Dry Run fails with weird error.

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#6950]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

For some reason, using Kusama for Dry Run - despite it supporting it ends with a error:
<img width="883" alt="Snímka obrazovky 2024-12-18 o 14 17 48" src="https://github.com/user-attachments/assets/ce5f3c49-dd3a-4918-a680-a2e455c22ca6" />

### Steps to reproduce

Using following query:
<img width="1737" alt="Snímka obrazovky 2024-12-18 o 14 19 35" src="https://github.com/user-attachments/assets/d18763c5-0ac5-40ac-bfae-dea3271e9e0f" />

EDIT:
Polkadot DRY RUN works fine, so probably something introduced in latest runtime.

**Comment by bkchr** [comment]
This will be fixed by: https://github.com/paritytech/polkadot-sdk/pull/5581

Basically there are some stale messages in the HRMP module that lead to this issue. With the next runtime release this will be fixed.
