### ISSUE TITLE
Unable to properly benchmark `pallet_bounties` when ED is 0

### ISSUE THREAD

**Issue by tsenovilla** [paritytech/polkadot-sdk#7009]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We cannot properly benchmark `pallet_bounties` in the [LAOS](https://github.com/freeverseio/laos) runtime, as all the following benchmarks fail:
```
The following 7 benchmarks failed:
- pallet_bounties::accept_curator
- pallet_bounties::award_bounty
- pallet_bounties::claim_bounty
- pallet_bounties::close_bounty_active
- pallet_bounties::extend_bounty_expiry
- pallet_bounties::propose_curator
- pallet_bounties::unassign_curator
Error: Input("7 benchmarks failed")
```

Upon investigation, we believe this issue may affect all runtimes where the existential deposit is set to 0, as is our case. [This issue](https://github.com/freeverseio/laos/issues/932) in LAOS outlines the root cause of this behavior, but I’ve included the relevant details below for easier tracking.

Concretely, [this function](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/bounties/src/benchmarking.rs#L92) is used in benchmarks to fund the treasury account.
If `ED` is 0, so is `T::Currency::minimum_balance()`, resulting in the treasury's balance being initialized to 0 before benchmarks that require treasury funding. 

As a result, there is no budget available for bounties in the benchmark suite. Consequently, [these lines](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/bounties/src/lib.rs#L1020-L1042) remain unreachable, preventing bounties from getting the Funded status. While not all the failing benchmarks depend directly on the Funded status, they do rely on a flow where the bounty has successfully progressed through that stage, hence the failure. 

### Steps to reproduce

Set a runtime using `pallet_treasury` + `pallet_bounties` as `SpendFunds` where the existential deposit is 0 and try to benchmark `pallet_bounties`. [LAOS](https://github.com/freeverseio/laos) is affected by this issue, so it may be used as reference as well

**Comment by AurevoirXavier** [comment]
Generally, I write this code for such issues.

```rs
#[cfg(feature = "runtime-benchmarks")]
const ED = 1;
#[cfg(feature = "runtime-benchmarks")]
const ED = 0;
```

---

But it's okay to report such issue and see if we can improve the benchmarks.

**Comment by tsenovilla** [comment]
> Generally, I write this code for such issues. (a lot of pallets had such issues in the past)
> 
> ```rust
> #[cfg(feature = "runtime-benchmarks")]
> const ED = 1;
> #[cfg(not(feature = "runtime-benchmarks"))]
> const ED = 0;
> ```
> 
> But it's okay to report such issues and see if we can improve the benchmarks.

Thanks for the reply! We were actually thinking in a such a workaround but did wanna to report it anyway as it should imply a simple fix (which is already on its way 😁)

**Comment by luispdm** [comment]
Hi @bkchr. Just wanted to mention that for the same reason some benchmarks fail in `pallet_balances` too. Specifically, these ones:
```
- pallet_balances::burn_allow_death
- pallet_balances::burn_keep_alive
- pallet_balances::force_transfer
- pallet_balances::upgrade_accounts
Error: Input("4 benchmarks failed")
```
Feel free to either include the fix in your PR or link another PR to this issue.

**Comment by bkchr** [comment]
Yeah for `pallet-balances` you need to enable the [`insecure_zero_ed` feature](https://github.com/paritytech/polkadot-sdk/blob/f19640bdf98f72c788e60f647628b3fc98192bb1/substrate/frame/balances/src/benchmarking.rs#L34) to make the benchmarks work properly.

**Comment by luispdm** [comment]
Thanks to both of you @AurevoirXavier @bkchr
