### ISSUE TITLE
Increase in error rate after upgrade to v0.9.36

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/polkadot-sdk#748]
On 2022-12-20 16:50:21 UTC we updated Polkadot RPC nodes v0.9.33 -> V0.9.36, and after that, we see more errors in logs than usual.
![image](https://user-images.githubusercontent.com/24387396/208884587-f2180d65-8ae6-4467-8db0-72aa24b63dc5.png)

Error:
```
ERROR tokio-runtime-worker jsonrpsee_server::transport::ws: WS transport error: i/o error: Transport endpoint is not connected (os error 107); terminate connection:
```

As far as I understand, the logs are due to broken `WS` connections. 

Is the new release breaking the WS or did Polkadot enable more logs?

**Comment by BulatSaif** [comment]
related: https://github.com/paritytech/jsonrpsee/issues/871

**Comment by niklasad1** [comment]
@BulatSaif This will be fixed by upgrading jsonrpsee and the PR is up for review now.
