### ISSUE TITLE
High warnings rate on Kusama after 0.9.31-rc6 update due to libp2p_yamux 

### ISSUE THREAD

**Issue by vstakhov** [paritytech/polkadot-sdk#758]
After our validators got updated to this version, there is a constant flow of warnings in the module `libp2p_yamux`. The logs are all similar:

```
WARN tokio-runtime-worker libp2p_yamux: dropping (Stream a9bc8821/65) because buffer is full
```

The sample warnings rate graph is here: https://grafana.parity-mgmt.parity.io/goto/V_rs4jHVk?orgId=1

CC @dmitry-markin @altonen

**Comment by lexnv** [comment]
@vstakhov are we still getting this error with the latest libp2p version bump?

I did not see this running a local node for ~ 4 days with libp2p backend. And did not reproduce during versi-net triaging

**Comment by ordian** [comment]
Indeed, don't see these warnings on our Kusama validators in the past 7 days.
