### ISSUE TITLE
disputes: escalate punishment on repeated dispute initiations

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot-sdk#785]
As of https://github.com/paritytech/polkadot/pull/5535, we don't disable validators for "against valid" disputes. But based on the number of disputes initiated by a validator within a session, we might want to disable it if it reaches a certain threshold. Since submitting more such disputes wastes the network bandwidth "for free".

We can also consider doing exponential slashing or slashing up to a certain number or what's suggested by @burdges in https://github.com/paritytech/polkadot-sdk/issues/790. 

But disabling a validator would have a greater short-term impact since slashes are only applied after a bonding period.

**Comment by tdimitrov** [comment]
Can we close this in favour of https://github.com/paritytech/polkadot-sdk/issues/784?

**Comment by Overkillus** [comment]
Will be solved by the new disabling strategy. 0% slashes dispensed for validators voting invalid on valid will cause disablement. Disablement has opportunity cost which should be enough of deterrent.
