### ISSUE TITLE
XCM - CurrencyAdapter doesn't check result

### ISSUE THREAD

**Issue by Dinonard** [paritytech/polkadot-sdk#797]
Hi!

I've noticed that in the [currency_adapter](https://github.com/paritytech/polkadot/blob/master/xcm/xcm-builder/src/currency_adapter.rs#L145) we don't check whether calling `deposit_creating` was successful or not.

A colleague of mine was sending DOTs back to Polkadot and although XCM execution was labeled as successful, he didn't receive any DOTs. His account didn't satisfy the ED requirement and the amount being sent was only `0.1` DOTs so it wasn't sufficient to create a new account.

It was quite misleading since we'd expect the execution to fail with some error.

Is this by design? Or should it be changed to result in an error?

**Comment by KiChjang** [comment]
Moving forward though, we encourage the usage of the `FungiblesAdapter` over `CurrencyAdapter`, as we are going to be deprecating the `Currency` soon. Closing as won't fix.
