### ISSUE TITLE
Add ARM binaries to releases

### ISSUE THREAD

**Issue by cor** [paritytech/polkadot-sdk#802]
Currently, there are only X86 binaries available on [the releases page](https://github.com/paritytech/polkadot/releases/). This is a problem for our team as some people are developing on M1 Macs. Can you please also release ARM binaries?

**Comment by shawntabrizi** [comment]
We really need this. 99% of our devs are probably using a Mac to develop on Polkadot-SDK.

Developer experiences are worse because of lacking native binaries:

```
➜  individuality2 git:(shawn-super-refactor) ✗ ./zombienet setup polkadot polkadot-parachain


------------------------------------------------------------------------

Note:  You are using MacOS. Please, clone Polkadot SDK from https://github.com/paritytech/polkadot-sdk 
 in order to build the polkadot and/or polkadot-parachain locally.
 At the moment there is no binaries for MacOs as releases.

------------------------------------------------------------------------
```

**Comment by th7nder** [comment]
> We really need this. 99% of our devs are probably using a Mac to develop on Polkadot-SDK.
> 
> Developer experiences are worse because of lacking native binaries:
> 
> ```
> ./zombienet setup polkadot polkadot-parachain
> 
> 
> ------------------------------------------------------------------------
> 
> Note:  You are using MacOS. Please, clone Polkadot SDK from https://github.com/paritytech/polkadot-sdk 
>  in order to build the polkadot and/or polkadot-parachain locally.
>  At the moment there is no binaries for MacOs as releases.
> 
> ------------------------------------------------------------------------
> ```
@shawntabrizi 
As a workaround for this situation, we're using `nix flake` which provides `polkadot` built on ARMs.

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs = {
        nixpkgs.follows = "nixpkgs";
       };
    };
    zombienet = {
      url = "github:paritytech/zombienet/dfc0f2e02dbab2361c3f2f983fe6e0f32261cc73"; # last known working version, because of: https://github.com/paritytech/zombienet/issues/1858
      inputs = {
        nixpkgs.follows = "nixpkgs";
      };
    };
  };
  outputs = { self, nixpkgs, flake-utils, rust-overlay, zombienet }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) zombienet.overlays.default ];
        pkgs = import nixpkgs {
          inherit system overlays;
        };
        rustToolchain = pkgs.pkgsBuildHost.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;
        buildInputs = with pkgs; [
          # Building Docker images and publishing to Azure Container Registry
          azure-cli
          # cargo-llvm-cov
          cargo-expand
          clang
          pkg-config
          rustToolchain
          subxt
          just
          taplo
          polkadot
          mdbook
          # Due to zombienet's flake.nix, needs to be prefixed with pkg.zombienet
          pkgs.zombienet.default
        ]
        ++ (lib.optionals stdenv.isDarwin [
          darwin.apple_sdk.frameworks.Security
          darwin.apple_sdk.frameworks.CoreServices
          darwin.apple_sdk.frameworks.SystemConfiguration
        ])
        ++ (lib.optionals stdenv.isLinux [
          cargo-llvm-cov
        ]);
      in
      with pkgs;
      {
        devShells.default = mkShell {
          inherit buildInputs;

          LIBCLANG_PATH = "${llvmPackages.libclang.lib}/lib";
          PROTOC = "${protobuf}/bin/protoc";
          RUST_SRC_PATH = "${rustToolchain}/lib/rustlib/src/rust/library/";
          ROCKSDB_LIB_DIR = "${rocksdb}/lib";
        };
      }
    );
}
```

^ this flake allows you to run zombienet natively on MacOS with running command like:
```bash
zombienet -p native spawn zombienet/local-testnet.toml
```

**Comment by shawntabrizi** [comment]
what is the blocker? i dont get how this isn't just done.

**Comment by kianenigma** [comment]
Would be great if we know if this is addressed by the next stable release or not. Given the 3 months release cadence, if the effort needed for it is minimal, I think it is reasonable to prioritize it in the next 2 weeks.

**Comment by KarimJedda** [comment]
I just had a chat with @EgorPopelyaev , the team has some capacity to take care of it next week. CI/CD ARM runner is in place, what is left is to add step to the binary build pipeline which is going to do an ARM build. 

@EgorPopelyaev would this fit in the timeline set by Kian? Let me know anything you need for this and I'll check with other teams who can assist.

**Comment by iulianbarbu** [comment]
We merged recently https://github.com/paritytech/polkadot-sdk/pull/6427, which brings support for releasing Apple Silicon ARM node binaries (polkadot, polkadot-prepare/execute-worker, polkadot-parachain & polkadot-omni-node) which will be part of the release pages artifacts section with the next.

The initial request of this issue was for Apple Silicon ARM binaries for development, and the node binaries should be sufficient I think, but please create a more specific issue if something is missing.

Other than this request for ARM Linux binaries was also mentioned (and got some likes), so I opened a dedicated issue here: https://github.com/paritytech/polkadot-sdk/issues/6678.
