### ISSUE TITLE
Fine grained CPU profiling

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#804]
There have been efforts to solve this earlier like https://github.com/paritytech/polkadot/pull/4871  but the results we got were not providing enough insights due to the low sampling rate/storage - https://pyroscope.io/docs/storage-design/ . We should continue the effort to implement something that works better for our usecase. We need as fine grained as possible CPU profiling (100us) with visualisation tooling to increase accuracy and decrease the scope of debugging when dealing with node performance issues or optimization work.

The solution should also consider this must also work easily with Zombienet to test performance regression in the CI pipeline.

**Comment by alexggh** [comment]
Superseeded by using subsystem benchmarks with pyroscope.
