### ISSUE TITLE
XCM v3: Integrate `NonFungibleAsset` traits

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot-sdk#865]
Integrate `NonFungibleAsset` traits into the XCM assets system to make NFTs transferable between chains.

**Comment by bkontur** [comment]
Some partial work was done: https://github.com/paritytech/polkadot-sdk/pull/2924 and https://github.com/paritytech/polkadot-sdk/pull/2796

And also there is older PR for `NonFungiblesV2Adapter` https://github.com/paritytech/polkadot-sdk/pull/1242

**Comment by bkontur** [comment]
> Integrate NonFungibleAsset traits into the XCM assets system to make NFTs transferable between chains.

@Szegoo @liamaharon Are we missing anything else to accomplish this? Are there any open issues for XCM NFTs transfer?

**Comment by Szegoo** [comment]
The only thing missing AFAIK is benchmarking XCM NFT transfers correctly, which is fixed here: https://github.com/paritytech/polkadot-sdk/pull/3455
