### ISSUE TITLE
PVF host: sandbox/harden worker process

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot-sdk#882]
## Overview

As future work for the PVF validation host we envisioned that the workers should be hardened.

Ideally, if a worker process was compromised then the attacker won't get the rest of the system on a silver plate. To do that, we may want to consider:

1. running workers under a different user
2. jailing/unshare or clone(2) with fresh new namespace
3. **seccomp**

## Summary / Roadmap

https://hackmd.io/@gIXf9c2_SLijWKSGjgDJrg/BkNikRcf2

## Potentially Useful Resources

https://www.redhat.com/sysadmin/container-security-seccomp

**Comment by mrcnski** [comment]
We have landlock, networking restrictions with seccomp, unshare/pivot_root, separate processes, and are in the process of [implementing clone with sandbox args](https://github.com/paritytech/polkadot-sdk/pull/2477). We've decided that this is enough security until the PolkaVM migration.
