### ISSUE TITLE
DepositAsset need failure recover of holding

### ISSUE THREAD

**Issue by zqhxuyuan** [paritytech/polkadot-sdk#912]
Current the logic of DepositAsset is first take assets from holding, then do AssetTransactor::deposit_asset(). If deposit_asset() throw Error, for example receiver not recognize token from sender, and for now it has no mechanism of recover holding, thus Config::AssetTrap would't be executed, in this case it'll cause token lossing.

I've [test this case](https://github.com/zqhxuyuan/open-runtime-module-library/commits/unknow_tests) in orml: paraA transfer tokenA to paraB, and we let paraB not recognize tokenA temporary which will throw an Error. and in my test result, when execute xcm on paraB side,it will loss tokenA, this's not we wanted.

So maybe we need recover holding data when deposit_asset cause an Error. and this ability may extend to other instructions? cc @gavofyork @KiChjang

**Comment by KiChjang** [comment]
Closing, as this is the responsibility of the sender to ensure that the recipient handles the asset kind that's being sent over -- the recipient has no way of representing the asset otherwise.
