### ISSUE TITLE
`create_inherent` return value improvement

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot-sdk#927]
```
fn create_inherent(data: &InherentData) -> Option<Self::Call> {
```

does 

```
return None
```

where we could continue operation with an empty inherent set, but `parent_header` is still required, which is currently only accessibly via `Client`, which is not avail in the runtime.

---

Background:

There is a different semantic meaning between `return None` and `return ParasInherent` with no candidates contained, since the first implies a failure to author a block.

**Comment by eskimor** [comment]
Seems obsolete.
