### ISSUE TITLE
0.9.43 Release Regressions

### ISSUE THREAD

**Issue by wpank** [paritytech/polkadot-sdk#94]
Collecting some common issues people have mentioned on 0.9.43 compared to 0.9.42 - seems like one of the main things noticed is that peer counts fluctuate a bit and are less stable. It might eventually stabilize though (so perhaps this is just expected behavior for when a node restarts?). So far all the following is for Kusama (unless otherwise mentioned). The following is from a few different people.

![image (5)](https://github.com/paritytech/polkadot/assets/9498646/8466547b-146e-4791-b193-451c618f6f0a)

> "Started out looking good. Got 26 peers. Then dropped. Then bumped to 38. Then dropped. Then up. Then down again. Seems to fluctuate between mid 20s to sub 10."

----

> "Rolled back to .42 last night. Peers seem to have stabilized to 40. So I guess this is an issue with .43??
I'm gonna try .43 again and see what happens."

![image (6)](https://github.com/paritytech/polkadot/assets/9498646/bf7df606-ae5c-48da-8e37-0840777b2e0d)

----

![image (7)](https://github.com/paritytech/polkadot/assets/9498646/fdd551fc-c084-4fbd-928c-4619b89d681b)

----

![image (8)](https://github.com/paritytech/polkadot/assets/9498646/3d2fb8fb-c761-4776-8c55-3551b4b4e4c8)

> "Peer update on our node post upgrade to .43. Definitely not as streamlined as it is using .42."

----

Also seems have to a little bit of increased network usage:

![image (9)](https://github.com/paritytech/polkadot/assets/9498646/878516f0-ef78-412e-91d3-12de360b53f0)

![Screenshot%20from%202023-06-15%2011-46-15](https://github.com/paritytech/polkadot/assets/9498646/cc93aef6-9f04-4167-8691-7577e2cee528)

-----

Peer count seems like it may stabilize over time though:

![image (10)](https://github.com/paritytech/polkadot/assets/9498646/cc63fcb0-36a5-464f-af13-78dadf97c60e)

**Comment by jun0tpyrc** [comment]
seem still reoccurs - is that a proper fix &/ workaround to fix the p2p problem for kusama nodes hitting this issue?

**Comment by altonen** [comment]
There is one workaround in the next release which should make the peer count more stable by making peer evictions less aggressive. That's not a fix though and but should merely mask the underlying problem.

**Comment by gituser** [comment]
> FWIW, finality lagging is reproducible for me on 0.9.42 if use a fix for the inbound substream spam. I'd advise you @gituser to open your firewall so that your Polkadot node can accept inbound connections, that should help with the issue.

I'm still having this issue with the latest `polkadot-v1.5.0` on Westend sync takes forever (p2p port is opened to the world btw):

```
Jan  6 23:56:09 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:09 ⚙️  Syncing  0.0 bps, target=#19003651 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 3.0kiB/s ⬆ 2.3kiB/s
Jan  6 23:56:15 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:15 ⚙️  Syncing  0.0 bps, target=#19003652 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 17.1kiB/s ⬆ 1.1kiB/s
Jan  6 23:56:20 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:20 ⚙️  Syncing  0.0 bps, target=#19003653 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 2.9kiB/s ⬆ 0.4kiB/s
Jan  6 23:56:28 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:28 ⚙️  Syncing  0.0 bps, target=#19003654 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 4.7kiB/s ⬆ 4.8kiB/s
Jan  6 23:56:34 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:34 ⚙️  Syncing  0.0 bps, target=#19003656 (10 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 5.7kiB/s ⬆ 5.3kiB/s
Jan  6 23:56:39 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:39 ⚙️  Syncing  0.0 bps, target=#19003656 (10 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 2.7kiB/s ⬆ 1.6kiB/s
Jan  6 23:56:46 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:46 ⚙️  Syncing  0.0 bps, target=#19003658 (10 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 6.0kiB/s ⬆ 21.1kiB/s
Jan  6 23:56:53 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:53 ⚙️  Syncing  0.0 bps, target=#19003644 (11 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 2.9kiB/s ⬆ 24.4kiB/s
Jan  6 23:56:59 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:56:59 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 20.9kiB/s ⬆ 4.3kiB/s
Jan  6 23:57:05 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:05 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 3.5kiB/s ⬆ 1.3kiB/s
Jan  6 23:57:11 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:11 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 2.4kiB/s ⬆ 0.9kiB/s
Jan  6 23:57:17 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:17 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 0.5kiB/s ⬆ 0.2kiB/s
Jan  6 23:57:28 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:28 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 3.1kiB/s ⬆ 25.8kiB/s
Jan  6 23:57:38 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:38 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 1.8kiB/s ⬆ 0.6kiB/s
Jan  6 23:57:46 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:46 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 6.4kiB/s ⬆ 0.8kiB/s
Jan  6 23:57:54 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:57:54 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 10.1kiB/s ⬆ 0.6kiB/s
Jan  6 23:58:03 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:58:03 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 3.6kiB/s ⬆ 15.3kiB/s
Jan  6 23:58:11 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:58:11 ⚙️  Syncing  0.0 bps, target=#19003644 (12 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 1.5kiB/s ⬆ 96 B/s
Jan  6 23:58:28 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:58:28 ⚙️  Syncing  0.0 bps, target=#19003667 (10 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 1.2kiB/s ⬆ 0.2kiB/s
Jan  6 23:58:35 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:58:35 ⚙️  Syncing  0.0 bps, target=#19003668 (10 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 9.2kiB/s ⬆ 0.4kiB/s
Jan  6 23:58:51 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:58:51 ⚙️  Syncing  0.0 bps, target=#19003668 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 5.5kiB/s ⬆ 0.1kiB/s
Jan  6 23:59:17 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:59:17 ⚙️  Syncing  0.0 bps, target=#19003668 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 1.3kiB/s ⬆ 0.2kiB/s
Jan  6 23:59:25 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:59:25 ⚙️  Syncing  0.0 bps, target=#19003668 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 2.2kiB/s ⬆ 0.1kiB/s
Jan  6 23:59:34 polkadot-testnet-dev polkadot[671]: 2024-01-06 23:59:34 ⚙️  Syncing  0.0 bps, target=#19003669 (9 peers), best: #18982793 (0xc140…9f35), finalized #18981888 (0x457a…2587), ⬇ 3.7kiB/s ⬆ 38 B/s
```

**Comment by altonen** [comment]
@gituser 

Please create a new issue if you're experiencing problems with the latest release. Also, could you run the node with `-lsync,sub-libp2p=trace` so I can take a look.

**Comment by gituser** [comment]
> @gituser
> 
> Please create a new issue if you're experiencing problems with the latest release. Also, could you run the node with `-lsync,sub-libp2p=trace` so I can take a look.

Unfortunately I've already nuked the database and got synced by using `--sync=fast`, it worked.
Also another issue I had with trying `master` version of polkadot over v1.5.0 database - polkadot was hanging with CPU usage about 1800% for long time and sometimes OOM'ing.
I don't have a copy of that database anymore though I could try on existing one by using `master` polkadot build again and see if it reproduces on synced DB.

**Comment by altonen** [comment]
If you run into this issue again, please open a new ticket. Sounds like this could be a problem with the database and not with `sc-network` but without logs it's hard to say
